### ISSUE TITLE
QueryField should support notContains operator

### ISSUE THREAD

**Issue by richardmcclellan** [aws-amplify/amplify-swift#1049]
[This documentation](https://docs.amplify.aws/lib/datastore/data-access/q/platform/ios#predicates) indicates that DataStore supports the `notContains` operator, but it [does not appear to be implemented](https://github.com/aws-amplify/amplify-ios/blob/e2f7f64e2a501f3b2807481ca921e71710c82b22/Amplify/Categories/DataStore/Query/QueryField.swift#L34-L44) in the library.   

On amplify-js, It appears to be [supported](https://github.com/aws-amplify/amplify-js/blob/6e28eaf37525ce231d7793bf82a960046fc7f8f4/packages/datastore/src/types.ts#L295-L299).

On Android, it is not supported, currently.  A customer reported this missing functionality, [here](https://github.com/aws-amplify/amplify-android/issues/1142).  Support is being added for Android in https://github.com/aws-amplify/amplify-android/pull/1145/

**Comment by lawmicha** [comment]
Hi @richardmcclellan, thanks for opening the issue

What does the SQL look like? I couldn't decipher exactly from the Android PR. 
Is it "NOT LIKE"? ` select * from table_name where table_column_name NOT LIKE '%1%'`
[SO ref](https://stackoverflow.com/questions/19896831/sqlite-select-where-column-does-not-contain-certain-data)

What does the AppSync operator look like? this one looks simply as `notContains`

**Comment by richardmcclellan** [comment]
> What does the SQL look like?

The SQL for `contains` is: `select * from table_name where instr(table_column_name,?) > 0`

I believe `LIKE` could be used instead of `instr`?   The performance of the two [appears to be about the same](https://stackoverflow.com/questions/2451608/which-is-faster-instr-or-like).   But, given that we were already using `instr` for contains, I chose to add support for `notContains` with a similar SQL command:

`select * from table_name where instr(table_column_name,?) = 0`

> What does the AppSync operator look like? this one looks simply as `notContains`

Correct, it is `notContains`.

**Comment by atierian** [comment]
Working implementation for strings, but still early exploratory phase.
https://github.com/aws-amplify/amplify-swift/pull/2789
