### ISSUE TITLE
Global sign out does not seem to invalidate tokens on another device

### ISSUE THREAD

**Issue by aizatomar** [aws-amplify/amplify-swift#1078]
**Describe the bug**
To test this scenario, I build and run the app on 2 different simulators.

When I global sign out from one of the simulator, I expect the tokens to be invalidated on the other simulator. However, when I call `fetchAuthSession` to retrieve the tokens, I found out the tokens are not invalidated at all and that the session is still signed in.

Am I missing something?

**To Reproduce**
1. Build and run app on 2 simulators.
2. Sign out globally on 1 simulator.
3. The other simulator session is still signed in. Expected to be signed out with Cognito tokens invalidated.

**Expected behavior**
Expect the Cognito tokens on the other simulator to be invalidated.

**Screenshots**

**Environment(please complete the following information):**
 - Cocoapods [1.10.1]
 - Amplify [1.6.0]
 - AmplifyPlugins/AWSCognitoAuthPlugin [1.6.0]
 - Swift 5
 - Xcode [12.3]

**Device Information (please complete the following information):*
 - Simulators:
 - iPhone 12 Pro Max (14.3)
 - iPhone SE - 2nd generation (14.3)

**Additional context**

**Comment by ruiguoamz** [comment]
Hi, @aizatomar 

Thanks for reaching out. 

There is one similar known [issue](https://github.com/aws-amplify/amplify-js/issues/3435). 

What happens basically is, when `globalSignOut()` is called, the refresh token is revoked, which means that id & access token cannot be refreshed anymore, but it takes some time (1 hour or longer depends on the configuration) for id & access token to become invalid. And I believe this is what causing you to observe the behavior. We are working on the fix, but cannot tell when the fix can be done.

**Comment by aizatomar** [comment]
Ok thank you for the reply. I have also tested it on my side and yes it will take about an hour for the token to be revoked.

**Comment by dilankaapt** [comment]
Upon calling globalSignOut will the id & access token be invalidated? Can this atleast be done in cognito itself or is this a bug in cognito?

**Comment by royjit** [comment]
Amplify library added (`revokeToken`)[https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_RevokeToken.html] that invalidates the `accessToken` as well while invoking signOut. You can also call this api directly using the escape hatch. 

Let us know if this solves your use case.

**Comment by kyptov** [comment]
> Amplify library added (`revokeToken`)[https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_RevokeToken.html] that invalidates the `accessToken` as well while invoking signOut. You can also call this api directly using the escape hatch.
> 
> Let us know if this solves your use case.

No, its not. Initially issue says about two devices. It is not possible to call revokeToken on device A from device B

**Comment by isair** [comment]
If the user thinks their account might be compromised and they changed their password whereby we globally sign them out, any malicious party who has access to the account will continue to do so for up to an hour with the current implementation.
