### ISSUE TITLE
How to refresh federated token and proceed with other AWS calls?

### ISSUE THREAD

**Issue by ppave** [aws-amplify/amplify-swift#1090]
As per https://docs.amplify.aws/sdk/auth/federated-identities/q/platform/ios

>>>
federatedSignIn() can be used to obtain federated “Identity ID” using external providers like Google, Facebook or Twitter. If the tokens are expired and new tokens are needed, a notification will be dispatched on the AWSMobileClient listener with the user state signedOutFederationTokensInvalid. You can give the updated tokens via the same federatedSignIn() method.

The API calls to get AWS credentials will be asynchronously blocked until you fetch the social provider’s token and give it to AWSMobileClient. Once you pass the tokens, the AWSMobileClient will fetch AWS Credentials using the new tokens and unblock all waiting calls. It will then use the new credentials.
>>>

What I do:

1. I call `Amplify.API.post(request: request)` - OK
2. I catch `signedOutFederationTokensInvalid` - OK
3. I catch `Amplify.API.post(request: request)` API error - OK
4. I refresh my OpenID token and pass it to federatedSignIn again - OK
5. On this step my token is refreshed - OK , but all SDK calls during step 4 have been failed - KO
6. How to proceed with my `Amplify.API.post(request: request)` from step 1 ?

What does `The API calls to get AWS credentials will be asynchronously blocked until you fetch the social provider’s token and give it to AWSMobileClient. Once you pass the tokens, the AWSMobileClient will fetch AWS Credentials using the new tokens and unblock all waiting calls.` mean?
Blocking the thread where I get `signedOutFederationTokensInvalid` doesn't help, `Amplify.API.post` triggers the error in any case.

Is my understanding correct that there is no an easy way here and we need to create a refresh mechanism with repeating all failed operations ourselves?

I think that it would be good to know the expiration time on the client and refresh a token before doing any AWS calls.

Thank you.

**Comment by palpatim** [comment]
Moved this to the Amplify repo since the final use for the credentials is an `Amplify.API` call

**Comment by lawmicha** [comment]
Hi @ppave, Thanks for opening this issue. What you mentioned is correct that amongst the SDK's (AWSMobileClient, AppSync SDK), the block would not be released until the user signs back in, and in the scenario where the user is unable to sign in, developers can call `AWSMobileClient.releaseSignInWait()` to unblock the calls. In Amplify, when using API Plugin, the calls will return immediately with a failure. This is the currently by design; developers have to react to the failures immediately, prompt the user to sign in, and depending on the UX, the end user would have to perform the same actions to execute those requests. 

Internally, the auth plugin is called `releaseSignInWait()` when the session expired, so there isn't a situation where it would make sense for the developer to call `releaseSignInWait()`, just want to call this out since you are going to the escape hatch for the AWSMobileClient instance, and this is also the reason why the API calls are not blocked, they are released immediately after being blocked.

Could you expand on your use case? Is there a difficulty of building the UX to retry the failed operations that you would rather have the calls block and be released upon sign in?

**Comment by ppave** [comment]
Hi @lawmicha, thank you for your response.

My use case:
- User launches the app 
- On the first app launch, user have to sign in using web-view with OpenID implementation
- This web-view returns JWT that is passed to Amplify `federatedSignIn`
- User is not supposed to enter credentials in web-view anymore during the app usage, so all refresh operations should happen in background (the only exception is our OpenID refresh token expiration)
- Our OpenID token lives a few mins, Cognito Identity Provider token lives 1hr, so after 1hr we get `signedOutFederationTokensInvalid` error
- We have many calls to AWS resources, so there is a chance that before we get `signedOutFederationTokensInvalid` and manage to refresh this Cognito token in background, several AWS calls may fail.

Some must-have requirements to our refresh mechanism are:
1. Seamless background work
2. Support execution order
3. Support concurrent execution

This requires some work in application layer, that I would like to have in Amplify layer if possible :)
And if we would need to write a custom refresh mechanism in application layer, in my opinion, it would easier to implement it before this kind of error occurs rather than after. For this case we just need to know when Cognito token expires.

Please let me know if you need a bit more details.

**Comment by lawmicha** [comment]
Hi @ppave, thanks for explaining. I found the docs that says the cognito session will expiry in one hour: https://docs.aws.amazon.com/cognito/latest/developerguide/accessing-aws-services.html

To better understand how the work could exist in the Amplify layer, what would the custom refresh mechanism look like in the application layer? Are you going to proactively refresh it before the hour expiry time?

**Comment by ppave** [comment]
Hi @lawmicha sorry for delay.

It's quite tricky to rely only on duration, would be better to rely on `createdAt` & `duration` or `expiredAt` params that hold ISO 8601 date. 

So in this case, before performing any API calls, I think we can do in app layer something like:

```swift
let shouldRefreshToken =  currentDate.addingTimeInterval(fiveMinutes) >= expirationDate
```

**Comment by thisisabhash** [comment]
Hello,
We have made several improvements to Amplify in v2 with respect to Auth category. Please let us know if this is still a problem.

https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios/
https://github.com/aws-amplify/amplify-swift/releases/tag/2.15.2

**Comment by atierian** [comment]
See [Identity Pool Federation > Token Refresh](https://docs.amplify.aws/lib/auth/advanced/q/platform/ios/#token-refresh) for more information. Thanks!
