### ISSUE TITLE
Add warning when adding AWSDataStorePlugin without AWSAPIPlugin

### ISSUE THREAD

**Issue by rochabr** [aws-amplify/amplify-swift#1093]
**Is your feature request related to a problem? Please describe.**
If a developer is using DataStore in offline mode, it is not very clear in the documentation that they need to enable AWSAPIPlugin to sync data to the cloud. The information is there, but not easily accessible.

**Describe the solution you'd like**
When initializing AWSDataStorePlugin in offline mode, add a warning message when running Amplify.configure() to notify the developer that, in order to sync data to the cloud, AWSAPIPlugin() also needs to be initialized. Letting the user know that they are working in offline mode only would prevent a lot of confusion as the user may think that the data is being synced to the cloud as well.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by palpatim** [comment]
Hi @rochabr,

The DataStore plugin does [emit a log message](https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Storage/StorageEngine+SyncRequirement.swift#L17) at `info` level when attempting to start sync without a configured API plugin. We actually debated the correct level for this and settled on `info` since we didn't want to add cruft to the logs for local-only use cases.

Hope this helps.

**Comment by rochabr** [comment]
Thanks for the answer, @palpatim. 

I still think that if I don't setup the log level, which I believe is something that a lot of first-timers will do, they will end up stumbling upon this and wonder why they are getting a success message and DynamoDB is not being updated. 

It'd would save beginners a few hours of debugging and frustration.

**Comment by palpatim** [comment]
The balance we want to strike is between the local-only use case, and an error where DataStore is expected to sync, but doesn't. Unfortunately, we haven't figured out a good way to discern the developer's intent in code other than inspecting for the existence of the API plugin.

We'll take this as feedback to do a better job surfacing the requirement to add the API plugin to enable DataStore sync, which may involve work in docs or the CLI, as well as messages on the console.

**Comment by rochabr** [comment]
Thanks for the help, @palpatim!

**Comment by rochabr** [comment]
@palpatim look at the first comment in [this video](https://www.youtube.com/watch?v=9UjP_TJOY5E) from @Kilo-Loco. This is a flutter example, but it paints the picture of what I'm proposing. New users are getting confused about this and they will not setup the log level in the beginning.

**Comment by lawmicha** [comment]
> look at the first comment in [this video](https://www.youtube.com/watch?v=9UjP_TJOY5E) from @Kilo-Loco. This is a flutter example, but it paints the picture of what I'm proposing

@rochabr I'm not sure which comment you're referring to, could you copy it to here for us to see?

**Comment by thisisabhash** [comment]
This is currently mentioned in the new documentation: 
https://docs.amplify.aws/lib/datastore/sync/q/platform/ios/#setup-cloud-sync

Please let us know if this is still a problem.
