### ISSUE TITLE
Too many models don't allow datastore syncing

### ISSUE THREAD

**Issue by 3m** [aws-amplify/amplify-swift#1106]
**Describe the bug**
I have a schema.graphql with 37 model/schema types.  When I run my iOS project and perform an amplify query (which starts the syncing process), I get a tremendous number of messages in the console, but the one appears to be the description of why syncing does not work is:

AppSyncRealTimeClient.AppSyncJSONValue.string("MaxSubscriptionsReachedError"), "message": AppSyncRealTimeClient.AppSyncJSONValue.string(

"**Max number of 100 subscriptions reached**"

)])])
lient.AppSyncJSONValue.object(["errorType": AppSyncRealTimeClient.AppSyncJSONValue.string("MaxSubscriptionsReachedError"), "message": AppSyncRealTimeClient.AppSyncJSONValue.string("Max number of 100 subscriptions reached")])]))

If I manually comment out all but 1 model in the AmplifyModels.swift so that only that single model registers, then the same code to query and save that model works and the syncing works (so I know I have everything configured properly... I can even manually add a record via AdminUI and see it show up on client).

I saw somewhere you could add @model(subscriptions: null) and I updated my @model attribute to that, and then regenerated the models (and amplify push), but when all 37 models registered (the AmplifyModels.swift got regenerated without my comments) I get the same error about max subscriptions reached.

Question:  Is there a way to specify only the tables that need to be synced?  If not, does that mean data store syncing only works with 33 tables (onCreate, OnUpdate, onDelete = 3 x 33 = 99)?

**Environment(please complete the following information):**
 - Amplify Framework Version: 1.5.3
 - Dependency Manager: Cocoapods
 - Swift Version: 5.0
 - CLI Version: 4.45.0

**Device Information (please complete the following information):**
 - Device: 
 - iOS Version: iOS 14.4
 - Specific to simulators:  iPad Simulator - iPad Pro (12.9) - 4th generation

**Comment by palpatim** [comment]
@3m You can define types used in your application as standard GraphQL types, without annotating them as `@model`. This will allow you to work with generated type code in your application, but will not create local DataStore tables or attempt to sync them. Currently, though, syncing is an all-or-nothing proposition on `@model`s for your app domain--we don't expose a way to treat data as "local-only".

We'll explore options for the max subscription error. Can you provide some more context around your use case for not syncing some models while syncing other ones? What local-only data would you like to be operating with?

**Comment by 3m** [comment]
I think I have found a work around — if I comment out some of the models in AmplifyModels.swift, it will not try and store them locally, but I can still use Amplify.API.mutate to hit the Appsync graphql endpoint on all of the models and thus update the dynamo db tables.

I don’t really want to to have some local and some not, I was just trying to figure out a way for this to work since currently the max subscription error is preventing it from working at all if there are too many tables.  Some of the tables are accessed much less frequently so I can use the API category for CRUD on those, but ideally I could work with everything locally and let Amplify do it’s magic to get it to the cloud for me.

Thanks much.

**Comment by felixolivares** [comment]
Is there a work around for schemas with 33+ tables ? I'm getting also the "Max number of 100 subscriptions reached" warning and I get the point where I cannot update my data, either from the admin UI or from my app. Is there anything we can do in this case to avoid subscriptions for just some specific tables ?

**Comment by lawmicha** [comment]
This looks related https://github.com/aws-amplify/amplify-js/issues/6260 For anyone coming back here now, this is an AppSync limit, you can request the limit to be increased via support team. (https://github.com/aws-amplify/amplify-js/issues/6260#issuecomment-1133229983)
