### ISSUE TITLE
Add ability to keep multiple configurations, e.g. a dev and prod one at the same time

### ISSUE THREAD

**Issue by cosimtaiuz** [aws-amplify/amplify-swift#1171]
It would be useful to be able to keep multiple `amplifyconfiguration.json` files at the same time, so that one can choose which database to connect to depending on the build.

E.g. if I'm building the internal test version of our app, it would be useful if I could just switch between the different GraphQL endpoints for dev and prod without having to run `amplify checkout env` etc etc.

It would be way more useful if I could do this via a scheme and xcconfigs on my own; Amplify would only need to let me have multiple configuration files at the same time, one per env, so that I can pass the correct one to the the initializer of `AmplifyConfiguration`. I'd create multiple schemes and targets which allow me to switch between my prod and dev environments via Xcode and to use different GraphQL and whatever else endpoints via Xcode rather than by amplify checkout.

This way I could always build both versions with different endpoints without having to amplify checkout.

**Comment by nmccann** [comment]
Not as nice as having built in support, but I'm accomplishing something like this via a Build Phase and environment variable: 
```
if [ -z "$ENV" ]; then
    echo "No ENV specified"
else
    echo "Copying ENV files for $ENV"
    cp -r "$PROJECT_DIR/amplifyconfiguration-$ENV.json" "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/amplifyconfiguration.json"
    cp -r "$PROJECT_DIR/awsconfiguration-$ENV.json" "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/awsconfiguration.json"
fi
```

This assumes that your files are named like `amplifyconfiguration-DEV.json`, and have a user defined build setting called `ENV`

**Comment by palpatim** [comment]
It sounds like you're asking for the CLI to allow for multiple configuration files to co-exist in the same source tree, is that right? If so, we'd need to take that up as a CLI feature request, although it's not clear how we would actually make that work in a way that's easier than just invoking `amplify checkout env`.

As a workaround, you could use @nmccann's suggestion. Or to avoid custom build phases, you could check out config files per environment, rename them as needed, and define them in an [.xcconfig file](https://nshipster.com/xcconfig/). Then, according to which config is active, you could use the same Amplify initialization code to retrieve the file from your local filesystem.

**Comment by EmmanueleVilla** [comment]
Can we also have an example on how to do this at runtime? Meaning have no .json file and initialize the configuration programmatically. There's an example here https://docs.amplify.aws/sdk/configuration/setup-options/q/platform/ios#configure-using-an-in-memory-object using the mobileClient object, but it doesn't work when using the AmplifyConfiguration obj

**Comment by EmmanueleVilla** [comment]
If you wish to add it to the documentation, I've managed to initialize the configuration at runtime by debugging the library and see the correct structure (also @cosimtaiuz you could use this approach instead of embedding different jsons):
```
func buildAuthConf() -> [String: JSONValue] {
        return [
               "awsCognitoAuthPlugin": [
                   "IdentityManager": [
                       "Default": [:]
                   ],
                   "Auth": [
                       "Default": [
                           "authenticationFlowType": "String"
                       ]
                   ],
                   "CognitoUserPool": [
                           "Default": [
                               "PoolId": "String",
                               "AppClientId": "String",
                               "Region": "String"
                       ]
                   ],
                   "CredentialsProvider": [
                       "CognitoIdentity": [
                           "Default": [
                               "PoolId": "String",
                               "Region": "String"
                           ]
                       ]

                   ]
               ]
           ]
    }

func buildApiConf() -> [String: JSONValue] {
    var api: [String: JSONValue] =
                [
                "awsAPIPlugin": [
                    "apiName" :  [
                        "endpoint": "String",
                        "endpointType": "String",
                        "authorizationType": "String",
                        "region": "String"
                    ]
                ]
            ]
}

func do() {
    let authConf = AuthCategoryConfiguration(plugins: buildAuthConf())
    let apiConf = APICategoryConfiguration(plugins: buildApiConf())
    let config = AmplifyConfiguration(
                analytics: nil,
                api: apiConf,
                auth: authConf,
                dataStore: nil,
                hub: nil,
                logging: nil,
                predictions: nil,
                storage: nil
            )
    try Amplify.configure(config)
    Ecc Ecc...
}
```

**Comment by harsh62** [comment]
Closing in favor of https://github.com/aws-amplify/amplify-swift/issues/1205.
