### ISSUE TITLE
Multiple Amplify.configure() in the same project

### ISSUE THREAD

**Issue by SiddharthChoudhary** [aws-amplify/amplify-swift#1205]
**Is your feature request related to a problem? Please describe.**
Hello all, whoever is active on this thread. I have been facing an issue exactly like this. Currently, I am building an SDK for our team and that SDK is for iOS which uses AWS REST APIs to interact with API GW.  I am using Amplify for that. Everything works as long as the client app importing our SDK doesn't have their own Amplify setup. 

When it does, one ends up in a situation where you can't configure Amplify twice! like Amplify.configure().  Also, not to mention the conflicts between configuration.json files sometimes. We are planning to move away from Amplify now cause even for just hitting one API request there're bunch of configurations and setup needed which doesn't even work for this use case.  

So, before doing that, I wanted to ask someone here that is it even possible to make this work?  Using Amplify SDK as a third party tool in our own SDK and then to avoid clashes between the client app leveraging our SDK at the very end.

**Describe the solution you'd like**
To have a multiple Amplify.configure() object support in the same project

**Describe alternatives you've considered**
Trying to set the configuration at the runtime but I am not sure if that's gonna work

**Additional context**
It's similar to this issue here :- https://github.com/aws-amplify/amplify-js/issues/2501

**Comment by mmolinahn** [comment]
@atierian You market this as completed, but I can't find the PR or docs on how to use the new feature

**Comment by atierian** [comment]
This was closed in favor of https://github.com/aws-amplify/amplify-swift/issues/1584
