### ISSUE TITLE
tvOS Support

### ISSUE THREAD

**Issue by abdelrahman-ahmed** [aws-amplify/amplify-swift#1235]
**Is your feature request related to a problem? Please describe.**
I have cross Apple platforms applications that run on iOS, tvOS, iPadOS, and macOS so we need to use amplify for all of the applications.

**Describe the solution you'd like**
Amplify does not support other Apple platforms tvOS, macOS and iPadOS.

**Describe alternatives you've considered**
tvOS Support highly needed.

**Additional context**
tvOS Support highly needed.

**Comment by Fredposk** [comment]
Any news on tvOS support?

**Comment by ruisebas** [comment]
Hi @Fredposk, thank you for reaching out.

Yes, we do plan on introducing tvOS support for Amplify for Swift. While we don’t have a timeline that we can share at the moment, we will keep you updated as we make progress towards this.

In the meantime, would you mind sharing your use case with us?

Thank you!

**Comment by Fredposk** [comment]
We have an iOS app and are building a new native tvOS app. Most of our iOS users use Apple ID or email to log in (web credentials) so it has been a source of complaints from testers that we can't actually log them in tvOS and save the tokens to keychain and refresh the session. Our use case is for amplify auth in tvOS.

**Comment by ruisebas** [comment]
`tvOS` support has been added in version [2.12.0](https://github.com/aws-amplify/amplify-swift/releases/tag/2.12.0)
