### ISSUE TITLE
Storage supporting more than 1000 keys (ie pagination)

### ISSUE THREAD

**Issue by jamescrowley** [aws-amplify/amplify-swift#1286]
**Describe the solution you'd like**
I expected Amplify.Storage to enable me to paginate beyond the 1000 key limit using NextContinuationToken or similar.

**Describe alternatives you've considered**
The only alternative right now seems to be to drop down to the S3 client, but this seems like a pretty basic requirement to support pagination?

Have I missed something?

**Comment by jamescrowley** [comment]
Commenting to avoid going stale.

**Comment by jcjimenez** [comment]
Hi, @jamescrowley, I just merged the addition of pagination to the v2 version of Amplify for Swift. Please give it a few days for this to make it to a release tag.
