### ISSUE TITLE
Support for failable/throwing GraphQL document decorators

### ISSUE THREAD

**Issue by diegocstn** [aws-amplify/amplify-swift#1291]
We should expand our GraphQL document decorators system so structs/classes conforming to `ModelBasedGraphQLDocumentDecorator` can provide a validation step and throw an error if a request is obviously malformed so that DataStore/API can fail early without sending the request over the wire.

An example of where this would be handy is when we send a subscription request for a model with an @auth rule requiring the `owner` field and there's no user authenticated.

**Additional context**

**Comment by lawmicha** [comment]
This is more of an improvement, ideally we can do it together with a feature we're looking to support. Moving this to internal tracking
