### ISSUE TITLE
Check for new installations before loading credentials from keychain

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-swift#1314]
**Is your feature request related to a problem? Please describe.**
As described in https://github.com/aws-amplify/amplify-ios/issues/1016 and https://github.com/aws-amplify/amplify-ios/issues/1185, if an end user signs in, uninstalls the app, then reinstalls the app, Amplify will read persisted credential data from the keychain.

This is current behavior, and working as designed, as described in our docs: https://docs.amplify.aws/lib/info/app-uninstall/q/platform/ios

However, it is not really expected that credentials should persist that way. 

**Describe the solution you'd like**
Amplify should adopt a strategy like the one we describe in those docs: store a "previously launched" flag in something like UserDefaults, that gets removed when an app is uninstalled. If the "previously launched" flag is not present at launch:
- Add the flag
- Clear credential data from the keychain

before proceeding with Auth configuration.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by VishnuNCS** [comment]
@palpatim ,

As described [here](https://github.com/aws-amplify/amplify-ios/issues/1016#issuecomment-775451665), `privateSession` is not working when we do `Auth.signout` for socialLogin after uninstalling and installing the app again. As described [here](https://github.com/aws-amplify/docs/pull/2941) we are checking `firstLaunch` from `userDefaults` It shows the sign alert. But it should not display any alert if we enable `privateSession` right? Can you please help to give some inputs on this

![test](https://user-images.githubusercontent.com/77132928/127281422-d88fa85c-0aa6-42c3-9158-2c9140f62df6.png)

**Comment by palpatim** [comment]
You can only specify `privateSession` during sign in, and that value is persisted in storage that gets removed on app uninstall. If you do a `signOut` in a context where Amplify Auth cannot determine whether `signIn` was invoked with a private session, then it defaults to assuming that `privateSession` was NOT set, and would invoke the ASAuthenticationWebSession without setting the `prefersEphemeralWebBrowserSession` flag.

I can't think of a good workaround for this with the Amplify API, short of using an escape hatch to clear the keychain rather than invoking signout:

```swift
func clearKeychain() throws {
    let plugin = try Amplify.Auth.getPlugin(for: "awsCognitoAuthPlugin") as? AWSCognitoAuthPlugin
    guard case .awsMobileClient(let awsMobileClient) = plugin?.getEscapeHatch() else {
        print("Failed to fetch escape hatch")
        return
    }
    awsMobileClient.clearKeychain()
}
```

@royjit can you think of any other workaround?

**Comment by royjit** [comment]
yes, I think that is the best option I can think of now. 

For future reference - https://developer.apple.com/forums/thread/36442?answerId=281900022#281900022

**Comment by syedhali** [comment]
Hey is there any progress on this? We're having the same issue in our app after logging in using the `preferPrivateSession` option with the web UI and then doing fresh install of the app while the user was still logged in.

**Comment by harsh62** [comment]
The team is actively working on 2.0.0 milestone which be released soon. We will post an update on the ticket after an update has been released.

**Comment by harsh62** [comment]
[Amplify 2.0](https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims) has been released that includes the feature of removing credentials from Keychain if the library detects it was a new installation.
