### ISSUE TITLE
No guidance on implementing TOTP with custom UI

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-swift#1399]
I have an iOS amplify project.  I have selected optional MFA for the Cognito User Pools.

Now I am building the UI for users to enable MFA on an optional bases.  But there doesn't to be any documentation at all for MFA.  I would like to have an authenticator (TOTP) based MFA.

Is this available for iOS?  And if so where can I find an example on what calls I need to make?

**Comment by royjit** [comment]
TOTP is not yet available in iOS, we will mark this as a feature request.

**Comment by royjit** [comment]
Closing this as duplicate, please follow https://github.com/aws-amplify/amplify-swift/issues/938 for update regarding TOTP support and selecting MFA option.
