### ISSUE TITLE
DataStore update mutation always sends all field values instead of only updated fields

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-swift#1450]
### Describe the bug

Original issue: https://github.com/aws-amplify/amplify-flutter/issues/930

Taking schema

```graphql
type AModel @model {
  id: ID!
  name: String!
  list: [Int]
}
```
Assuming a model with `list` value `[0, 1, 2]`, when update the `name` field of this model. It results `list` as `[0, 1, 2, 0, 1, 2]`. An unexpected conflict auto merge occurred.

The cause is that the update mutation GraphQL document included all fields instead of only updated fields.'

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Use any schema to use with DataStore
2. Update model
3. Observe GraphQL document
```

### Expected behavior

With an update mutation, the underlying GraphQL document should send only updated fields.

In addition, if I want to only update an element in the list, how it can avoid triggering auto merge?
e.g.
```
[0, 1, 2] => [0, 0, 2] instead of [0, 1, 2] => [0, 1, 2, 0, 0, 2]
```

### Amplify Framework Version

1.13.0

### Amplify Categories

DataStore

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

5.3.0

### Xcode version

13.0

### Device

iPhone 13 simulators

### iOS Version

iOS 15

**Comment by harsh62** [comment]
Closing the ticket because its stale and lot of refactors have been done in the codebase. Please reopen if its still an issue.
