### ISSUE TITLE
Recreate a Cognito user from the access, id and refresh tokens

### ISSUE THREAD

**Issue by jorgefrazaocosta** [aws-amplify/amplify-swift#1497]
### Is your feature request related to a problem? Please describe.

I'm using Amplify in an iOS app with a Safari Web Extension. 

Since it's not possible to share the same session between them, I would like to propose or ask if there is any way to recreate a Cognito session from the Web Extension in the iOS app.

The opposite (recreate an iOS session in the Safari Web Extension) is possible, following the creation of a CognitoUser and a CognitoUserSession presented in the [amplify JS library](https://github.com/aws-amplify/amplify-js/issues/2253).

### Describe the solution you'd like

Can we have something like the Amplify JS's implementation?

Something like @powerful23 describes:

```
const user = new CognitoUser({
     Username: username,
     Pool: new CognitoUserPool(...)
});

const session = new CognitoUserSession({
    IdToken,
    AccessToken,
    RefreshToken
});

user.setSignInUserSession(session);
```

I tried to create `AWSCognitoIdentityUserSession` or `AWSCognitoIdentityUser` but every property is read-only. 

### Describe alternatives you've considered

Right now, we are always requesting the user to Sign In at the iOS App.
Can I achieve this using the [AWS-SDK-iOS](https://github.com/aws-amplify/aws-sdk-ios)?

### Is the feature request related to any of the existing Amplify categories?

Auth

**Comment by royjit** [comment]
This is not currently possible with Amplify iOS, will take this as a feature request.

**Comment by royjit** [comment]
Closing this as duplicate for - https://github.com/aws-amplify/amplify-swift/issues/2508
