### ISSUE TITLE
Remove usage of the deprecated getIdentityId() in APIPlugin, Storage, etc

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-swift#1506]
> are there a lot of internal usages of the now deprecated API? I know storage plugin internally uses .getIdentityId() . perhaps we can make a list in this PR, then reference the list in an issue for us to track updating internal usages of the deprecated API.

https://github.com/aws-amplify/amplify-ios/search?q=getIdentityId

follow up to remove usage of the deprecated API in APIPlugin, Storage, etc

_Originally posted by @lawmicha in https://github.com/aws-amplify/amplify-ios/issues/1502#issuecomment-962103221_

**Comment by royjit** [comment]
This should be fixed in Amplify v2.0.0

**Comment by royjit** [comment]
Fixed in v2.0.0
