### ISSUE TITLE
How can I use Amplify Auth in a Notification Service Extension

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-swift#1538]
My app uses a few extensions such as the Notification Service Extension and Share Extension.  In the Share extension I need to be able to save items to my backend.  So I need to use API.mutate.

For this I have to share the Auth from the main app to the extension.  How can I do this?

**Comment by royjit** [comment]
Extension support is not yet available in Amplify, we will take this as a feature request.

**Comment by lawmicha** [comment]
let's take an action item to update Amplify documentation site to call out which type of Application templates are supported and which are not

**Comment by royjit** [comment]
Closing this as duplicate for https://github.com/aws-amplify/amplify-swift/issues/2508
