### ISSUE TITLE
There seems no way to capture GraphQL error triggered on DataStore mutation

### ISSUE THREAD

**Issue by HuiSF** [aws-amplify/amplify-swift#1555]
### Describe the bug

Some DataStore mutations may trigger GraphQL error. For example, saving an invalid url to a model field with type `AWSURL`. The data will be saved locally in SQLite without issues, the data however, cannot be synced to cloud due to the underlying GraphQL error. 

According to the [library documentation](https://docs.amplify.aws/lib/datastore/conflict/q/platform/ios/#custom-configuration-fields), a custom `errorHandler` should be provided to capture background operation errors. After testing, however, provided `errorHandler` has never been invoked on above described GraphQL errors, and the errors became silent.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Initialize DataStore with `errorHandler`
2. Trigger GraphQL error by a mutation
3. Data saved into local DB
4. Data cannot be synced to DynamoDB
```

### Expected behavior

The provided `errorHandler` should be invoked on background GraphQL errors. Or a configurable mechanism should be provided to handle this type error.

### Amplify Framework Version

1.16.0

### Amplify Categories

DataStore

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

The latest

### Xcode version

13.0

### Is this a regression?

No

### Device

iPhone 13 simulators

### iOS Version

iOS 15

**Comment by HuiSF** [comment]
Hi @diegocstn any progress update on this issue?

**Comment by applyinnovations** [comment]
Hey @diegocstn @ameter I have also logged the same issue on the `amplify-js` repository which is still open https://github.com/aws-amplify/amplify-js/issues/8891

**Comment by undefobj** [comment]
This is being tracked internally across platforms for standardized error handling and not swallowing service errors that conflict with the clients. @HuiSF please connect with PMs and SDMs on this to align with the spec.

**Comment by lawmicha** [comment]
When we worked on a related issue, handling "cannotParseError" error in the sync handling logic (https://github.com/aws-amplify/amplify-swift/pull/2532), we also made sure that the `errorHandler` gets called in all code paths. See this comment for more details https://github.com/aws-amplify/amplify-swift/pull/2532#discussion_r1014284029 It's an incremental step towards standardizing error handling, with making sure the error is not being swallowed.

**Comment by lawmicha** [comment]
Let's keep this open until we verify that the example ` saving an invalid url to a model field with type AWSURL` does infact propagated to the errorHandler

**Comment by lawmicha** [comment]
Debugging this

https://docs.aws.amazon.com/appsync/latest/devguide/scalars.html
```
AWSURL
A URL as defined by [RFC 1738](https://tools.ietf.org/html/rfc1738). For example, https://www.amazon.com/dp/B000NZW3KC/ or mailto:example@example.com. URLs must contain a schema (http, mailto) and can't contain two forward slashes (//) in the path part.
```

Passing in "not a url" as the string will fail with
```
GraphQLError missing extensions and errorType GraphQLError(message: "Variable \'url\' has an invalid value.", locations: Optional([Amplify.GraphQLError.Location(line: 1, column: 21)]), path: nil, extensions: nil)
```

Corresponding lines https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/MutationSync/OutgoingMutationQueue/ProcessMutationErrorFromCloudOperation.swift#L125-L126

This code path does call the error handler.

```swift
log.debug("GraphQLError missing extensions and errorType \(graphQLError)")
dataStoreConfiguration.errorHandler(DataStoreError.api(graphQLResponseError, mutationEvent))
```

Amplify V1 should have the same since the [fix](https://github.com/aws-amplify/amplify-swift/pull/2532) was applied to both `main` and `V1`

I'll close this now since we've verified this scenario results in calling the error handler.
