### ISSUE TITLE
File upload with % fails with non-useful error message

### ISSUE THREAD

**Issue by dkman94** [aws-amplify/amplify-swift#1608]
### Describe the bug

When trying to upload a file I inadvertently added a space to the file name, which was then translated to a string creating a upload with the following URL `.../task_ios_test%201_1643153821021.mp4`. The upload then failed with the below error message.

```
Failed: Unexpected error occurred with message: Domain: [com.amazonaws.AWSS3TransferUtilityErrorDomain
Code: [2
LocalizedDescription: [The operation couldn’t be completed. (com.amazonaws.AWSS3TransferUtilityErrorDomain error 2.)
LocalizedFailureReason: [
LocalizedRecoverySuggestion: [. This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an is
````

After a bit of trial and error, I tried with the following file name or URL `task_ios_test1_1643153821021.mp4` and the upload worked successfully. 

A more useful error message for unsupported file names (I'm guessing the space or % is not supported) would allow for better debugging for other developers facing the same issue. 

### Steps To Reproduce

```swift
Attempt to upload file using Amplify SDK call and fileNameKey containing a `%` or `space` character (e.g. `test%20`)

Amplify.Storage.uploadFile(
            key: fileNameKey,
            local: filename,
            progressListener: { progress in
```

### Expected behavior

Provide a more useful error message when the upload has failed, such as `The file name key is unsupported. Please try without spaces or formatted spaces such as %, and try again.`

### Amplify Framework Version

1.17.0

### Amplify Categories

Storage

### Dependency manager

Swift PM

### Swift version

5.3

### CLI version

7.6.5

### Xcode version

13.2

### Is this a regression?

No

### Device

iPhone 12 Mini

### iOS Version

15.1.1

**Comment by royjit** [comment]
Thank you for reaching us, most of the S3 operations are done through pre-signed urls. We do not get detailed response from these operations regarding failures, and we have to rely on status codes to find the error. We will look into this and try to provide a better error code/message. Next steps for amplify team:
1. Check the status returned by server and see if we can propagate the error to the api
2. Check if we can validate the input before calling presigned urls and return error early

**Comment by atierian** [comment]
This is resolved in Amplify Swift v2. For a list of characters that are safe and characters to avoid in key names, please see [Object key naming guidelines](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html#object-key-guidelines).

Thanks!
