### ISSUE TITLE
Using DataStore and custom mutations/queries in the same project via AppSync in iOS

### ISSUE THREAD

**Issue by maziarzamani** [aws-amplify/amplify-swift#1615]
Hi everyone. 

I am currently working on a project where we are utilizing DataStore to its fullest extend. However we recently ran into a problem where we need to utilize custom mutations/queries, which are unfortunately not functioning with the DataStore logic, but generated in the legacy `API.swift` file.

So my question is, is it possible to use the DataStore API logic while also using the AppSync client? And are there any examples on this? This does not seem to be clear in the documentation, and it is lacking these use-cases side-by-side.

If the answer is "no", is there a workaround to call these custom mutation/queries?

UPDATE: On [this page](https://docs.amplify.aws/lib/graphqlapi/concepts/q/platform/ios/) for iOS it describes three concepts for AWS AppSync, we are using the Amplify DataStore, but as far as I understand we also need AWS AppSync SDK, however we recently noticed that API.swift and the generated models are somehow conflicting (see the screenshot of API.swift in Xcode)?

Best regards, M.

**Which Category is your question related to?**
Amplify and iOS

**Amplify CLI Version** 
7.6.11

**What AWS Services are you utilizing?**
AppSync

<img width="1472" alt="Screen Shot 2022-01-25 at 14 04 12" src="https://user-images.githubusercontent.com/1084199/150984016-a6ee93a3-029f-4c24-8052-d274caa3a784.png">

**Comment by lawmicha** [comment]
Using AppSync SDK can get the work done if your specifically hitting other AppSync APIs that do not conflict with DataStore, but it's not a set of dependencies we're tested fully (which is probably why you are seeing some type conflicts). We'd like to support deveopers to use API plugin and DataStore in the same app, and have some plans for this (marking this issue as feature request). If it's a conflict in the naming of types generated for DataStore and API.swift, can you update API.swift manually to see if you can be unblocked? If you are infact just hitting one endpoint, you can also do custom graphql documents via https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios/

**Comment by maziarzamani** [comment]
We actually made a workaround by implementing the GraphQL calls manually with the AppSync SDK by writing them inline, not super optimal to be honest as I would expect the API.swift and DataStore to co-exist. :-/

**Comment by lawmicha** [comment]
Glad to hear you got it working, we would like to deprecate AppSync SDK and have developers directly use API via `Amplify.API` for the same use case, along side DataStore

**Comment by maziarzamani** [comment]
Would be great to have that feature!

**Comment by lawmicha** [comment]
if this is still relevant for you, we are introducing a compatibility layer to use API.swift with Amplify.API, please track the release of the documentation describing the Upgrade Guide in here https://github.com/aws-amplify/docs/pull/5649
