### ISSUE TITLE
How to create object with @manyToMany relation?

### ISSUE THREAD

**Issue by alionthego** [aws-amplify/amplify-swift#1630]
I am trying to use the new format for my schema manyToMany relations and there is no documentation to help out.

I am creating an object and want to add the relation.  How do I do this?

```
type Post @model {
  id: ID!
  title: String!
  content: String
  tags: [Tag] @manyToMany(relationName: "PostTags")
}

type Tag @model {
  id: ID!
  label: String!
  posts: [Post] @manyToMany(relationName: "PostTags")
}
```

So if I create a tag:

`let tag = Tag(label: "somelabel")`

how can I add the relation to the post?

Do I need to save the new tag first before adding relation or can I do it in one step?  And if so can someone tell me exactly how to do this?  It's frustrating not to have any examples or documentation to do these things and just keep on with the trial and error approach.

DoI need to query to get the post first (which can be an issue if the post has thousands of tags) then add the post in the new tag's posts?  I tried that unsuccessfully.

**Comment by robsaffi** [comment]
@alionthego were you able to figure this out? I can't find any documentation on the proper way to do this.

**Comment by alionthego** [comment]
@robsaffi when you add the @manyToMany a PostTags type is automatically created for you.  To add the relation you need to have both objects and pass them as arguments to create the PostTags.  So for example you would first query the comment by id to get the comment, then you will create and save the tag.  Finally you will create the PostTag passing the post you just queried and the tag you just saved.
I find it annoying that we can't just pass the id's of the post and tag.  That you actually have to waste another network call to get the object first.
Also I had many issues with naming conventions.  For example ABMessage will not work.  The server will create a reference of aBMessage and the codegen for iOS creates abMessage.  So you will get undefined field.
Also plurals are handled in an odd way that is also different for server and codegen so avoid a y as the last letter of your type.

**Comment by robsaffi** [comment]
@alionthego Thanks for the help with this. So essentially we're creating the tag the first time a tag is used, then each time an existing tag is added to a post, we're adding objects to the joining table "PostTags" with the Post id and Tag id.

**Comment by robsaffi** [comment]
@alionthego Makes sense. Thank you.

**Comment by lawmicha** [comment]
Thanks for opening this and the discussion @alionthego @robsaffi we'll keep this issue open and work on providing a better example when using DataStore and API with many-to-many schemas. There's a test here that showcases the call pattern in DataStore if that helps: https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/DataStore/AWSDataStoreCategoryPluginIntegrationTests/TransformerV2/DataStoreConnectionScenario5V2Tests.swift The call pattern is correct, you have to create the individual models first before saving the joining model for many to many relationship

**Comment by royjit** [comment]
Please find example of manyToMany relationship here - https://docs.amplify.aws/lib/datastore/relational/q/platform/ios/#many-to-many-relationships
