### ISSUE TITLE
Define the depth of eager loaded associations

### ISSUE THREAD

**Issue by drochetti** [aws-amplify/amplify-swift#168]
That's a good question and the part I struggled with. Right now the depth is not specified. This logic will even break in case or circular references.

How to decode missing properties to a Struct that require them? I'm having a hard time keeping the data model types consistent but optimize for performance and different use cases of associations (lazy vs eager, required vs optional)

_Originally posted by @drochetti in https://github.com/aws-amplify/amplify-ios/pull/164_

**Comment by thisisabhash** [comment]
For API, the depth of eager loaded associations can be achieved with custom selection sets.
For Datastore, this is not supported at the moment.
