### ISSUE TITLE
.paginatedList() query fails with Model that has name ending in y

### ISSUE THREAD

**Issue by louiss98** [aws-amplify/amplify-swift#1707]
### Describe the bug

On generated Model+Schema files, model.listPluralName is never set causing an undefined field error with paginatedList queries.

### Steps To Reproduce

```swift
Build api with conflict detection enabled
Create a model with name ending in y : (Story) 
Generate code.
Perform paginated list query on model. Will return error
```

### Expected behavior

Generated Model+Schema to contain a generated listPluralName.

### Amplify Framework Version

1.22.0

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

4.2

### CLI version

7.6.25

### Xcode version

13.2.1

### Is this a regression?

No

### Device

iPhone 8 Simulator

### iOS Version

iOS 12.1

### Additional context

Since there is no listPluralName set the query defaults to ```(queryType.rawValue + name).pluralize()``` resulting in an invalid field when the model name ends in y. For example Storys as opposed to Stories.

```
/// The GraphQL directive name translated from a GraphQL query operation and model schema data
func graphQLName(queryType: GraphQLQueryType) -> String {
    let graphQLName: String
    switch queryType {
    case .list:
        if let listPluralName = listPluralName {
            graphQLName = queryType.rawValue + listPluralName
        } else {
            graphQLName = (queryType.rawValue + name).pluralize()
        }
    case .sync:
        if let syncPluralName = syncPluralName {
            graphQLName = queryType.rawValue + syncPluralName
        } else if let pluralName = pluralName {
            graphQLName = queryType.rawValue + pluralName
        } else {
            graphQLName = (queryType.rawValue + name).pluralize()
        }
    case .get:
        graphQLName = queryType.rawValue + name
    }

    return graphQLName
}
```
ModelSchema file generates a pluralName instead of syncPluralName and listPluralName

**Comment by lawmicha** [comment]
Hi @louiss98, thank you for bringing this to our attention. I provisioned a backend with a `Story` model and can reproduce the issue you are seeing. There's actually a reason why the `.list` case does not use the `pluralName` in the if statement but does for `.sync`, the code change added here https://github.com/aws-amplify/amplify-ios/pull/1451/files#diff-421c7d70a341ab77f247ffb14cd2e2b87fdf781bf3470b684c1b6454596788e0 makes it compatible with previous versions of how the provisioning pluralizes the name. I believe V1 transform for list operation does not use the improved pluralization and sync operation does. 

If we are seeing `Stories` in the backend without `improvePluralization: true` in the cli.json for the list operations then that means the code in the V2 transform that you are using (`"transformerversion": 2`) has the improved pluralization by default for both list and plural.
 
The workaround that you described is the correct workaround for now. By manually adding 
```
// model.pluralName = "Stories" // remove this
model.listPluralName = "Stories" // add this for your use case 
model.syncPpluralName = "Stories" // this will be generated as well with the fix
```

Once this [CLI fix](https://github.com/aws-amplify/amplify-codegen/pull/255) is released, you can upgrade to the latest CLI and it will generate those fields for you automatically.

**Comment by lawmicha** [comment]
Please track https://github.com/aws-amplify/amplify-swift/issues/3135

**Comment by lawmicha** [comment]
Please use Amplify CLI 12.4.0 or greater to get the fix for the pluralization issue
