### ISSUE TITLE
Missing CognitoUserPools AuthProvider in API 

### ISSUE THREAD

**Issue by fjnoyp** [aws-amplify/amplify-swift#1738]
### Is your feature request related to a problem? Please describe.

In Amplify Android API I can provide Cognito User Pool information via a `CognitoUserPoolsAuthProvider`.  While Amplify iOS supports `AuthProviders` it does not have one for `CognitoUserPools`.  

### Describe the solution you'd like

Amplify iOS should have a `CognitoUserPoolsAuthProvider` that I can provide as an `AuthProvider` in the `API` constructor. 

### Describe alternatives you've considered

The only alternative is to add the Auth category and have Amplify iOS get the Cognito user pool information from there. 

### Is the feature request related to any of the existing Amplify categories?

API

### Additional context

It appears that Amplify iOS crashes if Amplify Auth module is not added with API module.  Ideally this shouldn't happen as Android does not crash in this instance.  Furthermore, the `AuthProviders` can give all necessary Auth information without one needing to add the Amplify Auth module anymore ...

**Comment by atierian** [comment]
Thanks for opening this feature request @fjnoyp. We'll update here with any developments.

**Comment by lawmicha** [comment]
Hi @fjnoyp, could you provide a more detailed example of the Android DX? This will help us translate it over to iOS and see what APIs iOS is missing. We should also update the documentation for these use cases in https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/ios/#oidc

**Comment by royjit** [comment]
Amplify Swift has Cognito User Pool as one of the auth provider as mentioned here - https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/ios/#amazon-cognito-user-pools . @fjnoyp does this work for your use case?
