### ISSUE TITLE
DataStore ObserveQuery snapshot on .ready

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-swift#1759]
### Describe the bug

ObserveQuery does not emit a snapshot when the state goes from `isSynced` false to true. Internally, the operation will listen to `.ready` event from the Hub. When this is received, it will mark internally the `isSynced` state to true, but does not emit a new snapshot.

Customer DX issue: If the loading indicator is displayed to the end user, and .ready is received, it should no longer be loading since the data is in sync. The next item update will cause the observeQuery to emit the next snapshot with isSynced true, which means there's a delay in removing the loading indicator.

**Internals**
There is a bit of change required than just emitting the event since the state of the modelSynced event is what's driving the `isSynced` value. Everytime a snapshot is emitted, it's using the `dispatchedModelSyncedEvent` value, which is set by another process. 

### Steps To Reproduce

```swift
.
```

### Expected behavior

.

### Amplify Framework Version

.

### Amplify Categories

DataStore

### Dependency manager

Cocoapods

### Swift version

.

### CLI version

.

### Xcode version

.

### Is this a regression?

No

### Device

.

### iOS Version

.

**Comment by diegocstn** [comment]
An edge case to consider is when the dataset is empty. `observeQuery` should emit a snapshot with `isSynced` true in that scenario as well

**Comment by lawmicha** [comment]
Thinking about this some more, i think it's as simple as the DataStoreObserveQueryOperation to emit a snapshot on .ready event. the problem is addressing emitting two snapshots, one for the .ready event and one for the `dispatchedModelSyncedEvent`. empty data set scenario can be tested and should have no impact on this change

**Comment by lawmicha** [comment]
this was released in https://github.com/aws-amplify/amplify-swift/releases/tag/v2.0.0 and https://github.com/aws-amplify/amplify-swift/releases/tag/v1.28.2
