### ISSUE TITLE
schema.graphql isn't automatically added to the Xcode project

### ISSUE THREAD

**Issue by atierian** [aws-amplify/amplify-swift#1765]
### Describe the bug

When a schema.graphql file is generated by the CLI, it is not automatically added to the Xcode project. This results in `amplify codegen` / `amplify push` + `generate code` failing. 

This docs PR adds a callout explaining how to manually add the file. 
https://github.com/aws-amplify/docs/pull/4251
This is temporary and must be removed from the docs after the underlying issue is fixed.

### Steps To Reproduce

```swift
- `amplify add api` > `graphql` to generate a schema.graphql
- `codegen models` 💥
```

### Expected behavior

When a `schema.graphql` is generated, it should automatically be adding to the Xcode project / main target.

### Amplify Framework Version

1.23.1

### Amplify Categories

API, DataStore

### Dependency manager

Swift PM

### Swift version

5.6

### CLI version

8.0.2

### Xcode version

13.3.1

### Is this a regression?

Yes

### Regression additional context

Worked on previous combinations of Amplify CLI + Xcode. Unsure of when the regression first occurred.

### Device

n/a

### iOS Version

n/a

**Comment by lawmicha** [comment]
Hi @atierian, the source schema `schema.graphql` get used by `amplify codegen` and `amplify push`. I don't think it needs to be added to Xcode, is there an issue you were seeing when it doesn't get added?
