### ISSUE TITLE
In a multipart upload using Amplify.Storage.uploadFile, pre-signed URLs for each part should have 50 minute expiration from the time that each part is created instead of the time from which the first part is created

### ISSUE THREAD

**Issue by sagarjoshi** [aws-amplify/amplify-swift#1838]
### Is your feature request related to a problem? Please describe.

I am hoping that this is a smaller fix than re-thinking the entire approach ( https://github.com/aws-amplify/amplify-ios/discussions/1740 )  which includes this idea + background uploads. Some of my users with poor upload bandwidth are running into timeout issues for large files.

### Describe the solution you'd like

in the title :) 

### Describe alternatives you've considered

long discussion here around longer term approach ( https://github.com/aws-amplify/amplify-ios/discussions/1740 ) 

### Is the feature request related to any of the existing Amplify categories?

Storage

**Comment by sagarjoshi** [comment]
@brennanMKE  FYI

**Comment by sagarjoshi** [comment]
Also , I am assuming that all the parts are not created at once. If they are then feel free to redo the bug.

**Comment by brennanMKE** [comment]
The way the SDK works has been this way for many years. The new Swift SDK will create the pre-signed URL just as the upload for a part is about to start, so it has the behavior that would handle the timeout better. If you'd like this update in the SDK please create a feature request. We are working on the Dev Preview for the new Amplify GA release which you may find will include many improvements that you want.

**Comment by brennanMKE** [comment]
@sagarjoshi Also check out the discussion below. WWDC starts Monday and I will try to get a lab session to discuss this issue.

https://github.com/aws-amplify/amplify-ios/discussions/1740

**Comment by sagarjoshi** [comment]
sorry, somehow I missed this. I thought https://github.com/aws-amplify/amplify-ios/issues/1838 was the feature request. 

Also please let us know the result of the discussion for https://github.com/aws-amplify/amplify-ios/discussions/1740

**Comment by sagarjoshi** [comment]
@brennanMKE

**Comment by sagarjoshi** [comment]
Definitely need this

**Comment by sagarjoshi** [comment]
Cannot reliably upload large files without this

**Comment by atierian** [comment]
@sagarjoshi we recently made improvements to speed at which uploads complete. Please see this comment for more information https://github.com/aws-amplify/amplify-swift/issues/1542#issuecomment-1533006240 and let us know if updating resolves your issue. Thanks!
