### ISSUE TITLE
automatically generated code is diffrent from API, AppSync and DataStore

### ISSUE THREAD

**Issue by bjg2327** [aws-amplify/amplify-swift#1841]
### Describe the bug

I have generated a model named EventNews.
But I'm getting an error in getList.
There is no problem with AWS AppSync Console and DataStore.

an error 

> Got failed result with GraphQL service returned a successful response containing errors: [Amplify.GraphQLError(messagee: "Validation error of type FieldUndefined: \'listEventNews**s**'\ in type \'Query'\ is undefined @\'listEventNews**s**\'", locations: Optional([Amplify.GraphQLError.Location(line: 2, column: 3)]), path: nil, extensions: nil)]

This problem seems to be due to the naming process

listEventNews**s**

```
// Code that causes an error
Amplify.API.query(request: .paginatedList(EventNews.self, limit: 100)
    .resultPublisher
    .sink { if case let .failure(error) = $0 { print("Got failed event with error \(error)") } }
    receiveValue: { result in
        switch result {
            case .success
            ...
           case .failure(let error):
               print("Got failed result with \(error.errorDescription)") // <-- Here
   }

```

```
// No problem with DataStore
Amplify.DataStore.query(EventNews.self)
   ...
```

```
// AWS AppSync Console
query MyQuery {
  listEventNews {
    items {
      id
    }
  }
}
```

### Steps To Reproduce

```swift
1. Generate Model 'EventNews'

2. do Query
Amplify.API.query(request: .paginatedList(EventNews.self, limit: 100)
```

### Expected behavior

Getting the list successfully

### Amplify Framework Version

1.26.0

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

5.6

### CLI version

8.3.1

### Xcode version

13.3.1

### Is this a regression?

No

### Device

iPhone 12 - Simulator

### iOS Version

15.4

**Comment by lawmicha** [comment]
Hi @bjg2327, could you provide us with the contents of your `amplify/cli.json` file from the amplify cli project? specifically `improvepluralization`, `useexperimentalpipelinedtransformer`, and `transformerversion`. 
```
// Example
{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false, // this value
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true, // this value
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2, // this value
      "suppressschemamigrationprompt": true,
      "securityenhancementnotification": false,
      "showfieldauthnotification": false
    },
...
```

There seems to be some regression happening, which i was able to reproduce here https://github.com/aws-amplify/amplify-ios/issues/1707#issuecomment-1079413894
> Once this https://github.com/aws-amplify/amplify-codegen/pull/255 is released, you can upgrade to the latest CLI and it will generate those fields for you automatically.
> CLI Issue: https://github.com/aws-amplify/amplify-codegen/pull/255

**Comment by bjg2327** [comment]
Hi @lawmicha 
Code Here
```
"features": {
    "addmissingownerfields": true,
    "improvepluralization": false,
    "validatetypenamereservedwords": true,
    "useexperimentalpipelinedtransformer": true, 
    "enableiterativegsiupdates": true,
    "secondarykeyasgsi": true,
    "skipoverridemutationinputtypes": true,
    "transformerversion": 2,
    "suppressschemamigrationprompt": true,
    "securityenhancementnotification": false,
    "showfieldauthnotification": false
}
...

```

> Once this https://github.com/aws-amplify/amplify-codegen/pull/255 is released, you can upgrade to the latest CLI and it will generate those fields for you automatically.

Thank you for answering

**Comment by purnachandarr** [comment]
Same issue facing

**Comment by lawmicha** [comment]
Please use Amplify CLI 12.4.0 or greater to get the fix for the pluralization issue
