### ISSUE TITLE
Xcode 14 fails to compile using SwiftUI Previews

### ISSUE THREAD

**Issue by ethan021021** [aws-amplify/amplify-swift#1874]
### Describe the bug

Using the newest Xcode 14 beta my app that uses Amplify (via SPM) will not compile using SwiftUI Preview's. Understandably it's in beta but I wanted to make sure I report this issue early on.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Open the newest Xcode-beta (Xcode 14)
2. Include a Swift Package that depends on Amplify
3. Open a SwiftUI View file and compile the Preview
4. Notice the error that returns from the SwiftUI Preview
```

### Expected behavior

SwiftUI Preview should compile/run

### Amplify Framework Version

1.26.1

### Amplify Categories

Analytics, API, Auth, DataStore, Geo, Predictions, Storage

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

8.3.0

### Xcode version

14.0 (14A5228q)

### Relevant log output

```shell
HumanReadableSwiftError

SettingsError: noExecutablePath(<IDESwiftPackageStaticLibraryProductBuildable:ObjectIdentifier(0x00006000128be7c0):'AWSCore'>)
```
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

iPhone 13 Pro

### iOS Version

iOS 15.5

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by ameter** [comment]
Thanks for reporting this.  Per our discussion on Discord, the betas are not supported, but we want to make sure we're aware of any issues to ensure they're resolved before release.

**Comment by gongzhang** [comment]
@ethan021021 I'm having the same problem here. However, I'm not quite sure if this error message is accurate. Have you tried to perform Generate Report command in the diagnostics window?

**Comment by geertbleyen** [comment]
This likely isn't an amplify issue. See https://developer.apple.com/forums/thread/707569. Others are having the same issues with other packages.

**Comment by sebsto** [comment]
I have the same issue with Xcode 14 GA

My cognito plugin initialization code is in the App Delegate.

Looks like Xcode Canvas (Preview) does not invoke this call to build the preview. The preview crashes with an error saying that Auth Cognito plugin is not initialized.

<img width="523" alt="image" src="https://user-images.githubusercontent.com/401798/190140732-b1dfd61a-d7ee-4d98-aff9-596365dba656.png">

**Comment by sebsto** [comment]
I opened another Xcode preview crash issue here https://github.com/aws-amplify/amplify-ios/issues/2308 
The symptoms are note the same, it might be related, or not

**Comment by ameter** [comment]
We created a [PR to address this problem](https://github.com/aws-amplify/amplify-ios/pull/2317).  The fix has been merged and will be included in our next release, which should be sometime next week.  In the meantime, feel free to target the main branch to test the fix, and let us know if you have any further problems with it.
