### ISSUE TITLE
DataStore ReconcileAndLocalSaveOperationTests fails on Xcode 13.4.1

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-swift#1903]
### Describe the bug

The following unit tests are failing in the test class ReconcileAndLocalSaveOperationTests
- testApplyRemoteModels_saveFail
- testApplyRemoteModels_deleteFail
- testApplyRemoteModels_saveMetadataFail

### Steps To Reproduce

```swift
Save model success
Save model success
Save model success
Save model success
Save model success
Save model success
Save metadata failed
mutationEventDropped(modelName: "Post", error: Optional(DataStoreError: Failed to save metadata))
```
The relevant code in ReconcileAndLocalSaveOperation
```swift
Publishers.MergeMany(publishers)
                .collect()
                .sink(
                    receiveCompletion: {
                        if case .failure(let error) = $0 {
                            result = .failure(error)
                        }
                    },
                    receiveValue: { _ in
                        result = .successfulVoid
                    }
                )
                .store(in: &self.cancellables)
```

It appears the Publisher.MergeMany(publishers).collect() is returning a completion event on the first failure

I think we need to identify what changes in the latest Swift version and behavior change in the Combine Publishers. Is it a regression or new behavior going forward?

**Comment by lawmicha** [comment]
verified this still exists on Xcode Version 14.0 (14A309)

**Comment by lawmicha** [comment]
The unit test that is failing is in ReconcileAndLocalSaveOperation, which is the process for taking models received from AppSync on the syncQuery and performing the reconciliation logic. The behavior of the failure handling appears to have changed with the Combine Publisher's `Publishers.MergeMany(publishers).collect()`. This behavior change in failure scenario means it impacts how DataStore recovers from these failures. 

We need to investigate further this unit test failure further and fix the implementation and test to capture the expected recovery behavior when the reconciliation receives the failure.

**Comment by 5d** [comment]
Closing this issue as the fix has been merged
