### ISSUE TITLE
Feature Request: Expose URLResponse in success case of REST APIs

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [aws-amplify/amplify-swift#1925]
**Which AWS Services is the feature request for?**

API

**Is your feature request related to a problem? Please describe.**
I cannot inspect response headers or status code if the response code is [200..300)--the API signature only returns Result<Data, Error>.

**Describe the solution you'd like**
I would like to be able to inspect the URLResponse object returned by the system so I can grab data contained within headers as well as the response code.

**Describe alternatives you've considered**
Moving away from AWS because this is an important thing to me. My backend sends me additional headers that I should be inspecting.

**Additional context**
None

**Comment by thisisabhash** [comment]
Hello,
You can inspect response headers or status codes like mentioned here in our docs:
https://docs.amplify.aws/lib/restapi/fetch/q/platform/ios/#handling-non-2xx-http-responses

**Comment by royjit** [comment]
Marking as duplicate for https://github.com/aws-amplify/amplify-swift/issues/1435
