### ISSUE TITLE
Wrap async calls in a Task and wait for expectation to prevent hanging tests

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-swift#2216]
For unit tests you will want to wrap these in a Task and use the support for async testing so that if an async function never returns it does not cause all unit tests to stall.

```swift
func testAsyncFunction() async throws {
    let done = asyncExpectation(description: "done")
    Task {
        // call to async function
        // test assertions
    }
    await waitForExpectations([done], timeout: 1.0)
    // test assertions
}
```

_Originally posted by @brennanMKE in https://github.com/aws-amplify/amplify-ios/pull/2214#discussion_r957556620_

See https://github.com/brennanMKE/AsyncTesting/blob/main/README.md for more details

**Comment by lawmicha** [comment]
This issue is a tracking issue to go over all tests in all packages (Amplify/ AWSPluginsCore / AmplifyPlugins DataStore/API/Storage/Analytics/Auth/etc) and add expectations and wait for them, and fulfill them after the async call. 

This prevents the tests from hanging and is especially important for integration tests that have an underlying network call before returning. I think unit tests one prioity less than integation tests (with network calls) since regression in unit testing can be caught locally. If you make a change to the codebase, and run the unit tests, and it is hanging, then you've caused a regression that needs to be fixed before the PR gets merged in. 

This PR https://github.com/aws-amplify/amplify-ios/pull/2214 is scoped to some DataStore changes and this commit can serve as an example of the changes required to improve the test stability.

**Comment by lawmicha** [comment]
Following this pattern for DataStore' integration test feels very heavy, as we have to perform multiple async calls to set up the system to test. We need to identify a pattern for multiple async calls, like
```swift
func testDeleteWithValidCondition() async throws {
        await setUp(withModels: TestModelRegistration())
        try await startAmplifyAndWaitForSync()
        let team = Team1(name: "name")
        let project = Project1(team: team)
        _ = try await Amplify.DataStore.save(team)
        _ = try await Amplify.DataStore.save(project)
        
        _ = try await Amplify.DataStore.delete(project, where: Project1.keys.team.eq(team.id))
                                               
        let queriedProject = try await Amplify.DataStore.query(Project1.self, byId: project.id)
        XCTAssertNil(queriedProject)
    }
```

In this case, we should create a new expectation for each async call, and then have one line wait at the bottom for the array of expectations

```
await waitForExpectations([savedTeam, savedProject, deletedProject, queriedProject], timeout: timeout)
```

So that if the test hangs on one of these calls, it will timeout after `timeout` has elapsed

**Comment by lawmicha** [comment]
Perhaps we can encapsulate the entire test with a single expectation to ensure the tests do not hang, like
```swift
func testPaginatedListProjects() async throws {
        let testCompleted = asyncExpectation(description: "test completed")
        Task {
            guard let team = try await createTeam(name: "name"),
                  let projecta = try await createProject(team: team),
                  let projectb = try await createProject(team: team) else {
                XCTFail("Could not create team and two projects")
                return
            }
            
            var results: List<Project1>?
            let predicate = Project1.keys.id == projecta.id || Project1.keys.id == projectb.id
            let request: GraphQLRequest<List<Project1>> = GraphQLRequest<Project1>.list(Project1.self, where: predicate)
            let result = try await Amplify.API.query(request: request)
            ...
            await testCompleted.fulfill()
        }
        await waitForExpectations([testCompleted], timeout: TestCommonConstants.networkTimeout)
    }
```

In the above code snippet, we have 4 awaited calls, all of which could hang the test

**Comment by harsh62** [comment]
@lawmicha Could this PR help https://github.com/aws-amplify/amplify-ios/pull/2271 ?

**Comment by lawmicha** [comment]
> @lawmicha Could this PR help #2271 ?

Yes that looks good! Will close this issue out, i believe it's up to the developer writing the tests to use those extensions
