### ISSUE TITLE
Storage is very unreliable on Device iOS

### ISSUE THREAD

**Issue by iThink32** [aws-amplify/amplify-swift#2228]
### Describe the bug

Earlier on an older version of Storage whenever I used to run my app on my device and download a protected image I at times used to get a 403 error.

Off late it began to increase and I recently updated to the latest version of Storage.

Now only image uploads work successfully and one in ten downloads succeed.I always get the following error

`StorageError: The HTTP response status code is [403].
Recovery suggestion: .
For more information on HTTP status codes, take a look at
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes`

Storage on amplify has become very unreliable off late. 
Would be very grateful if I get some help on the same.

the code used to download an image is as follows:

```
        let options = StorageDownloadDataRequest.Options(accessLevel: StorageAccessLevel.protected,
                                                         targetIdentityId: identityID)
        _ = Amplify.Storage.downloadData(key: path, options: options) { (result) in
            switch result {
            case let Result.success(data) :
                completion(data,nil)
            case let Result.failure(error):
                completion(nil,NetworkingError.apiError(description: error.errorDescription))
                print(error)
            }
        }
```

sample path is abcd@gmail.com#profile.jpg

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Download image
2. See the error displayed
3. Retry and rarely succeed
```

### Expected behavior

Work just like upload functionality

### Amplify Framework Version

1.28.0

### Amplify Categories

Storage

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

9.2.1

### Xcode version

13.4.1

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

iPhone 8

### iOS Version

15.6.1

### Specific to simulators

No

### Additional context

_No response_

**Comment by iThink32** [comment]
hey guys sorry to say but the issue in faced last year with s3 has stung me again.
here is the link https://github.com/aws-amplify/amplify-ios/issues/978
this was fixed earlier and has now broken.
Please expedite this.

**Comment by brennanMKE** [comment]
@iThink32 Please reach out on our Discord server. We'd like to collect details so we can review logs. 

https://discord.gg/jWVbPfC
