### ISSUE TITLE
Multiple auth rules for multi owners

### ISSUE THREAD

**Issue by askemottelson** [aws-amplify/amplify-swift#2289]
### Is your feature request related to a problem? Please describe.

The documentation allows for multiple owners of a model, buth the Amplify iOS implementation is lacking this important feature.

### Describe the solution you'd like

There is already some work on this, but it has been stalled for almost a year: https://github.com/aws-amplify/amplify-ios/pull/1606

### Describe alternatives you've considered

The alternative is to not share data between users, but this is hardly a solution.

### Is the feature request related to any of the existing Amplify categories?

DataStore

**Comment by atierian** [comment]
Thanks for opening this @askemottelson. We'll investigate the status of https://github.com/aws-amplify/amplify-ios/pull/1606 respond back to this issue with any updates.

**Comment by askemottelson** [comment]
Hi @atierian and @lawmicha - thanks for looking into this. I just noticed that remote DataStore real time events are also not triggered for multi auth models (i.e., only local events are fired when listening on `Amplify.DataStore.observeQuery`). This is a critical bug, as an app with shared data access will have to continuously and manually check for DataStore updates

**Comment by askemottelson** [comment]
@atierian any news on this? Seems like a pretty big deal that Amplify iOS cannot support data sharing across users?

**Comment by pixelier** [comment]
any update on this? @atierian

**Comment by siecola** [comment]
Hello! Someone has a workaround on how to share data across users with Amplify iOS? Thank you!

**Comment by askemottelson** [comment]
> Hello! Someone has a workaround on how to share data across users with Amplify iOS? Thank you!

I'm afraid not. We are still eagerly waiting for support for multi users, and receiving data update events in real time.

**Comment by marmll41** [comment]
any update on this please ... we wait a long time for it ? @atierian

**Comment by lawmicha** [comment]
This was released in https://github.com/aws-amplify/amplify-swift/releases/tag/2.19.0

**Comment by lawmicha** [comment]
Closing since this has been released. Feel free to open another issue with the relevant schema if something isn't working as expected in Amplify 2.19.0
