### ISSUE TITLE
`AuthUser.username` property returns a UUID on iOS but returns an email address on Android

### ISSUE THREAD

**Issue by mbernson** [aws-amplify/amplify-swift#2403]
### Describe the bug

Hi,
I'm working on two native apps that both use the latest version of the Amplify SDK with AWS Cognito as the auth provider.
On both platforms we use the `username` property of the `AuthUser` to show the user's email address in the UI. On Android this works as expected, but on iOS it returns the same value of the `userId` property - which is a UUID.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Log in using an AWS Cognito auth provider with the Amplify SDK
2. Get the current user: `let user = Amplify.Auth.getCurrentUser()`
3. Print the user's username: `print(user?.username)`
4. See the user's userId (UUID)
```

### Expected behavior

1. To see the user's email address

### Amplify Framework Version

1.28.1

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

n/a

### Xcode version

14.0

### Is this a regression?

No

### Device

iPhone 11, iPhone 13 simulator

### iOS Version

iOS 16

### Specific to simulators

No

**Comment by harsh62** [comment]
@mbernson 
The team is actively working on unifying `getCurrentUser` API behaviour on all platforms. We will post an update on the ticket after the change has been implemented.

Meanwhile, I would like to recommend to use [Fetch Attributes API](https://docs.amplify.aws/lib/auth/user-attributes/q/platform/ios/#fetch-the-current-users-attributes) to get logged in user details.

**Comment by harsh62** [comment]
[Amplify 2.0](https://github.com/aws-amplify/amplify-swift/releases/tag/v2.0.0) has been released which normalizes what values are returned in the `getCurrentUser` API. The API will now use the `accessToken` to determine the `userId` and `username` values. Adding the [reference to the implementation](https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Support/Helpers/TokenParserHelper.swift#L32) as well.
