### ISSUE TITLE
CUSTOM_AUTH authentication always ends with error: Incorrect username or password.

### ISSUE THREAD

**Issue by Robtles** [aws-amplify/amplify-swift#2458]
### Describe the bug

I am trying to authenticate using Amplify iOS SDK, with a `CUSTOM_AUTH` strategy. The expected process is a two-step one: the user first types his phone number, then he receives a SMS code to finalize his sign in.
But everytime I do so, I get this error:

> AuthError: Incorrect username or password.
> Recovery suggestion: Check whether the given values are correct and the user is authorized to perform the operation.
> ▿ notAuthorized : 3 elements
>    - .0 : "Incorrect username or password."
>    - .1 : "Check whether the given values are correct and the user is authorized to perform the operation."

My `amplifyconfiguration.json` file is very simple:

```
{
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "eu-west-3_XXXXXXXX",
                        "AppClientId": "XXXXXXXXXXXXXXXXXXXXXXXXXX",
                        "Region": "eu-west-3"
                    }
                },
                "Auth": {
                    "Default": {
                        "authenticationFlowType": "CUSTOM_AUTH"
                    }
                }
            }
        }
    }
}
```

I tried to log the user with a `USER_SRP_AUTH` strategy instead (so I replaced `CUSTOM_AUTH` with `USER_SRP_AUTH` in the JSON configuration file), and it worked fine:

```
Amplify.Auth.signIn(
    username: "usernameTest",
    password: "passwordTest"
)
```

For information, I added the phone number as a user attribute when creating the account:

```
Amplify.Auth.signUp(
    username: "usernameTest",
    password: "passwordTest",
    options: AuthSignUpRequest.Options(
        userAttributes: [
            AuthUserAttribute(.phoneNumber, value: "+3366023XXXX"), // the user phone number
        ]
    )
)
```

But now here is how I try to log in with the `CUSTOM_AUTH` attribute:

```
Amplify.Auth.signIn(
    username: "usernameTest" // I also tried with the phone number instead
)
```

Every time I do this, I get the error aforementioned.

I made sure with the backend team that it should work fine on their side, at least their implementation with a web client works as expected.

Am I missing something here?

Thank you for your help.

### Steps To Reproduce

```swift
Simply try to call Amplify.Auth.signIn(username: "XXX") with a `CUSTOM_AUTH` attribute in the configuration file.
```

### Expected behavior

The user should instead receive a SMS code to finalize his login process. The expected `nextStep` in the `.signIn()` completion block should be `.confirmSignInWithCustomChallenge`.

### Amplify Framework Version

1.28.1

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

Not used

### Xcode version

14.0.1

### Relevant log output

```shell
No relevant log apart from the error mentioned in the issue description.
```

### Is this a regression?

No

### Device

iPhone XR

### iOS Version

16.0.2

**Comment by royjit** [comment]
Note that if you are using v1 of Amplify Library for Swift , the custom auth always start with SRP as the first step. If you need to start the custom auth as a passwordless flow, you need to bypass the SRP as mentioned in the docs - https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/ios/#confirm-sign-in-with-custom-challenge. 

This behavior was fixed in v2.0.0 which was released recently.
