### ISSUE TITLE
Migrating from old library to the new one.

### ISSUE THREAD

**Issue by Ricardo1980** [aws-amplify/amplify-swift#2492]
My app uses an old framework. This is my cocoapods file:
```
pod 'AWSAppSync', '3.6.1'
pod 'AWSUserPoolsSignIn', '2.27.9'
pod 'AWSMobileClient', '2.27.9'
pod 'AWSS3', '2.27.9'
pod 'AWSPinpoint', '2.27.9'
```

Should I update my app to use this new framework? I don't have any issue at the moment. Is the framework I am using deprecated or too old? It is not clear to me why we have these different frameworks.
https://github.com/awslabs/aws-mobile-appsync-sdk-ios

Is there any migration guide? It seems everything is very different with this new framework.

If I use this new framework, will I have any issue with my backend files? (json files, cloud formation files, velocity templates...)

Thanks a lot.

**Comment by hdworld11** [comment]
Hello @Ricardo1980 👋 thanks for reaching out! You can find guidance on upgrading to the latest version here - https://github.com/aws-amplify/amplify-swift/blob/main/UpgradeGuide.md
