### ISSUE TITLE
Amplify's role in storing and managing cognito token (fetchAuthSession(), Shared Responsibility Model)

### ISSUE THREAD

**Issue by Eumag** [aws-amplify/amplify-swift#2496]
### Describe the bug

Hello Amplify team, 

I am using [fetchAuthSession](https://docs.amplify.aws/lib-v1/auth/access_credentials/q/platform/ios/) to retrieve the jwt/cognito tokens and [signIn](https://docs.amplify.aws/lib-v1/auth/signin/q/platform/ios/) for the login. These are IDToken and AccessToken. Document keeps it in a local variable. There is no mention or report upon how these tokens should be retained on mobile device by the ios/swiftUI app. And how Amplify helps in preventing against 
1. CSRF, 
2. XSS, 
3. a need to re-login after app-relaunch, 
4. a refresh requirement after token expiry. 

These preventions will translate to how the app is storing the token - as cookie, as http-only cookie, persist or in-memory, using UserDefaults/Keychain - and how fetchAuthSession, signIn are used. This is in context of passwordless-sms/email auth. How and where Amplify helps in preventing these problems. Some details like token location, sequence diagram can give an insight to developer using the sdk. Does [shared responsibility model](https://aws.amazon.com/compliance/shared-responsibility-model/) treats this aspect completely out of scope from aws/amplify boundary? What needs to be done from app side and how much is done from sdk side? ([Using Amplify 1.28.2-unstable.2](https://github.com/aws-amplify/amplify-swift/issues/2324#issuecomment-1252351132)).
Instead of app dealing with the storing, managing, passing-around the tokens to different app-modules, is it ok to call fetchAuthSession() at different places whenever access/id token is desired to be used, say to call downstream/rest services?

Thanks.

### Steps To Reproduce

```swift
https://docs.amplify.aws/lib-v1/auth/access_credentials/q/platform/ios/.
One need to implement and test against CSRF, XSS attacks, a need to re-login, a refresh requirement after token expiry.
```

### Expected behavior

These are important aspects on App security and user-facing functionality. It is required to include details and a report format on it for the developer.  

### Amplify Framework Version

1.28.2-unstable.2

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

9.2.1

### Xcode version

13.4 (13F17a)

### Is this a regression?

No

### Device

iPhone 11

### iOS Version

15.6.1

**Comment by palpatim** [comment]
Hi @Eumag, thanks for your message. We're reviewing your question and will respond here shortly.

**Comment by Eumag** [comment]
Thanks @palpatim for addressing the question/issue. Assuming the same applies to v1 as well. 

In the sample fragment given for [accessing credentials](https://docs.amplify.aws/lib-v1/auth/access_credentials/q/platform/ios/), there are couple of prints to console.
```
            print("User sub - \(usersub) and identity id \(identityId)")
            print("Access key - \(credentials.accessKey) ")
            print("Id token - \(tokens.idToken) ")
```
Are these all public and safe to print them like it? Or should these better be under Debug prints only and stated for caution under a comment. Prints suggest this is public data and does not pose an issue while sharing. To understand a bit about it, could you indicate (here/in-doc) what is private and should not be shared publicly by the app. I am referring to results of apis: `fetchAuthSession`, `getIdentityId`, `getAWSCredentials`, `getCognitoTokens`.

**Comment by palpatim** [comment]
Hi @Eumag,

We have updated the documentation for [v1](https://docs.amplify.aws/lib-v1/auth/access_credentials/q/platform/ios/) and [v2](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/ios/) to remove those print statements. Please see our existing documentation for best practices around [AWS Credentials](https://docs.aws.amazon.com/accounts/latest/reference/credentials-access-keys-best-practices.html) and [Cognito tokens](https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html).

**Comment by Eumag** [comment]
Awesome!

This ticket can be closed now.
