### ISSUE TITLE
[v2.0.1] AmplifyAWSServiceConfiguration has Double instead of String 

### ISSUE THREAD

**Issue by gurkarangulati** [aws-amplify/amplify-swift#2513]
### Describe the bug

![Screenshot 2022-10-27 at 8 30 07 PM](https://user-images.githubusercontent.com/4088575/198439936-d4495f53-32a7-41aa-b531-f4da6ae5dc15.png)
![Screenshot 2022-10-27 at 8 29 58 PM](https://user-images.githubusercontent.com/4088575/198439941-022f3aec-b594-49b0-9f81-722d307a77f2.png)

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Update from 2.0.0 to 2.0.1 and build.
```

### Expected behavior

Expected a successful build.

### Amplify Framework Version

2.0.1

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

10.4.0

### Xcode version

14.1

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

Physical iphone 14

### iOS Version

iOS 16

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by gurkarangulati** [comment]
Thanks all!

Appreciate the help.

Best,
Gurk

**Comment by royjit** [comment]
Can you please take a look now? You might need to clear your spm cache folder to fix it.

**Comment by gurkarangulati** [comment]
I've cleared my cache, my builds, my build location, it still picks up the
old version of the at file. I can see the new file was pushed but maybe
needs a new version?

Best,
Gurk

**Comment by royjit** [comment]
I believe you might need to remove the cached repo from as well from the local. Can you try removing these folders and see if that fixes your issue:

~/Library/Caches/org.swift.swiftpm/
~/Library/org.swift.swiftpm/
~/Library/Developer/Xcode/DerivedData/

**Comment by gurkarangulati** [comment]
Confirmed. That works. Thank you!

**Comment by royjit** [comment]
Glad it worked! Let us know if you are more questions, closing this issue.
