### ISSUE TITLE
Cannot find type 'AWSS3GetPreSignedURLRequest' in scope

### ISSUE THREAD

**Issue by mregnauld** [aws-amplify/amplify-swift#2535]
### Describe the bug

In my iOS project, I imported some AWS libraries:
- `Amplify`, in order to call webservices (API Gateway), using SPM
- `AWSS3` and `AWSMobileClient`, in order to get a presigned URL, so I can manually download a file from a S3 bucket (and no, I don't want to use `Amplify.Storage.downloadData` since I have specific needs), using Cocoapods

When I want to get a presigned URL for my custom S3 client, here is what I do:

```Swift
let awsS3GetPreSignedURLRequest: AWSS3GetPreSignedURLRequest = AWSS3GetPreSignedURLRequest()
awsS3GetPreSignedURLRequest.httpMethod = AWSHTTPMethod.GET
awsS3GetPreSignedURLRequest.key = key
awsS3GetPreSignedURLRequest.bucket = bucketName
awsS3GetPreSignedURLRequest.expires = Date(timeIntervalSinceNow: TimeInterval(900))
AWSS3PreSignedURLBuilder.default().getPreSignedURL(awsS3GetPreSignedURLRequest).continueWith { [self] task in
   // ...
}
```

It has always worked fine, until I added the `Amplify` library using SPM.

Now, for some reason, I get the following errors at compile time:

```
Swift Compiler Error (Xcode): Cannot find type 'AWSS3GetPreSignedURLRequest' in scope
Swift Compiler Error (Xcode): Cannot find 'AWSS3PreSignedURLBuilder' in scope
```

Of course, I checked that I have: `import AWSS3`

I cleaned every possible cache, rerun a `pod install`, but it doesn't want to compile.

Here is a [test project][1] for you to try. The problem appears as soon as I add the `Amplify` library using SPM.

  [1]: https://github.com/mregnauld/AWSAmplifyDemo/tree/master

### Steps To Reproduce

```shell
1. clone https://github.com/mregnauld/AWSAmplifyDemo/tree/master
2. run the project in Xcode
```

### Expected behavior

It should compile and run.

### Amplify Framework Version

2.0.2

### Amplify Categories

Storage

### Dependency manager

Swift PM

### Swift version

5.6.1

### CLI version

4.41.2

### Xcode version

13.4.1

### Relevant log output

```shell
Swift Compiler Error (Xcode): Cannot find type 'AWSS3GetPreSignedURLRequest' in scope
Swift Compiler Error (Xcode): Cannot find 'AWSS3PreSignedURLBuilder' in scope
```

### Is this a regression?

I don't know

### Device

iPhone 11

### iOS Version

15.5

**Comment by mregnauld** [comment]
OK so I don't know if it a bug or not, but for information, the problem came from the fact that, when I added the `Amplify` framework using SPM, I checked `AWSS3StoragePlugin`.
Not checking that plugin solved the problem.

**Comment by harsh62** [comment]
Please not that `AWSMobileClient` is not supported on Amplify 2.0 and greater. Also note that CocoaPod support has been also deprecated in Amplify 2.0.
