### ISSUE TITLE
When is Predictions available in v2.

### ISSUE THREAD

**Issue by anatomybook** [aws-amplify/amplify-swift#2539]
I apologise in advance, if this has been posted already, but I haven't been able to find hints regarding the inclusion of Predictions in v2.

I checked the [upgrade guide](https://docs.amplify.aws/lib/project-setup/upgrade-guide/q/platform/ios/), but it only says that there currently is no upgrade plan.

So my question is whether the inclusion of Predictions is planned? Will v1 be usable, i.e. maintained, until it is?

Thank you!

**Comment by atierian** [comment]
Predictions will be included in v2, it's currently being actively worked on.
The service level for v1 as a whole hasn't changed, it will still be maintained at the same level as it has been. If that should change in the future, we'll make an announcement.

**Comment by anatomybook** [comment]
Thanks very much for your answer. Predictions has been working really well for me and I look forward to the update.
