### ISSUE TITLE
App crash: $s7Amplify23AWSUnifiedLoggingPluginC7defaultAA6Logger_pvg

### ISSUE THREAD

**Issue by zhouhao27** [aws-amplify/amplify-swift#2547]
### Describe the bug

Application crashes with the following call stacks:

> Crashed: com.apple.main-thread
0  Amplify                        0x3b674 $s7Amplify23AWSUnifiedLoggingPluginC7defaultAA6Logger_pvg + 48
1  Amplify                        0x3b638 $s7Amplify23AWSUnifiedLoggingPluginCAA0C22CategoryClientBehaviorA2aDP7defaultAA6Logger_pvgTW + 20
2  Amplify                        0x7c114 $s7Amplify15LoggingCategoryC4infoyySSyXKF + 140
3  AmplifyPlugins                 0x1ea64 $s14AmplifyPlugins28AuthorizationProviderAdapterC13setupListener33_9F56DFBCB2FE52BF5B4A87DA0573D416LLyyFy15AWSMobileClient9UserStateO_SDyS2SGtcfU_ + 116
4  AWSMobileClient                0x166e0 $s15AWSMobileClient9UserStateOSDyS2SGIegyg_AcDytIegnnr_TRTA + 28
5  AWSMobileClient                0x2a4fc $s15AWSMobileClientAAC7signOutyyF + 2348
6  AWSMobileClient                0x2aec4 $s15AWSMobileClientAAC15internalSignOut33_92B29A0229F7802B642D31E4C9FB126DLL18presentationAnchor7options17completionHandlerySo8UIWindowCSg_AA0dE7OptionsVys5Error_pSgctF + 1380
7  AmplifyPlugins                 0x1a744 $s14AmplifyPlugins29AuthenticationProviderAdapterC13signOutWithUI33_8CDF2480850D24387F6F51D10DDDA818LL15isGlobalSignout17completionHandlerySb_ys6ResultOyyt0A09AuthErrorOGctF + 328
8  AmplifyPlugins                 0x1aea8 $s14AmplifyPlugins29AuthenticationProviderAdapterC7signOut7request17completionHandlery0A008AuthSignG7RequestV_ys6ResultOyytAG0K5ErrorOGctFyyScMYccfU_TA + 88
9  AmplifyPlugins                 0x6a2c0 $sIeg_IeyB_TR + 28
10 libdispatch.dylib              0x1e6c _dispatch_call_block_and_release + 32
11 libdispatch.dylib              0x3a30 _dispatch_client_callout + 20
12 libdispatch.dylib              0x11f48 _dispatch_main_queue_drain + 928
13 libdispatch.dylib              0x11b98 _dispatch_main_queue_callback_4CF + 44
14 CoreFoundation                 0x51800 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
15 CoreFoundation                 0xb704 __CFRunLoopRun + 2532
16 CoreFoundation                 0x1ebc8 CFRunLoopRunSpecific + 600
17 GraphicsServices               0x1374 GSEventRunModal + 164
18 UIKitCore                      0x514b58 -[UIApplication _run] + 1100
19 UIKitCore                      0x296090 UIApplicationMain + 364
20 Breeze                         0xd76c main + 42 (AppDelegate.swift:42)
21 ???                            0x103865da4 (Missing)

### Steps To Reproduce

```swift
Not reproducible. Happens randomly.
```

### Expected behavior

Show not crash.

### Amplify Framework Version

1.22.1

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

Don't know

### Xcode version

14.1

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

iPhone XR

### iOS Version

iOS 15.6.1

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by ruisebas** [comment]
Hi @zhouhao27, thanks for opening this issue.

While we investigate what's going on, could you please provide the following?
1. Your app's `amplifyconfiguration.json` file, with sensitive information removed.
2. Is it a regression starting on version **1.22.1**, or does it happen for older versions as well? 
3. Have you tried updating to the latest **1.x** ([v1.28.2](https://github.com/aws-amplify/amplify-swift/releases/tag/v1.28.2)) version?
4. Can you pinpoint if the crash happens in a particular moment (e.g. during start up, after signing in, etc)?

Thanks!
