### ISSUE TITLE
Should subscription terminate on failed decode?

### ISSUE THREAD

**Issue by dpilch** [aws-amplify/amplify-swift#2577]
### Is your feature request related to a problem? Please describe.

When data received from a subscription fails to decode the subscription is closed. This causes the DataStore sync engine to stop.

https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/API/Sources/AWSAPIPlugin/Operation/AWSGraphQLSubscriptionTaskRunner.swift#L158

### Describe the solution you'd like

Should the subscription be kept alive and the error is bubbled up to DataStore? 

### Describe alternatives you've considered

Functionality could be kept as is.

### Is the feature request related to any of the existing Amplify categories?

API, DataStore

**Comment by harsh62** [comment]
@dpilch Sorry to lose track of the issue. Is this still an issue that you are facing?

**Comment by dpilch** [comment]
I don't have experience on this. I made this issue on behalf of @lawmicha.

**Comment by lawmicha** [comment]
the relevant code at the link is:
```
private func onGraphQLResponseData(_ graphQLResponseData: Data) {
        do {
            let graphQLResponseDecoder = GraphQLResponseDecoder(request: request, response: graphQLResponseData)
            let graphQLResponse = try graphQLResponseDecoder.decodeToGraphQLResponse()
            send(.data(graphQLResponse))
        } catch let error as APIError {
            fail(error)
        } catch {
            // Verify with the team that terminating a subscription after failing to decode/cast one
            // payload is the right thing to do. Another option would be to propagate a GraphQL error, but
            // leave the subscription alive.
            // see https://github.com/aws-amplify/amplify-swift/issues/2577
            
            fail(APIError.operationError("Failed to deserialize", "", error))
        }
    }
```

If it fails to decode, we fail the entire subscription. Should we do this or send a failed event back, and keep the subscription alive?
