### ISSUE TITLE
Cannot receive error and keep receive the authentication email for authentication code incorrectly

### ISSUE THREAD

**Issue by candycandymidori** [aws-amplify/amplify-swift#2586]
### Describe the bug

I used Sign in with custom flow for authentication as it is for this document（https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/ios/#confirm-sign-in-with-custom-challenge[）](https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/ios/#confirm-sign-in-with-custom-challenge%EF%BC%89), **I will not receive an error when I enter the authentication code incorrectly, and I will continue to hit lambda and keep receive the authentication email all the time.**

Attachment is my logging use `Amplify.Logging.logLevel = .verbose` after configure.
[verboseLog.swift.zip](https://github.com/aws-amplify/amplify-swift/files/10063459/verboseLog.swift.zip)

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Keyin email address by using func login (https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/ios/#sign-in-a-user)
2. received authentication code by using func confirm (https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/ios/#confirm-sign-in-with-custom-challenge)
3. Keyin authentication code incorrectly
4. Will not receive an error and I will continue to hit lambda and keep receive the authentication email all the time
```

### Expected behavior

After [3.Keyin authentication code incorrectly] , I will receive error message in my logs. And will not receive  authentication code anymore.

### Amplify Framework Version

2.0.1

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

10.4.0

### Xcode version

14.1

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

iPhone 14 pro (similater)

### iOS Version

iOS 16

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by atierian** [comment]
Thanks for opening this issue @candycandymidori. We're looking into it and will respond back to you here with any questions or updates.

**Comment by harsh62** [comment]
@candycandymidori @Jessie0713

Created [draft PR](https://github.com/aws-amplify/amplify-swift/pull/2587) to address the endless execution of challenges during `confirmSignIn` API. Would you be able to validate if this addresses the issue?

**Comment by harsh62** [comment]
@candycandymidori  The PR has been merged which fixes the continuous execution of `confirmSignIn` API. 

I have noticed that the lambda returns the same challenge again after the initial request. Make sure that the lambdas are correctly setup for your use case and throw exceptions if there is a code mismatch. Please refer to the [custom auth documentation](https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/ios/#configure-auth-category)

**Comment by candycandymidori** [comment]
@harsh62 
Thank you very much ! 
I'm so sorry  for the very basic question...I'd like to try merged to main which include fixes the continuous execution of confirmSignIn API. Do I need to update Amplify Framework Version up to 2.1.0 (latest) ? Cuz I currently use 2.0.1 version.

**Comment by candycandymidori** [comment]
@5d Thank you so much for your reply. I got it ! I will keep checking for next release :)

**Comment by royjit** [comment]
The fix was released in https://github.com/aws-amplify/amplify-swift/releases/tag/v2.2.0, please update and verify whether the issue was resolved for you.

**Comment by candycandymidori** [comment]
> The fix was released in https://github.com/aws-amplify/amplify-swift/releases/tag/v2.2.0, please update and verify whether the issue was resolved for you.

Thanks for letting me know ! It was very helpful :)
