### ISSUE TITLE
Exact version dependency on SQLite.swift can cause resolution conflicts

### ISSUE THREAD

**Issue by cezarcp** [aws-amplify/amplify-swift#2592]
### Describe the bug

In Package.swift, the dependency on `SQLite.swift` is declared with an exact version match:

`.package(url: "https://github.com/stephencelis/SQLite.swift.git", exact: "0.13.2"),`

While this can be good practice when defining dependencies for applications, it is better avoided in libraries that may be added to projects that depend on other libraries that may share the same dependency but which require a newer version

### Steps To Reproduce

- Create a new package in Xcode
- Add a dependency to "https://github.com/stephencelis/SQLite.swift.git" with a version requirement that's greater than `0.13.2`:
`.package(url: "https://github.com/stephencelis/SQLite.swift.git", from: "0.13.3")`
- Add Amplify as a dependency
- Package resolution will fail due to impossible to satisfy version constraints

### Expected behavior

I'd expect to be able to use Amplify with other libraries that also depend on `SQLite.swift`, even if the require newer versions of said library.

### Amplify Framework Version

2.1.0

### Amplify Categories

Analytics, API, Auth, DataStore, Geo, Predictions, Storage

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

-

### Xcode version

14.1

### Is this a regression?

No

### Device

All

### iOS Version

All

### Specific to simulators

No

**Comment by phantumcode** [comment]
This is an intentional decision to pin to an exact version to avoid unplanned, unreviewed, untested dependency upgrade.
