### ISSUE TITLE
Refresh token after revoke token doesn't trigger sessionExpired or signedOut event

### ISSUE THREAD

**Issue by marcinp-volven** [aws-amplify/amplify-swift#2599]
### Describe the bug

We have just updated to newest Amplify version. 
Previously after revoke token, when Amplify tried to refreshToken it returned `HubPayload.EventName.Auth.sessionExpired` event via HUB
Right now it not sign out user or return sessionExpiration event.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Login into app through Amplify API
2. Take refreshToken and revoke it through rest API
3. Obtaining tokens(refresh)
4. Return AuthError.Unknown 
5. Users stays logged in
```

### Expected behavior

1. Login into app through Amplify API
2. Take refreshToken and revoke it through rest API
3. Obtaining tokens(refresh) after revoke 
4. Return AuthError.SessionExpired or different more detailed error
5. User is signOut from AWS

### Amplify Framework Version

2.1.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

-

### Xcode version

14.1

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

Yes

### Regression additional context

_No response_

### Device

iPhone 14

### iOS Version

iOS 16

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by marcinp-volven** [comment]
Updated to 2.2.0. Still an issue.
```
HubPayload(eventName: "Auth.fetchSessionAPI", context: nil, data: Optional(Swift.Result<Amplify.AuthSession, Amplify.AuthError>.success({
    awsCredentialsError = "AuthError: Unexpected error occurred with message: Unknown error occurred\nRecovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered 
    at: file: [...]amplify-ios/Amplify/Categories/Auth/Error/AuthError.swift\nfunction: recoverySuggestion
    line: 80"
    cognitoTokensError = ...
    identityIdError = ...
    userSubError = ...
    ```

**Comment by royjit** [comment]
@marcinp-volven Thank you for reporting this issue, I have created this PR - https://github.com/aws-amplify/amplify-swift/pull/2652 for the fix.

**Comment by ethan021021** [comment]
Can you please release this for V1 as well? Thanks!

**Comment by harsh62** [comment]
@ethan021021 This already works correctly on V1, I can see that a sessionExpired error is thrown and an Event is also fired when the `refreshToken` is revoked.

Cognito Result:
```
{"__type":"NotAuthorizedException","message":"Refresh Token has been revoked"}
```
Result from Amplify:
```
    ▿ cognitoTokensResult: Swift.Result<AWSPluginsCore.AuthCognitoTokens, Amplify.AuthError>.failure
      ▿ failure: AuthError: Session expired could not fetch cognito tokens
Recovery suggestion: Invoke Auth.signIn to re-authenticate the user
        ▿ sessionExpired: (3 elements)
          - .0: "Session expired could not fetch cognito tokens"
          - .1: "Invoke Auth.signIn to re-authenticate the user"
          - .2: nil
```

**Comment by ethan021021** [comment]
@harsh62 Gotcha. Will a Hub event emit as well?

**Comment by harsh62** [comment]
@ethan021021  Yes.
