### ISSUE TITLE
How to avoid Amplify.Auth.signOut() alert message?

### ISSUE THREAD

**Issue by MrJorgeXavier** [aws-amplify/amplify-swift#2600]
### Is your feature request related to a problem? Please describe.

The user sign's in successfully with google using `Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: view)`. 

But when he wants to signout, I call the `Amplify.Auth.signOut()` method and the following alert is displayed:
<img width="296" alt="Captura de Tela 2022-12-01 às 16 04 41" src="https://user-images.githubusercontent.com/33957786/205138322-d26958f7-ac64-49e4-af97-b663bbefa247.png">

### Describe the solution you'd like

I think there is a bug because  it shows "wants to sign in" when in fact the user is signing out. However, I want to avoid displaying the dialog altogether. Is this possible?

### Describe alternatives you've considered

I know that we can call the sign in using the preferPrivateSession to remove the alert, like `Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: view, options: .preferPrivateSession())`, however by doing  this the user is forced to input his credentials to sign in, instead of the usual social login behavior of already fetching the current active session credentials. I think this kind of behavior heavily impacts the user login experience, even more if we consider 2FA and complex passwords, so  I want to avoid this solution at all costs.

### Is the feature request related to any of the existing Amplify categories?

Auth

### Additional context

I'm importing amplify via SPM, using the version 2.1.0

**Comment by phantumcode** [comment]
@MrJorgeXavier This alert is a native OS alert whenever authenticating with 3rd party identity provider via web UI.  Please see Apple's documentation here: https://developer.apple.com/documentation/authenticationservices/aswebauthenticationsession

Configuring `options: .preferPrivateSession()` effectively sets the property `prefersEphemeralWebBrowserSession` to true on the session.  Setting this property true removes the alert but disables any sharing of cookies and SSO.

This is a behavior limitation by Apple that we cannot change.

**Comment by mridboy96** [comment]
I would like to know if there is any update on this?
Is there an update coming up where the alert message is not shown while the user is being signed out without using the preferPrivateSession() as an option.

**Comment by phantumcode** [comment]
@mridboy96 Please see the previous comment for reference, this is a native iOS behavior for 3rd authentication via web UI.  We do not have any plans for any workaround or updates to change this behavior.

**Comment by MrJorgeXavier** [comment]
It's okay to present the dialog when the user sign's in, it's a default behavior on iOS that I believe won't cause issues with the user experience.

But it is very strange to consider sign out having this alert a default iOS behavior... Other auth systems (like Firebase Authentication) doesn't have this problem.

The amplify sdk forces the user to signout in order to sign in using other platform, so we are forced to accept this **bug** when working with the sdk.

I think I'll try work around this bug by implementing the cognito flow on a webpage and using safariVC or external browser to sign in and redirect the token back to the app.. It's a horrible solution, but at least it'll not confuse the users with misleading messages.

**Comment by chinuchahal** [comment]
Facing similar issue. Any update on this?

with help of `options: .preferPrivateSession()` I'm able to bypass alert while signing out but have to enter google's credentials each time when user is trying to login using Google.

**Comment by phantumcode** [comment]
Hello @chinuchahal Unfortunately, this is a native iOS behavior for 3rd party web authentication that we currently don't have an update or workaround for.

**Comment by BigVeila** [comment]
I understand that showing a popup during sign-in is meant to protect the user, but having it during sign-out is really undesirable. I assume we all handle cases where the user calls an API and gets an authentication error — and the first thing we do is force sign the user out.
Currently, the user has to confirm by clicking the “Continue” button for the sign-out to complete.
Is there a way to sign out via API or something similar instead?

**Comment by harsh62** [comment]
@BigVeila I think there was a recent update where Amplify would avoid calling the sign out using ASWebAuthentication if the tokens are already expired. Can you try the latest version of Amplify?

**Comment by MahsaMaslahati** [comment]
I am using the latest version of Amplify swift (2.49.0), but I still have the popup during sign-out!

**Comment by harsh62** [comment]
If the users tokens are already expired, only in that case the pop wouldn't come up. If the tokens are still valid, WebUI will go through ASWebAuthentication to properly revoke tokens.
