### ISSUE TITLE
signIn completion handler - fetchAuthSession() is not available

### ISSUE THREAD

**Issue by Eumag** [aws-amplify/amplify-swift#2601]
### Describe the bug

I am using [signIn](https://docs.amplify.aws/lib-v1/auth/signin_next_steps/q/platform/ios/) and modified it with completion handler. Use case is to call REST api with cognito-access token in header to invoke insertion into DynamoDB as a user logs in for first time. Gist of the flow is: Swift -> Amplify-> signIn -> userNotFound error -> signUp -> signIn -> after signIn completion, call fetchAuthSession -> get cognito access token -> amplify -> REST api -> APIGateway -> Lambda -> insert metadata into DynamoDB.

After signIn(), in its completion handler, amplify.Auth.fetchSession() is gives error:
```
Fetch auth session failed with error - AuthError: There is no user signed in to retreive cognito tokens
Recovery suggestion: Call Auth.signIn to sign in a user and then call Auth.fetchSession

```
If I keep a sleep of 60s, it works. The delay sometime works for 30s and very few times for 20s. 

This is not mentioned anywhere. What can be done?

Using the signature:     
private func signIn(username: String, password: String, firstAttempt: Bool, completion: @escaping () -> Void) { .. }
where completion() is called at the end of function. Completion() block has a call to [fetchAuthSession()](https://docs.amplify.aws/lib-v1/auth/access_credentials/q/platform/ios/) when signIn succeeds.

    private func signIn(username: String, password: String,
                        firstAttempt: Bool,
                        completion: @escaping () -> Void) {
        print("signIn(\(username), \(password), \(firstAttempt))")
        Amplify.Auth.signIn(username: username, password: password) { result in
            do {...} catch {...}
            print("calling completion() in signIn()" + String(firstAttempt))
            completion()
        }
    }

Now, if this is unexplained and expected behaviour: 
1. Please put up an explaination on this in doc. 
2. Suggest what can be done to insert metadata after first signIn. This metadata require cognito tokens to pass them as header in downstream api calls. 

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Define a completion handler for signIn()
2. Call fetchAuthSession() in completion handler. fetchAuthSession() is called when signIn succeeds.
3. /* sleep(60) */ //to make it work
4. See error : Fetch auth session failed with error - AuthError: There is no user signed in to retreive cognito tokens. Recovery suggestion: Call Auth.signIn to sign in a user and then call Auth.fetchSession
```

### Expected behavior

When signIn completes, fetchAuthSession() should be able to return cognito access/id token for enabling calls to downstream apis.

### Amplify Framework Version

1.28.2-unstable.2

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

9.2.1

### Xcode version

Version 14.1 (14B47b)

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


Fetch auth session failed with error - AuthError: There is no user signed in to retreive cognito tokens
Recovery suggestion: Call Auth.signIn to sign in a user and then call Auth.fetchSession
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

iPhone11 - Real Device (ModelNo: MHDD3HN/A)

### iOS Version

iOS 16.1

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by ameter** [comment]
Based on information provided via the other ticket, the reason `Auth.fetchAuthSession` is returning "no user signed in" is because it's being called after `Auth.signIn`, but before `Auth.confirmSignIn`.

Note for amplify-swift team: More information is available in the following SIM: V780829163

**Comment by Eumag** [comment]
Information was helpful, thanks. 

I checked on it. Calling Auth.fetchSession() after Auth.confirmSignIn() produces the result fine and fetching of Cognito token succeeds. I will move Auth.fetchSession() from completion-handler of signIn to completion handler of Auth.confirmSignIn() under its success case.  

As I see it, confirmSignIn() is automatically invoked by the case "confirmSignInWithCustomChallenge" in Auth.signIn(). 

Flow: Swift -> Amplify-> signIn -> userNotFound error -> signUp -> signIn -> case "confirmSignInWithCustomChallenge" and prompt user for custom challenge answer -> Auth.confirmSignIn ->  Auth.fetchSession -> get cognito access token -> amplify -> REST api -> APIGateway -> Lambda -> insert metadata into DynamoDB

I am planning to move to v2 soon. For that, what is the way to represent this Flow with async/await? 

A sample fragment in doc can clarify and reason the behaviour better for adoption in an involved scenario.

**Comment by royjit** [comment]
Glad that it worked for you, the flow is same in v2 as well. You need to call `Auth.confirmSignIn` if the `Auth.signIn` api returned `confirmSignInWithCustomChallenge` as the next step. `Auth.fetchSession` will give you authenticated credentials only after the signIn process is complete.

You can find the documentation on v2 apis here - https://docs.amplify.aws/lib/auth/signin/q/platform/ios/

**Comment by Eumag** [comment]
Thanks. This ticket can be closed now.
