### ISSUE TITLE
Cannot sign out the user with custom flow

### ISSUE THREAD

**Issue by hihiweiping** [aws-amplify/amplify-swift#2605]
### Describe the bug

I used `sign in with custom flow` for authentication as it is for [this document](https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/ios/#sign-in-a-user), 
when I tried to sign out the user before verifying verification code, I got error `AuthError: Auth State not in a valid state`

Attachment is my error log use Amplify.Logging.logLevel = .verbose after configure.
[signInLog.txt](https://github.com/aws-amplify/amplify-swift/files/10183083/signInLog.txt)
[signOutLog.txt](https://github.com/aws-amplify/amplify-swift/files/10183085/signOutLog.txt)

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Key in email address by using func signIn() (https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/ios/#sign-in-a-user)
2. Received verification code by using func customChallenge() (https://docs.amplify.aws/lib/auth/signin_with_custom_flow/q/platform/ios/#confirm-sign-in-with-custom-challenge)
3. Try to sign out by using func signOutLocally()(https://docs.amplify.aws/lib/auth/signOut/q/platform/ios/) 
4. Received an error `AuthError: Auth State not in a valid state` and cannot sign out the user
```

### Expected behavior

After receiving verification code, I trigger `func signOutLocally()` and sign out successfully

### Amplify Framework Version

2.0.1

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

10.4.0

### Xcode version

14.1

### Is this a regression?

No

### Device

iPhone 14 pro (similater)

### iOS Version

iOS 16

**Comment by atierian** [comment]
Hey @hihiweiping, thanks for opening this issue.
It appears that this was addressed in [release 2.2.0](https://github.com/aws-amplify/amplify-swift/releases/tag/v2.2.0). Can you please try upgrading to 2.2.0 to see if that fixes your issue.

**Comment by Jessie0713** [comment]
Hello @atierian, thanks for your help, upgrading to 2.2.0 still didn't work for me, the followings are my sign in, log out logs and a demo video.
[bug_demo.zip](https://github.com/aws-amplify/amplify-swift/files/10205097/bug_demo.zip)
[log_out.txt](https://github.com/aws-amplify/amplify-swift/files/10205101/log_out.txt)
[sign_in.txt](https://github.com/aws-amplify/amplify-swift/files/10205102/sign_in.txt)

**Comment by royjit** [comment]
Thank you for the details, looks like the auth plugin is not cancelling an existing signIn flow. Ideally the flow should be like this:
1. User starts a sign in by calling `Amplify.Auth.signIn` using a username: user1
2. Auth plugin returns signIn verification 
3. User decides to change the username and retry the signIn by calling `Amplify.Auth.signIn` again with username: user2
4. SignIn should proceed without any issue

I have made a fix for the above steps to work - https://github.com/aws-amplify/amplify-swift/pull/2609

**Comment by JOiCh** [comment]
@royjit 
This branch(royjit.fixsignin) worked! thank you so much!!!!

**Comment by JOiCh** [comment]
@royjit we've tested version 2.2.1 and it worked fine, thank you so much.
