### ISSUE TITLE
Unchecked UInt64 cast fails for past expiration dates

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-swift#2636]
### Describe the bug

In https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/Core/AWSPluginsCore/Auth/Provider/AmplifyAWSCredentialsProvider.swift#L33:

The cast `UInt64(tempCredentials.expiration.timeIntervalSinceNow)` fails if the expiration is in the past. Since the intent is to indicate a local flag for expiration, if we know the expiration has past, it should be safe to replace any negative value with 0:

`UInt64(tempCredentials.expiration.timeIntervalSinceNow < 0 ? 0 : tempCredentials.expiration.timeIntervalSinceNow)`

### Steps To Reproduce

I discovered this working on a custom credentials provider that didn't validate expiration before passing it to the caller. Since there is no contract for `AuthAWSCredentialsProvider` beyond the protocol definition, it's not clear that `func getAWSCredentials() -> Result<AWSCredentials, AuthError>` expects only current credentials to be passed. (We could also document the contract, but defensively handling the expiration seems like a more robust approach.)

### Expected behavior

Expired credentials should be handled by converting the CRT Credentials to have an expiration of 0, which should result in local validation errors because of expired credentials. In the worst case, the service will reject the credentials.

### Amplify Framework Version

2.2.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

10.5.2

### Xcode version

14.1

### Is this a regression?

No

### Device

iPhone 14 simulator

### iOS Version

iOS 16.1

**Comment by palpatim** [comment]
See https://github.com/aws-amplify/amplify-swift/pull/2637

**Comment by atierian** [comment]
Fix was released in [v2.3.0](https://github.com/aws-amplify/amplify-swift/releases/tag/v2.3.0).
