### ISSUE TITLE
Update swiftdoc as it relates to storage transfer acceleration support

### ISSUE THREAD

**Issue by jcjimenez** [aws-amplify/amplify-swift#2640]
### Is your feature request related to a problem? Please describe.

In order to be at feature parity with JavaScript/React, we are adding storage transfer acceleration support as part of https://github.com/aws-amplify/amplify-swift/pull/2631

However, the swiftdoc will need to wait until we have proper documentation ready, specifically for Swift. Currently, we have this documented for JavaScript/React: https://docs.amplify.aws/lib/storage/transfer-acceleration/q/platform/js/

### Describe the solution you'd like

Document `StorageDownloadDataRequest `, 'StorageDownloadFileRequest', 'StorageUploadDataRequest' and `StorageUploadFileRequest ` option objects with something like this:

```
extension StorageDownloadDataRequest {
    ...
    struct Options {
        ...
        /// Extra plugin specific options, only used in special circumstances when the existing options do
        /// not provide a way to utilize the underlying storage system's functionality. See plugin
        /// documentation for expected key/values.
        ///
        /// As an example, if using the AWSS3StoragePlugin, one may be want to add something like the
        /// following (please note that `useAccelerateEndpoint`
        /// [should first be setup](https://docs.amplify.aws/lib/storage/transfer-acceleration/q/platform/js/),
        /// otherwise, requests will fail):
        ///
        /// ```
        ///  let options = StorageDownloadDataRequest.Options(
        ///      pluginOptions: [
        ///          "useAccelerateEndpoint": true
        ///      ]
        ///  )
        /// ```
        ///
        /// # Reference
        /// * [Storage - Use Transfer Acceleration](https://docs.amplify.aws/lib/storage/transfer-acceleration/q/platform/js/)
        /// * [Transfer Acceleration](https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html)
        ///
        /// - Tag: StorageDownloadDataRequestOptions.pluginOptions
        public let pluginOptions: Any?
```

### Describe alternatives you've considered

Considered documenting with references to [JavaScript/React documentation](https://docs.amplify.aws/lib/storage/transfer-acceleration/q/platform/js/).

### Is the feature request related to any of the existing Amplify categories?

Storage

**Comment by harsh62** [comment]
Documentation updated.
