### ISSUE TITLE
Calling 'Amplify.Auth.deleteUser()' when there is no internet connection (i.e. WIFI off) makes all Auth calls fail

### ISSUE THREAD

**Issue by stevesolius** [aws-amplify/amplify-swift#2643]
### Describe the bug

I have the following source code (from Swift V2, https://docs.amplify.aws/lib/auth/delete_user/q/platform/ios/).

When there is no internet connection, calling "Amplify.Auth.deleteUser()" will trigger an exception.
Then Auth goes into an unknown state.  All Auth calls will hang from then on since Auth goes into an unknown state
Then app has to be terminated and restarted.  For example, calling deleteUser again will hang indefinitely, exception is not triggered.  The app has to be terminated.

func deleteUser() async {
    do {
        try await Amplify.Auth.deleteUser()
        print("Successfully deleted user")
    } catch let error as AuthError {
        print("Delete user failed with error \(error)")
    } catch {
        print("Unexpected error: \(error)")
    }
}

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Login a user successfully
2. Turn off WIFI on the iPhone
3. Call "Amplify.Auth.deleteUser()"
4. Leave WIFI off or on
5. Call "Amplify.Auth.deleteUser()" (or other Auth functions)
6. Notice exception is not raised at the second or later try.  The call hangs indefinitely.  The app has to be terminated and restarted to make "Amplify.Auth" work. 

4. See error
```

### Expected behavior

Amplify.Auth.deleteUser() should check the network connection status first.  If there is no connection raise an exception.  Second or later calls should raise an exception instead of indefinite hanging.  Do not let deleteUser() makes the Auth go into undefined state.

### Amplify Framework Version

2.1.1

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.6.1

### CLI version

6.3.1

### Xcode version

Version 14.1 (14B47b)

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

Any iPhone

### iOS Version

16.1.1

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by royjit** [comment]
Thank you for reporting the issue. I am working on a fix here - https://github.com/aws-amplify/amplify-swift/pull/2656

**Comment by royjit** [comment]
This fix is released on https://github.com/aws-amplify/amplify-swift/releases/tag/2.3.2
