### ISSUE TITLE
 Full sync while app goes to background mode

### ISSUE THREAD

**Issue by sapir-muallem** [aws-amplify/amplify-swift#2657]
### Describe the bug

during full sync, if moving the app to the background and then back to the foreground:
1. Observed queries don't get the queried items - after coming back from background mode, `onItemsChangeDuringSync()` and `onItemChangeAfterSync()` in `AWSDataStoreObserveQueryOperation` aren't being called anymore, therefore the `observedQuery.sink()` will not get the items.
2. Sync restart is called after a long time being back in foreground mode (30-60 seconds) - I checked when `RemoteSyncEngine` received `cleaningUp` and `schedulingRestart` states.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Launch the app for the first time (for a full sync and NOT delta sync)
2. Shortly after the sync starts, move the app to background mode.
** You should go to background mode before the tested model with the `observedQuery` finished to sync
3. Get the app back to foreground mode
4. You should see some connection-related errors such as `ConnectionProviderError.connection`
5. Wait for about a minute until sync is restarted (if you add logs for the `modelSynced` event you'll be able to see it started again)
6. Datastore status becomes 'Ready' but the `observedQuery.sink()` didn't get any items inside the `querySnapshot`
```

### Expected behavior

1. After coming back from background mode to foreground mode, observed queries should work and get the expected items from the query.
2. After coming back from background mode to foreground mode, the sync should be restarted quickly.

### Amplify Framework Version

1.28.4

### Amplify Categories

DataStore

### Dependency manager

Cocoapods

### Swift version

5.7

### CLI version

7.6.26

### Xcode version

14.2

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

Yes

### Regression additional context

_No response_

### Device

iPhone 12 pro (not simulator)

### iOS Version

IOS 16

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by harsh62** [comment]
@sapir-muallem Sorry for losing track of this issue. 

Wanted to check if this is still something that is an issue you are facing? Please comment if it is, our team will prioritize looking into it.
