### ISSUE TITLE
DataStore doesn't load when starting the app in offline mode

### ISSUE THREAD

**Issue by albemala** [aws-amplify/amplify-swift#2668]
### Describe the bug

When starting the app while offline, DataStore doesn't load any data. It used to load all data correctly in version 1.19.1, but it doesn't work any more in 1.28.4.

I get this error loop in the logs from Cognito:

```
Connection 1: received failure notification
Connection 1: failed to connect 1:50, reason -1
Connection 1: encountered error(1:50)
Task <010B4DA3-A752-4C53-B43E-5EAFE6BF4FBE>.<1> HTTP load failed, 0/0 bytes (error code: -1020 [1:50])
Task <010B4DA3-A752-4C53-B43E-5EAFE6BF4FBE>.<1> finished with error [-1020] Error Domain=NSURLErrorDomain Code=-1020 "A data connection is not currently allowed." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x2821e9920 {Error Domain=kCFErrorDomainCFNetwork Code=-1020 "(null)" UserInfo={_NSURLErrorNWPathKey=unsatisfied (No network route), _kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <010B4DA3-A752-4C53-B43E-5EAFE6BF4FBE>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <010B4DA3-A752-4C53-B43E-5EAFE6BF4FBE>.<1>"
), NSLocalizedDescription=A data connection is not currently allowed., NSErrorFailingURLStringKey=https://cognito-idp.eu-west-1.amazonaws.com/, NSErrorFailingURLKey=https://cognito-idp.eu-west-1.amazonaws.com/, _kCFStreamErrorDomainKey=1}
```

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Turn off internet connection (wifi/mobile data...)
2. Open the app
3. I get an error loop in the logs and no data is loaded by DataStore
```

### Expected behavior

Expected: DataStore should load the local DB and display the data even if offline.

Actual: DataStore doesn't load any data and it gets stuck in an error loop

### Amplify Framework Version

1.28.4

### Amplify Categories

Auth, DataStore

### Dependency manager

Swift PM

### Swift version

5.x

### CLI version

8.5.1

### Xcode version

13.4.1

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

Yes

### Regression additional context

In version 1.19.1 the data did load correctly even if starting it while offline.

### Device

iPhone

### iOS Version

15.5

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by albemala** [comment]
A few more things:

- The problem is not related to an expired token. If I open the app while online, the app loads correctly (I can see all data in the app)
- If I open the app while online, then go offline while the app is open, everything seems to work fine. I can do mutations while offline and when going back online, they are synced correctly
- I cannot try Amplify v2, as I'm also using AWSAppSync in the same app, and there is a conflict with Amplify v2

**Comment by lawmicha** [comment]
Hi @albemala, DataStore APIs operates against the local database only. If there is data in the local DB that was previously synced while network was online, that data will be returned from `Amplify.DataStore.query` calls. While the app is offline, `DataStore.start` will attempt to sync data from AppSync to the local DB in a retry loop (if it detects the problem is a network problem), and should not impact your calls to get data from the local DB. 

> no data is loaded by DataStore

Can you confirm if what you mean by this is that you're calling `DataStore.query` and no data is returned on a successful callback result? Is the expected data already synced from a previously `DataStore.start` process? See https://github.com/aws-amplify/amplify-swift/pull/1678 for more details in accessing and reading the local database file to see if the data has already been synced.

**Comment by albemala** [comment]
Thanks @lawmicha for your prompt response. I run some more tests, here's the result:

- The first time I run the app while online, querying DataStore works correctly. All data is returned as expected. I wait for DataStore to fully sync and I receive a `DataStore.ready` event.
- If I run the app a second time while offline, `Amplify.DataStore.query` calls complete successfully, but they return empty data (for example an empty array instead of an array of items)
- Running the app again while online, it works as expected, returning all data again. So I believe the data is available locally, but DataStore doesn't return it when querying it while offline. 

> While the app is offline, DataStore.start will attempt to sync data from AppSync to the local DB in a retry loop (if it detects the problem is a network problem), and should not impact your calls to get data from the local DB.

Thanks for the clarification, that makes sense.

**Comment by albemala** [comment]
Please let me know if you need more information from me and if I can help, thanks

**Comment by albemala** [comment]
I did some further investigation, here's my findings. 

When starting the app, we stop and restart DataStore, to setup sync expressions based on current user:

```
// When opening the app, if a user is already logged in, start syncing DataStore
if let currentUser = Amplify.Auth.getCurrentUser() {
    logger.debug("current user: \(currentUser)")
    setDataStoreSyncExpression(owner: currentUser.username)
}

...

func setDataStoreSyncExpression(owner newOwner: String) {
    logger.debug("current owner: \(owner) - new owner: \(newOwner)")
    if owner == newOwner { return }
    logger.debug("setting new owner")
    owner = newOwner
    restartDataStoreSync()
}

func restartDataStoreSync() {
    // clear also stops DataStore syncing
    Amplify.DataStore.clear { result in
        switch result {
        case .success:
            logger.debug("DataStore stopped")
            Amplify.DataStore.start { result in
                switch result {
                case .success:
                    logger.debug("DataStore started")
                case .failure(let error):
                    logger.error("Error starting DataStore:\(error)")
                }
            }
        case .failure(let error):
            logger.error("Error stopping DataStore:\(error)")
        }
    }
}
```

As mentioned before, If I start the app while offline, querying DataStore returns no results (even if the underlying DB contains data). 

But if I disable the code that restarts DataStore (`restartDataStoreSync()`), then querying works again, even while offline. I believe the problem then is when stopping and restarting DataStore while offline.

I also get these logs when starting DataStore, I'm not sure they are relevant:

```
2023-04-27 10:56:38.683237+0200 Runner[60152:4569760] [Debug] [AWSDataStorePlugin.queue] [AmplifyConfiguration.swift:139] restartDataStoreSync() > DataStore started
2023-04-27 10:56:38.683241+0200 Runner[60152:4569784] [RemoteSyncEngine] pauseMutations()
2023-04-27 10:56:38.683252+0200 Runner[60152:4569784] [OutgoingMutationQueue] stopSyncingToCloud(_:)
2023-04-27 10:56:38.683837+0200 Runner[60152:4569784] [StateMachine<State, Action>] Notifying: receivedStop((Function))
2023-04-27 10:56:38.683950+0200 Runner[60152:4569784] [StateMachine<State, Action>] resolve(stopped, receivedStop((Function))) -> stopping((Function))
2023-04-27 10:56:38.683969+0200 Runner[60152:4569784] [OutgoingMutationQueue] New state: stopping((Function))
2023-04-27 10:56:38.684000+0200 Runner[60152:4569784] [OutgoingMutationQueue] respond(to:): stopping((Function))
2023-04-27 10:56:38.684007+0200 Runner[60152:4569784] [OutgoingMutationQueue] doStop(completion:)
2023-04-27 10:56:38.684012+0200 Runner[60152:4569784] [OutgoingMutationQueue] doStopWithoutNotifyingStateMachine(completion:)
2023-04-27 10:56:38.684027+0200 Runner[60152:4569784] [StateMachine<State, Action>] Notifying: doneStopping
2023-04-27 10:56:38.684044+0200 Runner[60152:4569784] [StateMachine<State, Action>] resolve(stopping((Function)), doneStopping) -> stopped
2023-04-27 10:56:38.684166+0200 Runner[60152:4569784] [OutgoingMutationQueue] New state: stopped
2023-04-27 10:56:38.686940+0200 Runner[60152:4569784] [StateMachine<State, Action>] Notifying: pausedMutationQueue(AWSDataStorePlugin.SQLiteStorageEngineAdapter)
2023-04-27 10:56:38.686990+0200 Runner[60152:4569784] [StateMachine<State, Action>] resolve(pausingMutationQueue, pausedMutationQueue(AWSDataStorePlugin.SQLiteStorageEngineAdapter)) -> clearingStateOutgoingMutations(AWSDataStorePlugin.SQLiteStorageEngineAdapter)
2023-04-27 10:56:38.687009+0200 Runner[60152:4569784] [RemoteSyncEngine] New state: clearingStateOutgoingMutations(AWSDataStorePlugin.SQLiteStorageEngineAdapter)
2023-04-27 10:56:38.687036+0200 Runner[60152:4569784] [OutgoingMutationQueue] respond(to:): stopped
2023-04-27 10:56:38.687061+0200 Runner[60152:4569784] [RemoteSyncEngine] respond(to:): clearingStateOutgoingMutations(AWSDataStorePlugin.SQLiteStorageEngineAdapter)
2023-04-27 10:56:38.687069+0200 Runner[60152:4569784] [RemoteSyncEngine] clearStateOutgoingMutations(storageAdapter:)
```

**Comment by royjit** [comment]
` Amplify.DataStore.clear()` will clear the local database, this might be the reason that you are getting empty result while offline.  If you are looking to stop the sync consider using ` Amplify.DataStore.stop()`

https://docs.amplify.aws/lib/datastore/other-methods/q/platform/ios/

**Comment by albemala** [comment]
@royjit you are absolutely right, that's the reason why it wasn't working! Thanks a lot for pointing it out.

I'm going to close this ticket as the problem is now solved.
