### ISSUE TITLE
Signup results in link being emailed not code.

### ISSUE THREAD

**Issue by orthoteks** [aws-amplify/amplify-swift#2670]
### Describe the bug

Despite the configuration on cognito, where we have the code option selected, a link is emailed instead of a code.

### Steps To Reproduce

```swift
Configure Amplify Auth normally with the "Email" option for username.
Amplify.Auth.signup(...)
Email is sent but with a link instead of a code. Our UI is prompting to enter the code.
```

### Expected behavior

Have a code emailed to a new signup, not a link.

### Amplify Framework Version

10.6.1

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

10.6.1

### Xcode version

14.2

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

iphone 14

### iOS Version

16

### Specific to simulators

_No response_

### Additional context

**Comment by orthoteks** [comment]
![Screenshot 2023-01-12 at 1 14 56 PM](https://user-images.githubusercontent.com/33560508/212150437-49024d40-4ec7-47c2-bc69-31af2e6e7dc4.png)

**Comment by atierian** [comment]
Thanks for opening this @orthoteks.
The Amplify version you noted is for the Amplify CLI. Can you please let us know which version of Amplify Swift you're using? Since you're using SPM, you can find the version in Project Navigator > Packaging Dependencies.

**Comment by atierian** [comment]
Also please include a code snippet showing how you're calling `Amplify.Auth.signUp(...)`. Thanks!

**Comment by orthoteks** [comment]
amplifyconfiguration.json (auth part)
<img width="288" alt="Screenshot 2023-01-12 at 2 05 02 PM" src="https://user-images.githubusercontent.com/33560508/212158863-f8f74b9c-1ada-4dcb-88a5-7f6597d9a237.png">

**Comment by atierian** [comment]
Thanks for this information. Can you confirm that the User Pool in the first screenshot is the same User Pool included in your `amplifyconfiguration.json`?

**Comment by orthoteks** [comment]
Yes... confirmed.

**Comment by orthoteks** [comment]
![Screenshot 2023-01-12 at 6 08 38 PM](https://user-images.githubusercontent.com/33560508/212200546-31a12d2a-3677-4567-a080-e67a5bec4473.png)

Log from a lambda function (fitsc0f77ae6CustomMessage-dev) that is executed when a user registers... the email/sms messaging is there.
 
![Screenshot 2023-01-12 at 6 12 54 PM](https://user-images.githubusercontent.com/33560508/212201012-156cad2e-7957-402f-8efc-dec4c4a61ab1.png)

**Comment by orthoteks** [comment]
Since the issue seemed to be in the lambda setup, I ran amplify update auth which resolved the issue.
Thanks
