### ISSUE TITLE
Unable to sign in

### ISSUE THREAD

**Issue by stephanemouawad** [aws-amplify/amplify-swift#2672]
### Describe the bug

Hello, first of all I am sorry if this problem has already been solved.

The **_Sign In_** api always throws a notAuthorized error even if the credentials are good.

`let result = try await auth.signIn(username: username, password: password)`

At the moment, I am able to sign up and confirm the sign up with the OTP.

### Steps To Reproduce

```swift
1 Sign Up
2 Confirm sign Up
3 try to sign in with the V2 api(s) Async / Await

Example:
do {
  let result = try await auth.signIn(username: username, password: password)
  print(result.nextStep)
} catch {
   // I am stuck here with a generic error
   print(error)
}
```

### Expected behavior

- Sign Up with username and a generic password
- Confirm Sign Up
- The generic password is no longer valid, the user must change it in order to continue using our services
- Sign In should return **_confirmSignInWithNewPassword_**
- Confirm Sign In with the new password

This scenario works fine with old Cognito api, Now we are replacing Cognito by Amplify Auth

My Config.json

```
{
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "IdentityManager": {
                    "Default": {}
                },

                "CredentialsProvider": {
                    "CognitoIdentity": {
                        "Default": {}
                    }
                },

                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "xxxxx",
                        "AppClientId": "xxxxx",
                        "Region": "xxxxx",
                        "Endpoint": "xxxxx"
                    }
                }
            }
        }
    },

    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "Default": {
                    "endpointType": "GraphQL",
                    "endpoint": "xxxxx",
                    "region": "xxxxx",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS"
                },

                "ApiKey": {
                    "endpointType": "GraphQL",
                    "endpoint": "xxxxx",
                    "region": "xxxxx",
                    "authorizationType": "API_KEY",
                    "apiKey": "xxxxx"
                }
            }
        }
    }
}

```

### Amplify Framework Version

2.2.1

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.7.1

### CLI version

I do not use it

### Xcode version

14.1

### Relevant log output

```
AuthError: Incorrect username or password.
Recovery suggestion: Check whether the given values are correct and the user is authorized to perform the operation.
  ▿ notAuthorized : 3 elements
    - .0 : "Incorrect username or password."
    - .1 : "Check whether the given values are correct and the user is authorized to perform the operation."
    - .2 : nil
```

### Is this a regression?

No

### Device

Simulator iPhone 14

### iOS Version

iOS 14.0

### Additional context

- We added a KeychainSharing
- We tried both options **Enabled** and **Legacy** of _PreventUserExistenceErrors_

**Comment by phantumcode** [comment]
@stephanemouawad Thank you submitting the issue and your patience.  I was not able to reproduce this issue.

Did you use amplify cli to configure your app and authentication? If so, can you provide the amplifyconfiguration.json file?
Based on the details of the config.json you provided, it doesn't look like you're missing the credentials provider.

Also, why is this password invalid signup an expected behavior after sign in? Can you point me to any documentation you're referencing that would cause the password to be invalidated after signup?

**Comment by phantumcode** [comment]
If you didn't use amplify cli to configure authentication, please provide additional details on your authentication configuration and any custom settings you've configured.

**Comment by stephanemouawad** [comment]
Hello, 

My amplifyconfiguration.json file is the one just above

**_Also, why is this password invalid signup an expected behavior after sign in? Can you point me to any documentation you're referencing that would cause the password to be invalidated after signup?_**

`https://docs.aws.amazon.com/cognito/latest/developerguide/signing-up-users-in-your-app.html`

```
Password Reset Required
The user account is confirmed, but the user must request a code and reset their password before they can sign in.

User accounts that are imported by an administrator or developer start in this state.

Force Change Password
The user account is confirmed and the user can sign in using a temporary password, but on first sign-in, the user must changetheir password to a new value before doing anything else.
```

**_Also, why is this password invalid signup an expected behavior after sign in?_**

```
The UX of our App does not suit the default Signup Cognito flow. Here is an example.

Cognito's default registration mechanism : username + password => OTP => done 
Our registration mechanism: username => OTP => password => done
```

_**If you didn't use amplify cli to configure authentication, please provide additional details on your authentication configuration and any custom settings you've configured.**_

```
Unfortunately, I don't know what the current configuration is :/.
I'm waiting for this information.
```

**Comment by phantumcode** [comment]
@stephanemouawad Thanks for your patience, I was not able to reproduce this issue.  I created a new user in Cognito User Pool with a temporary password and verified in Cognito User Pool the Confirmation Status was `Force change password`.  When I sign in via a test app, the user authentication state required a password reset.

![image](https://user-images.githubusercontent.com/103537251/218218764-86d1c4e7-a609-41d8-af5f-d07affdc01a9.png)
```
    "AuthState.configured" =     {
        "AuthenticationState.signingIn" =         {
            "SignInState.resolvingChallenge" =             {
                "SignInChallengeState.waitingForAnswer" =                 {
                    challenge = "AWSCognitoIdentityProvider.CognitoIdentityProviderClientTypes.ChallengeNameType.newPasswordRequired";
                    username = "ph*******ev";
                };
                challengeType = "AWSCognitoAuthPlugin.AuthChallengeType.newPasswordRequired";
                signInMethod = "AWSCognitoAuthPlugin.SignInMethod.apiBased(AWSCognitoAuthPlugin.AuthFlowType.userSRP)";
            };
        };
        "AuthorizationState.signingIn" =         {
        };
    };
```

Can you confirm that the user state in Cognito User Pool is in `Force change password` ?  Are you importing users or manually creating users in Cognito User Pool? Do you have a sign-in or sign-up lambda triggered to set a temporary password?

The logout output in the description is `not Authorized`, can you confirm that the username and/or temporary password is correct?  If would be helpful if you can provide the full log output as well.

**Comment by thisisabhash** [comment]
Hello, I am not able to reproduce this issue through `Amplify.signUp`. 
Only way I see to reach the `FORCE_CHANGE_PASSWORD` state is to create users from Cognito console and then call `Amplify.signIn` which I can confirm am able to reproduce the flow. 
From the Cognito docs, https://docs.aws.amazon.com/cognito/latest/developerguide/signing-up-users-in-your-app.html , that is how we can reach that state. Were you earlier using `AdminCreateUser` Cognito API in your use cases? 
Also, it'd be helpful if you can share verbose logs by calling `Amplify.Logging.loglevel = .verbose` before calling `Amplify.configure()` and removing sensitive information.

**Comment by harsh62** [comment]
The `FORCE_CHANGE_PASSWORD` workflow seems to work fine. Please reopen the issue with more details requested by @phantumcode and @thisisabhash, if you are still facing any problems.
