### ISSUE TITLE
Multiple instances of the Amplify SDK in a single app

### ISSUE THREAD

**Issue by paiv** [aws-amplify/amplify-swift#2723]
### Is your feature request related to a problem? Please describe.

In an app with two independent features backed by two Amplify backends we would like to delegate implementation to two teams, each using their own Amplify SDK configuration, and then integrate their work in a single app. (Each team producing a binary package/framework/library for integration.)

On a first glance this is not possible due to shared singleton configuration
https://github.com/aws-amplify/amplify-swift/blob/2c147038af06a6767882b665df31dea35d95380d/Amplify/Amplify.swift#L30-L37

Can you please confirm this is not supported in the current architecture, without me making a sample app?

### Describe the solution you'd like

There could be multiple Amplify instances, each having its own `setup` entry point.

### Describe alternatives you've considered

None really.

### Additional context

Related:
- https://github.com/aws-amplify/amplify-swift/issues/814

**Comment by phantumcode** [comment]
@paiv Thanks for submitting your question.  You are correct, the current Amplify architecture does not support multiple "Amplify instances".  Can you explain your use cases and what is the need for two independent features with different Amplify backends?  Amplify backends are different AWS services, i.e. storage is supported with AWS S3 and Geo is supported with AWS Location Services.

**Comment by paiv** [comment]
@phantumcode The "independent features" inside the app each use the full range of AWS services, and potentially will be billed to different AWS accounts.
