### ISSUE TITLE
AmplifyTests fails from the CLI

### ISSUE THREAD

**Issue by jcjimenez** [aws-amplify/amplify-swift#2745]
### Describe the bug

Running unit tests from the command line results in this failure:

```
amplify-swift/Amplify/Categories/Auth/AuthCategory.swift:18: Fatal error: Authentication category is not configured. Call Amplify.configure() before using any methods on the category.
error: Exited with signal code 5
```

### Steps To Reproduce

1. Checkout a fresh copy of the `main` branch
2. Run `swift test --filter AmplifyTests.AuthCategoryConfigurationTests`
3. See the error

### Expected behavior

All unit tests should pass

### Amplify Framework Version

2.x

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.7.1

### CLI version

10.4.1

### Xcode version

Version 14.1 (14B47b)

### Relevant log output

```shell
amplify-swift/Amplify/Categories/Auth/AuthCategory.swift:18: Fatal error: Authentication category is not configured. Call Amplify.configure() before using any methods on the category.
error: Exited with signal code 5
```

### Is this a regression?

No

### Device

iPhone Simulator

### iOS Version

16.1

**Comment by royjit** [comment]
The error is thrown because the following flag does not work if we start the test from the CLI - https://github.com/aws-amplify/amplify-swift/blob/61c9a6c7c9574a553cde05e14fadaba16cda4887/Amplify/Core/Support/AmplifyTesting.swift#L18

Consider running the test using xcodebuild
