### ISSUE TITLE
Amplify.Auth.signUp helper shows Type of expression is ambiguous without more context

### ISSUE THREAD

**Issue by RameshBoosa** [aws-amplify/amplify-swift#2754]
**Describe the bug**
Amplify.Auth.signUp implemented in  AuthCatageory+ ClientBehaviour.swift which is also adopted AuthCatageory protocol. both shouldn't be public, though it's public since we are calling with Auth which is a instance of AuthCatageory() it should show ambiguous issue

Currently blocked because of the above issue to integrate with my mobile app. please prioritize and provide quick fix

**To Reproduce**
1. Go to 'Add package and add amplify-ios' spm to your project
2. open any view and import 'import Amplify' 
3. Implement any auth function , in my case implemented  'Amplify.Auth.signUp(username: username, password: password, options: options) {}'
4. See error 'Type of expression is ambiguous without more context'

**Observed Behavior**

**Expected Behavior**
It should not show Type of expression is ambiguous without more context error rather it should allow consumer to signup via mobile app.

**Stack Trace**

**Code Snippet**
`func signUp(username: String, email: String, password: String) {
        let attributes = [AuthUserAttribute(.email, value: email)]
        let options = AuthSignUpRequest.Options(userAttributes: attributes)
        
        let result = Amplify.Auth.signUp(username: username, password: password, options: options) { [weak self] result in
            switch result {
            case .success(let signupResult):
                print("Signup result:", signupResult)
                switch signupResult.nextStep {
                case .done:
                    print("Finished signup")
                case .confirmUser(let details, _):
                    print(details ?? "details not available")
                    DispatchQueue.main.async {
                        authState  = .confirmCode(userName: username)
                    }
                }
            case .failure(let error):
                print("Signup failed:", error)
            }
        }
    }`

**Unique Configuration**
If you are reporting an issue with a unique configuration or where configuration can make a difference in code execution (i.e. Cognito) please provide your configuration. Please make sure to obfuscate sensitive information from the configuration before posting.

**Areas of the SDK you are using (AWSMobileClient, Cognito, Pinpoint, IoT, etc)?**
Amplify, AWSCognito

**Screenshots**

**Environment(please complete the following information):**
 - SDK Version: Amplify2.3.2
 - Dependency Manager: Swift Package manager
 - Swift Version : 5
 - Xcode Version: 14.2

**Device Information (please complete the following information):**
 - Device: 14 pro
 - iOS Version: 16.2
 - Specific to simulators: 14 pro

**Additional context**
Add any other context about the problem here like your specific use case.

**Relevant Console Output**
In some cases, it might be helpful to add any logs from your console that better help you tell the story of this issue. You can easily enable logging in your app by putting the following code in your app delegate.
```
AWSDDLog.sharedInstance.logLevel = .debug
AWSDDLog.add(AWSDDTTYLogger.sharedInstance)
```

**Logs**

Please logs in the code block below. (See: [Logs Guidance](https://github.com/aws-amplify/aws-sdk-ios/blob/main/LogsGuidance.md.md))

<details>
<summary>Log Messages</summary>

```
INSERT LOG MESSAGES HERE
```
</details>

**Comment by RameshBoosa** [comment]
Thanks @atierian, thank you for the response. found the updated docs and integrated as per latest docs. everything working as expected. 

in my use case assigning a changeWithNew password challenge for consumer and responding to challenge with new password. login is working and status also updated to confirmed in user pool. but both **SignIn** and **ConfirmSignwithnewpassword** helpers doesn't provide **tokens(id token, access token and refresh token in response)**. can you route me to the right helper function to fetch upon successful login?

**Comment by atierian** [comment]
Glad to hear you have sign up working as expected.

Here's the documentation on accessing tokens: [Authentication > Accessing Credentials](https://docs.amplify.aws/lib/auth/access_credentials/q/platform/ios/)

Note the text at the top of that page. Amplify handles everything auth related for other Amplify categories (Storage, Analytics, Geo, etc) behind the scenes. This means that you generally don't need to retrieve credentials yourself unless you need them to authenticate requests you're making outside of Amplify.

Let me know if you have any other questions.

**Comment by atierian** [comment]
Closing, as the questions appear to be resolved. Let me know if you have any other questions. Thanks!
