### ISSUE TITLE
Could not build Objective-C module 'libtommathAmplify'

### ISSUE THREAD

**Issue by leeari95** [aws-amplify/amplify-swift#2759]
### Describe the bug

I installed the library by setting it up with Tuist.
When I build after installation, the following problem occurs.

<img width="246" alt="image" src="https://user-images.githubusercontent.com/75905803/217467636-fdbfdf9c-3923-4e08-9519-64c039fea5a4.png">

```
Could not build Objective-C module 'libtommathAmplify'
```

### Steps To Reproduce

After tuist edit, set dependencies as follows.
```swift
public extension TargetDependency.SPM {
    static let Amplify = TargetDependency.external(name: "Amplify")
    static let AWSAPIPlugin = TargetDependency.external(name: "AWSAPIPlugin")
    static let AWSPinpointAnalyticsPlugin = TargetDependency.external(name: "AWSPinpointAnalyticsPlugin")
    static let AWSCognitoAuthPlugin = TargetDependency.external(name: "AWSCognitoAuthPlugin")
    static let AWSDataStorePlugin = TargetDependency.external(name: "AWSDataStorePlugin")
    static let AWSLocationGeoPlugin = TargetDependency.external(name: "AWSLocationGeoPlugin")
    static let AWSS3StoragePlugin = TargetDependency.external(name: "AWSS3StoragePlugin")
}

```

Afterwards, if you build by executing Xcode with the tuist generator command, the error occurs.

### Expected behavior

The build should succeed normally.

### Amplify Framework Version

2.0.0

### Amplify Categories

Storage

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

noon

### Xcode version

14.1

### Relevant log output

```
'../amplify_tommath.h' file not found
```

### Is this a regression?

No

### Device

iPhone 14 Pro

### iOS Version

iOS 16.1

**Comment by leeari95** [comment]
https://docs.tuist.io/guides/third-party-dependencies/#some-notes-on-the-integration-of-swift-packages

I found a solution through the link above.

**Comment by nonameplum** [comment]
@leeari95 Could you tell what exactly did you do to resolve the issue?

**Comment by nonameplum** [comment]
I have created small project representing the issue:
https://github.com/nonameplum/tuist-amplify
