### ISSUE TITLE
Unable to Build App for iOS 16.4 update with Swift 5.8

### ISSUE THREAD

**Issue by gurkarangulati** [aws-amplify/amplify-swift#2771]
### Describe the bug

Currently I've updated my test device to iOS 16.4 beta. To deploy to this device I had to update the Xcode to the Xcode 14.3 beta. The new beta also utilizes Swift 5.8. When I build my amplify project on this setup, I get the following error: 
![Screenshot 2023-02-19 at 12 41 26 AM](https://user-images.githubusercontent.com/4088575/219933176-c3e0c7d4-0e40-4ad5-b28e-218741eba6ee.png)

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Create amplify swift app with Xcode 14.3, Swift 5.8,
2. Add package dependency for Amplify
3. Build app
4. See error
```

### Expected behavior

Expected to be able to build application with new Swift version.

### Amplify Framework Version

2.4.0

### Amplify Categories

Analytics, API, Auth, DataStore, Geo, Predictions, Storage

### Dependency manager

Swift PM

### Swift version

5.8

### CLI version

10.7.3

### Xcode version

14.3-beta

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

Yes

### Regression additional context

Swift 5.7, Xcode 14.2 & iOS 16.3 works perfect okay

### Device

iPhone 14 pro

### iOS Version

iOS 16.4

### Specific to simulators

_No response_

### Additional context

Client Runtime error.

**Comment by atierian** [comment]
Thanks for opening this issue @gurkarangulati. We'll update you here once a fix has been released.

**Comment by gurkarangulati** [comment]
Thank you so much! Tested & confirmed. Works!

**Comment by atierian** [comment]
Version [2.4.1](https://github.com/aws-amplify/amplify-swift/releases/tag/2.4.1) contains the fix.
