### ISSUE TITLE
How to get and set _version with DataStore when attempting to replace a list

### ISSUE THREAD

**Issue by maziarzamani** [aws-amplify/amplify-swift#2779]
### Is your feature request related to a problem? Please describe.

I need to replace a list at every single mutation, and thus need the ability to get as well as set `_version`, otherwise AUTOMERGE conflict resolution will try to concatenate the data, which I do not wish. 

Here is an example of an attribute where it is necessary to override the standard AUTOMERGE behaviour of a list:

```graphql
type TestModel 
  @model 
  @auth(rules: [
    {allow: owner, ownerField: "owner"},
    {allow: owner, ownerField: "secondaryOwners", operations: [update, read, create]}
    {allow: private, operations: [create]}
  ]) {
  id: ID!
  owner: String!
  secondaryOwners: [String] 
}
```

With [AUTOMERGE](https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html) it is currently impossible to replace the list in secondaryOwners as this standard behaviour will fire:

- Conflict on a scalar field: GraphQL scalar or any field that is not a collection (i.e. List, Set, Map). Reject the incoming value for the scalar field and select the value existing in the server.

- Conflict on a list: GraphQL type and database type are lists. Concatenate the incoming list with the existing list in the server. The list values in the incoming mutation will be appended to the end of the list in the server. Duplicate values will be retained.

- Conflict on a set: GraphQL type is a list and database type is a Set. Apply a set union using incoming the set and the existing set in the server. This adheres to the properties of a Set, meaning no duplicate entries.

### Describe the solution you'd like

Ability to get and set `_version`

### Describe alternatives you've considered

None

### Is the feature request related to any of the existing Amplify categories?

DataStore

**Comment by royjit** [comment]
Hi @maziarzamani , thanks for opening this feature request. We’ll look into it and respond with an update here.

**Comment by 5d** [comment]
Hi @maziarzamani 
Could you provide more details about how you replacing the list? 
An example schema showing the relationship and the steps to replace list would help us to move forward.

**Comment by maziarzamani** [comment]
@5d, the procedure is quite simple, you get the current `_version`, and when you perform a mutation you set the same `_version` and the new list you wish to replace. This will avoid merging/concat the list types.

**Comment by maziarzamani** [comment]
Hi @royjit, any process on this issue? I will update the original post with extra context.

**Comment by maziarzamani** [comment]
Support suggested me to use OPTIMISTIC_CONCURRENCY, but this makes absolutely no difference. The current `_version` needs to be set in the mutation in order to replace the list. DataStore does not expose `_version` so this is practically impossible. How do people empty a list?

**Comment by maziarzamani** [comment]
We spoke to AWS Support, and trying out OPTIMISTIC_CONCURRENCY, which should solve the issue for us. I will return if something goes sideways. Thanks!

**Comment by 5d** [comment]
Hi @maziarzamani ,

The field named `_version` is intended for private use and is necessary for the default conflict strategy to function properly. It can only be modified by the server-side.

When using the `OPTIMISTIC_CONCURRENCY` conflict strategy, requests with same version numbers will be declined, as stated in the documentation. If multiple requests with the same `_version` number are submitted for the same record, only the first request received by the server will be accepted, while the others will be rejected. You may want to implemente proper error handling for the rejected requests.

In case you want to apply different conflict resolution on different fields within your model, one potential solution could be utilizing the `LAMBDA` conflict strategy with a custom lambda function.

**Comment by lawmicha** [comment]
Please re-open if this is still an issue for you, and please provide some more details around your call site, which APIs are you using from Amplify.DataStore and how you are performing the mutations.
