### ISSUE TITLE
How can sort in query of paginatedList in swift 5?

### ISSUE THREAD

**Issue by sonibhavik** [aws-amplify/amplify-swift#2786]
### Describe the bug

I am using aws amplify for chat purpose and using paginatedList query to get data and adding limit to get certain messages. Right now I am getting random messages, not in ascending or descending order. Can anybody help to get this done? It would be really helpful.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Expected behavior

Need data in ascending or descending order.

### Amplify Framework Version

1.28.3

### Amplify Categories

API, Storage

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

1.28.3

### Xcode version

14.2

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

iPhone 13

### iOS Version

16.2

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by royjit** [comment]
Hi, Will you be able to solve your use case by the code below using Datastore category:

```swift
let posts = try await Amplify.DataStore.query(
    Post.self,
    sort: .ascending(Post.keys.rating)
    paginate: .page(0, limit: 100))

```

I am checking if similar functionality exists in API category, if not we could configure the graphQL request as mentioned here [query with sorting](https://docs.amplify.aws/guides/api-graphql/query-with-sorting/q/platform/js/#implementation) and [use custom graphQL request](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios/).

**Comment by royjit** [comment]
I was able to get a sorted list with the following schema:

```
type Blog @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String!
  post: [Post] @hasMany(indexName: "postByBlog", fields: ["id"])
}

type Post @model @auth(rules: [{allow: public}]) {
  id: ID!
  name: String! @index(name: "postsByDate", queryField: "postsByDate", sortKeyFields: ["createdAt"])
  blog_id: ID @index(name: "postByBlog")
  blog: Blog @belongsTo(fields: ["blog_id"])
  createdAt: String!
}

```

Using the custom query:

```swift
extension GraphQLRequest {
    static func getcustomPost(byName name: String) -> GraphQLRequest<List<Post>> {
          let document = """
          query postsByDate($name: String!) {
            postsByDate(name: $name, sortDirection: ASC) {
                items {
                    id
                    name
                    __typename
                }
            }
          }
          """
          return GraphQLRequest<List<Post>>(
              document: document,
              variables: ["name": name],
              responseType: List<Post>.self,
              decodePath: "postsByDate"
          )
      }
}

```

and then invoking the query by:

```swift
let result = try await Amplify.API.query(request: .getcustomPost(byName: "<Post>"))
```

Let us know if this works for your use case.

**Comment by dan-codes1** [comment]
hey @royjit I'm having issues with that solution
