### ISSUE TITLE
Framework not found AWSAuthCore

### ISSUE THREAD

**Issue by bitsplash-andy** [aws-amplify/amplify-swift#2815]
I'm attempting to upgrade to the v2 library.

I previously installed the v1 via cocoapods but can't find an option for that for the v2 library.

I've followed the instructions to install via the package manager in XCode but when I attempt to build I am getting the error: 
'Framework not found AWSAuthCore'

Am I missing something in order to get this working?

**Comment by atierian** [comment]
Thanks for opening this issue @bitsplash-andy.

Amplify Swift v2 only supports SPM, and not CocoaPods.
Based on the error `Framework not found AWSAuthCore`. it sounds like you still have a reference to Amplify v1 with CocoaPods in your project. You'll need to remove that.

**Comment by bitsplash-andy** [comment]
Hi,

Many thanks for getting back to me.

I have removed all AWS and amplify references from the pod file, also ran
pod reintegrate, cleaned the build, emptied the derives data folder and
restarted the machine, but the error persists.

Any help would be appreciated.

**Comment by atierian** [comment]
Can you provide your full build logs please? You can find those in the **Report Navigator** tab of Xcode.
You can also check in **Project Navigator > <Your App Target> > Build Phases > Link Binary With Libraries** to see if `AWSAuthCore` or an Amplify v1 pod is included there.

**Comment by bitsplash-andy** [comment]
Sure! ...

`Ld /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/MyApp.app/MyApp normal (in target 'MyApp' from project 'MyApp')
    cd /Users/andy/Development/MyApp/Apps/iOS
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target arm64-apple-ios15.0-simulator -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.2.sdk -L/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/EagerLinkingTBDs -L/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.2.sdk/usr/lib/swift -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/EagerLinkingTBDs -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/Branch -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/FirebaseAppCheck -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/FirebaseCore -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/FirebaseCoreInternal -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/FirebaseInstallations -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/GoogleUtilities -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/IGIdenticon -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/PromisesObjC -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/nanopb -F/Users/andy/Development/MyApp/Apps/iOS/Pods/FirebaseAnalytics/Frameworks -F/Users/andy/Development/MyApp/Apps/iOS/Pods/Google-Mobile-Ads-SDK/Frameworks/GoogleMobileAdsFramework -F/Users/andy/Development/MyApp/Apps/iOS/Pods/GoogleAppMeasurement/Frameworks -F/Users/andy/Development/MyApp/Apps/iOS/Pods/GoogleUserMessagingPlatform/Frameworks/Release -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/FirebaseAnalytics/WithoutAdIdSupport -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/Google-Mobile-Ads-SDK -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleAppMeasurement/AdIdSupport -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleAppMeasurement/WithoutAdIdSupport -F/Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/XCFrameworkIntermediates/GoogleUserMessagingPlatform -filelist /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/arm64/MyApp.LinkFileList -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/arm64/MyApp_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/arm64/MyApp.swiftmodule -ObjC -lc++ -lsqlite3 -lz -framework AVFoundation -framework AudioToolbox -framework Branch -framework CFNetwork -framework CoreGraphics -framework CoreMedia -framework CoreServices -framework CoreTelephony -framework CoreVideo -framework FBLPromises -framework FirebaseAnalytics -framework FirebaseAppCheck -framework FirebaseCore -framework FirebaseCoreInternal -framework FirebaseInstallations -framework Foundation -framework GoogleAppMeasurement -framework GoogleAppMeasurementIdentitySupport -framework GoogleMobileAds -framework GoogleUtilities -framework IGIdenticon -framework MediaPlayer -framework MessageUI -framework MobileCoreServices -framework QuartzCore -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -framework UserMessagingPlatform -framework WebKit -framework iAd -framework nanopb -weak_framework AdSupport -weak_framework DeviceCheck -weak_framework JavaScriptCore -weak_framework LinkPresentation -weak_framework SafariServices -weak_framework WebKit -ObjC -lc++ -lsqlite3 -lz -framework AVFoundation -framework AWSAuthCore -framework AWSCognitoIdentityProvider -framework AWSCognitoIdentityProviderASF -framework AWSCore -framework AWSMobileClient -framework AWSPluginsCore -framework AWSS3 -framework Amplify -framework AmplifyPlugins -framework AudioToolbox -framework CFNetwork -framework CoreGraphics -framework CoreMedia -framework CoreTelephony -framework CoreVideo -framework FBLPromises -framework Foundation -framework GoogleAppMeasurement -framework GoogleMobileAds -framework GoogleUtilities -framework MediaPlayer -framework MessageUI -framework MobileCoreServices -framework QuartzCore -framework Security -framework StoreKit -framework SystemConfiguration -framework UIKit -framework UserMessagingPlatform -framework WebKit -framework nanopb -weak_framework AdSupport -weak_framework JavaScriptCore -weak_framework SafariServices -weak_framework SwiftUI -weak_framework WebKit -fprofile-instr-generate -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/MyApp.build/Debug-iphonesimulator/MyApp.build/MyApp.app-Simulated.xcent -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __ents_der -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/MyApp.build/Debug-iphonesimulator/MyApp.build/MyApp.app-Simulated.xcent.der -framework AdServices -framework Pods_MyApp -Xlinker -no_adhoc_codesign -Xlinker -dependency_info -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/MyApp.build/Debug-iphonesimulator/MyApp.build/Objects-normal/arm64/MyApp_dependency_info.dat -o /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Products/Debug-iphonesimulator/MyApp.app/MyApp -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/Amplify.build/Debug-iphonesimulator/AWSAPIPlugin.build/Objects-normal/arm64/AWSAPIPlugin.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/Amplify.build/Debug-iphonesimulator/Amplify.build/Objects-normal/arm64/Amplify.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/aws-sdk-swift.build/Debug-iphonesimulator/AWSClientRuntime.build/Objects-normal/arm64/AWSClientRuntime.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/smithy-swift.build/Debug-iphonesimulator/ClientRuntime.build/Objects-normal/arm64/ClientRuntime.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/aws-crt-swift.build/Debug-iphonesimulator/AwsCommonRuntimeKit.build/Objects-normal/arm64/AwsCommonRuntimeKit.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/swift-collections.build/Debug-iphonesimulator/Collections.build/Objects-normal/arm64/Collections.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/swift-collections.build/Debug-iphonesimulator/DequeModule.build/Objects-normal/arm64/DequeModule.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/swift-collections.build/Debug-iphonesimulator/OrderedCollections.build/Objects-normal/arm64/OrderedCollections.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/swift-log.build/Debug-iphonesimulator/Logging.build/Objects-normal/arm64/Logging.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/XMLCoder.build/Debug-iphonesimulator/XMLCoder.build/Objects-normal/arm64/XMLCoder.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/Amplify.build/Debug-iphonesimulator/AWSPluginsCore.build/Objects-normal/arm64/AWSPluginsCore.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/AppSyncRealTimeClient.build/Debug-iphonesimulator/AppSyncRealTimeClient.build/Objects-normal/arm64/AppSyncRealTimeClient.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/Starscream.build/Debug-iphonesimulator/Starscream.build/Objects-normal/arm64/Starscream.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/Amplify.build/Debug-iphonesimulator/AWSPinpointAnalyticsPlugin.build/Objects-normal/arm64/AWSPinpointAnalyticsPlugin.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/Amplify.build/Debug-iphonesimulator/AmplifyBigInteger.build/Objects-normal/arm64/AmplifyBigInteger.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/Amplify.build/Debug-iphonesimulator/AmplifySRP.build/Objects-normal/arm64/AmplifySRP.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/aws-sdk-swift.build/Debug-iphonesimulator/AWSCognitoIdentityProvider.build/Objects-normal/arm64/AWSCognitoIdentityProvider.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/aws-sdk-swift.build/Debug-iphonesimulator/AWSCognitoIdentity.build/Objects-normal/arm64/AWSCognitoIdentity.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/Amplify.build/Debug-iphonesimulator/AWSCognitoAuthPlugin.build/Objects-normal/arm64/AWSCognitoAuthPlugin.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/SQLite.swift.build/Debug-iphonesimulator/SQLite.build/Objects-normal/arm64/SQLite.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/aws-sdk-swift.build/Debug-iphonesimulator/AWSPinpoint.build/Objects-normal/arm64/AWSPinpoint.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/AmplifyUtilsNotifications.build/Debug-iphonesimulator/AmplifyUtilsNotifications.build/Objects-normal/arm64/AmplifyUtilsNotifications.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/Amplify.build/Debug-iphonesimulator/InternalAWSPinpoint.build/Objects-normal/arm64/InternalAWSPinpoint.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/Amplify.build/Debug-iphonesimulator/AWSLocationGeoPlugin.build/Objects-normal/arm64/AWSLocationGeoPlugin.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/aws-sdk-swift.build/Debug-iphonesimulator/AWSLocation.build/Objects-normal/arm64/AWSLocation.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/Amplify.build/Debug-iphonesimulator/AWSPinpointPushNotificationsPlugin.build/Objects-normal/arm64/AWSPinpointPushNotificationsPlugin.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/Amplify.build/Debug-iphonesimulator/AWSDataStorePlugin.build/Objects-normal/arm64/AWSDataStorePlugin.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/Amplify.build/Debug-iphonesimulator/AWSS3StoragePlugin.build/Objects-normal/arm64/AWSS3StoragePlugin.swiftmodule -Xlinker -add_ast_path -Xlinker /Users/andy/Library/Developer/Xcode/DerivedData/MyApp-fodukicgygfkrfbxthhozxthrlye/Build/Intermediates.noindex/aws-sdk-swift.build/Debug-iphonesimulator/AWSS3.build/Objects-normal/arm64/AWSS3.swiftmodule

ld: framework not found AWSAuthCore
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by bitsplash-andy** [comment]
So I can confirm it all installs and builds okay on a fresh app, but that doesn't help me on the upgrader pathway much.

I can't see any obvious references to any other AWS services / libraries though, not really sure where they may be buried in Xcode 🤔

**Comment by bitsplash-andy** [comment]
May thanks for your help, this was unfortunately an error at our end.

For anyone that may experience something similar, I ran `grep -r "AWSAuthCore" .` and noticed I got hits for `project.pbxproj`

It turns out somehow the old library was added to `OTHER_LDFLAGS` along the way.

**Comment by atierian** [comment]
Thanks for letting us know and for the tip for any future readers!
