### ISSUE TITLE
Amplify Calls in WidgetKit/Widget Extension Do Not Work

### ISSUE THREAD

**Issue by julianworden** [aws-amplify/amplify-swift#2861]
### Describe the bug

I have an Amplify iOS app I'm working on and it works great. However, I just tried to add a Widget Extension to the app and no network calls to Amplify appear to be working. Unfortunately, this is quite tricky to debug because there appears to be a bug in Xcode 14 that prevents breakpoints and print statements from executing in a Widget Extension, but I've narrowed the issue down to all asynchronous Amplify calls.

First, I started with a stock widget with no asynchronous calls or network calls and it worked perfectly fine with some static text, so I know the widget works. Then, I added a call to `Amplify.DataStore.query(User.self, byId: *userId Here*)` to simply display the username of the logged in user, and now my widget is blank. Calls to `Amplify.Auth` also produce no visible result in the widget. More notes:

- Amplify works fine in the iOS app itself, just not in the widget
- Other network calls work in the widget, only Amplify's don't
- There is a user logged in via the iOS app and the call to get the logged in user never throws an error, so I know a user is logged in
- Although the DataStore and Auth calls do not return a result, they also do not throw an error. It appears they just stall forever. **Even if I log out in the main app and then run the widget, no error is thrown**

Here is all the code for my widget (the DatabaseService is the same DatabaseService I use in the iOS app and it works fine there, so I know the problem isn't there, the code in the `getTimeline` method is most important, see my comments):

```
struct Provider: TimelineProvider {
    func placeholder(in context: Context) -> SimpleEntry {
        SimpleEntry(date: Date.now, user: User.example)
    }

    func getSnapshot(in context: Context, completion: @escaping (SimpleEntry) -> ()) {
        let entry = SimpleEntry(date: Date.now, user: User.example)

        // Check to see if data has been fetched. If it hasn't, use sample data. If it has, use real data
        if context.isPreview {
            entry = SimpleEntry(date: Date.now, user: User(username: "dfsa@gmail.com"))
        } else {
            entry = SimpleEntry(date: Date.now, user: User(username: "safd@gmail.com"))
        }

        completion(entry)
    }

    func getTimeline(in context: Context, completion: @escaping (Timeline<Entry>) -> ()) {
        Task {
            do {
                // This call does does not retrieve a User like it should, but it also never throws an error.
                let currentUser = try await DatabaseService.shared.getLoggedInUser()
                let entry = SimpleEntry(date: Date.now, user: currentUser)
                let timeline = Timeline(entries: [entry], policy: .atEnd)
                completion(timeline)
            } catch {
                // This block never gets reached, I know because the "ERROR" username never displays in the widget.
                var userDup = User.example
                userDup.username = "ERROR"
                let entry = SimpleEntry(date: Date.now, user: userDup)
                let timeline = Timeline(entries: [entry], policy: .atEnd)
                completion(timeline)
            }
        }
    }
}

struct SimpleEntry: TimelineEntry {
    let date: Date
    let user: User
}

struct AccountableWidgetsEntryView : View {
    let entry: SimpleEntry

    var body: some View {
        Text(entry.user.username)
    }
}

struct AccountableWidgets: Widget {
    let kind: String = "AccountableWidgets"

    var body: some WidgetConfiguration {
        StaticConfiguration(kind: kind, provider: Provider()) { entry in
            AccountableWidgetsEntryView(entry: entry)
        }
        .configurationDisplayName("This Week's Work")
        .description("A widget that shows the work stored in Accountable from the last week.")
        .supportedFamilies([.systemLarge])
    }
}
```

And just to be safe I also added the same Amplify setup code that's in my iOS app to the widget extension, the problem persists with and without it:

```
@main
struct AccountableWidgetsBundle: WidgetBundle {
    init() {
        configureAmplify()
    }

    func configureAmplify() {
        let apiPlugin = AWSAPIPlugin()
        let dataStorePlugin = AWSDataStorePlugin(modelRegistration: AmplifyModels())

        do {
            SDKLoggingSystem.initialize(logLevel: .warning)
            try Amplify.add(plugin: apiPlugin)
            try Amplify.add(plugin: dataStorePlugin)
            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            try Amplify.configure()
            
            Task {
                // Without this, syncing will not start immediately when the app starts.
                try await Amplify.DataStore.start()
            }
            print("Initialized Amplify")
        } catch {
            print("Could not initialize Amplify: \(error)")
        }
    }

    var body: some Widget {
        AccountableWidgets()
        AccountableWidgetsLiveActivity()
    }
}
```

Does Amplify support Widget Extensions? I don't see anything about them anywhere in the documentation and I can't find a single post from anyone anywhere trying to do what I'm doing, which is leading me to believe this might just not be possible. If this isn't possible, can anyone suggest a better way to go about this?

Thanks!

### Steps To Reproduce

Try to perform any Amplify call in WidgetKit and display the result in the widget, the widget will be blank.

### Expected behavior

The expected data should be fetched from Amplify and shown in the Widget.

### Amplify Framework Version

2.8.0

### Amplify Categories

Auth, DataStore

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

11.0.3

### Xcode version

Xcode 14.2 Build version 14C18

### Is this a regression?

No

### Device

iPhone 14 Pro Simulator and real iPhone 12 device

### iOS Version

iOS 16.2

### Specific to simulators

No

**Comment by jcjimenez** [comment]
@julianworden have you tried passing the data from your app to your widget instead of fetching it directly from the widget? It may be hitting a timeout (unable to initialize/fetch data in time) if all you're seeing is your widget's placeholder view/data.

**Comment by julianworden** [comment]
> @julianworden have you tried passing the data from your app to your widget instead of fetching it directly from the widget? It may be hitting a timeout (unable to initialize/fetch data in time) if all you're seeing is your widget's placeholder view/data.

I have not, mainly because I've seen other code examples where people successfully fetch data from APIs via widget extensions so I know it's possible. I probably could pass the data from the app (right after I learn how since I've never done that before), but I still think this is a bug since making network calls from a widget extension is possible with other APIs.

**Comment by julianworden** [comment]
> Hi, @julianworden, I was able to create a simple widget whose `IntentTimelineProvider` implementation does the following from `getTimeline(for:in:completion:)`:
> 
> 
> 
> * Configures Amplify, if needed
> 
> * Signs-In or Signs-Up, if needed
> 
> * Lists some files (using `Amplify.Storage.list`)
> 
> 
> 
> In order to make this work, I added `awsconfiguration.json` and `amplifyconfiguration.json` to the widget's target and made sure `getTimeline` callback was invoked within 30 seconds (I added some `Task.sleep` calls to confirm that anything past the 30 second mark resulted in my timeline request being considered MIA by Apple).
> 
> 
> 
> I also tried doing all this work from a ViewModel used by my widget's view, but it appears that anything beyond a single pass to the main runloop got ignored (so, it's probably best to do the network-related work from the `IntentTimelineProvider` implementation).
> 
> 
> 
> Please let us know if you have any other questions. Thanks!

Could you please share the code? It'd be great to see how you're making this work because I'm still not able to figure it out.

**Comment by julianworden** [comment]
@jcjimenez After working on this a bit more I'm finding that there are quite a few things missing from the documentation that would make working with a widget extension a lot easier, especially when communicating a log in/log out between the widget and the app when using Sign in with Apple or Google. I was able to figure all this stuff out and it appears to be working so I'll close this bug, but I'll happily make a more in depth write up in the https://github.com/aws-amplify/docs repo to hopefully get some more documentation on this topic added to help others who run into this too.

**Comment by julianworden** [comment]
@jcjimenez Sorry I take my previous post back, I thought I had it more figured out than I did.

For signing in with email and password, managing the auth state of the widget is fairly straightforward: When the user logs in, save their username and password as a new keychain item in the Keychain Access Group that the app and widget extension have access to. When they log out, delete the keychain item. In the widget's `getTimeline` method, check to see if a user's log in info is present in the Keychain Access Group. If it is, extract the login info from the keychain item and use it to sign in via `Amplify.Auth.signIn`. 

However, this workflow does not appear to be possible when using sign in with Google, Apple, etc. That's because:

- The sign in state of the user is not consistently and reliably maintained between the app and app extension. Signing in or out via the main app does not automatically sign in or out on the widget extension. However, somehow it appears that sometimes signing in via the main app actually will also sign in via the widget extension, but it's never instant even after calling `WidgetCenter.shared.reloadAllTimelines()`
- It's impossible to sign in with Google, Apple, etc. via the widget because the sheet UI is required so that the user can enter their info. You also can't access the password and email that the user enters on the sign in with Apple, Google, etc. sheet, and even if you could there would be no way to enter it.
- Although signing in with Google or Apple **does** create keychain items, there is no password or username/email address info (none that I can find anyway) included in these keychain items, so as far as I can tell they're basically useless for my use case

This seems related to #2508, do you agree? Either way, I'm not quite sure how to proceed from here. It looks like I'm going to have to remove sign in with Google and Apple in my app so that I can get the widget functionality I want, but it would be great if you could please verify that you experience the same behavior.

Also, after working through all this and coming to the conclusion mentioned above (assuming you have the same experience), this sounds like it should be entered as a separate bug or feature request given that it's totally different from what I initially posted about. Let me know if you agree.

**Comment by jcjimenez** [comment]
Hi, @julianworden,

> This seems related to https://github.com/aws-amplify/amplify-swift/issues/2508, do you agree?

Yes, I believe you're right.

I know you mentioned sharing data between your app and widget wasn't your preferred route, but to avoid having to remove support for Google and Apple sign-in, one workaround could be something like the following:

1. Add the **App Groups** capability to **both** your app and widget (From Xcode, clicking on the project, then each target, then the "Signing & Capabilities" tab, then the "+" button). Make sure you use the same app group name, e.g. `com.example.myapp`
2. Write data from your app to a file contained in your app group container, e.g.
```
if let groupURL = FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "com.example.myapp") {
    let timelineURL = groupURL.appending(component: "timeline.json")
    ...
}
```
3. Read the data from your widget from the same container.
4. Consider using a [background task](https://developer.apple.com/documentation/backgroundtasks/bgapprefreshtaskrequest) to refresh the contents of the data you put in the container when the app is in the background.

**Comment by julianworden** [comment]
@jcjimenez I actually started by doing this, the only issue is that I also plan to add a Live Activity to the app that will need to connect directly to the Amplify backend.

For more context, the app is basically designed to be used to keep track of how much time you dedicate to learning a particular skill. The user will use it to start a stopwatch and then a Live Activity will display the current stopwatch value at all times. The user should be able to stop the stopwatch and then when that happens the session should immediately get saved to the backend. Of course, this will require that the user is able to sign in via the main app and also immediately sign into the Widget via the Widget Extension, but with things the way they are, if they signed in with Apple, Google, etc. then I'll never be able to reliably guarantee that they'll be logged into the widget when they're logged into the app.

I suppose I could make it so that the data for the session that was stopped via the Live Activity gets saved to the `FileManager.default.containerURL`, and then the next time the app launches I could check for unsaved sessions and then save them. This sounds clunky to me and at the end of the day this is just an app for my portfolio so getting rid of the sign in with google/apple functionality isn't the end of the world.

In any event, I appreciate all your help! For now, I'll just make a comment in #2508 to mention that supporting app extensions when a user is signed in via an external provider would be a great addition.
