### ISSUE TITLE
Analytics - Data mismatch between CustomProperties and Pinpoint Attributes

### ISSUE THREAD

**Issue by abdallahshaban557** [aws-amplify/amplify-swift#2862]
### Is your feature request related to a problem? Please describe.

We need to allow the update of user attributes to accept an array of values, similar to what is mentioned in this Github issue https://github.com/aws-amplify/amplify-flutter/issues/2850

### Describe the solution you'd like

Proposal:

Allow the Pinpoint Endpoint attributes field to be set as a Map<String, List<String>> in UserProfile by:

- Removing the UserProfile.customProperties field
- Adding UserProfile.attributes of type Map<String, List<String>>
- Adding UserProfile.metrics of type Map<String, double>

### Describe alternatives you've considered

N/A

### Is the feature request related to any of the existing Amplify categories?

Analytics

**Comment by ruisebas** [comment]
This is supported in the new [`UserProfile`](https://github.com/aws-amplify/amplify-swift/blob/main/Amplify/Core/Model/UserProfile.swift#L25) protocol that is used on the **Push Notifications** category, as [`UserProfilePropertyValue`](https://github.com/aws-amplify/amplify-swift/blob/main/Amplify/Core/Model/UserProfilePropertyValue.swift#L23) supports being an array of `Strings`.

So this is perfectly valid:

```swift
let userProfile = BasicUserProfile(
    name: "Name",
    customProperties: [
        "attributes": ["value1", "value2", "value3"]
    ]
)
```

We just need to update Analytics's `identifyUser` API signature to take the new protocol instead and deprecate/remove the old [`AnalyticsUserProfile`](https://github.com/aws-amplify/amplify-swift/blob/fc5a60f99c465072c0b5f58f58470d47dbbe5c06/Amplify/Categories/Analytics/AnalyticsProfile.swift#L11)

**Comment by abdallahshaban557** [comment]
Understood - the request was mainly around making sure the attributes can accept an array of values as you've mentioned in your first response here. For the concerns you have on the `userProfile` being a category level concept, that makes sense.

**Comment by ruisebas** [comment]
Tracked in https://github.com/aws-amplify/amplify-swift/issues/1416
