### ISSUE TITLE
amplify-swift pods

### ISSUE THREAD

**Issue by dan-codes1** [aws-amplify/amplify-swift#2867]
### Describe the bug

Hi,

I want to ask if it is possible to download the releases (mainly v2) of amplify via cocoapods. I tried it with SwiftPM and it works, but doesn't with cocoa pods.

I later checked the cocoa pods page for amplify and saw that only releases from v1 are available. Is there a reason why?

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to your pod file.
2. Add amplify pods with the latest releases (mainly from v2)
3. Run pod install
4. See error [!] Unable to find a specification for *pod* (*version*)
```

### Expected behavior

Expected to install...just like the previous releases.

### Amplify Framework Version

2.8.0

### Amplify Categories

API

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

11.0.3

### Xcode version

14

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

iPhone 13

### iOS Version

15

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by jcjimenez** [comment]
Hi, @dan-codes1,

We currently don’t have any plans to support CocoaPods for Amplify Swift version 2.x. However, we’d like to understand your use case; Could you share the reason you can’t use SPM with us?

Thanks!

**Comment by dan-codes1** [comment]
@jcjimenez  thanks for the reply. I can use SPM; it is just that all of my other dependencies are on cocoa pods and in my pod file. It would be much more organized to have all of the dependencies in the same dependency manager. Having different managers might just not be too organized in the project.

Can you share the reason for not supporting CocoaPods for Amplify Swift 2x versions? I suggest you reconsider, however.

Thanks.

**Comment by jcjimenez** [comment]
Thanks, @dan-codes1. That's understandable.

Supporting CocoaPods requires additional effort and plans that are not currently on our roadmap. However, your request is noted!

**Comment by NewLand-Ju** [comment]
Currently, the flutter ios plugin supports only cocoapods, so amplify v2 cannot be used, so I am waiting for amplify v2 distribution through cocoapods.
