### ISSUE TITLE
Build Old AWS Project

### ISSUE THREAD

**Issue by smediomike** [aws-amplify/amplify-swift#2872]
### Describe the bug

I have one GM product which already run on market, but my Mac system happen critical issue, I have to move to another new Mac system. but  I can not make release build based on whole orginal project source with AWS Pod successfully. 

### Steps To Reproduce

```swift
two methods to reproduce this issue:

Case #1
1, copy one workable whole was project to another Mac system(like 13.3.1)
2, open orginal workspace and build
3, it can run on debug mode
4, but can not Archive one release build successfull

Detailed log as :
haseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/mike.wu/Library/Developer/Xcode/DerivedData/CloudBackup-hacchsqbopetljgtxrsizcluiqop/Build/Intermediates.noindex/ArchiveIntermediates/CloudBackup/IntermediateBuildFilesPath/CloudBackup.build/Release-iphoneos/CloudBackup.build/Script-DD5674631C5690F17B691EE7.sh (in target 'CloudBackup' from project 'CloudBackup')
    cd /Users/mike.wu/p4/IOS/BRANCH/CloudBackup/CloudBackup
    /bin/sh -c /Users/mike.wu/Library/Developer/Xcode/DerivedData/CloudBackup-hacchsqbopetljgtxrsizcluiqop/Build/Intermediates.noindex/ArchiveIntermediates/CloudBackup/IntermediateBuildFilesPath/CloudBackup.build/Release-iphoneos/CloudBackup.build/Script-DD5674631C5690F17B691EE7.sh

mkdir -p /Users/mike.wu/Library/Developer/Xcode/DerivedData/CloudBackup-hacchsqbopetljgtxrsizcluiqop/Build/Intermediates.noindex/ArchiveIntermediates/CloudBackup/BuildProductsPath/Release-iphoneos/CloudBackup.app/Frameworks
Symlinked...
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AWSAuthCore.framework" "/Users/mike.wu/Library/Developer/Xcode/DerivedData/CloudBackup-hacchsqbopetljgtxrsizcluiqop/Build/Intermediates.noindex/ArchiveIntermediates/CloudBackup/InstallationBuildProductsLocation/Applications/CloudBackup.app/Frameworks"
building file list ... rsync: link_stat "/Users/mike.wu/p4/IOS/BRANCH/CloudBackup/CloudBackup/../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AWSAuthCore.framework" failed: No such file or directory (2)
done

Case #2
1, I copy my source code without Pod project and pod file etc
2, I do start from CocoaPods steps from Pod init/ update pod file / pod install --repo-update
3, it will make new workspace 
4, but it can not make debug and release build, root cause is same to case #1
```

### Expected behavior

It's better one system make correct project, another environment can copy and make build.  or can make old project with case #2 steps.

### Amplify Framework Version

1.28.1

### Amplify Categories

API, DataStore, Storage

### Dependency manager

Cocoapods

### Swift version

5.0

### CLI version

4.4

### Xcode version

Xcode 14.2.1

### Relevant log output

```shell
PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/mike.wu/Library/Developer/Xcode/DerivedData/CloudBackup-hacchsqbopetljgtxrsizcluiqop/Build/Intermediates.noindex/ArchiveIntermediates/CloudBackup/IntermediateBuildFilesPath/CloudBackup.build/Release-iphoneos/CloudBackup.build/Script-DD5674631C5690F17B691EE7.sh (in target 'CloudBackup' from project 'CloudBackup')
    cd /Users/mike.wu/p4/IOS/BRANCH/CloudBackup/CloudBackup
    /bin/sh -c /Users/mike.wu/Library/Developer/Xcode/DerivedData/CloudBackup-hacchsqbopetljgtxrsizcluiqop/Build/Intermediates.noindex/ArchiveIntermediates/CloudBackup/IntermediateBuildFilesPath/CloudBackup.build/Release-iphoneos/CloudBackup.build/Script-DD5674631C5690F17B691EE7.sh

mkdir -p /Users/mike.wu/Library/Developer/Xcode/DerivedData/CloudBackup-hacchsqbopetljgtxrsizcluiqop/Build/Intermediates.noindex/ArchiveIntermediates/CloudBackup/BuildProductsPath/Release-iphoneos/CloudBackup.app/Frameworks
Symlinked...
rsync --delete -av --filter P .*.?????? --links --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AWSAuthCore.framework" "/Users/mike.wu/Library/Developer/Xcode/DerivedData/CloudBackup-hacchsqbopetljgtxrsizcluiqop/Build/Intermediates.noindex/ArchiveIntermediates/CloudBackup/InstallationBuildProductsLocation/Applications/CloudBackup.app/Frameworks"
building file list ... rsync: link_stat "/Users/mike.wu/p4/IOS/BRANCH/CloudBackup/CloudBackup/../../../IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AWSAuthCore.framework" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /AppleInternal/Library/BuildRoots/97f6331a-ba75-11ed-a4bc-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/rsync/rsync/main.c(996) [sender=2.6.9]
Command PhaseScriptExecution failed with a nonzero exit code
```

### Is this a regression?

No

### Device

Any

### iOS Version

iOS16 etc

**Comment by harsh62** [comment]
@smediomike Thanks for opening the issue. 
I cannot repro the issue in my local. Setting up with POD seems to work fine at my end. Some questions I have are: 
* Have you tried cleaning and clearing the derived data from the machine? 
* Would you be able to share the POD file? 
* If you have done anything different for release builds? 
* Do you have any special handling been done in the build script phase?

**Comment by smediomike** [comment]
Hello


please see my below comment:

  *   Have you tried cleaning and clearing the derived data from the machine?

==> Yes, I tried to clear all issue, folder and derived data


  *   Would you be able to share the POD file? ==> please see attachement
  *   If you have done anything different for release builds?

==>  no, i used save environment, i re-do according to AWS’s website document based on current project.


  *   Do you have any special handling been done in the build script phase?

==> no



Finally i resolved this issue at the steps:

1, make new same name xcode project
2, excute pod command like website document to initliaze and create workspace
3, copy old project files to replace new project, keep new workspace and pod project.
4, as this, i can make release build. so this issue should relate with the paths in build script’s release enviorment.

Regards,
mike.wu




在 2023年4月22日 01:14，Harshdeep ***@***.***> 写道：


@smediomike<https://github.com/smediomike> Thanks for opening the issue.
I cannot repro the issue in my local. Setting up with POD seems to work fine at my end. Some questions I have are:

  *   Have you tried cleaning and clearing the derived data from the machine?
  *   Would you be able to share the POD file?
  *   If you have done anything different for release builds?
  *   Do you have any special handling been done in the build script phase?
