### ISSUE TITLE
Does Amplify SDK support multiple simultaneous user sessions in run-time which can be switched amongst?

### ISSUE THREAD

**Issue by voicesmackiev** [aws-amplify/amplify-swift#2875]
Let’s say we have 2 users: “Parent” and “Child”. Can I log in as “Parent” user, then also log in as “Child” user, then have a toggle that lets me rapidly switch my session between “Parent” and “Child”?

The documentation seems to indicate that it supports one login session at a time, and to authenticate to “Child” user, “Parent” user would have to be logged out, requiring re-entry of password on every rapid-switch attempt.

Our application uses the Amplify Datastore and S3 storage. And we want to work with these storages per user. “Parent” user works with DataStore and the “Child” user works with “S3” storage.

**Comment by harsh62** [comment]
@voicesmackiev Are you using Auth from Amplify? 
* If yes, Amplify only supports one user logged in session at a time. 
* If no, you would need to check with the Auth provider you are using.

**Comment by kylanry** [comment]
@harsh62 Thank you for your quick response. Yes, I am using the Auth from Amplify.

**Comment by voicesmackiev** [comment]
@harsh62 Thank you for the quick response. Yes. I am using the Auth from Amplify.

**Comment by voicesmackiev** [comment]
@harsh62 Thank you for the quick response. Yes. I am using the Auth from Amplify.

**Comment by voicesmackiev** [comment]
Is it possible to retrieve id tokens for several users with other AWS APIs?

**Comment by harsh62** [comment]
> Is it possible to retrieve id tokens for several users with other AWS APIs? I am thinking of using the REST API instead of Amplify DataStore to access the data in DynamoDb with the Cognito Auth provider.

Unfortunately not. Amplify only supports retrieving tokens only for a single user at a time. You would have to sign out and sign in again to get a new pair of credentials.

**Comment by voicesmackiev** [comment]
Thanks @harsh62  for the answer.
