### ISSUE TITLE
Storage.getURL(key: "ExampleKey") should be able to throw a meaningful exception if the file does not exist in storage

### ISSUE THREAD

**Issue by kvramyasri7** [aws-amplify/amplify-swift#2877]
### Describe the bug

When we call getUrl from storage category we are receiving a presigned url even though the file does not exist.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
amplify add storage
Call Amplify.Storage.getUrl("NonexistedFile");. call getUrl with a non-existed File.
This produces a pre-signed url which is not expected.
```

### Expected behavior

The expected behavior is to return a meaningful exception if the file does not exist in the storage.

### Amplify Framework Version

N/A

### Amplify Categories

Storage

### Dependency manager

Swift PM

### Swift version

N/A

### CLI version

N/A

### Xcode version

N/A

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

Yes

### Regression additional context

_No response_

### Device

N/A

### iOS Version

N/A

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by harsh62** [comment]
@abdallahshaban557 @kvramyasri7  Would you be able to provide more details about the feature parity?

**Comment by abdallahshaban557** [comment]
Hi @harsh62  - We have a feature now available for Amplify JavaScript and Flutter that allows developers to get an error if they try to retrieve a file that does not exist when using the Storage category. The flag is `validateObjectExistence`, and we would like that to be available for Swift and Android as well. https://docs.amplify.aws/lib/storage/download/q/platform/js/#get
