### ISSUE TITLE
User is not authorized to perform action on API gateway when using Sign In with Apple 

### ISSUE THREAD

**Issue by Bathande** [aws-amplify/amplify-swift#2881]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-js/issues?q=is%3Aissue+) and [discussions](https://github.com/aws-amplify/amplify-js/discussions).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-js/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### JavaScript Framework

React

### Amplify APIs

Authentication, Analytics

### Amplify Categories

auth, api

### Environment information

<details>

# Put output below this line

I have these versions of SDK :
  pod 'AWSCore', '~> 2.28.0'
  pod 'AWSMobileClient', '~> 2.28.0'
  pod 'AWSAPIGateway', '~> 2.28.0'

</details>

### Describe the bug

We are experiencing an issue where users Signed In With Apple are getting "[”Message”: User: arn:aws:sts::x:xassumed-role/golfonaut-master-xxxx-unauthRole/CognitoIdentityCredentials is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:eu-central-1:xxxx:cccc/master/GET/xxx]” error when trying to access an API after being logged in for 10 minutes.

We are listening to user state changes but when issue is observed the event is not triggered.

### Expected behavior

Tokens expiry duration in cognito is configured to 30 days. So we expect the token to only expire after 30 days.

### Reproduction steps

I have these versions of SDK :
  pod 'AWSCore', '~> 2.28.0'
  pod 'AWSMobileClient', '~> 2.28.0'
  pod 'AWSAPIGateway', '~> 2.28.0'

### Code Snippet

```javascript
// Put your code below this line.

func init_aws() async {
        print("AuthManager init_aws")
        let (user_state, error) = await [self.aws ](http://self.aws/)_mobile_client_initialize()
        if let user_state_strong = user_state {
            await self.action_triage(user_state: user_state_strong, app_launch: true)
        }
        else if let error = error {
            print(error.localizedDescription)
        }
        AWSMobileClient.default().addUserStateListener(self) { (user_state, info) in
            print("AWSMobileClient listener : ", user_state)
            Task(priority: .medium) {
                // to avoid conflict with auth vc logic
                guard self.presenting_auth_vc == false else { return }
                await self.action_triage(user_state: user_state, app_launch: false)
            }
        }
        return
    }

private func aws_mobile_client_initialize() async -> (UserState?, Error?) {
        return await withCheckedContinuation { continuation in
            AWSMobileClient.default().initialize() { (user_state, error) in
                continuation.resume(returning: (user_state, error))
            }
        }
    }

func action_triage (user_state: UserState, app_launch: Bool) async {
        print("AuthManager action_triage : ", user_state)
        switch(user_state){
        case .signedIn:
            Mixpanel.mainInstance().track(event: "Phone: Auth Signed In")
            do {
                let (_,_) = try await Purchases.shared.logIn([CacheManager.Player.email ](http://cachemanager.player.email/))
            }
            catch {
                print("Purchases logIn error")
            }
            if CD_Player.fetch_last() != nil {
                // when user sign in during app use, just_sign_in method calls applicationDidFinishLaunching()
                if (app_launch == true){
                    await AccountManager.sharedAccountManager.applicationDidFinishLaunching()
                }
            }
            else{
                print("CD_Player.fetch_last() = nil, we force signed out")
                // If no player and signedIn, we try to get the email from the token.
                // Case 1: when someone signedIn re-install Golfonaut
                // Case 2: when I re-install Golfonaut
                let (email, _) = await AuthManager.sharedAuthManager.get_token_email_safe()
                if let email_strong = email {
                    await self.just_signed_in(email: email_strong)
                    if (app_launch == true){
                        await AccountManager.sharedAccountManager.applicationDidFinishLaunching()
                    }
                }
                else{
                    await self.sign_out()
                }
            }
        case .signedOut:
            Mixpanel.mainInstance().track(event: "Phone: Auth Signed Out")
            do {
                let _ = try await Purchases.shared.logOut()
            }
            catch {
                print("Purchases logOut error")
            }
            await [MainActor.run ](http://mainactor.run/) {
                self.presentAuthViewController()
            }
        case .signedOutFederatedTokensInvalid:
            Mixpanel.mainInstance().track(event: "Phone: Auth Signed Out Federated Token Invalid")
            await self.sign_out()
        case .signedOutUserPoolsTokenInvalid:
            Mixpanel.mainInstance().track(event: "Phone: Auth Signed Out User Pools Token Invalid")
            await self.sign_out()
        case .guest:
            Mixpanel.mainInstance().track(event: "Phone: Auth Guest")
            await [MainActor.run ](http://mainactor.run/) {
                self.presentAuthViewController()
            }
        case .unknown:
            Mixpanel.mainInstance().track(event: "Phone: Auth Unknown")
            await self.sign_out()
        }
    }

### Log output

<details>

```
// Put your logs below this line

```

</details>


### aws-exports.js

_No response_

### Manual configuration

_No response_

### Additional configuration

_No response_

### Mobile Device

_No response_

### Mobile Operating System

_No response_

### Mobile Browser

_No response_

### Mobile Browser Version

_No response_

### Additional information and screenshots

_No response_

**Comment by rvanbael** [comment]
Hello, 
@Bathande opened this Github for me, as part of AWS support service.
As you can see the code is in Swift. I am using "AWSMobileClient", "AWSAPIGateway" and "AWSCore" frameworks, version 2.30.4.

The issue is for Sign In With Apple users. After few minutes, they encounter issues with the API Gateway. Cognito says they are signed in, but API Gateway says they are unauth.

When the SIWA user launches the app, we init AWS. AWS says the user is signedIn (!). We also add the listener as you can see above.

When we need the API Gateway (just after), we ask for a fresh token
`AWSMobileClient.default().getTokens()`
It gives us a token. The token looks not expired, even if the expiration date is soon :
```
Tokens(idToken: Optional(AWSMobileClient.SessionToken(tokenString: Optional("**"))), accessToken: Optional(AWSMobileClient.SessionToken(tokenString: Optional("***"))), refreshToken: Optional(AWSMobileClient.SessionToken(tokenString: Optional("***"))), expiration: Optional(2023-04-07 17:24:58 +0000))
2023-04-07 16:29:16 +0000
```

We use this token with API gateway:
`let api_request = AWSAPIGatewayRequest(httpMethod: "GET", urlString: url_string, queryParameters: query_parameters, headerParameters: ["Content-Type": "application/json","Accept": "application/json", "Authorization": token], httpBody: nil)`

But we got rejected by API Gateway:
`User: arn:aws:sts::***:assumed-role/***-master-***-unauthRole/CognitoIdentityCredentials is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:**-**-1:************:***/master/GET/download*`

If we sign out, and sign in again the user, we get a valid token, accepted by API Gateway.

Am we missing something?

**Comment by rvanbael** [comment]
Hi @harsh62 , sorry for late response.
Also it took few days to reproduce the error.

1. Please find Sign In With Apple signing code:
```
var hosted_UI_options: HostedUIOptions = HostedUIOptions(identityProvider: "SignInWithApple", signInPrivateSession: true)
let (user_state, error) = await self.sign_in_with(hosted_UI_options: hosted_UI_options, calling_window: calling_window)

private func sign_in_with(hosted_UI_options: HostedUIOptions, calling_window: UIWindow) async -> (UserState?, Error?){
        return await withCheckedContinuation { continuation in
            AWSMobileClient.default().showSignIn(presentationAnchor: calling_window, hostedUIOptions: hosted_UI_options) { (user_state, error) in
                continuation.resume(returning: (user_state, error))
            }
        }
}

2. Logs in debug
```
AuthManager init_aws
2023-05-25 08:19:32:200 ***[60224:6420624] Configuring SignInProvider : CognitoUserPool.
AuthManager action_triage :  signedIn

download_player()
2023-05-25 09:05:41:612 ***[60432:6440343] Invoking hostedUI getTokens
2023-05-25 09:05:41:612 ***[60432:6440343] ED240171-6892-4CE6-8D45-93372EF08611 Created FetchUserPoolTokensOperation
2023-05-25 09:05:41:612 ***[60432:6440343] ED240171-6892-4CE6-8D45-93372EF08611 Start execution
2023-05-25 09:05:41:614 ***[60432:6440349] ED240171-6892-4CE6-8D45-93372EF08611 notStarted: startOperation -> fetching
2023-05-25 09:05:41:614 ***[60432:6440349] ED240171-6892-4CE6-8D45-93372EF08611 Inside fetch token
2023-05-25 09:05:41:618 ***[60432:6439999] Request headers:
{
    Authorization = "AWS4-HMAC-SHA256 Credential=***/20230525/eu-central-1/mobiletargeting/aws4_request, SignedHeaders=content-type;host;user-agent;x-amz-date;x-amz-security-token, Signature=***";
    "Content-Type" = "application/x-amz-json-1.1";
    Host = "pinpoint.eu-central-1.amazonaws.com";
    "User-Agent" = "aws-sdk-iOS/2.30.4 iOS/16.4.1 en_FR aws-amplify/cli";
    "X-Amz-Date" = 20230525T070541Z;
    "X-Amz-Security-Token" = "***";
}
2023-05-25 09:05:41:618 ***[60432:6439999] Request body:
{"OptOut":"NONE","ChannelType":"APNS_SANDBOX","Metrics":{},"EffectiveDate":"2023-05-25T07:05:41.617Z","Address":"***","Demographic":{"Locale":"en_FR","Timezone":"Europe\/Paris","PlatformVersion":"16.4.1","AppVersion":"2.11","Model":"iPhone","Make":"apple","Platform":"iOS"},"Location":{},"Attributes":{},"User":{"UserAttributes":{},"UserId":"[***@privaterelay.appleid.com](mailto:***@privaterelay.appleid.com)"}}
2023-05-25 09:05:41:619 ***[60432:6440349] ***-***-***-***-*** fetching: tokenFetched -> fetched
2023-05-25 09:05:41:619 ***[60432:6440349] ***-***-***-***-*** Success

get_token_safe - tokens_strong =  Tokens(idToken: Optional(AWSMobileClient.SessionToken(tokenString: Optional("***"))), expiration: Optional(2023-05-25 07:16:26 +0000))
2023-05-25 07:05:41 +0000

2023-05-25 08:19:32:366 ***[60224:6420619] Response headers:
{
    "Access-Control-Allow-Origin" = "*";
    "Cache-Control" = "no-store";
    "Content-Length" = 73;
    "Content-Type" = "application/json";
    Date = "Thu, 25 May 2023 06:19:32 GMT";
    Via = "1.1 ***.cloudfront.net (CloudFront)";
    "x-amz-apigw-id" = "***=";
    "x-amz-cf-id" = "**-**==";
    "x-amz-cf-pop" = "***-**";
    "x-amzn-requestid" = "***-***-***-***-***";
    "x-amzn-trace-id" = "Root=1-***-***";
    "x-cache" = "Miss from cloudfront";
}

2023-05-25 08:19:32:366 ***[60224:6420619] Response body:
{"RequestID":"***-df97-4976-9701-***","Message":"Accepted"}

download_player - *** server bad response - json =  ["message": User: arn:aws:sts::***:assumed-role/***-dev-***-unauthRole/CognitoIdentityCredentials is not authorized to perform: execute-api:Invoke on resource: arn:aws:execute-api:eu-central-1:********5006:***/dev/GET/downloadplayer]
```


```
3. awsconfiguration.json:

```
{
    "UserAgent": "aws-amplify/cli",
    "Version": "0.1.0",
    "IdentityManager": {
        "Default": {}
    },
    "CredentialsProvider": {
        "CognitoIdentity": {
            "Default": {
                "PoolId": "eu-central-1:***-***-***-***-***",
                "Region": "eu-central-1"
            }
        }
    },
    "CognitoUserPool": {
        "Default": {
            "PoolId": "eu-central-1_***",
            "AppClientId": "***",
            "Region": "eu-central-1",
            "AppClientSecret": "***"
        }
    },
    "Auth": {
        "Default": {
            "OAuth": {
                "WebDomain": "***.auth.eu-central-1.amazoncognito.com",
                "AppClientId": "***",
                "AppClientSecret": "***",
                "SignInRedirectURI": "***://",
                "SignOutRedirectURI": "***://",
                "Scopes": [
                    "phone",
                    "email",
                    "openid",
                    "profile",
                    "aws.cognito.signin.user.admin"
                ]
            },
            "authenticationFlowType": "USER_SRP_AUTH",
            "mfaConfiguration": "OFF",
            "mfaTypes": [
                "SMS"
            ],
            "passwordProtectionSettings": {
                "passwordPolicyMinLength": 8,
                "passwordPolicyCharacters": []
            },
            "signupAttributes": [
                "EMAIL"
            ],
            "socialProviders": [
                "GOOGLE",
                "APPLE"
            ],
            "usernameAttributes": [
                "EMAIL"
            ],
            "verificationMechanisms": [
                "EMAIL"
            ]
        }
    },
    "DynamoDBObjectMapper": {
        "Default": {
            "Region": "eu-central-1"
        }
    },
    "PinpointAnalytics": {
        "Default": {
            "AppId": "***",
            "Region": "eu-central-1"
        }
    },
    "PinpointTargeting": {
        "Default": {
            "Region": "eu-central-1"
        }
    }
}

```

**Comment by royjit** [comment]
It looks like the AWS Credentials are not loaded for the signed in user yet. Could you try invoking `AWSMobileClient.default().getAWSCredentials` before making your API call and see if the issue get resolved?
