### ISSUE TITLE
Using Amplify v2 with APIGateway autogenerated class

### ISSUE THREAD

**Issue by dcristolovean** [aws-amplify/amplify-swift#2941]
### Describe the bug

As the title implies, is it possible to achieve this ?

Installing only Amplify with SPM doesn't compile the generated class, this fails:  #import <AWSAPIGateway/AWSAPIGateway.h>
Adding that in Pods (because I couldn't find any way to add it somehow in SPM)  (pod 'AWSAPIGateway') works and compiles but then comes this:   
- the auto generated class needs to be initialized with a AWSCognitoCredentialsProvider. (in v1 and pre v1, this one was coming from AWSMobileClient.shared.getCredentialsProvider().
- I couldn't find any way to retrieve this from Amplify.

So, is it possible in any way to use the old autogenerated classes  with Amplify v2 (ideally, only with Amplify in SPM) ?
This is a REST API, not a GraphQL.

Moving to Amplify v2 and having to manually create hundreds of classes and methods is very hard and time consuming.  
**Also, why isn't there a way to generate the new classes for Amplify.API as we could do it before ?**

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. install Amplify v2 via SPM (no other old aws sdks)
2. generate classes with API Gateway
3. use them with Amplify v2
```

### Expected behavior

To be able to use Amplify v2 and APIGateway instead of moving everything to Amplify.API

### Amplify Framework Version

2.x

### Amplify Categories

API, Auth

### Dependency manager

Swift PM

### Swift version

5.x

### CLI version

- no CLI, existing project, config done via AWSConfiguration

### Xcode version

14.x

### Is this a regression?

No

### Device

Any

### iOS Version

> 13.0

**Comment by atierian** [comment]
Thanks for opening this issue @dcristolovean.

If I understand correctly, you were previously using Amplify v1 and the AWSAPIGateway framework from the AWS SDK for iOS. Now you've migrated to Amplify v2 and are trying to use the same AWSAPIGateway framework from the AWS SDK for iOS (through cocoapods). Is that correct?

The bad news is that using the AWS SDK for iOS with Amplify v2 isn't supported. This is because the the AWS SDK for iOS has target naming collisions with the AWS SDK for Swift that Amplify v2 uses. This is likely the underlying cause for the compiler error you're seeing.

The good news is that you can use the AWSAPIGateway framework from the AWS SDK for Swift. To do so, you'll have to explicitly add the AWS SDK for Swift as a dependency for your target (using SPM). Then add AWSAPIGateway in your target > general > Frameworks, Libraries, and Embedded Content. Also make sure to remove the cocoapods dependency on the AWS SDK for iOS' AWSAPIGateway framework.

You'll still need to make some code changes to migrate to the new (AWS SDK for Swift) AWSAPIGateway framework. For example, it uses async / await instead of the callback approach used in the AWS SDK for iOS. However, the autogenerated models and APIs in both frameworks are very similar.

I hope this helps. Let me know if you have any other questions, thanks!

**Comment by dcristolovean** [comment]
Yes, that's the case.  I am using (not even v1) old AWS classes and AWSMobileClient.
Actually with v1 or AWSMobileClient, there are no conflicts, I can use Pods for everything. I also managed to instantiate my api clients with AWSMobileClient,shared.getCredentialsProvider.

As for V2, this is where it gets interesting. You're saying there's an AWSAPIGateway also in the AWS SDK for Swift.  Assuming so and assuming I can add correctly everything in SPM/or embedd, is this in any way compatible with the old autogenerated class ? I assume no, different namings, the old class has an old objc import, which won't work anymore.

Is there any other autogeneration tool now ? On Web, in API Gateway, I can only generate the 'old' format. Is there a way now to generate all the models and the big class with methods for Amplify v2 ? I know how Amplify.API works now, how the models and async/await approach, so I assume everything would be different, not with AWSTask as before.
The docs explain how to create your own methods, but I have > 300 models and > 100 API requests, so recreating all by hand is very tedious. Not to mention hard to maintain for the future API changes/additions. There are external tools to generate an API from Swagger, but I'd prefer something from Amazon.

**Comment by dcristolovean** [comment]
Actually, I managed to do this too, added v2 via SPM and then also a pod 'AWSAPIGateway' and it worked.
All the dependencies from the autogenerated classes are satisfied in this way.

But then what ? :) If you go back to my initial post, I started with this question.

I did the auth in Amplify v2 and actually the config in code, not from a json file, because that's a requirement in our app. (many apps, orgs, dynamic values).  All good there.
Then the autogenerated files are also OK, compiling.
But how do I actually instantiate that client ?

The autogenerated client needs an AWSServiceConfiguration object. This one takes a region and a AWSCognitoCredentialsProvider like this:

`let serviceConfiguration = AWSServiceConfiguration(region: AWSRegionType.EUWest1, credentialsProvider: AWSMobileClient.default().getCredentialsProvider())`
Then, with this and a key (random string) you can create your API client.

There's no other way to initialize the autogenerated class correctly and completely.  And none of these classes exist anymore in Amplify 2, nor is the Amplify singleton able to return them. You can't get them from asking about authState or anything in Amplify v2.

In V1 it actually works, because to me Amplify V1 seems to actually be AWSMobileClient v2, if that makes sense :) You have access to those classes, everything is almost the same as before Amplify.

Can you provide a step 4 in your answer, that actually inits the auto-generated api client ?  (with correct data, that is also auto-refreshed when tokens expire,, etc, like it is now with AWSMobileClient)

**Comment by atierian** [comment]
> But how do I actually instantiate that client ?

You're just about there with this example!
```swift
let serviceConfiguration = AWSServiceConfiguration(
    region: AWSRegionType.EUWest1, 
    credentialsProvider: AWSMobileClient.default().getCredentialsProvider()
)
```

### How?

The missing piece is an `AWSCore.AWSCredentialsProvider` conforming type that acts as a proxy to pull the credentials from Amplify and forward them along to your service configuration.

#### CredentialsProxy

Here's an example of such a proxy.
```swift
import Foundation
import Amplify
import AWSPluginsCore
import AWSCore
import AWSCognitoAuthPlugin

class CredentialsProxy: NSObject, AWSCore.AWSCredentialsProvider {
    let session: AuthSession

    init(session: AuthSession) {
        self.session = session
    }

    func credentials() -> AWSTask<AWSCore.AWSCredentials> {
        guard let provider = session as? AuthAWSCredentialsProvider else {
            return .init(error: Error.missingCredentialsProvider)
        }

        do {
            let credentials = try provider.getAWSCredentials().get()
            guard let cognitoCredentials = credentials as? AuthAWSCognitoCredentials else {
                return .init(error: Error.missingCognitoCredentials)
            }

            let result = AWSCredentials(
                accessKey: cognitoCredentials.accessKeyId,
                secretKey: cognitoCredentials.secretAccessKey,
                sessionKey: cognitoCredentials.sessionToken,
                expiration: cognitoCredentials.expiration
            )

            return .init(result: result)
        } catch {
            return .init(error: error)
        }
    }

    func invalidateCachedTemporaryCredentials() { /* ... */ }
}

extension CredentialsProxy {
    enum Error: Swift.Error {
        case missingCredentialsProvider
        case missingCognitoCredentials
    }
}

extension CredentialsProxy {
    static func makeFromAmplify(
        auth: AuthCategoryBehavior = Amplify.Auth
    ) async throws -> CredentialsProxy {
        let session = try await auth.fetchAuthSession(options: nil)
        return CredentialsProxy(session: session)
    }
}
```

#### Usage
```swift
let credentialsProxy = try await CredentialsProxy.makeFromAmplify()
let configuration = AWSServiceConfiguration(
    region: AWSRegionType.<region>,
    credentialsProvider: credentialsProxy
)
```

### Why?
> In V1 it actually works, because to me Amplify V1 seems to actually be AWSMobileClient v2, if that makes sense :) You have access to those classes, everything is almost the same as before Amplify.

You're correct! 

Amplify v1 uses `AWSMobileClient` and other targets from the AWS SDK for iOS. Grabbing the credentials provider from `AWSMobileClient` (like in your example) works there because `AWSMobileClient` itself is managing the session for Amplify v1. 

Amplify v2 handles user / session management directly within Amplify, which is why you need to proxy the session from Amplify to something that the `AWSServiceConfiguration` can understand (an `AWSCore.AWSCredentialsProvider` conforming type).

-----

Please let us know if this resolves your issue or if you run into any problems!

**Comment by dcristolovean** [comment]
just one more question before I try this:

`let credentialsProxy = try await CredentialsProxy.makeFromAmplify()
let configuration = AWSServiceConfiguration(
    region: AWSRegionType.<region>,
    credentialsProvider: credentialsProxy
)`

This is good for credentialsProvider: credentialsProxy, assuming the types match or are just interfaces.
But...    where do you get this one from: AWSServiceConfiguration ?

There wasn't such a class/interface anymore in v2 and this is what the autogenerated api class needs.
Let me know if it is and if not, I might probably have to change the autogenerated class, see if how it uses this AWSServiceConfiguration.

**Comment by atierian** [comment]
> But... where do you get this one from: AWSServiceConfiguration ?

This comes from `AWSCore`.

`AWSAPIGateway` has a dependency on `AWSCore`, so simply adding `pod 'AWSAPIGateway'` in your Podfile will bring in the `AWSCore` pod as well.

**Comment by atierian** [comment]
Unfortunately, it looks like using SPM for both Amplify v2 and AWS SDK for iOS results in target naming collisions. 

>  Well, fingers crossed, I'll test as soon as I can.

I'm looking forward to hearing whether this setup (v2 SPM + iOS SDK Cocapods) works for you.

**Comment by jcjimenez** [comment]
@dcristolovean Keeping fingers crossed for you. Also, we were thinking that there may be a chance that the original proxy may end up keeping a reference to a session that could, in theory, become stale, so here's an updated implementation that does everything on-demand:

https://gist.github.com/jcjimenez/b6a2a1f948764937b2a6c1c8a8340962

**Comment by atierian** [comment]
Hey @dcristolovean, just checking in. We you able to get things working? Thanks.

**Comment by dcristolovean** [comment]
thanks for checking in.   Not yet, had other things to work on and I need to find a spare couple of days for this.  You know how work is :)

**Comment by atierian** [comment]
Closing the issue as it appears to be resolved based on our investigations.
