### ISSUE TITLE
Amplify pull overrides cli.json

### ISSUE THREAD

**Issue by dan-codes1** [aws-amplify/amplify-swift#2950]
### Describe the bug

Hey, I'm currently exeriencing the same bug as #1541 . I saw a solution to this here: https://github.com/aws-amplify/amplify-swift/issues/1541#issuecomment-1435043402 which was to update the cli.json file. I did this and it works,  but anytime I run `amplify pull`, the cli.json file gets overwritten. This means I have to manually update the cli file anytime i run `amplify pull`. 

Is there a way to make the changes in cli.json permanent?

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Update your cli.json file.
2. Run `amplify pull`.
```

### Expected behavior

I expect the manual changes in cli.json to be permanent.

### Amplify Framework Version

2.8.0

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

5

### CLI version

11.1.1

### Xcode version

14

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

iPhone 14 simulator

### iOS Version

iOS 16

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by atierian** [comment]
Thanks for opening this is @dan-codes1.

The flags in `cli.json` are included in `amplify push` /  `amplify pull`. Could it be that you're manually editing the file, then at some point in the future pulling without first having pushed those changes? 
If so, all you need to do is push after making editing the `cli.json`. After that, you shouldn't need to update the `cli.json` again after pulling.

If you're still experiencing this after ensuring you've pushed the changes first, please let us know and we'll transfer this issue over to the Amplify CLI repo for investigation.

Thanks!

**Comment by dan-codes1** [comment]
@atierian I rull `amplify push` but the cli doesn't detect the change. It show the no changes detected output.

**Comment by atierian** [comment]
Since `amplify/cli.json` is not a resource file, `amplify push` won't detect changes if that's changed in isolation. Assuming you don't want to also change project resources, you can `amplify push --force` to push to the `cli.json` changes. After which, any subsequent `amplify pull` will include the correct flags.

**Comment by dan-codes1** [comment]
This worked. Thanks @atierian
