### ISSUE TITLE
Can't add package: Package Resolution Failed

### ISSUE THREAD

**Issue by zhu-xiaowei** [aws-amplify/amplify-swift#2959]
### Describe the bug

when add amplify-swift 2.10.0 by swift package, it will show **Package resolution Failed**, it seems due to **SQLite.swift** package.
![](https://d23qo6nogd5qe7.cloudfront.net/amplify-add-package-error.png)

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. in any iOS project(swift or objective-c project) Click on Xcode File-> Add Packages 
3. input `https://github.com/aws-amplify/amplify-swift`.
4. Click Add Package, the error will show.
```

### Expected behavior

add package successful.

### Amplify Framework Version

2.10.0

### Amplify Categories

Analytics, API, Auth, DataStore, Geo, Predictions, Storage

### Dependency manager

Swift PM

### Swift version

5.8

### CLI version

NA

### Xcode version

14.3

### Relevant log output

```shell
could not add amplify-swift as swift package.
```

### Is this a regression?

Yes

### Device

Any Device

### iOS Version

Any Version

**Comment by ruisebas** [comment]
Hi @zhu-xiaowei, thanks for opening this issue.

I was unable to reproduce your problem, the package resolution worked and I was able to add it as a dependency

<img width="1095" alt="Screenshot 2023-05-15 at 09 44 12" src="https://github.com/aws-amplify/amplify-swift/assets/97059974/5366e544-0479-4cff-b4ec-ec90e7129e35">

Amplify latest **2.10.0** version did upgrade its `aws-sdk-swift` dependency to version `0.13.0`, so a package cache reset might solve your issue.

Could you please try going to **File -> Packages -> Reset Package Caches** and then try adding the package again?

Thanks

**Comment by zhu-xiaowei** [comment]
After click File -> Packages -> Reset Package Caches, add add package again, the same error will occur.
I try click **Add Anyway** button, then click File -> Packages -> Reset Package Caches, Xcode will fetch library:
![](https://d23qo6nogd5qe7.cloudfront.net/amplify_clear_cache.png)
but fail with error:
![](https://d23qo6nogd5qe7.cloudfront.net/amplify_sqlite_error.png)
Failed to resolve dependencies Dependencies could not be resolved because root depends on 'amplify-swift' 2.10.0. 'amplify-swift' 2.10.0 cannot be used because 'amplify-swift' 2.10.0 depends on 'sqlite.swift' 0.13.2 and no versions of 'sqlite.swift' match the requirement 0.13.2.

**Comment by zhu-xiaowei** [comment]
Update:
I try execute the following command to clear swiftpm caches:
> rm -rf ~/Library/Caches/org.swift.swiftpm

then add package and click **Add Anyway** button.
After click **File -> Packages -> Reset Package Caches**, it works with no error!
