### ISSUE TITLE
WatchOS support

### ISSUE THREAD

**Issue by gbitaudeau** [aws-amplify/amplify-swift#2961]
### Is your feature request related to a problem? Please describe.

We make an application available in both iOS and WatchOs and want to use Amplify datastore to synchronize user data between watch and iPhone.

Actually, when Amplify libraries are added in a watchOs project, a lot of compilation issues prevents the libraries to be used.

In README.md, I found: 
> Support for watchOS and tvOS is coming in future releases.

Is there a version planned which will support watchOS ?

### Describe the solution you'd like

Be able to use Amplify on watchOS

### Describe alternatives you've considered

Use AWS SDK for Swift without amplify, but this is currently in developer preview and can not be use in a production context.

**Comment by ruisebas** [comment]
`watchOS` support has been added in version [2.12.0](https://github.com/aws-amplify/amplify-swift/releases/tag/2.12.0)
