### ISSUE TITLE
Amplify Notifications Not Updating in AWS configuration file

### ISSUE THREAD

**Issue by Logan752000** [aws-amplify/amplify-swift#2967]
### Describe the bug

I have added notifications to my Amplify app, but when configuring Amplify in the init function at the starting point of my app, I get the error:
`Failed to initialize Amplify with PluginError: Unable to decode configuration
Recovery suggestion: Make sure the plugin configuration is in JSONValue`

After a quick look into the issue, I get found that I was missing the notifications section in the awscon

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Set up iOS Amplify project
2. Add notifications `amplify add notifications`
3. Initialize Amplify for iOS
`init() {
        do {
            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            try Amplify.add(plugin: AWSAPIPlugin())
            try Amplify.add(plugin: AWSDataStorePlugin(modelRegistration: AmplifyModels()))
            try Amplify.add(plugin: AWSPinpointPushNotificationsPlugin(options: [.badge, .alert, .sound]))
            try Amplify.configure()
            print("Amplify configured with API, Auth, DataStore, and Pinpoint plugins")
        } catch {
            print("Failed to initialize Amplify with \(error)")
        }
    }
`
4. See error: `Failed to initialize Amplify with PluginError: Unable to decode configuration
Recovery suggestion: Make sure the plugin configuration is in JSONValue`
```

### Expected behavior

In amplify config file, this should be added:

`"notifications": {
    "plugins": {
        "awsPinpointPushNotificationsPlugin": {
            "appId": "[APP ID]",
            "region": "[REGION]"
        }
    }
}`

### Amplify Framework Version

2.8.0

### Amplify Categories

Analytics

### Dependency manager

Swift PM

### Swift version

5.8 Release 2023-03-30 (a)

### CLI version

12.0.0

### Xcode version

14.1

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


Failed to initialize Amplify with PluginError: Unable to decode configuration
Recovery suggestion: Make sure the plugin configuration is in JSONValue
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

iPhone 14 Pro Max simulator

### iOS Version

16

### Specific to simulators

no

### Additional context

Originally a post here:

https://discordapp.com/channels/705853757799399426/1096681513124384820

**Comment by ruisebas** [comment]
Hi @Logan752000, thanks for opening this issue.

I was unable to reproduce this issue, my `amplifyconfiguration.json` file was properly updated after running `amplify add notifications`.

Which version of [Amplify CLI](https://docs.amplify.aws/cli/start/install/) are you using? You can check by running `amplify -version`. 
Amplify for Swift's Push Notifications require a version >= **`10.8.0`** in order to work.
