### ISSUE TITLE
Datastore gets stuck in an odd state after turning WiFi off while phone is locked

### ISSUE THREAD

**Issue by ethan021021** [aws-amplify/amplify-swift#2994]
### Describe the bug

1. Launch the app and make sure the iPhone is connected to wifi
2. Lock the phone
3. From control center on the lock screen disable wifi
4. Quickly unlock the phone back into the app
5. Notice how observeQuery's completion handler never gets called and DataStore is stuck in a odd state

This is an issue for us because we depend on the completion handler from observeQuery to hide our loading states.

This might be related to this issue: #2323

Here are some logs with `.verbose` logging turned on while reproducing this issue:

[dsstuckloadingstate.txt](https://github.com/aws-amplify/amplify-swift/files/11570255/dsstuckloadingstate.txt)

### Steps To Reproduce

```swift
1. Launch the app and make sure the iPhone is connected to wifi
2. Lock the phone
3. From control center on the lock screen disable wifi
4. Quickly unlock the phone back into the app
5. Notice how observeQuery's completion handler never gets called and DataStore is stuck in a odd state
```

### Expected behavior

Datastore to continue working and not get stuck in an odd state (completion handler on observeQuery will not fire when in this state)

### Amplify Framework Version

2.11.4

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5.5

### CLI version

12.0.0

### Xcode version

14.3

### Is this a regression?

Yes

### Device

iPhone 14 Pro

### iOS Version

16.5

**Comment by harsh62** [comment]
@ethan021021 Would you be able to share verbose logs for the issue?
