### ISSUE TITLE
[Documentation] Example for passing a `path` option as part of a `StorageListRequest` 

### ISSUE THREAD

**Issue by jcjimenez** [aws-amplify/amplify-swift#3002]
### Is your feature request related to a problem? Please describe.

This is a documentation issue created on behalf of a customer:

The way to pass a path to the list file [sic] is not mentioned.

* https://docs.amplify.aws/lib/storage/list/q/platform/ios/

You can pass in StorageListRequest.Options as a parameter.

```
let listOptions = StorageListRequest.Options(path: "<PATH>")
Amplify.Storage.list(options: listOptions) { ... }
```

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

**Comment by royjit** [comment]
Created this PR to update the docs - https://github.com/aws-amplify/docs/pull/5611/files
