### ISSUE TITLE
Sort option in paginatedList (Amplify.API.Query)

### ISSUE THREAD

**Issue by jvasanthan** [aws-amplify/amplify-swift#3006]
Hi Team, 

will sort option be added to the paginatedList in Amplify.API.Query?

I see there are workarounds suggested here to add a constant in the schema and then write custom query. I don't have any data that is constant in my existing schema. If I add "a constant" in the schema how can I fill the "constant data" in the existing database entries? or can I use __typename?

**Comment by royjit** [comment]
@jvasanthan Thank you for raising the feature request, will update here when we have more information to share.

**Comment by royjit** [comment]
Please find a similar github issue here and solution - https://github.com/aws-amplify/amplify-swift/issues/1435
