### ISSUE TITLE
DataStore - observe() stops working after clear()

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-swift#3021]
### Describe the bug

I have multiple observers that are initialized when the user logs in, when the user logs out I:
- Remove datastore data as recommended by the docs
- remove the observers and set the subscription back to nil

The problem is that when another user logs back in the observers don't work, this is a similar issue to [this one](https://github.com/aws-amplify/amplify-flutter/issues/395). This is a bug on Amplify side. If I don't clean datastore and another user logs in the data is going to get mixed up so for now I'm resorting to a terrible option of killing the app if a user logs out. Can someone take a look.

### Steps To Reproduce

```swift
- Add a project with auth
- Login and add observers
- Logout and clean datastore
- Log back in and add observers and you'll see they don't work
```

### Expected behavior

Observers working

### Amplify Framework Version

2.11.6

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5.8

### CLI version

12.0.3

### Xcode version

14.3.1

### Is this a regression?

Yes

### Device

iPhone 14

### iOS Version

16

**Comment by JonathonVega** [comment]
I have also been running into this same issue using the same steps. I've tried running Amplify.DataStore.start() before running the observers, but it returns nothing. It's not until I kill the app and go back in is when the app begins to work properly. Has anyone else found a way around this?

**Comment by 5d** [comment]
Hi @afern247 @JonathonVega ,

Could you provide a sample schema and the verbose log of this error scenario? I have tried tests using the auth rule `@auth(rules: [{ allow: owner, provider: userPools }])` and followed your reproduce setps, and it worked without any problems.

To enable verbose logging, please make sure to set `Amplify.Logging.logLevel = .verbose` before `try Amplify.configure()`.

**Comment by JonathonVega** [comment]
@5d 

My schema is:
type User
    @model
    @auth(rules: [{allow: owner, operations:[create, delete, update, read]}]){
}

The main issue here for me is that it seems to sync to the datastore, but it returns nothing after logging the user out and logging back in.

2023-06-20 23:33:29.150942-0400 Aupair Connect[1896:5308102] [ObserveQueryTaskRunner<User>] Time to generate snapshot: 0.002142 seconds. isSynced: true, count: 0

Once I quit the app and go back in. It's able to retrieve the data:
2023-06-20 23:41:44.121666-0400 Aupair Connect[2085:5313376] [ObserveQueryTaskRunner<User>] Time to generate snapshot: 0.0 seconds. isSynced: true, count: 1

**Comment by afern247** [comment]
> userPools



> Hi @afern247 @JonathonVega ,
> 
> Could you provide a sample schema and the verbose log of this error scenario? I have tried tests using the auth rule `@auth(rules: [{ allow: owner, provider: userPools }])` and followed your reproduce setps, and it worked without any problems.
> 
> To enable verbose logging, please make sure to set `Amplify.Logging.logLevel = .verbose` before `try Amplify.configure()`.

I noticed that you are using `userPools`, I'm using Cognito for the default auth provider and automerge for conflict resolution. Here's a sample schema:

```
type User @model @auth(rules: [{ allow: owner }, { allow: private, operations: [read] }]) {
  id: ID!
  age: Int
  name: String
  email: String
  createdAt: String
  premiumUntil: AWSDateTime
  # socialMedia: Social @hasOne
  userSettings: UserSettings @hasOne
}
```

**Comment by 5d** [comment]
@afern247 The default auth provider for Cognito is userPools. I have been unable to reproduce the issue using the provided schema. Could you please provide more detailed logs for further investigation? 

Additionally, I have identified a potential implementation issue that could be causing the problem. Would you be willing to try the branch [5d/fix-3021](https://github.com/aws-amplify/amplify-swift/tree/5d/fix-3021) to see if it resolves the issue?

**Comment by afern247** [comment]
The thing is that the logs don't show anything on Xcode console...

yeah absolutely, thanks, I'll give a try to that branch, give me some time I'm away from my desk atm

**Comment by afern247** [comment]
Update: I had to do a trip and I won't be at home until July 12, and then I can test it with your branch, sorry for the delay. Please keep this open.

**Comment by afern247** [comment]
@5d Hi, sorry for the delay I was away from home. I just tested your branch with the change and it's looking good, that solved the issue, can you please merge it, thanks!

**Comment by 5d** [comment]
@afern247 , thank you for confirming. I'veve submitted the PR for the changes.

**Comment by afern247** [comment]
Actually, it's starting datastore again but with the data of the previous user, give me some time to verify it's not an error on my end @5d

**Comment by afern247** [comment]
Some notes:

With/without your branch change when 1 user logs in and logs out that data the user had before gets carried over to the next user, so the observer gets triggered and it's telling me that it started but it's not actually doing anything, it doesn't create new data for a new user...

This is the flow:

Old user with data **logs in** -> data loads -> user **Old user logs out** -> I see datastore cleared correctly -> create new user from 0 -> tap login in and session is accepted -> observer start -> **data from old user is present**, I go check on Amplify Studio and new data for the new user is never there.

If I force crash the app or quit and start again, when the user is logged out and datastore.clear has finished and the new user tries to register/log in, then it works.

@5d

**Comment by afern247** [comment]
Ok this got even more weird:

1. I deleted the user
2. I deleted the app
3. created a new user
4. Logged out the user
5. Sign in the same user and the data from an old user is back which is being picked up by the observer...

@5d

**Comment by afern247** [comment]
I think I know what the problem is, because I recenty did a major refactor on the graphql model.
```
type User
  @model
  @auth(rules: [
    { allow: owner },
    { allow: private, operations: [read] }
  ])
{
  id: ID!
  owner: String # who owns the user - this is the same as the cognito auth user (sub-id), you don't need to modify this value, amplify will generated based on whoever creates the object, which is the auth user
  createdAt: String
  name: String
  age: Int
  ...
}
```

The observer might be getting all the users data and that's why it's reading old data.

Give me 1 or 2 days to query the data that only belongs to the user and check if the issue with the observer not being added is resolved, which I think it is.

**Comment by afern247** [comment]
Testing done, I can confirm as of `2.15.1` main branch the issue if not present, the observer gets cleaned and re-added back normally.

Thanks for the support @5d

**Comment by afern247** [comment]
I found the bug, the issue happens after you add start(), so if you do this:

`stop`
`clean`
`start`

it will not put the observer back up, but if you do this it will:

`stop`
`clean`

@5d
