### ISSUE TITLE
Error Handler not called in some scenario

### ISSUE THREAD

**Issue by sebsto** [aws-amplify/amplify-swift#3028]
### Describe the bug

My customer was able to reproduce the issue with error handler not being called in certain scenarios. I am attaching steps to reproduce and log output from amplify sdk so you have a full picture of what is going on. 

**TL;DR**
When fields in the database are added without going through the API, Amplify Datastore / AppSync metadata such as `_version` are missing.  Sync fails (this is expected) but custom error handler are not called, making it impossible for the app to know that something went wrong.

**Steps to reproduce**
1. Using Xcode, create empty iOS project and then follow [DataStore documentation](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios/#code-generation-amplify-cli ) 
2. Run `amplify init` and allow all default configurations
3. Run `amplify add api`, select graphql, enable conflict detection using automerge, choose single object with fields template, use default template as follow:

```
input AMPLIFY { globalAuthRule: AuthRule = { allow: public } } # FOR TESTING ONLY!

type Todo @model {
id: ID!
name: String!
description: String
}
```

4. Run `amplify codegen models` to get models
5. Run `amplify push` to provision cloud resources
6. Implement iOS app functionality to create and list models sample todo model using DataStore and API plugins (see eg. [GitHub repo](https://github.com/fzy-spyro/AmplifyDSErrorHandlerSample/tree/main) with project sample) and start the app on eg. simulator - sync works as expected, no errors etc. Play with the app to create todo items, delete app from simulator afterwards.

Up to this point, everything is ok - ios app works, we can create models and use DataStore to save them locally and they will be synced to cloud via API plugin as well.

Now let's imagine there's another team (lets say a backend team) that works on the backend functionalities and they need to modify the model to introduce new required field. For the sake of simplicity we will use the same project and files as above but will will not modify ios app or generate new code when asked. 

Steps: 
7. Update schema.graphql file and add new required field, eg `author: String!`

```input AMPLIFY { globalAuthRule: AuthRule = { allow: public } }
 # FOR TESTING ONLY!

type Todo @model {
id: ID!
name: String!
author: String! # new required field added
description: String
}

```

8. Push changes to amplify stack - **DO NOT generate model files or updated app**.

When asked:
- Do you want to update code for your updated GraphQL API ? Answer no 

9. Manualy add new entry to dynamodb with mandatory id field (do not add other fields) - this simulates eg. backend logic which runs DynamoDB PUT operation to create some users data. Backend team knows nothing about the contents of the dynamo tables except what's specified in schema file. After manually adding a field, it should look like eg:

<img width="1290" alt="Screenshot 2023-06-12 at 12 09 00" src="https://github.com/aws-amplify/amplify-swift/assets/401798/c90333d0-01e0-4d39-88c1-9a9c91c395ed">

At this point, lets try to use and install unmodified ios app from previous steps and see results - App will show empty screen with a button ("todo" list will be empty) and we will see logs like (attached full log separately):
```
2023-06-12 12:10:18.168820+0200 AmplifyDSErrorHandlerSample[9442:167533] [RemoteSyncEngine] DataStoreError: An error occurred syncing Todo
Caused by:
DataStoreError: failed to process graphqlResponseData
Caused by:
APIError: failed to process graphqlResponseData
Caused by:
DataStoreError: The key `__typename` was not found
Recovery suggestion: Check if the parsed JSON contains the expected `__typename`
```

This is expected as required meta data are missing from the database. 

BUT the code-level custom error handler IS NOT CALLED.

Our error we implemented [here](https://github.com/fzy-spyro/AmplifyDSErrorHandlerSample/blob/main/AmplifyDSErrorHandlerSample/AmplifyDSErrorHandlerSampleApp.swift#L38-L43) was not called - there is no way for app to know that something went wrong at this point.

### Steps To Reproduce

```swift
see above.
```

### Expected behavior

Custom error handler must be called.

### Amplify Framework Version

2.11.5

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

12.0.0

### Xcode version

14.3.1

### Is this a regression?

No

### Device

all

### iOS Version

all

### Specific to simulators

no

**Comment by royjit** [comment]
Looks like we are only handling signOut error during Initial sync send to the custom error handler - https://github.com/aws-amplify/amplify-swift/blob/d0b5b166813b9c80bdfaddb46a84a348ce484b8c/AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/InitialSync/InitialSyncOperation.swift#L132

Will check with the team why the above error is not passed to the customer error handler.

**Comment by fzy-spyro** [comment]
any update on the issue ? :)

**Comment by thisisabhash** [comment]
Thank you for your patience. We are investigating this issue and will post here when we have updates.

**Comment by fzy-spyro** [comment]
Hey, It's been a while since last update. are there any news here?

**Comment by lawmicha** [comment]
this was released in https://github.com/aws-amplify/amplify-swift/releases/tag/2.18.2

**Comment by fzy-spyro** [comment]
@lawmicha Thanks for the info. will keep you updated if we will find something
