### ISSUE TITLE
'UIScreen' is unavailable in xrOS

### ISSUE THREAD

**Issue by ncrews35** [aws-amplify/amplify-swift#3034]
### Describe the bug

VisionOS apps cannot build on Xcode 15 Beta 2, due to the following compiler error provided by Xcode on line 121 of `DeviceInfo.swift` (see: [here](https://github.com/aws-amplify/amplify-swift/blob/c716f73bb8a14409820ceb1f91cc318e6de3a71f/Amplify/Core/Support/DeviceInfo.swift#L121)).
```
'UIScreen' is unavailable in xrOS
``` 
![Screenshot 2023-06-21 at 11 43 29 PM](https://github.com/aws-amplify/amplify-swift/assets/33267791/d608911e-20e7-48ac-956e-b05376a9a40f)

Apple documentation does not list VisionOS as a supported OS (see: [documentation](https://developer.apple.com/documentation/uikit/uiscreen)). I imagine this type of error will be frequent as packages begin to support VisionOS.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Build an Amplify app on Xcode 15 Beta 2.
2. Point at a VisionOS simulator
3. See error
```

### Expected behavior

Apps should build and run as expected. Amplify should check if the OS is VisionOS before using `UIScreen`.

### Amplify Framework Version

2.11.6

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.9

### CLI version

11.0.3

### Xcode version

15 Beta 2

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Device

VisionOS

### iOS Version

iOS 17

### Specific to simulators

Yes

### Additional context

_No response_

**Comment by atierian** [comment]
Thanks for reporting this. We’re looking into it and will follow up with any new information.

**Comment by atierian** [comment]
Hey @ncrews35, thanks for your patience.

We've added preview support for visionOS in the `visionos-preview` branch.
More information can be found here in the [Platform Support section](https://github.com/aws-amplify/amplify-swift/tree/visionos-preview#platform-support) of the `visionos-preview` branch.

We'd love to hear your feedback and any visionOS specific feature requests you have.

**Comment by ncrews35** [comment]
Thanks for the quick turnaround! Everything seems to be working well on `visionos-preview`.

**Comment by gurkarangulati** [comment]
Will this be merged back into the releases?

**Comment by mansidaksgh** [comment]
Merge it!!
