### ISSUE TITLE
multiple products named 'AWSSQS' in: 'aws-sdk-ios-spm', 'aws-sdk-swift'

### ISSUE THREAD

**Issue by Rizwana-Desai** [aws-amplify/amplify-swift#3055]
### Describe the bug

I have the [aws-sdk-ios-spm](https://github.com/aws-amplify/aws-sdk-ios-spm) package installed in my project and now I added [aws-amplify/amplify-ios](https://github.com/aws-amplify/amplify-ios) packages to integrate amplify data store. After adding Amplify packages I received an error for multiple products. How can I resolve this error and keep both packages. as both the packages are useful, if I remove   [aws-sdk-ios-spm](https://github.com/aws-amplify/aws-sdk-ios-spm) then I wouldn't be able to use AWS IOT.
Please check the attached screenshot for reference.
<img width="396" alt="Screenshot 2023-06-27 at 12 52 01 AM" src="https://github.com/aws-amplify/amplify-swift/assets/129170170/6057c8e8-a58e-4be9-b7b8-e6ac442b4d24">

Thank you!

### Steps To Reproduce

```swift
Steps to reproduce the behaviour:
1. Add aws-sdk-ios-spm  "https://github.com/aws-amplify/aws-sdk-ios-spm"  packages
2. then add aws-amplify/amplify-ios "https://github.com/aws-amplify/amplify-ios" packages
3. Then you will see Package resolution failed, click on Add Anyway
4. Now you can see the error same as shown in screenshot
```

### Amplify Framework Version

2

### Amplify Categories

API, Auth, DataStore

### Dependency manager

Swift PM

### Swift version

5.7

### Xcode version

14.2

### iOS Version

iOS 16.2

**Comment by atierian** [comment]
Thanks for opening this @Rizwana-Desai.

To avoid those naming collisions, you'll need to add the AWS SDK for iOS via CocoaPods.
