### ISSUE TITLE
GraphQLError when update mutation

### ISSUE THREAD

**Issue by fr33css** [aws-amplify/amplify-swift#3061]
### Describe the bug

i work fine at create, delete but update mutation

### schema
```
type User @model @auth(rules: [{allow: public}]) {
  id: ID!
  username: String!
  posts: [Post] @hasMany(indexName: "byUser", fields: ["id"])
  comments: [Comment] @hasMany(indexName: "byUser", fields: ["id"])
}

type Comment @model @auth(rules: [{allow: public}]) {
  id: ID!
  content: String!
  postID: ID! @index(name: "byPost", sortKeyFields: ["content"])
  post: Post! @belongsTo(fields: ["postID"])
  userID: ID! @index(name: "byUser")
}

type Post @model @auth(rules: [{allow: public}]) {
  id: ID!
  content: String!
  thumbnailUrl: String
  comments: [Comment] @hasMany(indexName: "byPost", fields: ["id"])
  userID: ID! @index(name: "byUser")
}
```

### UpdatePostInput
```
input UpdatePostInput {
  id: ID!
  content: String
  thumbnailUrl: String
  userId: ID
}
```

### Swift

Normal mutate from https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios/ **[Failed]**
```
func updatePost() async {
  do {
  let post = Post(id: "xxx", content: "abcdefg", thumbnailUrl: "aaa", userId: "userId")
  let result = try await Amplify.API.mutate(request: .update(post))
    switch result {
            case .success(let post):
                print(post)
            case .failure(let error):
                print(error)
            }
        } catch {
            print("error")
        }
  }
}
```
return 
```
error: error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x13c5000015f50).
The process has been returned to the state before expression evaluation.
```

### CustomGraphQL for update mutation **[Success]**
```
func updatePostMutation() -> GraphQLRequest<Post> {
        let graphQLDocument = """
            mutation updatePost {
                updatePost(input: {id: "xxx", content: "post", thumbnailUrl: "abcdefg", userId: "userId"}) {
                    id
                    content
                    thumbnailUrl
                    userId
                }
            }
        """
        return GraphQLRequest(document: graphQLDocument,
                              responseType: Post.self,
                              decodePath: "updatePost")
    }
```

### is able to update the post but when i add **return** for the content **[Failed]**
`updatePost(input: {id: "xxx", content: "post\n\n aaa", thumbnailUrl: "abcdefg"})`

return `"The HTTP response status code is [400]."`

i think that is the https issue when include **\n**
can i know how to fix it ?

### AWSAppSync **[Success]**
```
mutation MyMutation {
  updatePost(input: {id: "xxx", content: "fafa \n\n\n"}) {
    id
  }
}
```

```
return 
{
  "data": {
    "updatePost": {
      "id": "25362627-D191-4EAF-AB7B-244A5EF5A75D"
    }
  }
}
```

### Steps To Reproduce

```swift
amplify init
amplify add auth (cognito)
amplify add api (with conflict detection-> auto merge)
amplify add storage
amplify codegen models
amplify push
```

### Expected behavior

is able to update post mutation successfully

### Amplify Framework Version

2.0

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

12.0.3

### Xcode version

14.2

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

Yes

### Regression additional context

```
error: error: Execution was interrupted, reason: EXC_BAD_ACCESS (code=1, address=0x13c5000015f50).
The process has been returned to the state before expression evaluation.
```

### Device

iPhone 14 Pro Max simulator

### iOS Version

16.2

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by atierian** [comment]
Thanks for opening this issue @fr33css.
You mentioned that you're using Amplify version 2.0. Are you using the exact version 2.0.0, or a different version? If you're using 2.0.0, please update to the most recent version (2.12.0) to see if that resolves your issue.

Thanks!

**Comment by fr33css** [comment]
@atierian 
Thanks for your reply.
i searched how to get amplify version that all shown `amplify --version`
i type` amplify --version` in my terminal it's show 
12.0.3

It's that same things ?
if not can you show me how to get the amplify version and update it ?

**Comment by atierian** [comment]
Thanks, `amplify --version` will give you the version of Amplify CLI. We need to know the exact version of Amplify Swift you have in your project.

Are you using SPM? If so, you'll be able to find in the Project Navigator pane of Xcode under **Package Dependencies**. 
Here's an example screenshot.

<img width="272" alt="amplify_version_spm" src="https://github.com/aws-amplify/amplify-swift/assets/52051793/48e1ad83-ba56-42c3-93ce-6854f3d15030">

**Comment by fr33css** [comment]
@atierian 

Thanks for your reply.
<img width="136" alt="Screenshot 2023-07-02 at 12 52 24" src="https://github.com/aws-amplify/amplify-swift/assets/56120515/23e1e848-8a1d-4100-a831-992b3dfc53e8">
ya, i am using the newest Amplify version.
