### ISSUE TITLE
GraphQL Multi-Auth Not Working

### ISSUE THREAD

**Issue by dan-codes1** [aws-amplify/amplify-swift#3089]
### Describe the bug

My app does not work with multi-auth (API and CognitoPools) simultaneously. I have set my schema to accept multi auth but it still does not work. If I set the default auth mode to API, cognito stops working, and if I set the auth mode to cognito, Api stops working. For example:

```
type To-Do @model @auth(
                  rules: [
                     {allow: owner}, 
                     {allow: public, operations: [read]}, 
                     {allow: private, operations: [read]}
                 ]) {
  id: ID!
}
```

With the schema above, I am unable to add a new  To-Do or update/delete a To-Do after authenticating with cognito.

here is my API Plugin configuration for amplifyConfiguration.json

    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "Eemo": {
                    "endpointType": "GraphQL",
                    "endpoint": "blahblah/graphql",
                    "region": "us-west-2",
                    "authorizationType": "API_KEY",
                    "apiKey": "blahlbah"
                }
            }
        }
    },

here is my APPSync configuration for awsConfiguration.json

    "AppSync": {
        "Default": {
            "ApiUrl": "blahblah/graphql",
            "Region": "us-west-2",
            "AuthMode": "API_KEY",
            "ApiKey": "blahblah",
            "ClientDatabasePrefix": "Eemo_API_KEY"
        },
        "Eemo_AWS_IAM": {
            "ApiUrl": "blahblah/graphql",
            "Region": "us-west-2",
            "AuthMode": "AWS_IAM",
            "ClientDatabasePrefix": "Eemo_AWS_IAM"
        },
        "Eemo_AMAZON_COGNITO_USER_POOLS": {
            "ApiUrl": "blahblah/graphql",
            "Region": "us-west-2",
            "AuthMode": "AMAZON_COGNITO_USER_POOLS",
            "ClientDatabasePrefix": "Eemo_AMAZON_COGNITO_USER_POOLS"
        }
    },

### Steps To Reproduce

```swift
try to follow the description and use the schema/configuration provided.
```

### Expected behavior

I expect it to allow owner to create update and delete

### Amplify Framework Version

2.12.0

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

5.8

### CLI version

12.1.1

### Xcode version

14

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

Yes

### Regression additional context

_No response_

### Platforms

_No response_

### OS Version

MacOs Ventura

### Device

iphone 14

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by harsh62** [comment]
@dan-codes1 Thanks for opening the issue. Would you be able to share verbose logs and error that you are seeing?

You can enable verbose logging to the console by doing this before calling `Amplify.configure`:
```
Amplify.Logging.logLevel = .verbose
```

This will immensely help us narrow down our investigation.

**Comment by dan-codes1** [comment]
@harsh62  this is the log:

<<<< FigByteStream >>>> FigByteStreamStatsLogOneRead: ByteStream read of 137,230 bytes @ 63,591 took 0.7807 sec. to complete, 2 reads >= 0.5 sec.
Starting query 9B81E8D8-F289-4B0D-BEB3-6E1EF2F03DDC
{
  "variables" : {
    "limit" : 2,
    "filter" : {
      "and" : [
        {
          "favouriteUserId" : {
            "eq" : "b551c6ad-c91a-41d0-bd1a-e06a75f4726f"
          }
        },
        {
          "favouriteEemoId" : {
            "eq" : "8549F477-85BF-4633-8D07-BE7A2146E33C"
          }
        }
      ]
    }
  },
  "query" : "query ListFavourites($filter: ModelFavouriteFilterInput, $limit: Int) {\n  listFavourites(filter: $filter, limit: $limit) {\n    items {\n      id\n      createdAt\n      favouriteEemoId\n      favouriteUserId\n      updatedAt\n      eemo {\n        id\n        __typename\n      }\n      user {\n        id\n        __typename\n      }\n      __typename\n    }\n    nextToken\n  }\n}"
}
Starting network task for query 9B81E8D8-F289-4B0D-BEB3-6E1EF2F03DDC

successful amplify operation graphQLApi

Creating loaded list of Favourite
Starting mutation 1C507575-787A-4A12-96F9-E179DE42414C
{
  "query" : "mutation CreateFavourite($input: CreateFavouriteInput!) {\n  createFavourite(input: $input) {\n    id\n    createdAt\n    favouriteEemoId\n    favouriteUserId\n    updatedAt\n    eemo {\n      id\n      __typename\n    }\n    user {\n      id\n      __typename\n    }\n    __typename\n  }\n}",
  "variables" : {
    "input" : {
      "favouriteEemoId" : "8549F477-85BF-4633-8D07-BE7A2146E33C",
      "id" : "98A2A709-43F1-4E51-AE2F-684572033BD2",
      "favouriteUserId" : "b551c6ad-c91a-41d0-bd1a-e06a75f4726f"
    }
  }
}
Starting network task for mutation 1C507575-787A-4A12-96F9-E179DE42414C
GraphQLResponseError<Favourite>: GraphQL service returned a successful response containing errors: [Amplify.GraphQLError(message: "Not Authorized to access createFavourite on type Mutation", locations: Optional([Amplify.GraphQLError.Location(line: 2, column: 3)]), path: Optional([Amplify.JSONValue.string("createFavourite")]), extensions: Optional(["data": Amplify.JSONValue.null, "errorInfo": Amplify.JSONValue.null, "errorType": Amplify.JSONValue.string("Unauthorized")]))]
Recovery suggestion: The list of `GraphQLError` contains service-specific messages

**Comment by dan-codes1** [comment]
@harsh62 just to clarify, the `Favourite` model has the following auth rules:

type Favourite @model @auth(rules: [{allow: owner}, {allow: public, operations: [read]}, {allow: private, operations: [read]}]) {
  id: ID!
}

**Comment by royjit** [comment]
You `amplifyconfiguration.json` does not contain multiple authorizations, please follow the steps here https://docs.amplify.aws/lib/graphqlapi/authz/q/platform/ios/#configure-multiple-authorization-modes to configure the endpoints and invoke the api appropriately.

**Comment by dan-codes1** [comment]
@royjit I have added this to my amplifyconfig file

"api": {
        "plugins": {
            "awsAPIPlugin": {
                "Eemo_API_KEY": {
                    "endpointType": "GraphQL",
                    "endpoint": "blah blah",
                    "region": "us-west-2",
                    "authorizationType": "API_KEY",
                    "apiKey": " blah blah "
                },
                "Eemo_AMAZON_COGNITO_USER_POOLS": {
                    "endpointType": "GraphQL",
                    "endpoint": " blah blah",
                    "region": "us-west-2",
                    "authorizationType": "AMAZON_COGNITO_USER_POOLS",
                    "apiKey": "blah blah"
                }
            }
        }
    },

however even when i run `amplify push --force` the changes do not seem to be pushed because when i run `amplify pull` after running `amplify push --force`, the `amplifyconfiguration.json` file doesnt have the change added above.

Also, I get a new error:
APIError: More than one graphQL API configured. Could not infer which API to call
Recovery suggestion: Use the apiName to specify which API to call

failed amplify operation graphQLApi with error:
The operation couldn’t be completed. (Amplify.APIError error 1.)

**Comment by dan-codes1** [comment]
@royjit @harsh62  any updates on this? Almost been 2 weeks.

**Comment by harsh62** [comment]
@dan-codes1 If you are changing the configuration file by hand, it will always get overridden during amplify pull/push. From the latest error it seems the graphQL API is not configured correctly. I would suggest to follow the guide to set up the category again and document each steps. If you still face an issue, please comment on the issue with all the steps you have documented and we will try to recreate the issue at our end. 
ATM, I am not able to repro this issue in my local project.

**Comment by dan-codes1** [comment]
i have created a new api and even user pool and added multi auth to the API via cli. Multi auth is still not working and it still doesn't add the multi auth under plugins API section of the `amplifyconfiguration.json` file.

This is the documented cli step:

? Choose the default authorization type for the API API key
✔ Enter a description for the API key: · public api
✔ After how many days from now the API key should expire (1-365): · 30
? Configure additional auth types? Yes
? Choose the additional authorization types you want to configure for the API Am
azon Cognito User Pool
Cognito UserPool configuration
Use a Cognito user pool configured as a part of this project.

⚠️ WARNING: owners may reassign ownership for the following model(s) and role(s): Message: [owner], Favourite: [owner], EemoVideo: [owner], EemoImage: [owner], Review: [owner], Address: [owner], Eemo: [owner], User: [owner]. If this is not intentional, you may want to apply field-level authorization rules to these fields. To read more: https://docs.amplify.aws/cli/graphql/authorization-rules/#per-user--owner-based-data-access.
✅ GraphQL schema compiled successfully.

Edit your schema at /Users/danieleze/Documents/eemo/amplify/backend/api/eemo/schema.graphql or place .graphql files in a directory at /Users/danieleze/Documents/eemo/amplify/backend/api/eemo/schema
✅ Successfully updated resource

**Comment by tobias-feldmann** [comment]
Have the same problem since upgrading from Amplify v1 to v2. 
Previously, Multi-Auth worked without any problems. I only use the DataStore and not the API directly.
Everything configured as described. And it still worked before the upgrade.

**Comment by dan-codes1** [comment]
@tobias-feldmann oh so your multi with worked in v1 but stopped in v2? 

I started with v2 and mine has never worked.

**Comment by tobias-feldmann** [comment]
Yes exactly, with the same setup it worked with V1 @dan-codes1.

I also deleted the Amplify project and created it again.
When creating the API, i added Amazon Cognito User Pool as the default authorization type and additional IAM. Allow unauthenticated logins is active for Auth.
Only users who are logged in via the user pool can save data.

The DatastorePlugin is configured like this:

`Amplify.add(
              plugin: AWSDataStorePlugin(
                  modelRegistration: models,
                  configuration: .custom(authModeStrategy: .multiAuth)
              )
          )`

**Comment by lawmicha** [comment]
Let's take a look at this use case:

Let's take a look at the use case:
```
type Todo @model @auth(
                  rules: [
                     {allow: owner}, 
                     {allow: public, operations: [read]}, 
                     {allow: private, operations: [read]}
                 ]) {
  id: ID!
  content: String
}
```

What is the expected behavior?
1. All users signed in can create, update, delete, and read todos.
 1a. A signed in user subscribes to Todo mutations without owner input specified, receives all todos.
 1b. A signed in user subscribes to Todo mutations with owner input specified, receives only todos created/updated/deleted by the owner specified.
3. All users not signed in, can read todos (when not passing in owner input in the subscription), and cannot create/update/delete
4. IAM user can read all todos, and cannot create/update/delete


There seems to be 2 issues with DataStore. The first one is for a user that is not signed in, the subscriptions that are established is passing in owner input of empty string. This means that the read is specified for an empty owner, so no data is ever received on the API Key read-only use case. 

The second issue is when the user is signed in, it's subscribing with an owner input of the logged in user, filtering down to only data created/updated/deleted by the user themselves (use case 1b)

**Comment by lawmicha** [comment]
Everything seems to be working well with 
```
@auth(
  rules: [
    {allow: owner, operations: [create, update, delete]}, 
    {allow: public, operations: [read]}, 
    {allow: private, operations: [read]}
]) 
```
Make sure if you update the auth rules, `amplify push` and re-run `amplify codegen models` to pick up the schema changes in the model swift files.

Not signed in users, using API Key subscriptions, doesn't have owner field, which receives all mutations:
```
subscription OnCreateTodo {
  onCreateTodo {
    id
    content
    createdAt
    updatedAt
    __typename
    _version
    _deleted
    _lastChangedAt
    owner
  }
}\"
```

Signed In user, also using the above operation, and with the Authorization payload to be the token, is receiving all mutations. By not setting read access for the signed in user, the priority of auth types used in the DataStore multiauth takes `private` over `public` while `owner` does not have any read access.

**Comment by dan-codes1** [comment]
@lawmicha Does this only work for datastore category? because I'm using the API category and its still not working. Im getting this error:
`GraphQLResponseError<Address>: GraphQL service returned a successful response containing errors: [Amplify.GraphQLError(message: "Not Authorized to access createAddress on type Mutation", locations: Optional([Amplify.GraphQLError.Location(line: 2, column: 3)]), path: Optional([Amplify.JSONValue.string("createAddress")]), extensions: Optional(["errorType": Amplify.JSONValue.string("Unauthorized"), "data": Amplify.JSONValue.null, "errorInfo": Amplify.JSONValue.null]))]
Recovery suggestion: The list of `GraphQLError` contains service-specific messages `

Address Schema:
`type Address @model @searchable @auth(rules: [{allow: public, operations: [read]}, {allow: private, operations: [read]}, {allow: owner, operations: [create, update, delete]}]) {
  id: ID!`

Default auth = API Key. Secondary auth mode is cognito.

**Comment by lawmicha** [comment]
Hey @dan-codes1, I can see in the response, the mutation failed because it's trying to send the mutation request using the API key. if you're making API calls using a different auth type from the primary auth mode, you'll have to modify the configuration as per https://github.com/aws-amplify/amplify-swift/issues/3089#issuecomment-1642370311 to use the correct interceptors. The amplifyconfiguration.json currently only generates the primary auth mode, and is expected I believe. I understand you mentioned that the file gets overwriten on `pull` which is expected since local modifications to the file do get stored in your amplify project.

Ideally the solution we provide here a way to specify the auth type in code instead of the configuration file, where you can do something like this:
```swift
Amplify.API.mutate(request: request, authtype: .cognitoUserPool)
```

**Comment by dan-codes1** [comment]
@lawmicha thanks it worked. However, though I rarely run `amplify pull`, this means I'd have to keep updating my `amplifyconfiguration.json` each time I call `amplify pull`. 

Your suggestion `Amplify.API.mutate(request: request, authtype: .cognitoUserPool)` makes sense to me. Hope to see it in future releases.

**Comment by lawmicha** [comment]
@dan-codes1 please track/thumbs up this https://github.com/aws-amplify/amplify-swift/issues/3133 for the feature request of adding auth type. Since the original issue here is solved, please open an new issue if you face any other problems. @tobias-feldmann If you are still experienceing issues, please open a new issue with the details of your use case and schema.

**Comment by tobias-feldmann** [comment]
@lawmicha I described my use case with more details in #3136
