### ISSUE TITLE
DynamoDB help

### ISSUE THREAD

**Issue by wills721** [aws-amplify/amplify-swift#3105]
I'm using Amplify and while its great for a DynamoDB table via Datastore -- using a DynamoDB which was created outside Amplify inside Amplify is escaping me.  I've seen that you can 'amplify import storage' and I see my external DynamoDB but when I try wrapping code around it Amplify assumes the table has all the versioning/createAt/etc metadata.  I cant use AppSync separately for it since only one AppSync per Project (I'm using xcode) is allowed.  Is there any help anyone here can give to guide me?

**Comment by wills721** [comment]
This is the only documentation I have found.  Over and above below is there something perhaps unique in the schema.graphql for this scenario to avoid the CRUD ops generated that expect to find 'version', etc. ?

Select the "DynamoDB table - NoSQL Database" option when you've run amplify import storage. In order to successfully import your DynamoDB table, your DynamoDB table needs to be located within the same region as your Amplify project.

Run amplify push to complete the import procedure.

**Comment by thisisabhash** [comment]
Hello, thank you for posting this.
You may try some of the options below : 
- Create an AppSync API and set up data resolvers to interact with DynamoDB. This provides an API interface to make requests to so you can use Amplify.API client to talk to the AppSync backend
- Use AWS DynamoDB SDK to interact with the DynamoDB backend directly.

**Comment by wills721** [comment]
Thank you for responding :)

Regarding your second option,  I have tried to include the AWS-SDK package to my xCode project however it fails with many conflicts.  The Amplify packages I believe embed the SDK but do not make it available. 

Any idea how I can import AWS DynamoDB SDK into xCode?


Thanks again!

:)

**Comment by harsh62** [comment]
@wills721 It would be nice if you can share more information about your integration. i.e.

* What Amplify version are you using? 1.x or 2.x?
* What errors are you exactly seeing in Xcode?
* Steps for replicating those errors, so that we can reproduce the issue at our end and help you with an accurate answer. 
* Any code samples you believe are helpful for the investigation?

**Comment by harsh62** [comment]
Issue resolved in [discord thread](https://discord.com/channels/705853757799399426/1136675530230480916).
