### ISSUE TITLE
Verification codes expiration date

### ISSUE THREAD

**Issue by Elza-Hoff** [aws-amplify/amplify-swift#3127]
### Describe the bug

Hey!
In our app we use Amplify for the sign in flow and password reset. We have some bug in logic compares to Android sdk, which works as expected. 
User receives verification code #1 and then request another code #2. We expect that only newest verification code will be valid, but in fact all received verification codes are valid.
Android sdk accept only newest verification code.
This function is used for password reset.
<img width="1129" alt="Screenshot 2023-08-02 at 12 09 00" src="https://github.com/aws-amplify/amplify-swift/assets/55557935/ee36578c-f7dd-4f59-9d34-b78c95e5e022">

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Got to reset password
2. Click on 'Resend code' and have 2 codes in your mail.
3. Use old one 
4. This old one code is accepted as valid
```

### Expected behavior

Only newest verification code accepted

### Amplify Framework Version

2.8.1

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5

### CLI version

-

### Xcode version

14.3

### Is this a regression?

Yes

### OS Version

15.0

### Device

iPhone 13 Pro max

### Specific to simulators

no

**Comment by harsh62** [comment]
@Elza-Hoff I tested on Amplify Swift and can see that older codes are not accepted. Amplify Swift simply passes on the code to Cognito and doesn't have any client side logic. 

Would you be able to share testing steps that you are performing for this use case? Is there anything different compared to iOS and Android implementation?

**Comment by harsh62** [comment]
@Elza-Hoff 

I am still not super clear what the use case is.. You have shared with me 2 very different API's. One API is for sign up whereas the other one is for reset password.

Would you be able to share the code snippet that is causing you this problem?
