### ISSUE TITLE
Amplify V2 on CocoaPods

### ISSUE THREAD

**Issue by 8Rav3n** [aws-amplify/amplify-swift#3150]
### Is your feature request related to a problem? Please describe.

I am trying to include Amplify libraries through CocoaPods but apparently the pods only refresh V1 APIs. if they are not going to be supported going forward, is there a pan to include V2 in CocoaPods?

### Describe the solution you'd like

Include V2 APIs in CocoaPods

### Describe alternatives you've considered

is there any? (other discontinue CocoaPods)

**Comment by atierian** [comment]
Thanks for opening this feature request @8Rav3n.

We currently don't have any plans to support CocoaPods for Amplify Swift version 2.x. However, we'd like to understand your use case; can you share the reason you can't use SPM with us? Thanks!

**Comment by 8Rav3n** [comment]
hi @atierian 
thanks for your feedback. 
the reason behind is currently we are managing all our dependencies as cocoapods and we do not really use SPM Of course the 2 can be combined in a single project but it increases complexity...

**Comment by ruisebas** [comment]
@8Rav3n thanks for sharing your use case. As you mentioned, combining SPM and CocoaPods is indeed possible as long as there are no target name conflicts.
You could also explore wrapping Amplify V2 in an `xcframework` and/or host that `xcframework` as a podspec in your build system, but I believe that would increase complexity even more.

As per @atierian's comment, we currently don't have any plans to support CocoaPods for Amplify V2, so I'm closing this issue.
