### ISSUE TITLE
xCode Cloud Support for CI/CD

### ISSUE THREAD

**Issue by Etep15** [aws-amplify/amplify-swift#3151]
I'm looking at xCode Cloud to create iOS builds of our app each time a check-in occurs to our main branch for CI/CD purposes. However I have an error stating that it requires the following files to be checked into GIT.

- awsconfiguration.json
- amplify/.config/local-env-info.json
- amplifyconfiguration.json

However, we are a multi developer team and do this would likely cause all kinds of issues as we merge pull requests etc. Any experience or suggestions? We'd really like our iOS app to auto build with CI/CD after we do a push to our branch.

**Comment by ruisebas** [comment]
If you wish to avoid pushing these files, one thing you could do is to have them stored somewhere and pull them during the pre-build.

For example, you could have the files stored in private s3 buckets and download them to your app's directory. 
Or store their contents in Secret Environment Vars, and run a script to create the files from them.
