### ISSUE TITLE
AuthTokenURLInterceptor overriding Content-Type header to application/json always

### ISSUE THREAD

**Issue by sandeepklr** [aws-amplify/amplify-swift#3184]
### Describe the bug

Relevant amplifyconfiguration.json api configuration blob:

```
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "AbcApi": {
                    "endpointType": "REST",
                    "endpoint": "https://yyyyyyyyyy.execute-api.us-west-2.amazonaws.com/dev",
                    "region": "us-west-2",
                    "authorizationType": "OPENID_CONNECT"
                }
            }
        }
    }
```

I'm trying to use the Amplify API plugin to make `multipart/form-data` requests to API Gateway. From documentation listed here[1], I'd have expected to be able to do the following:

```
let headers = ["content-type": "multipart/form-data; boundary=....."]
let request = RESTRequest(path: ...., headers: headers, body: ...)
```

Ideally this would allow me to pass in the custom content-type while constructing a RESTRequest object[2], and then eventually override the default `application/json` content-type used while constructing a URLRequest object[3].

However, when the interceptors are run the AuthTokenURLInterceptor kicks and always overwrites the content-type header to set it to `application/json` [4, 5]. 

Is there a reason the AuthTokenURLInterceptor needs to set content-type? 

As a workaround, I could just create another URLInterceptor and set the Content-Type there but given that the rest of the Amplify library is set up to accept custom headers it seems redundant to do that. 

[1] https://docs.amplify.aws/lib/restapi/authz/q/platform/ios/#none
[2] https://github.com/aws-amplify/amplify-swift/blob/9d6fa8b8b9b03493932b442b0c054bcb30209385/Amplify/Categories/API/Request/RESTRequest.swift#L35-L39
[3] https://github.com/aws-amplify/amplify-swift/blob/9d6fa8b8b9b03493932b442b0c054bcb30209385/AmplifyPlugins/API/Sources/AWSAPIPlugin/Support/Utils/RESTOperationRequestUtils.swift#L61-L66
[4] https://github.com/aws-amplify/amplify-swift/blob/9d6fa8b8b9b03493932b442b0c054bcb30209385/AmplifyPlugins/API/Sources/AWSAPIPlugin/Interceptor/RequestInterceptor/AuthTokenURLRequestInterceptor.swift#L35-L36
[5] Debug details:

URLRequest in AWSRESTOperation _before_ AuthTokenURLInterceptor runs:

```
Printing description of urlRequest:
▿ ...
  ▿ httpMethod : Optional<String>
    - some : "POST"
  ▿ allHTTPHeaderFields : Optional<Dictionary<String, String>>
    ▿ some : 2 elements
      ▿ 0 : 2 elements
        - key : "Cache-Control"
        - value : "no-store"
      ▿ 1 : 2 elements
        - key : "Content-Type"
        - value : "multipart/form-data; boundary=CC1F1DBE-9CC3-448E-AE78-A1782C9D2BED"
  ▿ httpBody : Optional<Data>
    ▿ some : 2051407 bytes
      - count : 2051407
      ▿ pointer : 0x00007f7bfc821000
        - pointerValue : 140170494087168
  - httpBodyStream : nil
  - httpShouldHandleCookies : true
  - httpShouldUsePipelining : false
``` 
URLRequest in AWSRESTOperation _after_ AuthTokenURLInterceptor runs:

```
Printing description of finalRequest:
▿ ....
  ▿ httpMethod : Optional<String>
    - some : "POST"
  ▿ allHTTPHeaderFields : Optional<Dictionary<String, String>>
    ▿ some : 5 elements
      ▿ 0 : 2 elements
        - key : "User-Agent"
        - value : "amplify-iOS/1.16.1 iOS/16.4 en_US"
      ▿ 1 : 2 elements
        - key : "Cache-Control"
        - value : "no-store"
      ▿ 2 : 2 elements
        - key : "Authorization"
        - value : "...."
      ▿ 3 : 2 elements
        - key : "Content-Type"
        - value : "application/json"
      ▿ 4 : 2 elements
        - key : "X-Amz-Date"
        - value : "20230828T103145Z"
  ▿ httpBody : Optional<Data>
    ▿ some : 2051407 bytes
      - count : 2051407
      ▿ pointer : 0x00007f7bfc821000
        - pointerValue : 140170494087168
  - httpBodyStream : nil
  - httpShouldHandleCookies : true
  - httpShouldUsePipelining : false  
```

### Steps To Reproduce

```swift
See above.
```

### Expected behavior

Overriding Content-Type should work in RESTRequest should work.

### Amplify Framework Version

2.15.2

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

5.8.1

### CLI version

12.2.5

### Xcode version

14.3.1

### Is this a regression?

No

### Platforms

iOS

### OS Version

All

### Device

All

**Comment by atierian** [comment]
The fix for this was released in [Amplify Swift 2.17.2](https://github.com/aws-amplify/amplify-swift/releases/tag/2.17.2)
Thanks again for reporting this and your feedback in the PR review process!
