### ISSUE TITLE
Unable to create user-session for CognitoSDK after sign in done through SSO.

### ISSUE THREAD

**Issue by jav8r1at** [aws-amplify/amplify-swift#3203]
### Describe the bug

How can i create a user session with these tokens recieved from SS0 ..
Im using cognito 2.33.0 version in swift.

### Steps To Reproduce

```swift
I have launched a webview for the user which has a redirecturi .
User will be prompted to enter the user name and password and after successful authenticaltion . I get a code on the redirect URI.
I then extract the code from it and call a Auth/Token post Api and get all the tokens for the user (id token , access and refersh)

how to activate the user session for that token recieved
```

### Expected behavior

I should be able to activate session either manually

### Amplify Framework Version

Cognito 2.33.0

### Amplify Categories

API, Auth

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

0

### Xcode version

13.5

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Platforms

iOS

### OS Version

16

### Device

iPhone

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by phantumcode** [comment]
@jav8r1at Can you help clarify what you mean by `activate the user session for that token recieved` ? What is the goal or use case you're trying to solve?

Here are Cognito documentation for the usage of id token, access token, and refresh tokens: https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html

**Comment by harsh62** [comment]
@jav8r1at Also would you be able to clarify what version of Amplify are you using? 

We don't have a version you shared in the ticket.

> Amplify Framework Version
> Cognito 2.33.0

**Comment by jav8r1at** [comment]
I am using CognitoSDK and not Amplify..

**Comment by jav8r1at** [comment]
> @jav8r1at Can you help clarify what you mean by `activate the user session for that token recieved` ? What is the goal or use case you're trying to solve?
> 
> Here are Cognito documentation for the usage of id token, access token, and refresh tokens: https://docs.aws.amazon.com/cognito/latest/developerguide/amazon-cognito-user-pools-using-tokens-with-identity-providers.html

there is a method getusersession(userId) .. i have the tokens from SSO im able to fetch userdetails from JWT token but this metho getusersession(userId) is not giving a call back
