### ISSUE TITLE
Amplify.Auth.confirmResetPassword does not throw exception when username not found 

### ISSUE THREAD

**Issue by jmhuang12** [aws-amplify/amplify-swift#3209]
### Describe the bug

I have a question regarding the confirmResetPassword method. 

1) Shouldn't userNotFoundException be thrown when you call the confirmResetPassword method for an user who is not in Cognito User Pool?

2) Also shouldn't codeMismatchException be thrown when calling confirmResetPassword for a wrong confirmation code?
per https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ForgotPassword.html#API_ForgotPassword_Errors

see also https://docs.amplify.aws/lib/auth/password_management/q/platform/ios/#reset-password.

However, no exception is thrown for both of these scenarios. 

I also referred to a similar issue -> https://github.com/aws-amplify/amplify-js/issues/4699
However, "Prevent User Existence Errors turned to Enabled" under app client no longer has a "legacy" option. 

Please help. thanks 

### Steps To Reproduce

```swift
do {
                        var res = Amplify.Auth.confirmResetPassword(for: "username", with: " ", confirmationCode: "1233")
                    } catch let error as AuthError {
                        print("Reset password failed with error \(error)")
                        if let cognitoAuthError = error.underlyingError as? AWSCognitoAuthError {
                            switch cognitoAuthError {
                            case .aliasExists:
                                print("alias exists")
                            case .codeDelivery:
                                print("code delivery")
                            case .codeExpired:
                                print("code expired")
                            case .codeMismatch:
                                Text("wrong code")
                            case .failedAttemptsLimitExceeded:
                                print("failed attempts limit exceeded")
                            case .deviceNotTracked:
                                print("device not tracked")
                            case .errorLoadingUI:
                                print("error loading UI")
                            case .invalidAccountTypeException:
                                print("invalid account type exception")
                            case .invalidParameter:
                                print("invalid parameter")
                            case .invalidPassword:
                                print("invalid password")
                            case .lambda:
                                print("lambda")
                            case .limitExceeded:
                                print("limit exceeded")
                            case .mfaMethodNotFound:
                                print("mfaMethodNotFound")
                            case .network:
                                print("network")
                            case .passwordResetRequired:
                                print("passwordResetRequired")
                            case .requestLimitExceeded:
                                print("requestLimitExceeded")
                            case .resourceNotFound:
                                print("resourceNotFound")
                            case .softwareTokenMFANotEnabled:
                                print("softwareTokenMFANotEnabled")
                            case .userCancelled:
                                print("userCancelled")
                            case .userNotConfirmed:
                                print("userNotConfirmed")
                            case .userNotFound:
                                print("userNotFound")
                            case .usernameExists:
                                print("usernameExists")
                            }
                        }
                    } catch {
                        print("Unexpected error: \(error)")
                    }
```

### Expected behavior

exception thrown for nonexistent user name or wrong confirmation code 

### Amplify Framework Version

2.12.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.8.1

### CLI version

12.1.1

### Xcode version

14.3.1

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Platforms

iOS

### OS Version

17

### Device

iphone11

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by ruisebas** [comment]
Hi @jmhuang12 , thanks for opening this issue. 
What you are describing indeed looks like the result of **Prevent User Existence Errors** being enabled. 

Here are the steps to modify this setting:
1. Sign in to the [Amazon Cognito console](https://console.aws.amazon.com/cognito/home).
2. Select an existing user pool from the list.
3. Click on the **App Integration** tab.
4. Under **App client list**, select an app client from the list.
5. Under the **App client information** section, click the **Edit** button.
6. Scroll to the bottom to find the **Prevent user existence errors** checkbox under _Advanced security configurations_. 
7. Save your changes.

Having said that, you should still be getting a `.codeMismatch` error when calling `confirmResetPassword (for:with:confirmationCode:)` with a wrong confirmation code. Are you not getting anything at all (i.e. no success nor failure)?

**Comment by jmhuang12** [comment]
> Hi @jmhuang12 , thanks for opening this issue. What you are describing indeed looks like the result of **Prevent User Existence Errors** being enabled.
> 
> Here are the steps to modify this setting:
> 
> 1. Sign in to the [Amazon Cognito console](https://console.aws.amazon.com/cognito/home).
> 2. Select an existing user pool from the list.
> 3. Click on the **App Integration** tab.
> 4. Under **App client list**, select an app client from the list.
> 5. Under the **App client information** section, click the **Edit** button.
> 6. Scroll to the bottom to find the **Prevent user existence errors** checkbox under _Advanced security configurations_.
> 7. Save your changes.
> 
> Having said that, you should still be getting a `.codeMismatch` error when calling `confirmResetPassword (for:with:confirmationCode:)` with a wrong confirmation code. Are you not getting anything at all (i.e. no success nor failure)?

======

Thanks for your prompt reply. I have **Prevent User Existence Errors** disabled in the cognito app client console. I get a success when calling `confirmResetPassword (for:with:confirmationCode:)` with a wrong confirmation code. 

In fact, my XCode compiler tells me that "'catch' block is unreachable because no errors are thrown in 'do' block " when calling `confirmResetPassword (for:with:confirmationCode:)`. So calling "confirmResetPassword" would always be a success and no exception would ever be thrown. Please see the picture. 

<img width="1546" alt="Screenshot 2023-09-07 at 11 48 00 AM" src="https://github.com/aws-amplify/amplify-swift/assets/144288214/04d262e9-f196-4079-a8f9-ebcd4db86b8f">

**Comment by ruisebas** [comment]
🤔 I'm confused by that, [confirmResetPassword(for:with:confirmationCode)](https://github.com/aws-amplify/amplify-swift/blob/main/Amplify/Categories/Auth/AuthCategory%2BClientBehavior.swift#L74) not only `throws`, but it is also an `async` function without a return type.

So it shouldn't compile unless you call it like this:
```swift
try await Amplify.Auth.confirmResetPassword(
    for: username, 
    with: newPassword, 
    confirmationCode: confirmationCode
)
```

Are you sure you are using Amplify version `2.12.0`? You might be using `1.x`, which was not `async` and it did return an operation.
You can check under **Package Dependencies** in Xcode's Navigator view.

**Comment by jmhuang12** [comment]
Yes indeed I have Amplify version (1.30.4) installed instead of version 2.12.0. Amplify was installed using cocoapod. However, i cannot update Amplify to 2.12.0 by running "pod install --repo-update". How do i update Amplify to the latest version?  

> 🤔 I'm confused by that, [confirmResetPassword(for:with:confirmationCode)](https://github.com/aws-amplify/amplify-swift/blob/main/Amplify/Categories/Auth/AuthCategory%2BClientBehavior.swift#L74) not only `throws`, but it is also an `async` function without a return type.
> 
> So it shouldn't compile unless you call it like this:
> 
> ```swift
> try await Amplify.Auth.confirmResetPassword(
>     for: username, 
>     with: newPassword, 
>     confirmationCode: confirmationCode
> )
> ```
> 
> Are you sure you are using Amplify version `2.12.0`? You might be using `1.x`, which was not `async` and it did return an operation. You can check under **Package Dependencies** in Xcode's Navigator view.

<img width="1056" alt="Screenshot 2023-09-07 at 5 13 32 PM" src="https://github.com/aws-amplify/amplify-swift/assets/144288214/8cb54194-792b-4425-bf2e-8a7376e320a6">

**Comment by ruisebas** [comment]
Amplify 2.x is only available through **Swift Package Manager** and we currently don't have any plans to support CocoaPods.

**Amplify 1.x** Auth APIs behave differently: they are not async and don't throw errors, but you need to handle the result by either providing a completion handler closure or retaining the returned `AnyCancellable` and attaching a subscriber. 

For example, something like this:
```swift
Amplify.Auth.confirmResetPassword(for: username, with: newPassword, confirmationCode: confirmationCode) { result in
    switch result {
    case .success:
        print("Password reset confirmed")
    case .failure(let error):
        print("Reset password failed with error \(error)")
        guard let cognitoAuthError = error.underlyingError as? AWSCognitoAuthError else {
            print("Unexpected error: \(error)")
            return
        }

        // Handle cognitoAuthError...
    }   
}
```

You can find more information in the [v1 doc page](https://docs.amplify.aws/lib-v1/auth/password_management/q/platform/ios/#change-password)

----
Having said that, we encourage you to migrate, as Amplify v1 is now in **Maintenance Mode** until May 31st, 2024. This means that we will continue to include updates to ensure compatibility with backend services and security, but no new features will be introduced.

**Comment by jmhuang12** [comment]
> 

Amplify v2 is added using SPM. thank you for your help! closing issue.
