### ISSUE TITLE
Revoke token error  AWSCognitoRevokeTokenError.

### ISSUE THREAD

**Issue by jav8r1at** [aws-amplify/amplify-swift#3211]
### Is your feature request related to a problem? Please describe.

 I am signing in to Amplify with a temperory password/default password and presenting a screen to enter a new password and then calling
 
 //                    Task{
//                        do {
//                            let signInResult = try await Amplify.Auth.confirmSignIn(challengeResponse: changePasswordViewModel.newPassword)
//                            if signInResult.isSignedIn {
//                                print("Confirm sign in succeeded. The user is signed in.")
//                                DispatchQueue.main.async {
//                                    NotificationCenter.default.post(name: NSNotification.resetPasswordForFirstLoginSucess,
//                                                                    object: nil, userInfo: [:])
//                                }
//                            } else {
//                                print("Confirm sign in succeeded.")
//                                print("Next step: \(signInResult.nextStep)")
//                                // Switch on the next step to take appropriate actions.
//                                // If `signInResult.isSignedIn` is true, the next step
//                                // is 'done', and the user is now signed in.
//                            }
//                        } catch let error as AuthError {
//                            changePasswordViewModel.isErrorFromBackend = true
//                            changePasswordViewModel.errorMessage = error.errorDescription
//                            print("Confirm sign in failed \(error)")
//                        } catch {
//                            print("Unexpected error: \(error)")
//                            changePasswordViewModel.errorMessage = "Something went wrong"
//                        }
//                    }

                         
 once the new password is set i log out the user and show the login page for re-login..
 
  NotificationCenter.default.post(name: NSNotification.resetPasswordForFirstLoginSucess,
//                                                                    object: nil, userInfo: [:]) uiang this observer im logging out the user.
 
while i logout im facing the above issue

### Describe the solution you'd like

I would like to get how can i completet the logout flow

### Describe alternatives you've considered

I've tried clearing the web cookies as well but didn't serve the process

### Is the feature request related to any of the existing Amplify categories?

API

**Comment by phantumcode** [comment]
@jav8r1at Thanks for submitting the issue.  
`Amplify.Auth.confirmSignIn(...)` is used to confirm sign in in multi-factor authentication; to sign in using the MFA challenge code.  Please see the [multi-factor auth documentation ](https://docs.amplify.aws/lib/auth/signin/q/platform/ios/#multi-factor-authentication)for reference.

There is a different set of Auth APIs for changing or setting the user's password.  See [documentation here](https://docs.amplify.aws/lib/auth/password_management/q/platform/ios/#reset-password).

**Comment by jav8r1at** [comment]
The solution is that we need to enable token revocation in our user pool

**Comment by ruisebas** [comment]
@jav8r1at just to clarify, did you solve your issue?

**Comment by jav8r1at** [comment]
yes I did . Thanks
