### ISSUE TITLE
Build Fails because of AWSCognitoAuthPlugin

### ISSUE THREAD

**Issue by afern247** [aws-amplify/amplify-swift#3217]
### Describe the bug

My app build is failing because of , the issue seems to be an optimization level that needs to be done. Here's how it looks:

![image](https://github.com/aws-amplify/amplify-swift/assets/34192856/8e4cfd62-8562-4ea8-8ba8-787890275532)

```
CompileSwift normal x86_64 (in target 'AWSCognitoAuthPlugin' from project 'Amplify')
...
/Users/arturo/.../Build/Intermediates.noindex/Amplify.build/Release-iphonesimulator/AWSCognitoAuthPlugin.build/Objects-normal-tsan/x86_64/outputs-5 -index-unit-output-path-filelist /Users/arturo/.../DerivedData/.../Build/Intermediates.noindex/Amplify.build/Release-iphonesimulator/AWSCognitoAuthPlugin.build/Objects-normal-tsan/x86_64/index-unit-outputs-5

Command CompileSwift failed with a nonzero exit code
```

![image](https://github.com/aws-amplify/amplify-swift/assets/34192856/ba68c422-3e50-4458-8d3f-645e53fe26fd)

I tested the same code, same Amplify version on Xcode 14.2 (14C18) and works fine.

This is a blocker to upgrade to the new Xcode version coming out now, please fix assap

In case it's an optimization issue, here are my settings:
![image](https://github.com/aws-amplify/amplify-swift/assets/34192856/c8a06236-f8d4-4903-9233-82ffa950901c)

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
Download the latest version of Xcode from the App Store Xcode 14.3.1 (14E300c) and try to compile the app, make sure to clean build and app data.
```

### Amplify Framework Version

2.17.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.8

### CLI version

12.4.0

### Xcode version

14.3.1 (14E300c)

### Is this a regression?

Yes

### Platforms

iOS

### OS Version

16.1

### Device

iPhone 14

**Comment by atierian** [comment]
Thanks for reporting this @afern247.

Can you please see if deleting your DerivedData resolves this?

**Comment by afern247** [comment]
That's the first thing I tried, it didn't fix it :/ @atierian

**Comment by atierian** [comment]
From the screenshot you provided, can you paste the build log message from above the "Command CompileSwift failed with a nonzero exit code" message?

![267314516-ba68c422-3e50-4458-8d3f-645e53fe26fd-1](https://github.com/aws-amplify/amplify-swift/assets/52051793/b9fd25e3-6f1a-4276-b1d8-db828aeb4a18)

**Comment by atierian** [comment]
I understand you already tried deleting DerivedData - have you tried deleting your SPM cache at `~/Library/Caches/org.swift.swiftpm`?
(make sure to quit Xcode before doing so)

**Comment by afern247** [comment]
Some notes:

- On the simulator it fails with the mentioned error, but if I use a real device as simulator then it succeeds. However if I submit the release version to test flight it fails on a real device.
- If I put it on Release on Run config. it fails, if I put it on debug it succeeds.
![image](https://github.com/aws-amplify/amplify-swift/assets/34192856/9be5b87e-3f0d-42e5-83fe-0a7597faf646)

- I can't run the SwiftUI preview, I get this error:
```
== PREVIEW UPDATE ERROR:

    SchemeBuildError: Failed to build the scheme "MyApp"
    
    Build target AWSCognitoAuthPlugin:
    note: Set ENABLE_PREVIEWS=NO because SWIFT_OPTIMIZATION_LEVEL=-Owholemodule, expected -Onone (in target 'AWSCognitoAuthPlugin' from project 'Amplify')
```

- Here's the log you asked for:
[log.txt](https://github.com/aws-amplify/amplify-swift/files/12597838/log.txt)
- I clean up everything and the error persists.
@atierian

**Comment by atierian** [comment]
Do you have Thread Sanitizer (TSan) enabled in your Run scheme?
Based on the stack dump from the crash, it looks like that may be the case. It's also the only way I'm able to reproduce this.
```
0. Running pass 'Function Pass Manager' on module '.../Objects-normal-tsan/x86_64/ASFAppInfo.o'.
```


TSan can't be used when running on device. [[Apple Docs](https://developer.apple.com/documentation/xcode/diagnosing-memory-thread-and-crash-issues-early#Detect-data-races-among-your-apps-threads)]
> Important
>
> You can’t use Thread Sanitizer to diagnose iOS, tvOS, and watchOS apps running on a device. Use Thread Sanitizer only on your 64-bit macOS app, or to diagnose your 64-bit iOS, tvOS, or watchOS app running in Simulator.

It's my understanding that it only works in Debug builds on Simulator as well.

**Comment by afern247** [comment]
Without the thread it seems to work, but I haven't pushed to the app store yet to fully test it, let's keep this open until my next release so I can provide confirmation.

right now these options are enabled:

![image](https://github.com/aws-amplify/amplify-swift/assets/34192856/42a7d019-c0a0-4ee6-a536-8eff9c268c13)
@atierian

**Comment by atierian** [comment]
Thanks for letting us know; I'm happy to hear it appears to be resolved.

We'll check back in a week or two if we haven't heard from you by then.

**Comment by atierian** [comment]
Hey @afern247, just checking in - were you able to release?
