### ISSUE TITLE
Xcode warnings - 'id' is deprecated: Use .primaryKey(fields:)

### ISSUE THREAD

**Issue by jmhuang12** [aws-amplify/amplify-swift#3219]
### Describe the bug

I'm getting a lot of warnings such as:
<img width="344" alt="Screenshot 2023-09-12 at 3 17 27 PM" src="https://github.com/aws-amplify/amplify-swift/assets/144288214/1322a4ad-aa6f-4ed6-8e17-3c95f720c58b">

For the contacts+schema.swift file generated by CLI command "Amplify codegen models". 

<img width="1262" alt="Screenshot 2023-09-12 at 3 18 22 PM" src="https://github.com/aws-amplify/amplify-swift/assets/144288214/9896d5d3-a25d-4e43-87b8-fae90caedf23">

There was a prior issue opened related to this -> https://github.com/aws-amplify/amplify-swift/issues/2460
and was tracked and partially resolved the "pluralName deprecation" by issue -> https://github.com/aws-amplify/amplify-swift/issues/3135. However, the "id" deprecation issue doesn't seem to be resolved. 

I tried to set the "respectprimarykeyattributesonconnectionfield" flag in the cli.json file to true and run "Amplify push" and then "Amplify codegen models". but i got the same "'id' is deprecated: Use .primaryKey(fields:)" warning. 

<img width="767" alt="Screenshot 2023-09-12 at 3 29 45 PM" src="https://github.com/aws-amplify/amplify-swift/assets/144288214/5176e611-c3cc-4cb1-93b4-b5958453a784">

I also tried to manually change the "contacts+schema.swift" file, by changing ".id()" to ".primaryKey(fields:)" as the warning suggests. however, i got different errors instead. 

<img width="1258" alt="Screenshot 2023-09-12 at 3 31 48 PM" src="https://github.com/aws-amplify/amplify-swift/assets/144288214/47b320e4-2b2b-4281-a7ab-af4baa3eb499">

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. define "contacts" model as below 

import Amplify
import Foundation

public struct Contacts: Model {
  public let id: String
  public var contactId: String
  public var contactName: String
  public var contactProfileImageKey: String
  public var userProfileContactsId: String?
  
  public init(id: String = UUID().uuidString,
      contactId: String,
      contactName: String,
      contactProfileImageKey: String,
      userProfileContactsId: String? = nil) {
      self.id = id
      self.contactId = contactId
      self.contactName = contactName
      self.contactProfileImageKey = contactProfileImageKey
      self.userProfileContactsId = userProfileContactsId
  }
}

2. run cli command  "amplify codegen models" to generate "contacts+schema.swift"
```

### Expected behavior

no warnings generated 

### Amplify Framework Version

2.17.1

### Amplify Categories

API, DataStore

### Dependency manager

Swift PM

### Swift version

swift 5 

### CLI version

12.4.0

### Xcode version

14.3.1

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

Yes

### Regression additional context

_No response_

### Platforms

iOS

### OS Version

ios 17

### Device

iphone11

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by ruisebas** [comment]
Hi @jmhuang12, thanks for opening this issue.

In order to avoid using the deprecated `.id()` field when generating the models, in addition to setting the feature flag you need to add the `@primaryKey` tag to the proper attribute in your schema. 

For example:
```graphql
type Contacts @model {
  id: ID! @primaryKey
  contactId: String!
  contactName: String!
  contactProfileImageKey: String!
  contactId: String
}
```

**Comment by jmhuang12** [comment]
thank you! i added @primarykey and cli told me to migrate to migrate graphql from v1 to v2, which automatically does it foro me. see https://docs.amplify.aws/cli/migration/transformer-migration/#relationship-mappingconnection-changes
