### ISSUE TITLE
Update AWS iOS Swift example code

### ISSUE THREAD

**Issue by davepander** [aws-amplify/amplify-swift#3245]
### Describe the bug

The code samples here: https://aws.amazon.com/getting-started/hands-on/build-ios-app-amplify/

...are a bit out-dated given the updates for iOS 17. 

### Steps To Reproduce

```swift
Follow the instructions given here:
https://aws.amazon.com/getting-started/hands-on/build-ios-app-amplify/

find errors based on deprecated code.
```

### Expected behavior

Compilation.

### Amplify Framework Version

5.0.14

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

12.5.1

### Xcode version

15.0

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Platforms

iOS

### OS Version

17

### Device

iPhone

### Specific to simulators

_No response_

### Additional context

This was brought up in the discord, and it was suggested that I open this issue.
<img width="1207" alt="Screenshot_2023-09-11_at_5 16 15_PM" src="https://github.com/aws-amplify/amplify-swift/assets/300903/c326144b-36da-412a-92db-d3d4271c6180">
<img width="1236" alt="Screenshot_2023-09-11_at_5 17 10_PM" src="https://github.com/aws-amplify/amplify-swift/assets/300903/4a4a9a51-0fe1-4eab-8ef6-653794f4780f">

**Comment by davepander** [comment]
@atierian Any thoughts or questions on this update?

**Comment by atierian** [comment]
We're working on updating the documentation -- we'll update you here once that's complete. In the meantime, are there any specific questions around usage that we can help you with?

**Comment by GitPappaBaker** [comment]
Updates?  I have hit these two issues.  If you have an update (or workaround) please provide it even if you can not update the official documentation yet.  Thanks!    (PS:  there is actually another issue in the example code where some print statements are not terminated properly. If you give a fix to these issues I'll open a defect for that component)

**Comment by GitPappaBaker** [comment]
I'll put my own update in here.  Not sure this is how it is *supposed* to function, but this will get you through. 

1) to fix the async issue just wrap each of the self.updateUserData call in a task.  here is an example, repeated for each one:
            case HubPayload.EventName.Auth.signedIn:
                print("==HUB== User signed In, update UI")
                Task{
                    await self.updateUserData(withSignInStatus: true)
                }
2) for the Amplify.Auth.signInWithWebUI call, just make an empty call: Amplify.Auth.signInWithWebUI()

3) Although it is not mentioned in this defect, there are quite a few improperly terminated strings in a series of case statements.  Here is one example "case" from the switch that has been fixed:
        case let .partial(revokeTokenError, globalSignOutError, hostedUIError):
            if let hostedUIError = hostedUIError {
                print("HostedUI error  \(String(describing: hostedUIError))")
            }

I just mention this so no one overthinks the errors that this series of switch/case generates. 

I'm happy to have someone tell me a different way to fix these issues but for now...the code is working ;)

**Comment by davepander** [comment]
Coming up on two months.  I've just been sending people to Firebase.

**Comment by ruisebas** [comment]
Hi all, I wanted to provide an update.

The team is working on re-writing the old sample tutorial found at https://aws.amazon.com/getting-started/hands-on/build-ios-app-amplify/ in order to use the latests tools, practices and features from both Swift and Amplify.

We appreciate your patience while we complete and publish this update.

In the meantime, you can visit our official [**Amplify Documentation for Swift**](https://docs.amplify.aws/swift/) website, where you will also find:
- [Instructions on how to create a simple example app and integrate it with Amplify](https://docs.amplify.aws/swift/start/getting-started/introduction/)
- [More details on how to use each Amplify Category to support your use cases](https://docs.amplify.aws/swift/build-a-backend/)
  - For example, in the [**Authentication**](https://docs.amplify.aws/swift/build-a-backend/auth/) you will find information and examples on how to handle your authentication flows.
  
Thanks!

**Comment by atierian** [comment]
The updated guide is queued up for release -- we'll let you know once it's complete.

**Comment by davepander** [comment]
> The updated guide is queued up for release -- we'll let you know once it's complete.

Any update on the release?

**Comment by atierian** [comment]
No updates at this time. We'll be sure to let you know on this issue once the updated guide is released.

Please let us know if you have any concrete questions on getting started with Amplify Swift after reviewing the links posted a few comments up.

> In the meantime, you can visit our official [**Amplify Documentation for Swift**](https://docs.amplify.aws/swift/) website, where you will also find:
>  - [Instructions on how to create a simple example app and integrate it with Amplify](https://docs.amplify.aws/swift/start/getting-started/introduction/)
>  - [More details on how to use each Amplify Category to support your use cases](https://docs.amplify.aws/swift/build-a-backend/)
>    - For example, in the [**Authentication**](https://docs.amplify.aws/swift/build-a-backend/auth/) you will find information and examples on how to handle your authentication flows.
> 
> Thanks!
