### ISSUE TITLE
Unable to use Amplify Auth when running macOS app

### ISSUE THREAD

**Issue by Pedrosolisg** [aws-amplify/amplify-swift#3266]
### Describe the bug

I have a native cross-platform app for `iOS (17.0` and `macOS(14.0`) written fully using `SwiftUI` and the latest Framework version from `AWS Amplify (2.19.0)`.

This app uses `AWS Congnito` for internal purposes, where admin users need to `signIn` in order to retrieve a session token used for the rest of API requests for content management.
The `signIn()` with `Amplify Auth` works with no issues when eg. logging in on iOS (iPhone or iPad), **but when running on macOS, I get the following error:**

```
AUTH_SESSION - Login failed with error - AuthError: Unexpected error occurred with message: 
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-swift/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't.
Caused by:
KeychainStoreError: Keychain error occurred with status: -34018
Recovery suggestion: This should not happen. There is a possibility that there is a bug if this error persists. Please take a look at https://github.com/aws-amplify/amplify-ios/issues to see if there are any existing issues that match your scenario, and file an issue with the details of the bug if there isn't. Issue encountered at:
file: /Users/pedrosolisgarcia/Library/Developer/Xcode/DerivedData/KalistenAdmin-donhmyqmajqeeiduiggfhhzefjck/SourcePackages/checkouts/amplify-ios/AmplifyPlugins/Core/AWSPluginsCore/Keychain/KeychainStoreError.swift
function: recoverySuggestion
line: 69
AUTH_SESSION - This error is not covered by AWSCognito
```

This is the `signIn()` implementation, used across all platforms, as I said, it works on iOS but gets the error above on macOS

```
func login(username: String, password: String) async {
        status.load()
        do {
            let signInResult = try await Amplify.Auth.signIn(
                username: username,
                password: password
            )
            if signInResult.isSignedIn {
                log(Log.Auth.Login.Info.done)

                await self.fetchCurrentAuthSession()
            } else {
                log(Log.Auth.Login.Info.stepRequired)
                switch signInResult.nextStep {
                case .confirmSignUp(let details):
                    log("Account not Validated: \(String(describing: details))")
                default:
                    log(Log.Auth.Login.Error.unknown)
                }
            }
        } catch let error as AuthError {
            log(Log.Auth.Login.Error.loginFailed(with: error))

            self.authError.getSessionError(from: error)
        } catch {
            log(Log.Auth.Login.Error.loginFailed(with: error))
        }
    }
```

This is the data I include on my `amplifyconfiguration.json` (Showing different values for safety purposes)

```
{
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "eu-east-1_LXxB1H7js",
                        "AppClientId": "4dug67vgkujjm6mr97et80l02r",
                        "Region": "eu-east-1"
                    }
                }
            }
        }
    }
}
```

Is anyone aware of this issue? or is there any other configuration needed to satisfy requests on macOS?

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to any `macOS` app using `Amplify Auth`
2. Go to a eg. Login screen
3. Attempt to perform a signIn(username:password:) with valid data
4. See error in console
```

### Expected behavior

The login should be successful, the same way it is already on iOS

### Amplify Framework Version

2.19.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.9

### CLI version

12.4.0

### Xcode version

Version 15.0 (15A240d)

### Relevant log output

NA

### Is this a regression?

No

### Platforms

macOS

### OS Version

14.0

### Device

MacBook Pro 16-inch, 2021

**Comment by atierian** [comment]
Hi @Pedrosolisg, thanks for opening this issue. When running on macOS, you need to enable Keychain Sharing capability in your app.

Here's some more information from our [docs](https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios/#prerequisites)

> To use Auth in a macOS project, you'll need to enable the Keychain Sharing capability. In Xcode, navigate to your application target > Signing & Capabilities > + Capability, then select Keychain Sharing.
This capability is required because Auth uses the Data Protection Keychain on macOS as a platform best practice. See [TN3137: macOS keychain APIs and implementations](https://developer.apple.com/documentation/technotes/tn3137-on-mac-keychains) for more information on how Keychain works on macOS and the Keychain Sharing entitlement.
For more information on adding capabilities to your application, see [Xcode Capabilities](https://developer.apple.com/documentation/xcode/capabilities).

**Comment by Pedrosolisg** [comment]
You are absolutely right! That fixed the issue. Thanks a lot and apologies for such a rookie waste of time! :P

**Comment by atierian** [comment]
Thanks for confirming that resolved your issue! And thank you for opening it - you're not the first person to report this, so we're now looking at improving the error messaging for this case.
