### ISSUE TITLE
Build Errors When Integrating AWSAPIPlugin via SPM

### ISSUE THREAD

**Issue by Cyclic** [aws-amplify/amplify-swift#3270]
### Describe the bug

Here is a framework package that I have referenced in my main Xcode project. I am encountering build errors when trying to integrate AWSAPIPlugin via Swift Package Manager. Below are the package definition and the build error log:
```

// swift-tools-version: 5.9

/*
See the LICENSE.txt file for this sample’s licensing information.

Abstract:
The package that defines the app's user interface elements.
*/

import PackageDescription

let package = Package(
    name: "BackyardBirdsUI",
    defaultLocalization: "en",
    platforms: [
        .iOS(.v17),
        .macOS(.v14),
        .watchOS(.v10),
        .tvOS(.v17)
    ],
    products: [
        .library(
            name: "BackyardBirdsUI",
            type: .dynamic,
            targets: ["BackyardBirdsUI"]
        )
    ],
    dependencies: [
        .package(path: "../BackyardBirdsData"),
        .package(path: "../LayeredArtworkLibrary"),
        .package(url: "https://github.com/aws-amplify/amplify-swift", .upToNextMajor(from: "2.0.0"))
    ],
    targets: [
        .target(
            name: "BackyardBirdsUI",
            dependencies: [
                .product(name: "BackyardBirdsData", package: "BackyardBirdsData", condition: nil),
                .product(name: "LayeredArtworkLibrary", package: "LayeredArtworkLibrary", condition: nil),
                .product(name: "AWSAPIPlugin", package: "amplify-swift")
            ],
            path: "."
        )
    ]
```
)

I would appreciate any assistance on resolving these build errors. Thank you!

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Open the example project.
2. You can use the Backyard Birds sample app from Apple to try adding the dependency to the AWSAPIPlugin package to the BackyardBirdsData
3. Check out the package in the BackyardBirdsUI framework to see the reference, and also the reference in the Xcode project
4. See error
```

### Expected behavior

Project should build.

### Amplify Framework Version

Latest

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

5.9

### CLI version

na

### Xcode version

Version 15.0 (15A240d)

**### [BackyardBirds.zip](https://github.com/aws-amplify/amplify-swift/files/12796886/BackyardBirds.zip)**

### Relevant log output

Ld /Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks/AWSClientRuntime_6243340EBB32613E_PackageProduct.framework/AWSClientRuntime_6243340EBB32613E_PackageProduct normal (in target 'AWSClientRuntime' from project 'aws-sdk-swift')
    cd /Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/SourcePackages/checkouts/aws-sdk-swift
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -Xlinker -reproducible -target arm64-apple-ios13.0-simulator -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk -O0 -L/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Intermediates.noindex/EagerLinkingTBDs/Debug-iphonesimulator -L/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator -L/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/lib -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Intermediates.noindex/EagerLinkingTBDs/Debug-iphonesimulator -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -F/Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -iframework /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -iframework /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator17.0.sdk/Developer/Library/Frameworks -filelist /Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Intermediates.noindex/aws-sdk-swift.build/Debug-iphonesimulator/AWSClientRuntime\ product.build/Objects-normal/arm64/AWSClientRuntime_6243340EBB32613E_PackageProduct.LinkFileList -install_name @rpath/AWSClientRuntime_6243340EBB32613E_PackageProduct.framework/AWSClientRuntime_6243340EBB32613E_PackageProduct -Xlinker -rpath -Xlinker /usr/lib/swift -Xlinker -rpath -Xlinker /Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Intermediates.noindex/aws-sdk-swift.build/Debug-iphonesimulator/AWSClientRuntime\ product.build/Objects-normal/arm64/AWSClientRuntime_6243340EBB32613E_PackageProduct_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -L/usr/lib/swift /Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks/AwsCommonRuntimeKit_-4BF287267C1FE4D_PackageProduct.framework/AwsCommonRuntimeKit_-4BF287267C1FE4D_PackageProduct /Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks/ClientRuntime_-11D472C3C358BEB0_PackageProduct.framework/ClientRuntime_-11D472C3C358BEB0_PackageProduct -Xlinker -dependency_info -Xlinker /Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Intermediates.noindex/aws-sdk-swift.build/Debug-iphonesimulator/AWSClientRuntime\ product.build/Objects-normal/arm64/AWSClientRuntime_6243340EBB32613E_PackageProduct_dependency_info.dat -o /Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Products/Debug-iphonesimulator/PackageFrameworks/AWSClientRuntime_6243340EBB32613E_PackageProduct.framework/AWSClientRuntime_6243340EBB32613E_PackageProduct -Xlinker -add_ast_path -Xlinker /Users/thomas.goddard/Library/Developer/Xcode/DerivedData/Foo-geuzcmdpkauebrfmqvvjnvbxdagr/Build/Intermediates.noindex/aws-sdk-swift.build/Debug-iphonesimulator/AWSClientRuntime.build/Objects-normal/arm64/AWSClientRuntime.swiftmodule

ld: Undefined symbols:
  XMLCoder.XMLDecoder.__allocating_init(trimValueWhitespaces: Swift.Bool, removeWhitespaceElements: Swift.Bool) -> XMLCoder.XMLDecoder, referenced from:
      AWSClientRuntime.Ec2QueryError.init(httpResponse: ClientRuntime.HttpResponse) throws -> AWSClientRuntime.Ec2QueryError in AWSClientRuntime.o
      AWSClientRuntime.RestXMLError.init(httpResponse: ClientRuntime.HttpResponse) throws -> AWSClientRuntime.RestXMLError in AWSClientRuntime.o
      AWSClientRuntime.RestXMLError.init(httpResponse: ClientRuntime.HttpResponse) throws -> AWSClientRuntime.RestXMLError in AWSClientRuntime.o
  type metadata accessor for XMLCoder.XMLDecoder, referenced from:
      AWSClientRuntime.Ec2QueryError.init(httpResponse: ClientRuntime.HttpResponse) throws -> AWSClientRuntime.Ec2QueryError in AWSClientRuntime.o
      AWSClientRuntime.RestXMLError.init(httpResponse: ClientRuntime.HttpResponse) throws -> AWSClientRuntime.RestXMLError in AWSClientRuntime.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Is this a regression?

Yes

### Platforms

iOS

### OS Version

17

### Device

iPhone 15

### Additional context

See attached project

**Comment by thisisabhash** [comment]
Hello, Thank you for posting this - we are inevstigatin the issue and will post updates here.

**Comment by thisisabhash** [comment]
Hello,
You'd need to remove the `Amplify` package from the `Backyard Birds` project dependencies since `AWSAPIPlugin` is already included in the `BackyardBirdsUI` library. This was the source of build errors you were seeing. I have included the `.zip` with the fix as well.

Before
![remove-package](https://github.com/aws-amplify/amplify-swift/assets/23294582/1bda986c-2cd1-4f15-9f02-58c59c41fff3)

After
![build-fixed](https://github.com/aws-amplify/amplify-swift/assets/23294582/16a2acb4-6059-46c2-a28b-f65b8c79ef12)

Zip with fixed build: 
[BackyardBirdsBuildingAnAppWithSwiftDataAndWidgets.zip](https://github.com/aws-amplify/amplify-swift/files/12797788/BackyardBirdsBuildingAnAppWithSwiftDataAndWidgets.zip)

Please let us know if you have any more questions.

**Comment by Cyclic** [comment]
Thank you!
