### ISSUE TITLE
Amplify uses 'shared-access-group' keyChain store, while also making an assumption it's private

### ISSUE THREAD

**Issue by myeyesareblind** [aws-amplify/amplify-swift#3277]
### Describe the bug

We have a few build of our app - AhHoc, Beta, Alpha, AppStore.

At some point, we found that when internal dev installs & launches 'Beta', it will magically sign off user from AppStore or any other build.
Turns out, we have 'keychain-access-group' entitlement added to the app.
Now, by default, KeyChain writes to ('first-keychain-access-group' ?? app-id).
Which makes the keyChain store actually shared across all the apps.
We are using cognito & it writes to the same key.

https://developer.apple.com/documentation/security/ksecattraccessgroup
> If you don’t explicitly set a group, keychain services defaults to the app’s first access group, which is either the first keychain access group, or the app ID when the app has no keychain groups

I don't know why Apple has made such design choice, but the Amplify 'must' set keychain-group to app-id, otherwise it makes it shared.

Here is my keychain item that I got from Cognito, as you can see there is **'Access Group'** added.
<img width="537" alt="Screenshot 2023-10-04 at 23 00 49" src="https://github.com/aws-amplify/amplify-swift/assets/575303/848b0c98-75e5-4965-87d2-870b78098a7e">
<img width="536" alt="Screenshot 2023-10-04 at 23 00 55" src="https://github.com/aws-amplify/amplify-swift/assets/575303/77486316-2d36-49ce-856a-d069f016b805">

### Steps To Reproduce

```swift
There are no steps, as it's mostly about build configuration.
The issue can be observed if organisation has few applications (with different bundleids) that have a shared keychain-access-group.
Both application would write into the same keychainItem.
```

### Expected behavior

Cognito KeyChain is not shared across the apps.

### Amplify Framework Version

2.3.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.9

### CLI version

12.1.1

### Xcode version

14.3.1

### Relevant log output

```shell
na
```

### Is this a regression?

No

### Platforms

iOS, macOS

### OS Version

iOS 16

### Device

iPhone X

### Additional context

My team spend quite some time figuring this out ...

**Comment by atierian** [comment]
Thanks for reporting this and for the thorough explanation @myeyesareblind!

We're actively investigating it and will get back back to you here as soon as possible.

**Comment by thisisabhash** [comment]
Hello,
Thank you for posting this.
Currently, you may workaround this by adding a unique keychain access group(eg. Bundle ID of your app flavor) to top of the list in the
keychain group.

![access-group](https://github.com/aws-amplify/amplify-swift/assets/23294582/c636a92d-aa1f-458a-9615-76c44da7b422)


We currently have a feature request in place for adding an `accessGroup` parameter to `AWSCognitoAuthPlugin` to support Keychain access groups. You may track that feature request there. https://github.com/aws-amplify/amplify-swift/issues/2508

**Comment by thisisabhash** [comment]
Tracking this in #2508 and closing this.
