### ISSUE TITLE
Undefined symbols when tried to run the tests

### ISSUE THREAD

**Issue by cyopaulo** [aws-amplify/amplify-swift#3279]
**Describe the bug**
When I try to run the tests I got this issue

<img width="438" alt="Screenshot 2023-10-05 at 12 55 12" src="https://github.com/aws-amplify/aws-sdk-ios/assets/115005537/19e1d0a6-e7ca-4e3b-8a83-afb2ecf660bb">

**To Reproduce**
1. Added the AWSCognitoAuthPlugin, AWSS3StoragePlugin
2. Run the unit tests

**Stack Trace**

Showing Recent Errors Only

Build target AWSClientRuntime with configuration Debug

ld: Undefined symbols:
  XMLCoder.XMLDecoder.__allocating_init(trimValueWhitespaces: Swift.Bool, removeWhitespaceElements: Swift.Bool) -> XMLCoder.XMLDecoder, referenced from:
      AWSClientRuntime.Ec2QueryError.init(httpResponse: ClientRuntime.HttpResponse) throws -> AWSClientRuntime.Ec2QueryError in Ec2QueryError.o
      AWSClientRuntime.RestXMLError.init(httpResponse: ClientRuntime.HttpResponse) throws -> AWSClientRuntime.RestXMLError in RestXMLError.o
      AWSClientRuntime.RestXMLError.init(httpResponse: ClientRuntime.HttpResponse) throws -> AWSClientRuntime.RestXMLError in RestXMLError.o
  type metadata accessor for XMLCoder.XMLDecoder, referenced from:
      AWSClientRuntime.Ec2QueryError.init(httpResponse: ClientRuntime.HttpResponse) throws -> AWSClientRuntime.Ec2QueryError in Ec2QueryError.o
      AWSClientRuntime.RestXMLError.init(httpResponse: ClientRuntime.HttpResponse) throws -> AWSClientRuntime.RestXMLError in RestXMLError.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Undefined symbols:

Linker command failed with exit code 1 (use -v to see invocation)

**Environment(please complete the following information):**
 - SDK Version: [e.g. 2.6.29]
 - Dependency Manager: SPM
 - Swift Version : 5.7
 - Xcode Version: 15

**Device Information (please complete the following information):**
 - Device: iPhone 13
 - iOS Version: 17.0

**Comment by thisisabhash** [comment]
It seems like there is duplication of imports.
Can you check if your main project has `Amplify` in the package dependencies along with other dependencies which also have `Amplify` in its dependencies? If so, please remove `Amplify` from the main project package dependencies.

**Comment by cyopaulo** [comment]
I removed the Amplify on the main project but the error persists

**Comment by thisisabhash** [comment]
Hello,
Can you post code snippets and your `Package.swift` with sensitive information removed so that we can try to reproduce the issue?

**Comment by cyopaulo** [comment]
There is no Package.swift I just added the Amplify by Swift Package xcode interface

**Comment by thisisabhash** [comment]
I see. Can you add the `Amplify` and plugins to the Linked Binaries of Host Application of the test target.
 
And remove `Amplify` and plugins from the Linked Binaries of the test target and try a `Clean Build Folder` and run.

![remove-linked-binary](https://github.com/aws-amplify/amplify-swift/assets/23294582/4e2c2b9d-aa4d-4535-b017-b5d0d32b40e2)

**Comment by cyopaulo** [comment]
I added the into the link Binaries of my main project but the error still the same 

<img width="1065" alt="Screenshot 2023-10-05 at 15 58 17" src="https://github.com/aws-amplify/amplify-swift/assets/115005537/ac0e0617-dd79-47ae-a6ee-a5644657e24e">

**Comment by thisisabhash** [comment]
How does the Link Binary section of the test target look like?

**Comment by cyopaulo** [comment]
<img width="1091" alt="Screenshot 2023-10-05 at 16 03 21" src="https://github.com/aws-amplify/amplify-swift/assets/115005537/5cc241a1-4ced-484b-8b97-8ccc5c0483d4">

**Comment by thisisabhash** [comment]
Do any of these binaries have `Amplify`/ Plugins in their dependencies?

**Comment by cyopaulo** [comment]
Yes I'm able to run it, I don't know which one has the amplify but I just removed all the link binary and it's works

**Comment by thisisabhash** [comment]
That's great to hear! Let us know if you have more questions.
