### ISSUE TITLE
AuthError: Incorrect username or password but can register

### ISSUE THREAD

**Issue by confusionhill** [aws-amplify/amplify-swift#3282]
### Describe the bug

I tried to call the sign in method on amplify

```
func signIn(username: String, password: String) {
        let options = AWSAuthSignInOptions(authFlowType: .userSRP)
        Amplify.Auth.signIn(
            username: username,
            password: password,
            options: .init(pluginOptions: options)) { result in
            switch result {
            case .success(let resp):
                print("is signed in? ",resp.isSignedIn)
            case .failure(let err):
                print("error bro : ",err)
            }
        }
    }
```

but the server responded with "AuthError: Incorrect username or password", somehow registration works like a charm without any trouble so what did I do wrong to be exact?

here's my configuration
```
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CredentialsProvider": {
          "CognitoIdentity": {
            "Default": {
              "PoolId": "ap-southeast-1:xxxxxx",
              "Region": "ap-southeast-1"
            }
          }
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "ap-southeast-1_xxxxxx",
            "AppClientId": "7590jxxxxx",
            "Region": "ap-southeast-1"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH",
            "OAuth": {}
          }
        }
      }
    }
  }
}

```
note : I did not set any client secret, so I still have no idea why it doesn't work
### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Register
2. Confirm
3. Login
```

### Expected behavior

Login succesfully without any error

### Amplify Framework Version

latest

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.8

### CLI version

12.6.0

### Xcode version

14.3

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Platforms

_No response_

### OS Version

ios 15.0

### Device

emulator

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by confusionhill** [comment]
the email is hard coded, is it not possible?

**Comment by thisisabhash** [comment]
The emails are different.

`self.signIn(username:"myemail@gmail.com", password:"mypassword")` 

```
Amplify.Auth.signIn(
            username: "enemes.sys@gmail.com",
```

**Comment by confusionhill** [comment]
> The emails are different.
> 
> `self.signIn(username:"myemail@gmail.com", password:"mypassword")`
> 
> ```
> Amplify.Auth.signIn(
>             username: "enemes.sys@gmail.com",
> ```

it was a typo, I've updated it

**Comment by confusionhill** [comment]
well i tried to debug the library and found this

what does it indicate? what ar the insights?
<img width="642" alt="Screenshot 2023-10-06 at 13 08 56" src="https://github.com/aws-amplify/amplify-swift/assets/71744284/db91ad05-b058-4fd2-bff4-bb851420ea52">

**Comment by confusionhill** [comment]
> well i tried to debug the library and found this
> 
> what does it indicate? what ar the insights? <img alt="Screenshot 2023-10-06 at 13 08 56" width="642" src="https://user-images.githubusercontent.com/71744284/273119386-db91ad05-b058-4fd2-bff4-bb851420ea52.png">

how about this one? i find it hard to debug 
<img width="718" alt="Screenshot 2023-10-06 at 13 43 53" src="https://github.com/aws-amplify/amplify-swift/assets/71744284/a41918d7-7238-4717-8fe4-d21fb86d98ef">
and know what it means

**Comment by confusionhill** [comment]
> It says that you've exceeded the password attempt count. I would recommend to create a new user and is you still see an error, please share verbose logs with us.
> 
> You can enable verbose logging to the console by doing this before calling `Amplify.configure`:
> 
> ```
> Amplify.Logging.logLevel = .verbose
> ```

still doesn't give me any hint
```
error bro :  AuthError: Incorrect username or password.
Recovery suggestion: Check whether the given values are correct and the user is authorized to perform the operation.
```
