### ISSUE TITLE
Update needed for Starscream from 4.0.4 to latest

### ISSUE THREAD

**Issue by Josiah-Agosto** [aws-amplify/amplify-swift#3290]
When using Socket.IO-Client for iOS, the StarscreamAdapter+Delegate files, didReceive methods enum has updated and throws an error to add the .peerClosed case. Without this enum case added it fails and can't be fixed. I see the starscream package is set to exactly 4.0.4, as of this ticket 4.0.6 is latest, this should either be set regularly or next minor etc.

**Comment by atierian** [comment]
a
