### ISSUE TITLE
App rejected from store during upload

### ISSUE THREAD

**Issue by mkrn** [aws-amplify/amplify-swift#3324]
### Describe the bug

My Framework includes amplify-swift which in turn depends on aws-crt-swift

The built app works on device in Debug and Release.

During upload to TestFlight the following error appears:
 
The app references non-public symbols in Payload/appnew.app/Frameworks/.....MyFramework: _CCCryptorGCMAddAAD, _CCCryptorGCMFinalize, _CCCryptorGCMSetIV (ID: 18f105e0-1452-4a69-b9ee-...)

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Archive app and upload to App Store
2. See error
```

### Expected behavior

App should upload 

### Amplify Framework Version

2.21.1

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

5.9

### CLI version

11.1.1

### Xcode version

Version 15.0.1 (15A507)

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Platforms

_No response_

### OS Version

iOS 17.0.1

### Device

iPhone 13 pro

### Specific to simulators

_No response_

### Additional context

Xcode Version 15.0.1 (15A507)
![image](https://github.com/aws-amplify/amplify-swift/assets/1870075/3e47ff3b-8f18-4ace-90d2-5aacc727fe84)
![image](https://github.com/aws-amplify/amplify-swift/assets/1870075/028d279a-973c-419d-bc01-1abe964bf45f)

**Comment by atierian** [comment]
Thanks for opening this @mkrn. We're investigating.

**Comment by mkrn** [comment]
Thanks @atierian   
I suspected it's because of using openssl here https://github.com/awslabs/aws-crt-swift/blob/main/Source/LibCrypto/shim.h  which may have triggered the requirements for encryption documentation in France, but removing France from countries where app is available didn't solve it.

**Comment by atierian** [comment]
Do you have any other logs or messages that suggest it's coming from `aws-crt-swift`? If so, please include it here. I'm not seeing anything in the messages you provided that suggest it's coming from `aws-crt-swift`. 

From what I can tell, the `/LibCrypto/shim.h` you linked above is only included when built on Linux. [[reference](https://github.com/awslabs/aws-crt-swift/blob/main/Package.swift#L45-L55)]

I think this is most likely coming from `aws-c-cal`, an upstream dependency of `aws-crt-swift`.

**Comment by mkrn** [comment]
Downgrading solved it! Thanks.   FYI going forward it may be an issue in new versions

**Comment by atierian** [comment]
Glad to hear, thanks for confirming! And yes, this is just a workaround until we can resolve the issue on newer versions. We'll update this issue with any news.

**Comment by atierian** [comment]
I'm having some difficulties reproducing this. Can you please include some more details:
- Which targets are you linking to your app target? You can find these under `Your App Target > General > Frameworks, Libraries, and Embedded Content`
![frameworks-libraries-embdedded_content](https://github.com/aws-amplify/amplify-swift/assets/52051793/0a47512a-fcd8-42a1-9463-02ed5585c6f1)

- Which platforms does your app support, and what are the deployment targets?

- How are you uploading to AppStoreConnect? If you're doing the standard Archive + Distribute through Xcode, which option did you select here?
![distribute](https://github.com/aws-amplify/amplify-swift/assets/52051793/325303e3-1443-4a0c-9ba8-506e40ef2fc4)

**Comment by atierian** [comment]
### Adding some notes for reference.

1. Link all Amplify Swift products to app target.
2. Build app and navigate to build folder.
3. Run `for f in $(find . -name "*.o"); do echo "dumping $f"; objdump -t $f | grep CCCryptor; done`
```
dumping ./AwsCEventStream.o
dumping ./libtommathAmplify.o
dumping ./AWSAPIPlugin.o
dumping ./AwsChecksums.o
dumping ./AWSPolly.o
dumping ./AmplifyBigInteger.o
dumping ./AWSPinpointPushNotificationsPlugin.o
dumping ./Amplify.o
dumping ./AwsCHttp.o
dumping ./CoreMLPredictionsPlugin.o
dumping ./OrderedCollections.o
dumping ./AWSTranslate.o
dumping ./AwsCSdkUtils.o
dumping ./SQLiteObjc.o
dumping ./AwsCPlatformConfig.o
dumping ./AWSLocation.o
dumping ./XMLCoder.o
dumping ./InternalAWSPinpoint.o
dumping ./AWSTranscribeStreaming.o
dumping ./Logging.o
dumping ./ClientRuntime.o
dumping ./AppSyncRealTimeClient.o
dumping ./AwsCIo.o
dumping ./Starscream.o
dumping ./AWSCloudWatchLoggingPlugin.o
dumping ./AWSPinpoint.o
dumping ./AwsCCommon.o
dumping ./AWSPinpointAnalyticsPlugin.o
dumping ./AWSRekognition.o
dumping ./AWSPluginsCore.o
dumping ./AWSCloudWatchLogs.o
dumping ./SQLite.o
dumping ./AmplifySRP.o
dumping ./AWSTextract.o
dumping ./AwsCAuth.o
dumping ./DequeModule.o
dumping ./AWSS3StoragePlugin.o
dumping ./AWSCognitoAuthPlugin.o
dumping ./AwsCCompression.o
dumping ./AWSComprehend.o
dumping ./AWSLocationGeoPlugin.o
dumping ./AWSClientRuntime.o
dumping ./AWSS3.o
dumping ./AmplifyUtilsNotifications.o
dumping ./AWSDataStorePlugin.o
dumping ./AwsCCal.o
0000000000000000         *UND* _CCCryptorCreateWithMode
0000000000000000         *UND* _CCCryptorFinal
0000000000000000         *UND* _CCCryptorGCMAddAAD
0000000000000000         *UND* _CCCryptorGCMAddIV
0000000000000000         *UND* _CCCryptorGCMFinal
0000000000000000         *UND* _CCCryptorGCMFinalize
0000000000000000         *UND* _CCCryptorGCMSetIV
0000000000000000         *UND* _CCCryptorRelease
0000000000000000         *UND* _CCCryptorUpdate
dumping ./AWSPredictionsPlugin.o
dumping ./AwsCommonRuntimeKit.o
dumping ./AWSCognitoIdentity.o
dumping ./AWSCognitoIdentityProvider.o
dumping ./Collections.o
```

**Comment by atierian** [comment]
@mkrn could it be that your app target's scheme > Archive > Build Configuration is set to `Debug` instead of `Release`? That's the only way I can reproduce what you're seeing.
![archive_config](https://github.com/aws-amplify/amplify-swift/assets/52051793/f433dbe1-faa1-4a0d-9500-973a00ac353a)

**Comment by mkrn** [comment]
@atierian Archive is release, just retried with the new version it is happening still when trying to upload. 2.19.0 not

**Comment by atierian** [comment]
Thanks for confirming the Build Configuration. Can you please answer the questions from the [previous comment](https://github.com/aws-amplify/amplify-swift/issues/3324#issuecomment-1777682263)? That information will help in reproducing the issue. Thanks!

**Comment by maxchuquimia** [comment]
I have just experienced this after updating from 2.18.2 to 2.2.21 when uploading an archive via `xcrun altool --upload-app`. 

We link against the package from another Swift Package via our Package.swift.

**Comment by mkrn** [comment]
My app includes my framework which in turn uses Amplify via Package Manager 
![image](https://github.com/aws-amplify/amplify-swift/assets/1870075/a48f620c-4498-4e9f-ace7-f963b596d4b7)
![image](https://github.com/aws-amplify/amplify-swift/assets/1870075/e426d1f8-146b-4a5e-8454-30e9b26c24b3)
![image](https://github.com/aws-amplify/amplify-swift/assets/1870075/9c3d34f6-c07f-40a0-b376-f06d92a52dc9)

Uploading using XCode Archive + Distribute through Xcode=> TestFlight & App Store option 

Platforms & Deployment targets:
![image](https://github.com/aws-amplify/amplify-swift/assets/1870075/fdff5276-1a13-478d-a05e-b95f23f472c2)

**Comment by atierian** [comment]
Thanks for the details @mkrn.

And thanks @maxchuquimia for letting us know that you're also experiencing this. You mentioned:
> We link against the package from another Swift Package via our Package.swift.

Can you tell me some more about how this is setup -- is your app target dynamically linking a framework that contains Amplify?

**Comment by atierian** [comment]
I was able to reproduce by including Amplify (+ plugin targets) in a framework and linking that framework in my app target. We're continuing to investigate.

Two workarounds that are known at this time:
- Use Amplify Swift <= 2.19.0
- Statically link Amplify targets against your app instead of embedding them in a framework first.

**Comment by atierian** [comment]
linking related issue in `aws-crt-swift`
- https://github.com/awslabs/aws-crt-swift/issues/206

**Comment by maxchuquimia** [comment]
> Can you tell me some more about how this is setup -- is your app target dynamically linking a framework that contains Amplify?

Our app's Xcode project target doesn't contain all our app's code. Instead, we have a local Swift Package `MyApp` with our code (main scene, AppDelegate etc). The classes from `MyApp` are then used when our app launches.

`MyApp`'s Package.swift is what defines our dependency on Amplify:
```
products: [
    .library(
        name: "MyApp",
        type: .dynamic,
        targets: [
            "MyApp
        ]
    ),
],
dependencies: [
    .package(url: "https://github.com/aws-amplify/amplify-swift", exact: "2.18.2"),
    ...
]
```

**Comment by atierian** [comment]
Thanks @maxchuquimia. `type: .dynamic` linking is similar to using a wrapper `.framework` here in that the unused non-public symbols are being included in the framework within the app bundle.

The underlying cause has been addressed in `aws-c-cal` / `aws-crt-swift` and we're working on getting those updates into Amplify Swift. Here's the PR for reference:
- https://github.com/aws-amplify/amplify-swift/pull/3333

We'll update here once this is merged and Amplify Swift has been released. Thanks to both of you for reporting this and your assistance in reproducing it.

**Comment by atierian** [comment]
[Amplify Swift 2.21.3](https://github.com/aws-amplify/amplify-swift/releases/tag/2.21.3) was released with a fix resolving this issue.
Thanks again to both of @mkrn  and @maxchuquimia for reporting this!
