### ISSUE TITLE
Adopt Apple Privacy Manifest and describe use of required reason APIs that are being used by the SDK

### ISSUE THREAD

**Issue by SwiftNativeDeveloper** [aws-amplify/amplify-swift#3327]
### Is your feature request related to a problem? Please describe.

The SDK doesn't disclose in the new Privacy Manifest what purposes it uses the new required reason APIs. When Apple starts sending notices out to teams, lots of the usage is going to originate from your SDK. Apple states on their developer page that they will start notifying teams that are using 'required reason' APIs Fall 2023. App submissions will be rejected in Spring 2024.

### Describe the solution you'd like

Implement Apple's new Privacy Manifest which has been a think since Xcode 15 this fall (summer if counting beta).

Specifically, implement the required reason usage part. Even usage of UserDefaults will flag an app as needing to disclose why it uses that API. 

Check the full list of affected APIs and description of the manifest changes here: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#

Related to #3326

### Describe alternatives you've considered

There isn't any alternatives for this one.

**Comment by atierian** [comment]
Privacy Manifests were added in [2.21.5](https://github.com/aws-amplify/amplify-swift/releases/tag/2.21.5)
Thanks for opening this issue.
