### ISSUE TITLE
Unable to sign in using Federated Identity Provider Azure-AD through signInWithWebUI

### ISSUE THREAD

**Issue by dsakhapo** [aws-amplify/amplify-swift#3329]
### Describe the bug

Hello Amplify Team,

I'm unable to use the amplify-cli due to my level of access, so I have created the `amplifyconfiguration.json` according to the documentation listed here:  [https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios/#prerequisites](https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios/#prerequisites)

Here is my config:

```
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "[POOL ID]",
            "AppClientId": "[APP CLIENT ID]",
            "AppClientSecret": "[APP CLIENT SECRET]",
            "Region": "[REGION]"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH",
            "OAuth": {
              "WebDomain": "https://[ENV]-[APP NAME].auth.[REGION].amazoncognito.com",
              "AppClientId": "[CLIENT ID]",
              "SignInRedirectURI": "myapp://",
              "SignOutRedirectURI": "myapp://",
              "Scopes": [
                "email",
                "openid"
              ],
              "ResponseType": "code"
            }
          }
        }
      }
    }
  }
}
```

Inside my application, this is how I'm calling `signInWithWebUI` :

```swift
func socialSignInWithWebUI(window: UIWindow) async {
        do {
            let signInResult = try await Amplify.Auth.signInWithWebUI(for: .saml("Azure-AD"), presentationAnchor: window)
            if(signInResult.isSignedIn) {
                print("Sign in succeeded.")
            }
        } catch let error {
            print("Unexpected error: \(error)")
        }
}
```

I looked through documentation to see if I'm even using the right approach (that is, using `signInWithWebUI`) and I found these pages referring to federation identities:

- Identity Pool Federation (Advanced Workflows): [https://docs.amplify.aws/lib/auth/advanced/q/platform/ios/](https://docs.amplify.aws/lib/auth/advanced/q/platform/ios/)
- Federated Identities [https://docs.amplify.aws/sdk/auth/federated-identities/q/platform/ios/](https://docs.amplify.aws/sdk/auth/federated-identities/q/platform/ios/)

The last reference being a little older but the issue is that I'm not using an Identity Pool - is it required in this scenario? I wasn't able to find any concrete information about this.

Lastly, accessing the Hosted UI through the console works just fine and so does Postman when I set up the `Authorization` section and filled in the proper values.

If I could please receive some assistance regarding this issue it would be greatly appreciated - thank you.

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Create a Cognito User Pool
2. Create a Federated Identity Provider of type SAML
3. Create an app client with an app client secret
4. Create a Hosted UI with the IdP and appropriate callback URLs
5. Set up an amplifyconfiguration.json without using the amplify cli
6. Call the signInWithWebUI api
```

### Expected behavior

I expect for a modal view to open and display the Hosted UI I'm seeing in the desktop browsers I've tested in, so that the user can enter in their credentials in Azure and be redirected according to the URL Scheme I've designated.

### Amplify Framework Version

2.16.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5

### CLI version

N/A

### Xcode version

15.0.1 (15A507)

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


2023-10-25 21:43:22.897470-0700 AppName[47208:3645645] [Amplify] Configuring
2023-10-25 21:43:22.924388-0700 AppName[47208:3645645] [Amplify] Could not find Cognito Identity Pool configuration
2023-10-25 21:43:22.937836-0700 AppName[47208:3645645] [Amplify] Successfully initialized Amplify
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Platforms

iOS

### OS Version

iOS 16.0

### Device

iPhone 14 Pro Max

### Specific to simulators

iPhone 13 Pro Simulator

### Additional context

I'm receiving this popup once the api call is triggered:


<img width="220" alt="api-popup" src="https://github.com/aws-amplify/amplify-swift/assets/15305936/6305bdbd-2363-4a48-887f-2b00b294cecf">

This is the modal that appears once I proceed:


<img width="386" alt="modal-error" src="https://github.com/aws-amplify/amplify-swift/assets/15305936/6a283dd6-e4f8-4a0c-99ce-a30597c06c33">

**Comment by phantumcode** [comment]
@dsakhapo Thanks for submitting your issue, we'll investigate further and get back to you soon.

**Comment by dsakhapo** [comment]
@phantumcode Thank you I appreciate it.

**Comment by dsakhapo** [comment]
I was able to solve my issue, as I suspected my `amplifyconfiguration.json` was missing some fields. This is my working config:

```
{
  "auth": {
    "plugins": {
      "awsCognitoAuthPlugin": {
        "IdentityManager": {
          "Default": {}
        },
        "CognitoUserPool": {
          "Default": {
            "PoolId": "[POOL ID]",
            "AppClientId": "[APP CLIENT ID]",
            "AppClientSecret": "[APP CLIENT SECRET]",
            "Region": "[REGION]"
          }
        },
        "Auth": {
          "Default": {
            "authenticationFlowType": "USER_SRP_AUTH",
            "OAuth": {
              "WebDomain": "[ENV]-[APP NAME].auth.[REGION].amazoncognito.com",
              "TokenURI": "https://[ENV]-[APP NAME].auth.[REGION].amazoncognito.com/oauth2/token",
              "SignInURI": "https://[ENV]-[APP NAME].auth.[REGION].amazoncognito.com/oauth2/authorize",
              "AppClientId": "[CLIENT ID]",
              "AppClientSecret": "[APP CLIENT SECRET]",
              "SignInRedirectURI": "myapp://",
              "SignOutRedirectURI": "myapp://",
              "Scopes": [
                "email",
                "openid"
              ],
              "ResponseType": "code"
            }
          }
        }
      }
    }
  }
}
```

The added fields being `TokenURI`, `SignInURI`,  and `AppClientSecret` to the `OAuth` section. 

I was only able to find my needed fields through what seems to be older documentation: [https://docs.amplify.aws/sdk/auth/hosted-ui/q/platform/ios/#signing-out-via-the-hosted-ui](url)

I think it would be very helpful if the template provided in the newer documentation either included these fields or mentioned them:
[https://docs.amplify.aws/lib/auth/getting-started/q/platform/ios/#set-up-backend-resources](url)

Lastly, while I see many social providers mentioned, I did not see any mention of SAML providers in the below page which I think would useful as I began to doubt whether I was using the right api call which the older documentation mentions above:

[https://docs.amplify.aws/lib/auth/social/q/platform/ios/](url)

**Comment by phantumcode** [comment]
@dsakhapo Thanks for the feedback.  We'll add to our backlogs work items to update our documentation and template.  We recommend to use Amplify CLI to manage your configuration when possible so that all configurations are configured properly via the CLI questionnaires based on your use case and avoid typo and other errors that could be introduced through manual edits.
