### ISSUE TITLE
Amplify Pull Always Failed in Xcode Run Script

### ISSUE THREAD

**Issue by bevanchristian** [aws-amplify/amplify-swift#3332]
### How did you install the Amplify CLI?

curl -sL https://aws-amplify.github.io/amplify-cli/install | bash

### If applicable, what version of Node.js are you using?

v18.16.0

### Amplify CLI Version

12.1.1

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

no i use default model (todo)

### Describe the bug

I have an Xcode project that will implement Amplify GraphQL, and I intend to pull the schema and regenerate the queries every time the application is built to obtain the latest schema. And this script works as desired when run in a regular terminal. However, when I run it as an Xcode run script, I always encounter errors. Here is the bash.script

And I found that the amplify pull command is causing the error, while the amplify codegen command runs normally when I comment out amplify pull.

```
set -e
cd ${PROJECT_DIR}
# Run Amplify commands
amplify="/Users/.amplify/bin/amplify"
IFS='|'

# Check if Amplify CLI is installed
if ! command -v "$amplify" &>/dev/null; then
    echo "Amplify CLI not found. Installing..."
    if ! curl -sL https://aws-amplify.github.io/amplify-cli/install | bash; then
        echo "Failed to install Amplify CLI."
    fi
else
    echo "Amplify CLI found."
fi


CODEGEN="{\
\"generateCode\":true,\
\"codeLanguage\":\"swift\",\
\”fileNamePattern\”:\”graphql/**/*.graphql\”,\
\"generatedFileName\":\"API\",\
\"generateDocs\":true\,
\”maxDepth\”:2\
}"

SWIFTCONFIG="{\
\"SourceDir\":\"src\",\
\"XcodeProject\":\"MyProject.xcodeproj\",\
\"BuildCommand\":\"xcodebuild\",\
\"StartCommand\":\"swift run\"\
}"

AWSCLOUDFORMATIONCONFIG="{\
\"configLevel\":\"project\",\
\"useProfile\":false,\
\"profileName\":\"default\",\
\"accessKeyId\":\"xxxxx\",\
\"secretAccessKey\":\"xxxxxxxx+\",\
\"region\":\"us-east-1\"\
}"
AMPLIFY="{\
\"projectName\":\"xxxx\",\
\"appId\":\"xxxxx\",\
\"envName\":\"dev\",\
\"defaultEditor\":\"xcode\"\
}"

FRONTEND="{\
\"frontend\":\"ios\"
}"

PROVIDERS="{\
\"awscloudformation\":$AWSCLOUDFORMATIONCONFIG\
}"
# Run Amplify pull command
environment=""

# Set the environment based on the CONFIGURATION variable
if [ "$CONFIGURATION" == "Production" ]; then
  environment="dev"
  echo "Current environment: Production"
elif [ "$CONFIGURATION" == "Staging" ]; then
  environment="dev"
  echo "Current environment: Staging"
else
  environment="dev"
  echo "Invalid environment. Exiting."
  exit 1
fi


echo "Fetching changes from backend..."
"$amplify" pull \
  --yes \
  --debug \
  --restore \
  --amplify "$AMPLIFY" \
  --frontend "$FRONTEND" \
  --providers "$PROVIDERS"



# Check if Amplify pull succeeded
if [ $? -eq 0 ]; then
  echo "Amplify pull succeeded."
else
  echo "Amplify pull failed. Check the error logs for more information."
  exit 1
fi

# ReGenerate code model, schema, and query
"$amplify" codegen \
  --config "$CODEGEN" \
  --statements \
  --model \
  --yes

# Check if code generation succeeded
if [ $? -eq 0 ]; then
  echo "Code generation succeeded."
else
  echo "Code generation failed. Check the error logs for more information."
  exit 1
fi

echo "Amplify project configured for iOS."

```

This is the error
<img width="715" alt="Screen Shot 2023-07-09 at 18 32 36" src="https://github.com/aws-amplify/amplify-cli/assets/50088801/8fe90857-834f-4a53-bc31-da9053289871">

### Expected behavior

- amplify pull works pefectly fine in run script

### Reproduction steps

- add script to build phase, before compile sources
- add this code

<img width="1275" alt="Screen Shot 2023-07-09 at 18 36 43" src="https://github.com/aws-amplify/amplify-cli/assets/50088801/b4667a35-c876-4db4-978d-250a54637674">

- and build will failed

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by phantumcode** [comment]
@bevanchristian Are you able to unblock yourself once your script is moved out of the Xcode build phase?
