### ISSUE TITLE
Unexpected sessionExpired error.

### ISSUE THREAD

**Issue by myeyesareblind** [aws-amplify/amplify-swift#3344]
### Describe the bug

We are using cognito userpools with APIPlugin,
here is the config:

```
{
    "UserAgent": "aws-amplify-cli/2.0",
    "Version": "1.0",
    "api": {
        "plugins": {
            "awsAPIPlugin": {
                "rest-api": {
                    "endpointType": "REST",
                    "endpoint": "https://xxxxxx",
                    "region": "eu-west-1",
                    "authorizationType": "OPENID_CONNECT"
                },
            }
        }
    },
    "auth": {
        "plugins": {
            "awsCognitoAuthPlugin": {
                "UserAgent": "aws-amplify/cli",
                "Version": "0.1.0",
                "IdentityManager": {
                    "Default": {}
                },
                "CognitoUserPool": {
                    "Default": {
                        "PoolId": "xxxxx",
                        "AppClientId": "xxxxx",
                        "Region": "eu-west-1"
                    }
                },
                "Auth": {
                    "Default": {
                        "OAuth": {
                            "WebDomain": "xxxxx",
                            "AppClientId": "xxxxxx",
                            "SignInRedirectURI": "xxxx",
                            "SignOutRedirectURI": "xxxxx",
                            "ResponseType": "Code",
                            "Scopes": [
                                "openid",
                                "email",
                                "profile",
                                "phone",
                                "aws.cognito.signin.user.admin"
                            ]
                        },
                        "authenticationFlowType": "USER_SRP_AUTH"
                    }
                }
            }
        }
    }
}
```

at some point,
clients might receive [AuthError.sessionExpired](https://github.com/aws-amplify/amplify-swift/blob/2604241a75bf96fe1185e0abb4f7cf905a697d42/Amplify/Categories/Auth/Error/AuthError.swift#L35)

Our refreshToken expiration is set to 548days, so it cannot expire. 
We naturally don't expect this error to happen, but here we are.
It seem to be affecting a small group of users (<1%), but it's still quite inconvenient.

[Looking at the code](https://github.com/aws-amplify/amplify-swift/blob/2604241a75bf96fe1185e0abb4f7cf905a697d42/AmplifyPlugins/Auth/Sources/AWSCognitoAuthPlugin/Actions/FetchAuthorizationSession/InformSessionError.swift#L39), seem amplify treats all the nonAuthorised errors as 'sessionExpired'.
Would it be possible to add more shadows to this error or propagate underlying error to the client?

Note: 
Since this happened to our internal team member, we know that it wasn't caused by 'global' sign out.

# Why it's important
We are forcing users to relogin, while the error seem to be temporary/intermittent by the look of things.

### Steps To Reproduce

```swift
Wish I knew
```

### Expected behavior

Do not receive '.sessionExpired' error.

### Amplify Framework Version

2.19.0

### Amplify Categories

API, Auth

### Dependency manager

Swift PM

### Swift version

5.9

### CLI version

12.1.1

### Xcode version

14.3.1

### Relevant log output

```shell
2023/11/01 12:55:51:115  APIError: Es besteht anscheinend keine Verbindung zum Internet.
Recovery suggestion: Es besteht anscheinend keine Verbindung zum Internet.
Caused by:
Error Domain=NSURLErrorDomain Code=-1009 "Es besteht anscheinend keine Verbindung zum Internet." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x600001e261c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_NSURLErrorNWPathKey=unsatisfied (No network route), _kCFStreamErrorCodeKey=50, _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <20673331-0896-441A-8B24-C1D60F5B0799>.<43>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <20673331-0896-441A-8B24-C1D60F5B0799>.<43>"
), NSLocalizedDescription=Es besteht anscheinend keine Verbindung zum Internet., NSErrorFailingURLStringKey=https://xxxx, NSErrorFailingURLKey=https://xxxx, _kCFStreamErrorDomainKey=1}

/// some network operations went through in-between, and then eventually:

2023/11/01 13:39:37:645  APIError: Failed to retrieve authorization token.
Caused by:
AuthError: Session expired could not fetch cognito tokens
Recovery suggestion: Invoke Auth.signIn to re-authenticate the user
```
```


### Is this a regression?

No

### Regression additional context

_No response_

### Platforms

iOS, macOS

### OS Version

iOS 16

### Device

iPhone X

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by myeyesareblind** [comment]
thanks @harsh62 .
Will try to collect more logs (together with details of NotAuthorizedException) and will get back.

**Comment by myeyesareblind** [comment]
sadly I couldn't get the verbose logs. But we did log the error that seem to cause this:

```
"description": "AWSCognitoAuthPlugin/InformSessionError.swift Starting execution, error: service(ClientRuntime.SdkError<AWSCognitoIdentityProvider.InitiateAuthOutputError>.client(ClientRuntime.ClientError.retryError(ClientRuntime.SdkError<AWSCognitoIdentityProvider.InitiateAuthOutputError>.service(AWSCognitoIdentityProvider.InitiateAuthOutputError.notAuthorizedException(AWSCognitoIdentityProvider.NotAuthorizedException(_headers: Optional(Content-Type: application/x-amz-json-1.1, \nx-amzn-RequestId: c9982878-aef6-488b-b297-450fa04245e5, \nx-amzn-ErrorType: NotAuthorizedException:, \nx-amzn-ErrorMessage: Refresh Token has been revoked, \nConnection: keep-alive, \nDate: Tue, 14 Nov 2023 07:36:11 GMT, \nContent-Length: 78), _statusCode: Optional(http_status_400), _message: Optional(\"Refresh Token has been revoked\"), _requestID: Optional(\"c9982878-aef6-488b-b297-450fa04245e5\"), _retryable: false, _isThrottling: false, _type: ClientRuntime.ErrorType.client, message: Optional(\"Refresh Token has been revoked\"))), \nStatus Code: http_status_400 \n x-amzn-RequestId: c9982878-aef6-488b-b297-450fa04245e5, \nx-amzn-ErrorMessage: Refresh Token has been revoked, \nx-amzn-ErrorType: NotAuthorizedException:, \nDate: Tue, 14 Nov 2023 07:36:11 GMT, \nContent-Length: 78, \nContent-Type: application/x-amz-json-1.1, \nConnection: keep-alive)), nil))"
```

there are more, only attaching x-amzn-RequestIds, as they are otherwise identical. (These all from different users)
c70d6dcb-e8ce-43ef-937c-a8facdbb15f5
c6fc4762-d3c6-43b4-8af5-f5fdf89e0488
61981a8f-9470-492c-8f31-4d1e8f5f3ce7
ea0477e1-9914-4448-8faa-83b21c6d377d
2eae21f7-e5cc-4c0c-b862-657708f500a3
202d61bb-844a-4ae9-8896-742959fff5fd
61981a8f-9470-492c-8f31-4d1e8f5f3ce7
8eb647e4-8393-4e09-9080-5f9e2c1bf414
2f7da1ec-b416-472a-9bf5-5542bc38d909
dc5bae98-7dc2-4e2c-b998-cfdcda302c39
8706b66c-5dd6-47b7-a2e0-850602d793e5
e8e2c8f2-44d7-4ca9-8271-02b0499f3e73
995d1a28-ed93-4154-a191-de89879e7f44
a2822d32-7843-4ca8-8ef6-21e9adcf96e4
0040903d-7383-4e78-a7f8-ef07aea60ce4
a8665faa-6939-435c-90d8-086b12a77ddb
1a3e419c-818d-4815-93fe-4f99a4d9ff38
32375de3-b748-4b69-9bad-491644c8ed44
d80d0f7a-ae35-407f-839a-577849112924
04943c00-7c50-4514-aa8a-4018580ef0c3
c404574f-02e1-4c13-9c59-1878a7c0a9ed

Our app does use `signOut(globally: true)`, but from the tracking that we have it looks like the number of users who get this error is much higher than the number of users who signOut-globally.
Do you happen to know if Cognito can issue this 'notAuthorizedException' in other cases?

**Comment by myeyesareblind** [comment]
we don't use any custom scopes and the issue happens randomly, not consistently

**Comment by myeyesareblind** [comment]
> Is Swift the only platform this is happening in? Do you use any other libraries such as Android, JS in which this issue has also been noticed? Are you able to find any commonalities between the users facing these issues?

sadly we only have iOS/mac-catalyst

> Also if you can share when it started happening, I can go back in the history and look at changes that were done.

It's likely that this has been happening for awhile now. We've launched this functionality in the September 2023 and it's been happening right from the beginning. 
We had a different issue (I've also reported it here) with key-chain sharing and multi-apps, so it's not trivial to untangle this.

**Comment by 5d** [comment]
Sorry @myeyesareblind , we are unable to replicate the issue you're experiencing. To facilitate further investigation, could you provide additional details, logs, or stacktraces from your end?

**Comment by myeyesareblind** [comment]
Hi @5d ,
yesterday this happened to one of our engineers.
He was using the app and all of a sudden got logged out. (He did NOT use Amplify global logout at any point).
This time we had logs from iOS app and some logs from the WebApp.

Let me give a bit more context on how auth works in our app:
we have a frontend (Vue.js, but it doesn't matter), which is opened in a UIWebView inside the app.
When user authenticates with email/password, we login with Amplify.JavaScript-SDK and forward the tokens to the app.
WebApp then finishes and executes logout.

Now, from the logs we have found that the 'logout' part seem to be repeated multiple times. E.g. WebView got leaked and was executing 'logout' requests rapidly & multiple times.

If we spam Cognito with SignOut requests, will this result into the exception below?
```
|AWSCognitoAuthPlugin|[Authentication] AWSCognitoAuthPlugin/InformSessionError.swift Starting execution, error: service(ClientRuntime.SdkError<AWSCognitoIdentityProvider.InitiateAuthOutputError>.client(ClientRuntime.ClientError.retryError(ClientRuntime.SdkError<AWSCognitoIdentityProvider.InitiateAuthOutputError>.service(AWSCognitoIdentityProvider.InitiateAuthOutputError.notAuthorizedException(AWSCognitoIdentityProvider.NotAuthorizedException(_headers: Optional(x-amzn-ErrorType: NotAuthorizedException:, 
Content-Type: application/x-amz-json-1.1, 
x-amzn-RequestId: 678341f4-b6ec-4e59-a132-7e1cae1c4236, 
x-amzn-ErrorMessage: Refresh Token has been revoked, 
Content-Length: 78, 
Date: Mon, 04 Dec 2023 14:52:46 GMT, 
Connection: keep-alive), _statusCode: Optional(http_status_400), _message: Optional("Refresh Token has been revoked"), _requestID: Optional("678341f4-b6ec-4e59-a132-7e1cae1c4236"), _retryable: false, _isThrottling: false, _type: ClientRuntime.ErrorType.client, message: Optional("Refresh Token has been revoked"))), 
Status Code: http_status_400 
 Content-Type: application/x-amz-json-1.1, 
Connection: keep-alive, 
Content-Length: 78, 
Date: Mon, 04 Dec 2023 14:52:46 GMT, 
x-amzn-RequestId: 678341f4-b6ec-4e59-a132-7e1cae1c4236, 
x-amzn-ErrorMessage: Refresh Token has been revoked, 
x-amzn-ErrorType: NotAuthorizedException:)), nil))
```
this is the exception from iOS app. Unfortunately, we don't have detailed logs from the WebApp. We just know that 'signOut' was issued multiple times with 50ms delay between the calls.

We only have error-level amplify logs, unfortunately:
[other-amplify-logs.txt](https://github.com/aws-amplify/amplify-swift/files/13598084/other-amplify-logs.txt)

**Comment by myeyesareblind** [comment]
> How do you forward the tokens from the webView to the app?

over https://developer.apple.com/documentation/webkit/wkscriptmessagehandler/1396222-usercontentcontroller.
Basically JS makes a callback to the iOS app.

> And then how are these tokens supplied to Amplify Swift?

we have a patched version of the Amplify that exposes the API to set the tokens directly.
I'm aware of the AWSCognitoAuthPlugin#signIn(username: String?, password: String?, options: AuthSignInRequest.Options?). IDK why it wasn't used when this was implemented.

> After logging in and passing the tokens to the app, why do you logout? What is the use case/reasoning behind this logic?

that's a bug. It actually looks like an underlying issue we were after and I'll be closing this thread.
The 'signIn' flow is multi-step process where user is expected to set it's name and other settings. During that, he can also 'discard' current info and jump back to the 'register' page, which should signout the current-user. 
So it's reasonable to have it there, but it's unexpected that it's executed after the successful form completion.

> How were you able to come to this conclusion? Using web app logs?

yes. We joined web-logs of the user and ios-logs.

> Yes. The refresh tokens get revoked.

and this is the bug we were after.
I'm very grateful for your involvement into this & grateful for the tips. I'll be closing the thread folks.

**Comment by Shilaghae** [comment]
Hi, we are experiencing something similar in our app, and are very interested in understanding whether this issue was solved and how @myeyesareblind any update you might give us, you are more than welcome!

**Comment by myeyesareblind** [comment]
Hi, @Shilaghae . Yes it was resolved, see my answer above https://github.com/aws-amplify/amplify-swift/issues/3344#issuecomment-1846889211. In a nutshell, we misused the API.

**Comment by Shilaghae** [comment]
Sorry I missed that last message :(
