### ISSUE TITLE
Amplify PluginError: Could not cast incoming configuration to JSONValue

### ISSUE THREAD

**Issue by shriramBaNW** [aws-amplify/amplify-swift#3361]
### Describe the bug

When trying to initialize amplify via:

 do {
            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            try Amplify.add(plugin: AWSAPIPlugin())
            try Amplify.add(plugin: AWSS3StoragePlugin())
            try Amplify.configure()
            print("Amplify configured successfully")
            completionHandler(true)
        } catch {
            print("could not initialize Amplify", error)
            completionHandler(false)
        }
        
  I get the log output included later in this report

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Install Amplify CLI and add Amplify packages to XCode project
2. Configure Amplify and create a new user as per provided instructions
3. Pull an existing environment 
4. Run in Xcode
```

### Expected behavior

Amplify is configured and can be used

### Amplify Framework Version

2.22.0

### Amplify Categories

Auth, DataStore, Geo, Storage

### Dependency manager

Swift PM

### Swift version

5.8

### CLI version

12.5.0

### Xcode version

14.3

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


could not initialize Amplify PluginError: Could not cast incoming configuration to JSONValue
Recovery suggestion: The specified configuration is either nil, or not convertible to a JSONValue. Review the configuration and ensure it contains the expected values, and does not use any types that aren't convertible to a corresponding JSONValue:

```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Platforms

iOS

### OS Version

16.4

### Device

Iphone 14

### Specific to simulators

No

### Additional context

_No response_

**Comment by atierian** [comment]
Hey @shriramBaNW, thanks for opening this issue.

Do you have an `ampliifyconfiguration.json` file in your project? If so, is it included in the target membership of your app target?
 
If the answer to both of those questions is "yes", then please paste the contents of your `amplifyconfiguration.json` file here. Thanks!

**Comment by shriramBaNW** [comment]
Hey! 

The configurations files were there, but it seems like I had forgot to add the API through the CLI and was trying to add the API plugin! Sorry about that!

**Comment by atierian** [comment]
No worries, glad you figured it out!
