### ISSUE TITLE
Using Amplify.API.mutate(request: .update(object)) always appends to arrays

### ISSUE THREAD

**Issue by dacarson** [aws-amplify/amplify-swift#3366]
### Describe the bug

When my object contains an array that I add and remove items from, then `update`, the current array items are appended to the items stored in the database, rather than replace the items in the database.
If this is correct functionality, how do I remove specific (or all) items from the array?

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Create a schema like:
type User @model @auth(rules: [{ allow: private }]) {
  id: ID!
  name: String!
  listId: [ID]
}

2. Follow steps to push and codgen the classes

3. Create a User object, eg:
user = User(name: "Joe")
user.listId = ["String"]

4. Create it, eg:
Amplify.API.mutate(request: .create(user))

5. Modify it:
user.listId.append("String2")

6. Update it:
Amplify.API.mutate(request: .update(user))

The returned `user` has 3 items in the listId array now:
["String", "String", "String2"]
```

### Expected behavior

I would expect that the in memory User object would be identical to the on disk User object.

### Amplify Framework Version

2.19.0

### Amplify Categories

API, DataStore

### Dependency manager

Swift PM

### Swift version

5.9

### CLI version

12.8.2

### Xcode version

15.0.1 (15A507)

### Is this a regression?

No

### Platforms

iOS

### OS Version

iOS 17.0

### Device

iPhone 15 Pro

**Comment by atierian** [comment]
Hi @dacarson, I'm not able to reproduce this issue from the example you provided.
```swift
var user = User(name: "Joe")
user.listId = ["String"]
// User(id: "D134EC2F-82D3-47BC-BBA1-E16A9154CD88", name: "Joe", listId: ["String"])

let created = try await Amplify.API.mutate(request: .create(user))
// User(id: "D134EC2F-82D3-47BC-BBA1-E16A9154CD88", name: "Joe", listId: ["String"], createdAt: ..., updatedAt: ...)

user.listId?.append("String2")
// User(id: "D134EC2F-82D3-47BC-BBA1-E16A9154CD88", name: "Joe", listId: ["String", "String2"])

let updated = try await Amplify.API.mutate(request: .update(user))
// User(id: "D134EC2F-82D3-47BC-BBA1-E16A9154CD88", name: "Joe", listId: ["String", "String2"], createdAt: ..., updatedAt: ...)
```


Can you confirm that you're still experiencing this issue on the most recent version of Amplify Swift -- currently [2.25.0](https://github.com/aws-amplify/amplify-swift/releases/tag/2.25.0)

If so, please include the contents of your `amplifyconfiguration.json` file here. Additionally, let us know if you have conflict resolution enabled and which mode. Thanks!
