### ISSUE TITLE
Enable AWS S3 Transfer acceleration for Amplify SDK 

### ISSUE THREAD

**Issue by Ankish** [aws-amplify/amplify-swift#3380]
**State your question**
Enable AWS S3 Transfer acceleration for Amplify SDK request or provide a alternative way to implement the same with AWS SDK.

**Which AWS Services are you utilizing?**
AWS / Amplify / iOS SDK

**Provide code snippets (if applicable)**
Currently using Amplify to upload file:

 let option = StorageUploadFileRequest.Options(accessLevel: StorageAccessLevel.private, targetIdentityId: nil,
                                                      metadata: [Utils.createTimeStampKey : "\(createTime)"], contentType: nil, pluginOptions:nil)
        
 Amplify.Storage.uploadFile(key: videoId, local: localURL, options: option, progressListener: { progress

**Environment(please complete the following information):**
 - Amplify SDK Version: 2.33.1
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: All
 - iOS Version: All
 - Specific to simulators: No

How can I migrate this to use with S3 Acceleration code with access level and metadata information ?

If you need help with understanding how to implement something in particular then we suggest that you first look into our [developer guide](https://docs.aws.amazon.com/aws-mobile/latest/developerguide/aws-mobile-android-and-iOS.html). You can also simplify your process of creating an application, as well as the associated backend setup by using the [Amplify CLI](https://aws-amplify.github.io/media/get_started).

**Comment by ruisebas** [comment]
The [**Use transfer acceleration**](https://docs.amplify.aws/swift/build-a-backend/storage/transfer-acceleration/) section has been added to the **Amplify Documentation for Swift** site.

**Comment by Ankish** [comment]
```
let options = StorageUploadFileRequest.Options(
    accessLevel: .private,
    targetIdentityId: nil,
    metadata: [
        Utils.createTimeStampKey : "(createTime)"
    ],
    contentType: nil,
    pluginOptions: [
        "useAccelerateEndpoint": true
    ]
)
let task = Amplify.Storage.uploadFile(
    key: videoId,
    local: localURL,
    options: options
)
``` 
Confirming, This is not supported in Amplify V1 ? I am using V1 and updated with above code and this does not throw any error.

**Comment by ruisebas** [comment]
Yes, this is only supported in Amplify v2.
Setting `"useAccelerateEndpoint": true` in `pluginOptions` has no effect in Amplify v1.

**Comment by Ankish** [comment]
The issue now is Amplify SPM and AWS SPM both does not work in same project, there is an open issue already on AWS.
So I need to use AWS Sdk for uploading via transfer acceleration. Do you have sample code or an example to migrate this code with AWS SDK with transfer acceleration? As stated in this ticket. Need to enable the acceleration while we work on complete migration to V2. Thanks  !

```
let option = StorageUploadFileRequest.Options(accessLevel: StorageAccessLevel.private, targetIdentityId: nil,
metadata: [Utils.createTimeStampKey : "(createTime)"], contentType: nil, pluginOptions:nil)

Amplify.Storage.uploadFile(key: videoId, local: localURL, options: option, progressListener: { progress
```

This is how we initialise the configuration:
```
///configure the amplify if it is not done previously
    @discardableResult
    public func configureIfNeeded() -> Result<Any, Error>? {
        guard !AmplifyUtil.isAmplifyConfigured else {
            return nil
        }
        
        do {
            let apiPlugin = AWSAPIPlugin(apiAuthProviderFactory: MyAPIAuthProviderFactory())
            let storagePlugin = AWSS3StoragePlugin()
            let logging = AWSUnifiedLoggingPlugin()
            #if COACHDEBUG
            AWSDDLog.sharedInstance.logLevel = .debug
            AWSLogger.default().logLevel = .debug
            #endif
            try Amplify.add(plugin: apiPlugin)
            try Amplify.add(plugin: storagePlugin)
            try Amplify.add(plugin: logging)
            try Amplify.add(plugin: AWSCognitoAuthPlugin())
            
            ///can configure here target's configuration file from which configuaration need to read
            guard let path = Bundle.main.path(forResource: amplifyConfigurationFileName, ofType: "json") else {
                return Result.failure(GeneralError.generalError(NSLocalizedString("not able to read amplify configuration file", comment: ""),nil))
            }
            
            let configurationData = try Data(contentsOf: URL(fileURLWithPath: path), options: .mappedIfSafe)
            let configurationResult = try JSONSerialization.jsonObject(with: configurationData, options: .mutableLeaves)
            
            ///gets the api and storage plugins
            guard let result = configurationResult as? [String:Any],
                let apiConfig = getApiConfiguration(configuration: result),
                let storageConfig = getStorageConfiguration(configuration: result),
                let autConfig = getAuthConfiguration() else {
                    return Result.failure(GeneralError.generalError(NSLocalizedString("not able to read api or storage values from configuration file", comment: ""),nil))
            }
            
            let config = AmplifyConfiguration(api: apiConfig, auth: autConfig, storage: storageConfig)
            try Amplify.configure(config)
            
            AmplifyUtil.isAmplifyConfigured = true
        } catch let error {
            print(error.localizedDescription)
            return Result.failure(GeneralError.generalError(NSLocalizedString("unknown error occured during configuration. Please try again", comment: ""),nil))
        }
        
        return nil
    }
    ```

**Comment by Ankish** [comment]
@ruisebas  :  Help would be greatly appreciated. I know there are samples but I am not able to find a AWS replacement for my above amplify 1.0 code.
