### ISSUE TITLE
Subscribe to real-time events Documentation Incorrect?

### ISSUE THREAD

**Issue by Etep15** [aws-amplify/amplify-swift#3391]
### Describe the bug

I'm looking at the documentation here

https://docs.amplify.aws/swift/build-a-backend/graphqlapi/subscribe-data/

I've tried both the Async/Await method and combine methods and both have issues.

Async/Await I get an error Cannot find type 'AmplifyAsyncThrowingSequence' in scope.

With the Combine method I get Type 'Amplify' has no member 'Publisher'.

What am I missing?

### Steps To Reproduce

```swift
Copy the examples from the documentation into a swift file with the rest of the relevant imports and setup. Compilation errors will show.
```

### Expected behavior

It should compile. 

### Amplify Framework Version

Latest, I just did a pod update

### Amplify Categories

API

### Dependency manager

Cocoapods

### Swift version

5

### CLI version

12.8.2

### Xcode version

15.0.1 (15A507)

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


Cannot find type 'AmplifyAsyncThrowingSequence' in scope

OR

Type 'Amplify' has no member 'Publisher'.
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Platforms

iOS

### OS Version

iOS 17.1

### Device

iPhone 12Pro

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by 5d** [comment]
Hi @Etep15, thanks for opening this issue. I will take a look of this tomorrow and will follow up with you soon.

**Comment by ruisebas** [comment]
Hi @Etep15! You mentioned `pod update`, so this means you're using Amplify **v1**. However, it seems you are looking at **v2**'s documentation.

You can click the **v1** button next to Swift to select the proper version.
<img width="320" alt="image" src="https://github.com/aws-amplify/amplify-swift/assets/97059974/e447cfac-ea2b-4b8e-97ca-c984855f6e6a">

**Comment by Etep15** [comment]
Thanks @ruisebas I honestly thought I was working with v2. But apparently not. Is v2 only supported by the Swift Package Manager?
