### ISSUE TITLE
Document amplifyconfiguration.json format or schema for push notification plugin configuration.

### ISSUE THREAD

**Issue by sungwonshinn** [aws-amplify/amplify-swift#3410]
### Describe the bug

Amplify doesn't document the AWSPinpointPushNotificationsPlugin configuration in ampliyconfiguration.json.  We are using our existing AWS resources and we don't use Amplify CLI to manage resources.
Since the json for push notification plugin is not documented, we can't customize amplifyconfiguration.json.   It needs to documented.

### Steps To Reproduce

```swift
Since this is a defect in the document, there is no repro steps.

If the push plugin configuration is not added, it will throw a configuration error during initialization.

I've added the following, but it crashes the app at PushNotificationCategory.recordNotificationReceived(_:).  So, I assume it is not configured properly.

"notifications": {
        "plugins": {
            "awsPinpointPushNotificationsPlugin": {
                "appId": "xxx",
                "region": "xxx",
                "pinpointTargeting": {
                    "region": "xxx"
                }
            }
        }
    }
```

### Expected behavior

The schema of the push plugin configuration section of amplifyconfiguration.json is documented.

### Amplify Framework Version

2.22.0

### Amplify Categories

Analytics

### Dependency manager

Swift PM

### Swift version

5.9

### CLI version

No using CLI

### Xcode version

15.0.1

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Platforms

iOS

### OS Version

iOS 17.1.2

### Device

Iphone Pro Max 14

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by atierian** [comment]
Thanks for opening this issue @sungwonshinn
The structure of the `amplifyconfiguration.json` for notifications is documented under [Push Notifications > Set up backend resources > Existing resources tab](https://docs.amplify.aws/swift/build-a-backend/push-notifications/set-up-push-notifications/#set-up-backend-resources).
```
"notifications": {
    "plugins": {
        "awsPinpointPushNotificationsPlugin": {
            "appId": "[APP ID]",
            "region": "[REGION]"
        }
    }
}
```

What's the error message that you're seeing when configuring the plugin? And what is the crash message you receive when invoking `PushNotificationCategory.recordNotificationReceived(_:)`

**Comment by sungwonshinn** [comment]
@atierian Thank you.

> What's the error message that you're seeing when configuring the plugin?
I think it will work properly with a notification body in awsconfiguration.json.  So, I think it's fine.
PluginError: Unable to decode configuration
Recovery suggestion: Make sure the plugin configuration is JSONValue
  ▿ pluginConfigurationError : 3 elements
    - .0 : "Unable to decode configuration"
    - .1 : "Make sure the plugin configuration is JSONValue"

> And what is the crash message you receive when invoking PushNotificationCategory.recordNotificationReceived(_:)

It was EXC_BREAKPOINT (SIGTRAP). I have attached the crash report.  
[amplify push crash.txt](https://github.com/aws-amplify/amplify-swift/files/13621215/amplify.push.crash.txt)

**Comment by atierian** [comment]
Great, please let us know when you confirm that it works with the correct configuration. Thanks!

**Comment by atierian** [comment]
Closing as this appears to be resolved. If you're still experiencing this, please open a new issue. Thanks!
