### ISSUE TITLE
Having issue with refresh token, getting Nil while calling awsmobileclient.default().gettokens in swift

### ISSUE THREAD

**Issue by abdurrazax** [aws-amplify/amplify-swift#3431]
### Describe the bug

while calling this method in swift on Xcode "awsmobileclient.default().gettokens" I am getting nil value.
I am calling after the successful login with Amplify.Auth.signIn
after that when I am trying to call any mutation I'm getting Auth error

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Login with amplify Amplify.Auth.signIn
2. after successfully login call awsmobileclient.default().gettokens
3. in the result I'm getting Nil instead of token
```

### Expected behavior

There should be an token in the return 

### Amplify Framework Version

2.25.0

### Amplify Categories

API, Auth

### Dependency manager

Swift PM

### Swift version

5.8

### CLI version

10.8.1

### Xcode version

15.0.1

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


Error: notSignedIn(message: "User is not signed in to Cognito User Pool, please sign in to use this API.")
```
</details>
```


### Is this a regression?

Yes

### Regression additional context

_No response_

### Platforms

iOS

### OS Version

iOS 17.0

### Device

iPhone 14 Pro Max

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by Montchat** [comment]
I'm also experiencing this issue

**Comment by thisisabhash** [comment]
I see you're using Amplify version 2.25.0
After calling `Amplify.Auth.signIn()`, you may fetch the credentials/tokens by following the documentation here:

https://docs.amplify.aws/swift/build-a-backend/auth/accessing-credentials/

**Comment by abdurrazax** [comment]
> I see you're using Amplify version 2.25.0 - `AWSMobileClient` is no longer used in Amplify v2.
> 
> After calling `Amplify.Auth.signIn()`, you may fetch the credentials/tokens by following the documentation here:
> 
> https://docs.amplify.aws/swift/build-a-backend/auth/accessing-credentials/

After calling the documentation method I'm unable to call any mutation with this method

appDelegate.appSyncClient?.fetch(query: query, cachePolicy: .fetchIgnoringCacheData)  { [weak self] (result, error) in 

after getting the token AWSMobileClient is setting the auth token and can we do in the amplify V2 ?

**Comment by thisisabhash** [comment]
After calling `Amplify.Auth.signIn()`, Amplify automatically fetches tokens from Cognito UserPool and Identity Pool and saves it in Keychain. 
To get the aws credentials/cognito user tokens, you can call like this:

```
import AWSPluginsCore

do {
    let session = try await Amplify.Auth.fetchAuthSession()

    // Get user sub or identity id
    if let identityProvider = session as? AuthCognitoIdentityProvider {
        let usersub = try identityProvider.getUserSub().get()
        let identityId = try identityProvider.getIdentityId().get()
        print("User sub - \(usersub) and identity id \(identityId)")
    }

    // Get AWS credentials
    if let awsCredentialsProvider = session as? AuthAWSCredentialsProvider {
        let credentials = try awsCredentialsProvider.getAWSCredentials().get()
        // Do something with the credentials
    }

    // Get cognito user pool token
    if let cognitoTokenProvider = session as? AuthCognitoTokensProvider {
        let tokens = try cognitoTokenProvider.getCognitoTokens().get()
        // Do something with the JWT tokens
    }
} catch let error as AuthError {
    print("Fetch auth session failed with error - \(error)")
} catch {
}
```

**Comment by IvanSolaris** [comment]
I'm facing a similar issue, when doing:

```
    // Get cognito user pool token
    if let cognitoTokenProvider = session as? AuthCognitoTokensProvider {
        let tokens = try cognitoTokenProvider.getCognitoTokens().get()
        // Do something with the JWT tokens
    }
  ```
 
the cast on the iflet cognitoTokenProvider is nil so it won't work, but interesting thing is that if i debug it and do it in the debugger the cast works

![Captura de pantalla 2024-01-12 a las 10 36 50](https://github.com/aws-amplify/amplify-swift/assets/148055095/a817e364-7ad2-414c-ae5f-7f6e81f0a61f)

**Comment by thisisabhash** [comment]
Hi @IvanSolaris , If you have enabled guest user in Cognito Identity Pool and no user is signed in, you will be able to access only identityId and AWS credentials. All other session details will give you an error.
