### ISSUE TITLE
Support Amazon Lex v2

### ISSUE THREAD

**Issue by tingyao-chang** [aws-amplify/amplify-swift#3433]
### Is your feature request related to a problem? Please describe.

I currently have a chatbot developed using Amazon Lex v2. I want to develop an iOS APP to access this chatbot, although AWS SDK for Swift supports Amazon Lex v2, but it is currently in Developer Preview. So there is no iOS related SDK that can directly do this for production workloads. 

### Describe the solution you'd like

Amplify Library for Swift can support Amazon Lex v2.

### Describe alternatives you've considered

Amplify Library for Swift can provide a signature library for iOS APP to easily sign Amazon Lex v2 API requests.

References: 
[1] https://docs.aws.amazon.com/lexv2/latest/APIReference/welcome.html
[2] https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_aws-signing.html

### Is the feature request related to any of the existing Amplify categories?

Predictions

**Comment by lawmicha** [comment]
Thank you for raising the feature request. Our team will prioritize it and will post an update on the issue once we have more information.

**Comment by lawmicha** [comment]
Hi @tingyao-chang, Amplify V2 (currently our active development and `main` branch) depends on [AWS SDK for Swift](https://github.com/awslabs/aws-sdk-swift) so unless we implement our own layer to interact with AWS Lex V2, fulfilling this feature request in Amplify will also make use of the sames clients in the Swift SDK. I'd recommend getting it working with the Swift SDK and pinning the version in your dependencies. 

Is this the client you are looking to use? https://github.com/awslabs/aws-sdk-swift/blob/main/Sources/Services/AWSLexModelsV2/LexModelsV2Client.swift#L8 

You can use Amplify.Auth as the credentials provider when initializing the configuration https://docs.amplify.aws/swift/build-a-backend/auth/accessing-credentials/

**Comment by tingyao-chang** [comment]
Thanks @lawmicha, I'm actually not sure if I should send this feature request to Amplify Swift. I know that the AWS SDK for Swift supports Amazon Lex v2, but since the AWS SDK for Swift is still in developer preview and workloads will go into production later, we are not considering using the AWS SDK for Swift at this time.
