### ISSUE TITLE
Edit x-amz- headers from custom interceptor

### ISSUE THREAD

**Issue by gevartosky** [aws-amplify/amplify-swift#3491]
### Is your feature request related to a problem? Please describe.

While trying to apply my custom V4 signature to an AWSAPIPlugin request, I keep getting a CRT 6148 error that comes from the `Signer.swift` when the postludeInterceptors are applied.

I use a custom V4 signature and I haven't found anywhere in the documentation indicating how to add a custom signature.

### Describe the solution you'd like

Being able to customize V4 signatures from custom URLInterceptors

### Describe alternatives you've considered

I haven't found any alternative in the documentation

### Is the feature request related to any of the existing Amplify categories?

API

**Comment by gevartosky** [comment]
Is there any alternative to achieve this using a different approach or escape hatch?
I'm migrating my client's entire app to Amplify V2 in one go (since it can't coexist with AppSync) so unfortunately time is of the essence.

**Comment by lawmicha** [comment]
Hi @gevartosky, how are you applying the custom logic onto the request? For some context, we introduced the new interceptors pattern in https://github.com/aws-amplify/amplify-swift/pull/3190 that has the `postludeInterceptors` you are referring to.

**Comment by lawmicha** [comment]
`postludeInterceptors` are only added according to the configuration, you can set the configuration's authorizationType to `NONE` https://docs.amplify.aws/swift/build-a-backend/graphqlapi/customize-authz-modes/#none and define a custom interceptor

**Comment by gevartosky** [comment]
Thank you @lawmicha I was able to overwrite the headers by setting the auth type to "NONE".

When I was first looking at this I went straight to Advanced Workflows > Adding Headers to Outgoing Requests
https://docs.amplify.aws/swift/build-a-backend/graphqlapi/advanced-workflows/#adding-headers-to-outgoing-requests

It does mention `By default, the API plugin includes appropriate authorization headers on your outgoing requests`, but I think it would be beneficial to make a connection with that other page (Customize Auth Modes) in case devs are looking to overwrite authorization headers and fall in the same situation.

**Comment by thisisabhash** [comment]
Hello @gevartosky, We have merged the update to the docs site which includes a call out to `NONE` authorization.
https://github.com/aws-amplify/docs/pull/6886
