### ISSUE TITLE
Endless retry of mutation request when server responds with 401 error code

### ISSUE THREAD

**Issue by MuniekMg** [aws-amplify/amplify-swift#3511]
### Describe the bug

When trying to mutate model with custom auth strategy, without having permission to this model, our server responds with 401 witch causes DataStore to start endless retry of this mutation

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Mutate a model without permission
```

### Expected behavior

DataStore should retry mutation again with different auth type if available (once per auth type)

### Amplify Framework Version

2.26.0

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5

### CLI version

12.10.0

### Xcode version

15.2

### Relevant log output

```
GraphQL mutation operation received result: failure(APIError: The HTTP response status code is [401].
Recovery suggestion: The metadata associated with the response is contained in the HTTPURLResponse.
For more information on HTTP status codes, take a look at
https://en.wikipedia.org/wiki/List_of_HTTP_status_codes)


scheduleRetry(advice:withAuthType:) scheduling retry for mutation RequestRetryAdvice(shouldRetry: true, retryInterval: Dispatch.DispatchTimeInterval.milliseconds(0))
```

### Is this a regression?

No

### Platforms

iOS

### OS Version

iOS 17

### Device

iPad 10th gen

**Comment by lawmicha** [comment]
Hi @MuniekMg, thanks for raising this issue and the PR, we'll take a look and get back to you!
