### ISSUE TITLE
Version 2.25.7 & 2.26.0 have Package Resolution Failed

### ISSUE THREAD

**Issue by gurkarangulati** [aws-amplify/amplify-swift#3514]
### Describe the bug

Add amplify-swift from Swift Package manager for version 2.25.7 or 2.26.0 and get a Package Resolution Failed. 
![Screenshot 2024-02-11 at 3 01 52 AM](https://github.com/aws-amplify/amplify-swift/assets/4088575/f62eaa37-fd9b-4d29-8131-363392f48c04)

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to Swift package manager. 
2. Add amplify-swift package by URL
3. Try to add version 2.25.7 or 2.26.0 and see the error for Package Resolution Failed
```

### Expected behavior

Expect swift package manager resolves package and we can add the appropriate modules. 

### Amplify Framework Version

2.25.7 & 2.26.0

### Amplify Categories

Analytics, API, Auth, DataStore, Geo, Predictions, Storage

### Dependency manager

Swift PM

### Swift version

Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5) Target: arm64-apple-darwin23.4.

### CLI version

12.10.1

### Xcode version

Version 15.2 (15C500b)

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

Yes

### Regression additional context

_No response_

### Platforms

macOS

### OS Version

14.4 Beta (23E5191e)

### Device

Mac Studio

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by lawmicha** [comment]
Hi @gurkarangulati, thanks for opening this issue, we'll investigate and get back to you.

**Comment by lawmicha** [comment]
I'm installing 15.2 right now but couldn't reproduce on Xcode 15.1. Can you try again? Maybe it was a git hiccup.

**Comment by lawmicha** [comment]
Couldn't reproduce with Xcode 15.2, most likely a transient network issue

**Comment by gurkarangulati** [comment]
Confirmed - if you do packages cache reset, it works. Sorry for the false alarm. 

https://stackoverflow.com/questions/71960361/xcode-suddenly-can-not-get-swift-package-revision-couldnt-get-revision
