### ISSUE TITLE
visionOS AWSS3StoragePlugin Compilation Issue

### ISSUE THREAD

**Issue by LarissaKim** [aws-amplify/amplify-swift#3528]
### Describe the bug

I'm unable to run a project in the visionOS simulator after adding `AWSS3StoragePlugin` as a dependency via Swift PM (no configuration or reference in codebase, just install). I am able to run the project when `AWSCognitoAuthPlugin` is installed, configured, and used in the codebase. It just seems to be S3 that's the issue. Have I missed a step in the package installation?

1) `No such file or directory` errors for the following files (only seems to happen when visionOS 1.1 set as minimum deployment):
- `AWSS3StoragePlugin.abi`
- `AWSS3StoragePlugin.swiftdoc`
- `AWSStoragePlugin.swiftmodule`
- `AWSS3StoragePlugin.swiftsourceinfo`

2) `Command SwiftCompile failed with a nonzero exit code` errors (happens for both visionOS 1.0 and 1.1 set as minimum deployment):
- `/Users/REDACTED/Library/Developer/Xcode/DerivedData/REDACTED/SourcePackages/checkouts/amplify-swift/AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/Attempt.swift:16:68 Cannot convert value of type '(any Error) -> Void' to closure result type '()'`
- `/Users/REDACTED/Library/Developer/Xcode/DerivedData/REDACTED/SourcePackages/checkouts/amplify-swift/AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/Attempt.swift:32:65 Cannot convert value of type '(any Error) -> Void' to closure result type '()'`

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Create a new Xcode project for visionOS
2. Add Amplify and AWSS3StoragePlugin as dependencies, with the Dependency Rule set to Branch and the value set to visionos-preview.
3. Run the app with simulator
4. See error
```

### Expected behavior

I expect to be able to compile and run the project in the simulator after just installing the dependencies and the `AWSS3StoragePlugin` is not yet used anywhere in the codebase.

### Amplify Framework Version

visionos-preview (61994b9)

### Amplify Categories

Storage

### Dependency manager

Swift PM

### Swift version

5.9.2

### CLI version

N/A

### Xcode version

Version 15.3 beta 2 (15E5188j)

### Is this a regression?

No

### Regression additional context

I have not previously created projects for visionOS with this package before.

### Platforms

visionOS (Preview)

### OS Version

visionOS 1.0 / visionOS 1.1

### Device

Apple Vision Pro (only using simulator at the moment)

### Specific to simulators

Apple Vision Pro

**Comment by thisisabhash** [comment]
Hello @LarissaKim, We have put in a fix to the `visionos-preview` branch. Please update/refresh your package dependencies and let us know if you still face any issues.

**Comment by LarissaKim** [comment]
@harsh62 @thisisabhash I appreciate the prompt update.

I removed the package, cleaned the build folder, restarted Xcode, then re-installed Amplify and AWSS3StoragePlugin.

The errors regarding the missing files has resolved, however, I still can't run the project in the simulator due to the following `Command SwiftCompile failed with a nonzero exit code` errors (still happens for both visionOS 1.0 and 1.1 set as minimum deployment):
- `/Users/REDACTED/Library/Developer/Xcode/DerivedData/REDACTED/SourcePackages/checkouts/amplify-swift/AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/Attempt.swift:16:68 Cannot convert value of type '(any Error) -> Void' to closure result type '()'`
- /Users/REDACTED/Library/Developer/Xcode/DerivedData/REDACTED/SourcePackages/checkouts/amplify-swift/AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/Attempt.swift:32:65 Cannot convert value of type '(any Error) -> Void' to closure result type '()'`

Is `AWSPluginsCore` a required "plugin", by any chance? I didn't see it mentioned in the documentation.

**Comment by thisisabhash** [comment]
![Screenshot 2024-02-16 at 15 13 04](https://github.com/aws-amplify/amplify-swift/assets/23294582/c46131f2-ebe8-4fed-a46e-180e0c2d9be8)

Are you able to see the latest commit `bcd7602` in your Xcode like above?

**Comment by LarissaKim** [comment]
@harsh62 @thisisabhash Ah indeed it was still the old commit. I can confirm `bcd7602` has fixed the errors. Thank you!
