### ISSUE TITLE
GraphQL API Bug

### ISSUE THREAD

**Issue by dan-codes1** [aws-amplify/amplify-swift#3533]
### Describe the bug

I am trying to create a new model using the api `try await Amplify.API.mutate(.create(type))`

```bash
GraphQLResponseError<Listing>: GraphQL service returned a successful response containing errors: [Amplify.GraphQLError(message: "Validation error of type UnknownType: Unknown type CreateEemoInput", locations: Optional([Amplify.GraphQLError.Location(line: 1, column: 29)]), path: nil, extensions: nil), Amplify.GraphQLError(message: "Validation error of type FieldUndefined: Field \'createEemo\' in type \'Mutation\' is undefined @ \'createEemo\'", locations: Optional([Amplify.GraphQLError.Location(line: 2, column: 3)]), path: nil, extensions: nil)]
Recovery suggestion: The list of `GraphQLError` contains service-specific messages
```
I have an idea of what the error is about. So 'Eemo' is a model i had created in GraphQL schema but I later changed the name to 'Listing'. So i'm guessing that when I want to create a new 'Listing', the api points to the old 'createEemo' mutation instead of 'createListing'. I have generated new schema, mutation, and queries via `amplify codegen` and it worked; they were all created using the new names of the models. So I don't know what exactly is wrong here.

This is what the new schema looks like:
```graphql
type Listing @model @searchable @auth(rules: [{allow: public, operations: [read]}, {allow: private, operations: [read]}, {allow: owner, operations: [create, update, delete]}])
```

### Steps To Reproduce

```swift
amplSteps to reproduce the behavior:
1. Create a new project and add graphql api to your project.
2. Create a new model and generate the models and other GraphQL files using `amplify codegen`
3. Test it to see if it works. You can also try to create new instances of the model via the GraphQL API.
4. Now change the name of the model to a new name and create new graphql files for it using `amplify codegen`.
5. Now try to mutate, specifically create, a new instance of the model using `try await Amplify.API.mutate(.create(type))`
6. Does it work?
```

### Expected behavior

I should be able to perform operations on a model, even after changing its name.

### Amplify Framework Version

2.26.1

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

5.9

### CLI version

12.10.1

### Xcode version

15.2

### Relevant log output

```shell
GraphQLResponseError<Listing>: GraphQL service returned a successful response containing errors: [Amplify.GraphQLError(message: "Validation error of type UnknownType: Unknown type CreateEemoInput", locations: Optional([Amplify.GraphQLError.Location(line: 1, column: 29)]), path: nil, extensions: nil), Amplify.GraphQLError(message: "Validation error of type FieldUndefined: Field \'createEemo\' in type \'Mutation\' is undefined @ \'createEemo\'", locations: Optional([Amplify.GraphQLError.Location(line: 2, column: 3)]), path: nil, extensions: nil)]
```

### Is this a regression?

No

### Platforms

iOS

### OS Version

iOS 16

### Device

iPhone 15

### Specific to simulators

no

**Comment by ruisebas** [comment]
Hi @dan-codes1, thanks for opening this issue.
The team will take a look and post an update here.

**Comment by dan-codes1** [comment]
Any updates on this? @ruisebas

**Comment by ruisebas** [comment]
Hi @dan-codes1! I've tried several times to reproduce this issue but was unable to, the new model is created properly. I'm using Amplify CLI version `12.10.1`.

Just to be sure, could you confirm that you:
- run `amplify push --allow-destructive-graphql-schema-updates` after updating your local model. If you did, do you recall if it finished successfully or reported any error? 
- run `amplify codegen models` to generate the models. The `models` parameter is missing in your repro steps, that's why I'm asking.

Additionally, can you check in your AppSync console if the schema has indeed been updated?

**Comment by dan-codes1** [comment]
resolved.
