### ISSUE TITLE
Unknown  errors

### ISSUE THREAD

**Issue by alekkova** [aws-amplify/amplify-swift#3546]
### Is your feature request related to a problem? Please describe.

`LivenessEventKind.Exception` has some predefined exceptions:

https://github.com/aws-amplify/amplify-swift/blob/358699cc83daf4f9718003bab3c3cbac94f1737d/AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Events/LivenessEvent.swift#L41-L55

Predefined exceptions are translated to a corresponding `FaceLivenessSessionError`. But all other exceptions are translated to `FaceLivenessSessionError.unknown`.

https://github.com/aws-amplify/amplify-swift/blob/358699cc83daf4f9718003bab3c3cbac94f1737d/AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/SPI/AWSPredictionsPlugin%2BLiveness.swift#L71-L92

When other exceptions happen it is impossible to understand the reason for an error.

User was receiving a `FaceLiveness.FaceLivenessDetectionError(code: 0, message: "An unknown error occurred.", recoverySuggestion: "Please open an issue....")` and it took way too much effort to prepare and distribute a special build for the user using a modified Amplify package where a `InvalidSignatureException` exception header value could finally be observed which hinted about the underlying issue.
 https://github.com/aws-amplify/amplify-swift/blob/358699cc83daf4f9718003bab3c3cbac94f1737d/AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSession.swift#L150-L152

### Describe the solution you'd like

Provide better error descriptions and avoid using unknown errors. Providing at least exception header value would already help in understanding the underlying error.

### Describe alternatives you've considered

There are no alternatives.

### Is the feature request related to any of the existing Amplify categories?

Predictions

**Comment by phantumcode** [comment]
@alekkova Thanks for submitting the issue.  We'll investigate and provide updates here.

**Comment by phantumcode** [comment]
@alekkova The code currently supports all possible exception from `LivenessEventKind.Exception`.  The default `unknown` is to provide a graceful fallback if or when a new exception type is added from the Rekognition.  Are you observing or seeing an exception that is properly handled?

**Comment by alekkova** [comment]
@phantumcode thank you for looking into it.

We have stumbled on a case where `LivenessEventKind.Exception` is initialised with a `rawValue: "InvalidSignatureException"` . This happens here:

https://github.com/aws-amplify/amplify-swift/blob/358699cc83daf4f9718003bab3c3cbac94f1737d/AmplifyPlugins/Predictions/AWSPredictionsPlugin/Liveness/Service/FaceLivenessSession.swift#L150-L152

This leads to a very unclear "unknown error" on client side, which gives no information about the issue at all. I am worried if there are also other exception types that lead to an unknown error on client side.

**Comment by phantumcode** [comment]
@alekkova This is a bug with the service not properly catching the `InvalidSignatureException` and returning an `AccessDeniedException`.  A ticket has been created and assigned to the Rekognition service team to fix this issue.

**Comment by alekkova** [comment]
Thanks @phantumcode. It would also be appreciated if we received more descriptive errors on client side. For example `InvalidSignatureException` is more descriptive than `AccessDeniedException`.

**Comment by phantumcode** [comment]
@alekkova Thanks you for your feedback.  Can you submit a feature request to improve the Liveness client side error messages in the Liveness repo https://github.com/aws-amplify/amplify-ui-swift-liveness
