### ISSUE TITLE
Localization issues

### ISSUE THREAD

**Issue by bfallon** [aws-amplify/amplify-swift#3548]
### Describe the bug

It appears that Amplify/Cognito doesn't support localization for error handling.

### Steps To Reproduce

We are using Amplify for authentication in our app that supports multiple languages. Unfortunately I cannot find a standard approach to support this task. 

**Approach A:  Simply present users with a localized description.**

The localized descriptions we receive from Amplify are not user friendly. For example, this is what you will see in Chinese if you enter the wrong username/password:

`未能完成操作。（Amplify.AuthError错误4。）`

In English:
`The operation couldn’t be completed. (Amplify.AuthError error 4.)`

However, the "not localized" `AuthError` description is more clear:
`Incorrect username or password.`

**Approach B: Switch through the possible errors and return our custom localized string.** 

Unfortunately the AuthError enum has params that prevents this approach (as outlined here: https://github.com/aws-amplify/amplify-swift/issues/3197)

However, sometimes we can get the underlyingError and can enumerate through the `AWSCognitoAuthError` cases. For example:

```swift
 if let cognitoAuthError = authError.underlyingError as? AWSCognitoAuthError {
    //This is great! We can work with this!
}
```

But, not all AuthErrors have the underlying errors, for example wrong username/password doesn’t have the underlying error.

- How does AWS suggest we handle multiple languages?
- Is it possible to add the underlyingError/ AWSCognitoAuthError to all AuthErrors?

### Expected behavior

I would expect consistency with all **AuthErrors** having an **underlyingError**. 

### Amplify Framework Version

2.27.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.9.2

### CLI version

12.4.0

### Xcode version

15.2

### Is this a regression?

Yes

### Platforms

iOS

### OS Version

17.3.1

### Device

iPhone 14 Pro

**Comment by 5d** [comment]
Hi @bfallon,

Thanks for opening the issue. Our team will look into it and give you an update once we have more information.

**Comment by bfallon** [comment]
Thank you for your response. This resolves my issue.
