### ISSUE TITLE
Created and deleted model on one device appears as created on the other

### ISSUE THREAD

**Issue by MuniekMg** [aws-amplify/amplify-swift#3553]
### Describe the bug

This is the same bug as [2982](https://github.com/aws-amplify/amplify-swift/issues/2982)
This bug was recently closed and solved but I still can reproduce this issue

### Steps To Reproduce

```swift
1. We have two phones: PhoneA and PhoneB
2. App is open only on PhoneA
3. on PhoneA add model and then remove this model (DataStore)
4. Open app on PhoneB
5. PhoneB will receive onCreate but not onDelete
```

### Expected behavior

in step 5 phoneB should receive:
- receive onCreate but then onDelete
or
- receive nothing

### Amplify Framework Version

2.27.0

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5

### CLI version

12.7.0

### Xcode version

Version 15.2 (15C500b)

**Comment by MuniekMg** [comment]
@5d This is how model looks in DynamoDB table:

"id","__typename","_deleted","_lastChangedAt","_ttl","_version","address","createdAt","name","owner","updatedAt"

"20DE73FE-C4D3-4E91-90AF-E52DCA7952D2",
"Space",
"true",
"1709749749259",
"1712341749",
"2",
"bbb",
"2024-03-06T18:29:04.110Z",
"aaa",
"ca740603-9c2c-4e44-9e69-1adcbfe0cd8c::ca740603-9c2c-4e44-9e69-1adcbfe0cd8c",
"2024-03-06T18:29:04.110Z"

**Comment by 5d** [comment]
Thanks @MuniekMg,

The record did mark as deleted. I've reviewed PR https://github.com/aws-amplify/amplify-swift/pull/3554. LGTM
