### ISSUE TITLE
Upload file to bucket without Cognito Identity Pool

### ISSUE THREAD

**Issue by symmetry-max** [aws-amplify/amplify-swift#3569]
### Is your feature request related to a problem? Please describe.

I'm trying to upload a file via:

```
let uploadTask = Amplify.Storage.uploadData(
      key: key,
      data: data
)
```
The user is correctly logged in, `accessKeyId`, `secretAccessKey`, `sessionToken`, `bucketName`, `region`, `accountId`, are all available at run-time.
But when I try to upload the file, I always get the error:

```
Successfully completed execution for Auth.fetchSessionAPI with result:
{
    awsCredentialsError = "AuthError: Could not fetch AWS Credentials, AWS Cognito Identity Pool is not configured\nRecovery suggestion: Follow the steps to configure AWS Cognito Identity Pool and try again\nCaused by:\ninvalidAccountTypeException";
    cognitoTokens = "[\"idToken\": \"*********\", \"accessToken\": \"*********\", \"refreshToken\": \"*********\", \"expiry\": 2024-03-14 05:09:00 +0000]";
    identityIdError = "AuthError: Could not fetch identity Id, AWS Cognito Identity Pool is not configured\nRecovery suggestion: Follow the steps to configure AWS Cognito Identity Pool and try again\nCaused by:\ninvalidAccountTypeException";
    isSignedIn = true;
    userSub = "*****************";
}
```

We're not using an AWS Cognito Identity Pool, authentication is supposed to happen via idToken, so my `awsconfiguration.json` and `amplifyconfiguration.json` don't contain identity pool data.

### Describe the solution you'd like

I'd like to update the `Storage` (and/or `Auth`) plugin configuration at run-time with the data received from a server and then upload the file using the tokens as authentication.

### Describe alternatives you've considered

Using AWS SDK "S3" package instead of Amplify for the file upload, but the package manager in xCode seems to have trouble resolving.

### Is the feature request related to any of the existing Amplify categories?

Storage

### Additional context

I'm sorry if my request seems non-sensical.
I'm new to AWS / Amplify, and the person giving me tasks either doesn't understand AWS either or is unwilling elaborate any further than "we don't use Identity Pool, you should use the tokens".

**Comment by thisisabhash** [comment]
Thank you for posting this issue. Our team will take a look and post updates.

**Comment by symmetry-max** [comment]
Thank you!
I also finally figured out how to use AWS SDK
_(note to later readers who have trouble with this: the correct way is NOT to add the `aws-sdk-swift` to the project next to `Amplify`, Amplify already has `aws-sdk-swift` as a dependency and you'll run into conflicts. Instead, just use `getEscapeHatch`: https://docs.amplify.aws/swift/build-a-backend/auth/sdk/ )_
but I'm still no wiser as to how to use either Amplify or AWS SDK's `CognitoIdentityProviderClient` to override the credentials and allow uploads without Identity Pool.

**Comment by thisisabhash** [comment]
Hello,
There are two steps in the Authentication flow:
 
- Authorization flow: You would need Cognito Identity Pool to fetch temporary `AWSCredentials` which have appropriate roles to engage with AWS resources (S3 bucket in your case)

- Authentication flow: Amplify uses Cognito User Pool for user management and generate auth tokens. These auth tokens are used to fetch the temporary `AWSCredentials` mentioned above. 

However, if you're using an external IdP provider (Facebook, Google, Apple, Amazon or any other OIDC provider), you can use a social provider sign in [Social Sign In](https://docs.amplify.aws/swift/build-a-backend/auth/add-social-provider/) 
By doing so, it creates a user in your Cognito User Pool corresponding to the user from IdP provider and the user pool then creates an auth token which is used to fetch `AWSCredentials`. All of this is handled by Amplify internally.

As an advanced workflow, if you don't want the user creation in Cognito User Pool, you can directly federate into identity pools by exchanging token from your IdP provider. 
[Identity Pool Federation](https://docs.amplify.aws/swift/build-a-backend/auth/advanced-workflows/#identity-pool-federation ) Do note that, some Amplify APIs won't work in this case like `getCurrentUser()` or token refresh.

**Comment by symmetry-max** [comment]
@thisisabhash Thank you so much for the explanation.

Can you please explain (or share a link on) how to use the `AWSCredentials` from a User Pool?
I can't find which function would accept them to make the upload work.

For context, the flow that I have to use is:

1) Sign in with User Pool ID and Client ID, `authenticationFlowType` is `USER_PASSWORD_AUTH`.
I can successfully sign up new new users with `Amplify.Auth.signUp` and sign in with `Amplify.Auth.signIn`.
I also get the `accessToken` and `idToken`.

2) Use an http request to query credentials from our server.
Here I receive `accessKeyId`, `secretAccessKey` sessionToken` and `bucketPrefix`.

3) Use the above to upload a file to the bucket (bucketId is known).
This is where I get the above mentioned error `AWS Cognito Identity Pool is not configured`.

**Comment by symmetry-max** [comment]
@harsh62 Thank you!
As mentioned above, using the Identity Pool is not possible. (I don't get to decide how the AWS side of things is set up, I just get the job of implementing the iOS app).

So my feature request would be to allow setting the accessKeyId and secretAccessKey in the Storage plugin.

Or, if there is an alternative to allow uploading files to an S3 bucket from iOS without an Identity Pool, I'd like to know about it.

I've found https://github.com/soto-project/soto-s3-file-transfer but haven't been able to get it to work yet.

**Comment by symmetry-max** [comment]
@harsh62 Thank you so much!
