### ISSUE TITLE
Listening to progress of individual parts in a multipart upload

### ISSUE THREAD

**Issue by CesarChretien** [aws-amplify/amplify-swift#3576]
### Is your feature request related to a problem? Please describe.

My use case requires me to manually start a multipart upload, and I'd like my UI to be able to the upload progress of the individual parts I'm uploading. I'm roughly doing the following:

```swift
// get the escape hatch
let plugin = try Amplify.Storage.getPlugin(for: "awsS3StoragePlugin")
guard let storagePlugin = plugin as? AWSS3StoragePlugin else {
  // handle error
}
let client: S3Client = storagePlugin.getEscapeHatch()

// initiate multipart upload
var request = CreateMultipartUploadInput()
request.bucket = bucket
request.key = key
let response = try await client.createMultipartUpload(input: request)

// upload part, of this i want to observe the progress
let data: Data = // the data i want to upload
var request = UploadPartInput()
request.bucket = bucket
request.key = key
request.uploadId = uploadId
request.partNumber = partNumber
let contentLength = data.count
request.contentLength = contentLength
request.body = .data(data)
let response = try await client.uploadPart(input: request)
```
The upload itself is working fine, but I haven't been able to figure out how to attach a listener to the individual parts being uploaded.

### Describe the solution you'd like

Being able to do
```swift
var request = UploadPartInput()
request.progressListener = { progress in
    // progress contains something like bytesSent, totalBytesSent, totalBytes; or fractionCompleted
}
```
would be amazing.

Or if it's already included in the current version sdk, I'd like some pointers in the right direction (sample code welcome).

### Describe alternatives you've considered

Previously the data structure used for the body was different, which allowed me to create my own polling mechanism by checking a hidden field on the request body via reflection. Admittedly this is a hack and not a proper solution but on the latest version this doesn't work at all anymore.

I remember this was possible via using `TransferUtility`, but I can't seem to find an equivalent in v2.

### Is the feature request related to any of the existing Amplify categories?

Storage

**Comment by lawmicha** [comment]
Hi @CesarChretien, `Amplify.Storage.uploadData` provides a `progress` property that's an AsyncSequence you can get progress from. https://docs.amplify.aws/swift/build-a-backend/storage/upload/#upload-data

```swift
Task {
    for await progress in await uploadTask.progress {
        print("Progress: \(progress)")
    }
}
```

I assume there was something that the Amplify.Storage plugin did not support for you to go to the escape hatch, let us know if this works for you.

**Comment by lawmicha** [comment]
Let me check with the team to see if anyone done this before, getting progress on a request. The client we expose comes from https://github.com/awslabs/aws-sdk-swift so you may be able to get some insight if you open another issue to ask over there. A rough guess, I think you might be able to inject your own HTTP client to perform the upload, which then you might have access to the progress of that operation

**Comment by ruisebas** [comment]
Since this feature request is about `UploadPartInput` and other types defined by the SDK, I'm transferring it to the [**AWS SDK for Swift**](https://github.com/awslabs/aws-sdk-swift) repository. The SDK team also might be able to suggest other ways to achieve what you want.

**Comment by ruisebas** [comment]
Since this feature request is about `UploadPartInput` and other types defined by the SDK, please open a new issue in the [**AWS SDK for Swift**](https://github.com/awslabs/aws-sdk-swift) repository. 

The SDK team also might be able to suggest other ways to achieve what you want.
