### ISSUE TITLE
Crash when saving data using datastore

### ISSUE THREAD

**Issue by amruth-movano** [aws-amplify/amplify-swift#3595]
### Describe the bug

We are saving data to data store with predicate. I am getting crash when predicate is not nil. But when predicate set to nil, everything works fine.

Fatal error: SWIFT TASK CONTINUATION MISUSE: save(_:modelSchema:where:) tried to resume its continuation more than once, throwing DataStoreError: Cannot apply a condition on model which does not exist.
Recovery suggestion: Save the model instance without a condition first.!

But we want to add predicate for all the queries

### Steps To Reproduce

```swift
1. Save the data using predicate
```

### Expected behavior

App should save data to dynamodb

### Amplify Framework Version

2.28.0

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

NA

### Xcode version

15.2

### Relevant log output

```shell
Fatal error: SWIFT TASK CONTINUATION MISUSE: save(_:modelSchema:where:) tried to resume its continuation more than once, throwing DataStoreError: Cannot apply a condition on model which does not exist.
Recovery suggestion: Save the model instance without a condition first.!
```

### Is this a regression?

No

### Platforms

iOS

### OS Version

iOS 17.4

### Device

iPhone 15 Plus

**Comment by ruisebas** [comment]
Hi @amruth-movano , thanks for opening this issue. We will try to reproduce and post any updates here.

To help us root cause, could you please enable verbose logging by adding `Amplify.Logging.logLevel = .verbose` before calling `Amplify.configure()` and share with us the logs up until the crash?

If you can add some code snippets on how you're using the API, that's also helpful.

Thanks!

**Comment by amruth-movano** [comment]
@ruisebas please see the attached file with verbose output. 
[amplify_verbose.txt](https://github.com/aws-amplify/amplify-swift/files/14876964/amplify_verbose.txt)

**Comment by ruisebas** [comment]
Hi @amruth-movano, thank for all the information. I was able to reproduce the crash and I'm working on a fix for it.

However, please note that setting a predicate condition on a **create** operation (i.e. calling `save` with a model that does not exist) is not supported and it will result in a failure. You can only set conditions on **update** operations (i.e. calling `save` with a model that already exist).

**Comment by 5d** [comment]
The DataStore feature is designed to enable data accessibility even when the device is not connected to the internet or has limited connectivity. When you create model instances using `DataStore.save`, it does not directly create the item in the DynamoDB table. Instead, it saves the data to a local SQLite database first, and then synchronizes it with the DynamoDB table later.
If you want to apply conditional checks while creating items directly in the DynamoDB table, you can use the API plugin provided by Amplify.
```
Amplify.API.mutate(.mutation(...))
```
