### ISSUE TITLE
pod Amplify 版本不支持

### ISSUE THREAD

**Issue by zhangshouyin** [aws-amplify/amplify-swift#3596]
### Describe the bug

https://github.com/aws-amplify/amplify-swift
这个是Amplify代码仓库，为什么我用pod依赖管理工具pod 'Amplify' 得到的代码目录结构和git仓库的目录结构不一样？而用Swift Package Manager引入的库就和git仓库的目录结构一样的，而且用 Swift Package Manager 得到的版本比pod高很多，这是为什么？

### Steps To Reproduce

```swift
Amplify iOS端 一共分两种引入方式：
1、SPM   这种方式亚马逊官方在用很适合美国那边的开发者，看了一下版本比较高都到2.28.0以上了
2、pod    这种方式很适合中国的开发者，但是最高版本是1.30.8，很显然这个版本比SPM低多了，我用这个方式引入后调用终端代码报错，说signInResult找不到isSignedI字段。
func signIn(username: String, password: String) async {
        do {
            let signInResult = try await Amplify.Auth.signIn(
                username: username,
                password: password
                )
            if signInResult.isSignedIn {
                print("Sign in succeeded")
            }
        } catch let error as AuthError {
            print("Sign in failed \(error)")
        } catch {
            print("Unexpected error: \(error)")
        }
    }
而SPM方式不会报错，我看源码发现这两种版本的代码确实不一样：
SPM的定义：
public func signIn(username: String? = nil,
                       password: String? = nil,
                       options: AuthSignInRequest.Options? = nil) async throws -> AuthSignInResult {
        return try await plugin.signIn(username: username, password: password, options: options)
    }

pod的定义：
func signIn(
        username: String? = nil,
        password: String? = nil,
        options: AuthSignInOperation.Request.Options? = nil
    ) -> AuthSignInOperation {
        signIn(username: username, password: password, options: options, listener: nil)
    }
很明显看到不一样的地方是：SPM版本的返回值是AuthSignInResult，所以有isSignedI字段。而pod版本的返回值是AuthSignInOperation，没有isSignedI字段。pod版本的Amplify太落后。

我的问题是：想请您帮我找一下有没有比较高的pod版本的Amplify，和SPM版本的Amplify SDK保持一致，同步更新的版本。
```

### Expected behavior

不支持  pod Amplify最新版本。

### Amplify Framework Version

1.30.8

### Amplify Categories

Auth

### Dependency manager

Cocoapods

### Swift version

v5.8

### CLI version

12+

### Xcode version

14.2

### Relevant log output

```shell
signInResult找不到isSignedI字段。
```

### Is this a regression?

No

### Platforms

iOS

### OS Version

ios 13+

### Device

any

### Specific to simulators

any

**Comment by ruisebas** [comment]
Hi @zhangshouyin!
**Amplify v2** (i.e. versions 2.x.x. and higher) is only distributed through SPM, and we have no plans of adding CocoaPods support.

**Amplify v1** (i.e. versions 1.x.x) is currently in Maintenance Mode, so we advice you to use Amplify v2 instead.

**Comment by zhangshouyin** [comment]
> Hi @zhangshouyin! **Amplify v2** (i.e. versions 2.x.x. and higher) is only distributed through SPM, and we have no plans of adding CocoaPods support.
> 
> **Amplify v1** (i.e. versions 1.x.x) is currently in Maintenance Mode, so we advice you to use Amplify v2 instead.

**Comment by zhangshouyin** [comment]
> Hi @zhangshouyin! **Amplify v2** (i.e. versions 2.x.x. and higher) is only distributed through SPM, and we have no plans of adding CocoaPods support.
> 
> **Amplify v1** (i.e. versions 1.x.x) is currently in Maintenance Mode, so we advice you to use Amplify v2 instead.

**Comment by zhangshouyin** [comment]
> Hi @zhangshouyin! **Amplify v2** (i.e. versions 2.x.x. and higher) is only distributed through SPM, and we have no plans of adding CocoaPods support.
> 
> **Amplify v1** (i.e. versions 1.x.x) is currently in Maintenance Mode, so we advice you to use Amplify v2 instead.

I saw that aws-sdk-ios is written in Objective-C, with 1.7K stars, it should be very stable, will it continue to be updated?
So should I give up Amplify v2 and use aws-sdk-ios instead? I don't know which solution is better for me?
What are the advantages of Amplify v2 compared to aws-sdk-ios?

**Comment by zhangshouyin** [comment]
> Hi @zhangshouyin! **Amplify v2** (i.e. versions 2.x.x. and higher) is only distributed through SPM, and we have no plans of adding CocoaPods support.
> 
> **Amplify v1** (i.e. versions 1.x.x) is currently in Maintenance Mode, so we advice you to use Amplify v2 instead.

Hi @ruisebas 
I saw that aws-sdk-ios is written in Objective-C, with 1.7K stars, it should be very stable, will it continue to be updated?
So should I give up Amplify v2 and use aws-sdk-ios instead? I don't know which solution is better for me?
What are the advantages of Amplify v2 compared to aws-sdk-ios?

**Comment by ruisebas** [comment]
The **AWS SDK for iOS** is still maintained, although we advice you to use **Amplify v2** instead.

Amplify v2 is written fully in Swift and takes advantages of the language's features. It provides higher level APIs that support a wide range of common use cases out of the box. The SDK on the other hand is more of a low-level client that lets you interact directly with AWS APIs, but as such you will need a deeper understanding of how they work and how to handle them.

You can read more about it in this FAQ: [**How is the SDK different from the Amplify Libraries**](https://docs.amplify.aws/swift/sdk/#how-is-the-sdk-different-from-the-amplify-libraries-for-ios), and in Amplify's documentation main page: [**How Amplify works**](https://docs.amplify.aws/swift/how-amplify-works/).

**Comment by zhangshouyin** [comment]
> Hi @zhangshouyin! **Amplify v2** (i.e. versions 2.x.x. and higher) is only distributed through SPM, and we have no plans of adding CocoaPods support.
> 
> **Amplify v1** (i.e. versions 1.x.x) is currently in Maintenance Mode, so we advice you to use Amplify v2 instead.

Hi @ruisebas 
Is it feasible for me to privatize the Amplify v2 code into my own repository and then add the corresponding podspec files to each library?

**Comment by zhangshouyin** [comment]
> Hi @zhangshouyin! **Amplify v2** (i.e. versions 2.x.x. and higher) is only distributed through SPM, and we have no plans of adding CocoaPods support.
> 
> **Amplify v1** (i.e. versions 1.x.x) is currently in Maintenance Mode, so we advice you to use Amplify v2 instead.

Hi @ruisebas!
I'm accustomed to using CocoaPods to manage code libraries and not comfortable with SPM. I still want to use CocoaPods.
So, Is it feasible for me to privatize the Amplify v2 code into my own repository and then add the corresponding podspec files to each library?

**Comment by ruisebas** [comment]
You're free to fork the repo and make modifications to the code that fits your use cases better, but please be aware that we cannot offer any support on forks.

Alternatively, you might be able to wrap Amplify v2 in an `xcframework` and/or host that `xcframework` as a podspec in your build system.

**Comment by zhangshouyin** [comment]
> You're free to fork the repo and make modifications to the code that fits your use cases better, but please be aware that we cannot offer any support on forks.
> 
> Alternatively, you might be able to wrap Amplify v2 in an `xcframework` and/or host that `xcframework` as a podspec in your build system.

Hi @ruisebas  Thanks for your advice I tried packaging into xcframework.
