### ISSUE TITLE
AwsCommonRuntimeKit potentially needs a privacy manifest

### ISSUE THREAD

**Issue by rowanlsnapper** [aws-amplify/amplify-swift#3603]
### Describe the bug

I'm working through some privacy manifest issues with an app that I'm working on, and the last remaining required reason API warning that I'm still dealing with is "file timestamps" (https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278393).

I'm confident that the app itself is not directly using any of the mentioned file timestamp APIs, and I've worked through the dependencies to see which of them could be using these without proper privacy manifest declarations. I notice that AwsCommonRuntimeKit is using `fstat(_:,_:)` in a couple of C source files, and it looks like the module doesn't declare this in a privacy manifest.

Could this please be investigated and actioned if necessary.

### Steps To Reproduce

```swift
1. Create an app that includes `amplify-swift` using SPM (in my case am linking `Amplify`, `AWSPluginsCore`, and `AWSCognitoAuthPlugin` to my app target).
2. Submit app to the App Store for RR API validation (can be triggered by assigning a build to a TestFlight external tester group).
3. Observe App Store Connect sends an email advising undeclared required reason API usage.
```

### Expected behavior

App Store Connect does not send an email advising undeclared required reason API usage, app passes validation.

### Amplify Framework Version

2.29.0

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.9

### CLI version

N/A

### Xcode version

15.3

### Is this a regression?

No

### Platforms

iOS

### OS Version

N/A

### Device

N/A

**Comment by phantumcode** [comment]
@rowanlsnapper Thanks for submitting the issue.  We will investigate and provide updates here.

**Comment by phantumcode** [comment]
Transferring to the AWS Common Runtime repo to investigate if a privacy manifest is need/provided.

**Comment by phantumcode** [comment]
Unable to transfer issue since AWSCRT is in a different org.

**Comment by phantumcode** [comment]
Recreated issue in AWS CRT repo.

**Comment by rowanlsnapper** [comment]
Thank you @phantumcode 👍
