### ISSUE TITLE
File at path does not exist

### ISSUE THREAD

**Issue by maggie-wiedner** [aws-amplify/amplify-swift#3609]
### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v20.12.0

### Amplify CLI Version

12.10.3

### What operating system are you using?

mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

some background -- 
i set up a project for this Xcode project yesterday, but when i went to upload to app store connect, i continued to get 2 errors: 

  - /Volumes/workspace/repository/Bandit/awsconfiguration.json: No such file or directory
  - /Volumes/workspace/repository/Bandit/amplifyconfiguration.json: No such file or directory

after troubleshooting for an entire day, i deleted the project and reinstall. but, now that i'm reinstalling, i'm getting this new error.

### Describe the bug

File at path: '/Users/maggiewiedner/amplify/backend/backend-config.json' does not exist

### Expected behavior

project is created

### Reproduction steps

run amplify init to set up project
an error will occurred when you attempt to create

### Project Identifier

Session Identifier: ca3c80dc-4818-4db3-a2a8-dd1a49a94e72

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by phantumcode** [comment]
@maggie-wiedner Can you help clarify what you mean by `upload to app store through github`.  Are you referring to uploading your app binary to the Apple Store Connect?  Are you seeing this error as part of building the app or archiving the app? How are you doing that via GitHub?  Can you provide a screen on what or where you're seeing the error message?

**Comment by maggie-wiedner** [comment]
ah, for some reason I had to do a manual upload. i'm all set now you can close this out. 

thank you!
