### ISSUE TITLE
Update SQLite.swift

### ISSUE THREAD

**Issue by maxchuquimia** [aws-amplify/amplify-swift#3614]
### Is your feature request related to a problem? Please describe.

Our project uses [Apollo](https://github.com/apollographql/apollo-ios/) and Amplify Swift. Both have dependencies on [SQLite.swift](https://github.com/stephencelis/SQLite.swift)

In Apollo's latest version, the SQLite.swift dependency requirement is now defined as `.upToNextMajor(from: "0.15.1")`

However, Amplify Swift's dependency requirement is `exact: "0.13.2"`.

### Describe the solution you'd like

Update Amplify Swift to support newer versions of SQLite.swift

### Describe alternatives you've considered

As a work around, we can avoid updating Apollo for now.

**Comment by phantumcode** [comment]
@maxchuquimia Thanks for submitting the feature request.  We will prioritize the request and provide updates here.

**Comment by harish-suthar** [comment]
@phantumcode Thanks for adding as feature request I am also facing same issue here, so waiting for a quick release for it.

**Comment by maxchuquimia** [comment]
@phantumcode please note that this is now more important because we need SQLite's XCPrivacy manifest in order to comply with Apple's new rules starting tomorrow.

**Comment by patrickmarshall** [comment]
@phantumcode Thank you for addressing this issue. We are encountering the same problem on our end as well. We require the use of SQLite 0.14.1 or a newer version.
