### ISSUE TITLE
build error on xcode15.3

### ISSUE THREAD

**Issue by smediomike** [aws-amplify/amplify-swift#3620]
### Describe the bug

after upgrade xcode15.3,  AWS SDK always happen build issue.

build error: Cannot convert value of type '(any Error) -> Void' to closure result type '()'

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. open xcode15.3
2. open existed AWS project
3. build all
4. See error(Cannot convert value of type '(any Error) -> Void' to closure result type '()' in Attempt.swift amplify-swift/AmplifyPlugins/Storage/Sources/AWSS3StoragePlugin/Support/Internal/Attempt.swift)

xcode15 and xcode15.2 do not have such issue.
```

### Expected behavior

build correct.

### Amplify Framework Version

2.17.2

### Amplify Categories

Storage

### Dependency manager

Swift PM

### Swift version

4.5 or 5.0

### CLI version

12.10.3

### Xcode version

15.3

### Relevant log output

```shell
Cannot convert value of type '(any Error) -> Void' to closure result type '()'
```

### Is this a regression?

No

### Regression additional context

this is compatibility with xcode15.3 issue

### Platforms

iOS, macOS

### OS Version

Mac OS 14.4.1

### Device

do not need

**Comment by iosmoon38** [comment]
Same issue.

**Comment by iosmoon38** [comment]
Does anyone have a solution?

**Comment by ruisebas** [comment]
This has been fixed in [2.26.1](https://github.com/aws-amplify/amplify-swift/releases/tag/2.26.1). Please update your dependencies to use the latest version.

**Comment by smediomike** [comment]
Thanks for your feedback, I meet one strange thing, My AWS existed package upgrade in Xcode can not arrive at 2.26.1 or 2.29, only can see 2.18.  did we change path or rule?

**Comment by ruisebas** [comment]
Make sure you're using "Up to Next Major Version" as **Dependency Rule** in your project's settings.
![image](https://github.com/aws-amplify/amplify-swift/assets/97059974/867c57dc-8078-4b2a-914a-69bc71f85f8e)
Then just go to **File -> Packages -> Update to Latest Package Versions**
![image](https://github.com/aws-amplify/amplify-swift/assets/97059974/e34c9fcc-c3cf-4427-ade6-57fbcd234981)

**Comment by smediomike** [comment]
Thank for your help! already can build successfully.

**Comment by lawmicha** [comment]
Thanks for confirming! Let us know if you have any other issues or questions
