### ISSUE TITLE
Update `aws-sdk-swift` dependency to v0.42.0

### ISSUE THREAD

**Issue by rowanlsnapper** [aws-amplify/amplify-swift#3629]
### Is your feature request related to a problem? Please describe.

See https://github.com/aws-amplify/amplify-swift/issues/3603

Updating the `aws-sdk-swift` dependency to the latest version (0.42.0) should resolve privacy manifest issues caused by the `AwsCommonRuntimeKit` module.

### Describe the solution you'd like

Update `aws-sdk-swift` dependency to v0.42.0

### Describe alternatives you've considered

N/A

### Additional context

https://github.com/awslabs/aws-sdk-swift/issues/1191#issuecomment-2073191387

**Comment by lawmicha** [comment]
Hi @rowanlsnapper, thanks for letting us know. 0.36.1 to 0.42.0 sounds like a big jump. We will have to investigate to see if there is any additional work once we bump it up to 0.42.0.

**Comment by ruisebas** [comment]
As of Amplify [2.41.0](https://github.com/aws-amplify/amplify-swift/releases/tag/2.41.0), the SDK dependency has been upgraded to version 1.0.0.

Closing this.
