### ISSUE TITLE
amplifyconfiguration.json & awsconfiguration.json not updating when switching amplify environments

### ISSUE THREAD

**Issue by JonathonVega** [aws-amplify/amplify-swift#3651]
### Describe the bug

When I switched from my amplify dev environment to my prod environment using "amplify env checkout prod", the amplifyconfiguration.json & awsconfiguration.json files were not updated. I did "amplify status" and confirmed that it is currently in prod and it is showing the correct resources. When I run my app, it is still retrieving data from my dev environment. Is there a way to fix this?

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Expected behavior

When switching to my amplify prod environment, the data within the app should come from the relevant prod resources.

### Amplify Framework Version

2.31.1

### Amplify Categories

API

### Dependency manager

Swift PM

### Swift version

5.10

### CLI version

12.11.1

### Xcode version

15.3

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

No

### Regression additional context

_No response_

### Platforms

iOS

### OS Version

iOS 17

### Device

iPhone SE 2nd generation

### Specific to simulators

_No response_

### Additional context

_No response_

**Comment by JonathonVega** [comment]
@lawmicha I don't quite remember but I believe it was from what I did  just doing Amplify.init when I started my project. I don't believe I dragged and dropped it initially. On my app on xcode, the AmplifyConfig folder isn't showing anything under it. The folder is there but the dropdown is showing nothing.

**Comment by lawmicha** [comment]
It sounds like the file isn't under AmplifyConfig but somewhere else in the folder structure, and still added to the target which is why `Amplify.configure()` is working and reading it from the main Bundle. 

Can you locate the file? To test things out, you can manually replace the contents of it with your prod file whenever you switch and pull the different environment.
