### ISSUE TITLE
Login can not switch another google account

### ISSUE THREAD

**Issue by zhangshouyin** [aws-amplify/amplify-swift#3661]
### Describe the bug

Amplify.Auth.signInWithWebUI( presentationAnchor: UIApplication.shared.windows.first!)  调用这个方法下次重新登录会展示手动输入账号密码界面 ，从而给用户一次 选择登录方式的机会。但是，调用Amplify.Auth.signInWithWebUI( for: .google, presentationAnchor: UIApplication.shared.windows.first!) 方法指定了google登录就永远不给用户选择其他登录方式的机会了。无论怎么退出登录都不给用户切换登录方式的机会（作为用户当然是希望不管哪种登录都应该在退出后可以有选择其他登录方式的机会）。
假如 用户有2个Google账号，要切换另一个账号，这两种 Amplify.Auth.signInWithWebUI( presentationAnchor: UIApplication.shared.windows.first!)  和 Amplify.Auth.signInWithWebUI( for: .google, presentationAnchor: UIApplication.shared.windows.first!)  调用方法都无法切换Google账号。这就麻烦了。
这是个严重的问题，希望能得到您的帮助，再次感谢。

### Steps To Reproduce

```swift
Steps to reproduce the behavior:
1. Launching App for ios with aws amplify
2. func performOnAppear() async throws {//这个是iOS端的代码
            do{
                let _ = try await Amplify.Auth.fetchAuthSession()
            }catch let error as AuthError {
                print("Authentication error : \(error)")
                await socialSignInWithWebUI() //google登录
            }
    }

func socialSignInWithWebUI() async {
    do {
        let signInResult = try await Amplify.Auth.signInWithWebUI(for: .google, presentationAnchor: UIApplication.shared.windows.first!)
        if signInResult.isSignedIn {
            print("Sign in succeeded")
        }
    } catch let error as AuthError {
        print("Sign in failed \(error)")
    } catch {
        print("Unexpected error: \(error)")
    }
}


func signOutGlobally() async {
        let result = await Amplify.Auth.signOut(options: .init(globalSignOut: true))
        guard let signOutResult = result as? AWSCognitoSignOutResult
        else {
            print("Signout failed")
            return
        }

        print("Local signout successful: \(signOutResult.signedOutLocally)")
        switch signOutResult {
        case .complete: break
            // handle successful sign out
        case .failed(let error): break
            // handle failed sign out
        case let .partial(revokeTokenError, globalSignOutError, hostedUIError): break
            // handle partial sign out
        }
    }
```

### Expected behavior

我希望Amplify有切换其他账号的功能， Amplify.Auth.signInWithWebUI( for: .google, presentationAnchor: UIApplication.shared.windows.first!) 能切换其他Google账号。

### Amplify Framework Version

2.29.1

### Amplify Categories

Auth

### Dependency manager

Swift PM

### Swift version

5.8

### CLI version

12+

### Xcode version

14.2

### Relevant log output

```shell
<details>
<summary>Log Messages</summary>


INSERT LOG MESSAGES HERE
```
</details>
```


### Is this a regression?

Yes

### Regression additional context

_No response_

### Platforms

_No response_

### OS Version

ios 13+

### Device

iPhone 8

### Specific to simulators

iPhone 14+ iOS15

### Additional context

_No response_

**Comment by ruisebas** [comment]
Hi @zhangshouyin. What you are describing is expected, as your app is "sharing" the session with Google.
Logging out of Identity Providers is not supported by Amplify.

If you wish to always show the Google login screen to your users, you can try setting the `preferPrivateSession` options:
```swift
try await Amplify.Auth.signInWithWebUI(
    presentationAnchor: self.view.window!,
    options: .preferPrivateSession()
) {
    ...
}
```

A similar discussion can be found here: https://github.com/aws-amplify/amplify-swift/issues/3593#issuecomment-2038048857

**Comment by zhangshouyin** [comment]
> Hi @zhangshouyin. What you are describing is expected, as your app is "sharing" the session with Google. Logging out of Identity Providers is not supported by Amplify.
> 
> If you wish to always show the Google login screen to your users, you can try setting the `preferPrivateSession` options:
> 
> ```swift
> try await Amplify.Auth.signInWithWebUI(
>     presentationAnchor: self.view.window!,
>     options: .preferPrivateSession()
> ) {
>     ...
> }
> ```
> 
> A similar discussion can be found here: [#3593 (comment)](https://github.com/aws-amplify/amplify-swift/issues/3593#issuecomment-2038048857)

@ruisebas  thank you , I got it.
