### ISSUE TITLE
Amplify SwitUI - Auth Signout documentation error

### ISSUE THREAD

**Issue by tarunsunny3** [aws-amplify/amplify-swift#3711]
https://docs.amplify.aws/gen1/swift/build-a-backend/auth/sign-out/

In the given signOutLocally method
`
func signOutLocally() async {
    let result = await Amplify.Auth.signOut()
    guard let signOutResult = result as? AWSCognitoSignOutResult
    else {
        print("Signout failed")
        return
    }

    print("Local signout successful: \(signOutResult.signedOutLocally)")
    switch signOutResult {
    case .complete:
        // Sign Out completed fully and without errors.
        print("Signed out successfully")

    case let .partial(revokeTokenError, globalSignOutError, hostedUIError):
        // Sign Out completed with some errors. User is signed out of the device.
        
        if let hostedUIError = hostedUIError {
            print("HostedUI error  \(String(describing: hostedUIError))
        }

        if let globalSignOutError = globalSignOutError {
            // Optional: Use escape hatch to retry revocation of globalSignOutError.accessToken.
            print("GlobalSignOut error  \(String(describing: globalSignOutError))
        }

        if let revokeTokenError = revokeTokenError {
            // Optional: Use escape hatch to retry revocation of revokeTokenError.accessToken.
            print("Revoke token error  \(String(describing: revokeTokenError))
        }

    case .failed(let error):
        // Sign Out failed with an exception, leaving the user signed in.
        print("SignOut failed with \(error)")
    }
}`

the print statements are not properly enclosed. 
**They are supposed to end with )"**

**Comment by thisisabhash** [comment]
Thank you for posting this - we have created a PR to resolve this and will post updates here.

**Comment by thisisabhash** [comment]
This has been merged to `main` and reflecting on the docs website.
