### ISSUE TITLE
Real-time event subscriptions do not working when the app is in the background.

### ISSUE THREAD

**Issue by Santosh2332** [aws-amplify/amplify-swift#3756]
iOS real-time event subscriptions do not working when the app is in the background.
Issue Description: When subscribing to real-time events using the Amplify API, the callback functions work fine when the app is in the foreground. However, once the app is moved to the background, the callbacks are not triggered. I have also enabled background mode from Xcode capabilities, but the issue persists.

Amplify Version: -- 12.12.2

Sample Code: {

```
func createSubscription() {
        subscription = Amplify.API.subscribe(request: .subscription(of: Todo.self, type: .onCreate))
        Task {
            do {
                if let subscriptions = subscription {
                    for try await subscriptionEvent in subscriptions {
                        switch subscriptionEvent {
                        case .connection(let subscriptionConnectionState):
                            print("Subscription connect state is \(subscriptionConnectionState)")
                        case .data(let result):
                            switch result {
                            case .success(let createdTodo):
                                isOnCreateSubscriptionEstablished = true
                                print("Successfully got todo from subscription: \(createdTodo)")
                            case .failure(let error):
                                print("Got failed result with \(error.errorDescription)")
                            }
                        }
                    }
                }
            } catch {
                print("Subscription has terminated with \(error)")
            }
        }
    }
}

```
}

_Originally posted by @Santosh2332 in https://github.com/aws-amplify/amplify-swift/issues/3437#issuecomment-2175882384_

**Comment by 5d** [comment]
Hi @Santosh2332 ,

Thanks for opening the issue.

This behavior is expected. The real-time event subscription relies on a WebSocket connection, but Apple does not support running URLSessionWebSocketTask in the background.

refs:
 - https://forums.developer.apple.com/forums/thread/723657
 - https://forums.developer.apple.com/forums/thread/716118
 - https://developer.apple.com/forums/thread/85066
 - https://developer.apple.com/documentation/foundation/urlsessionwebsockettask
