### ISSUE TITLE
iOS App Using AWS Amplify DataStore Does Not Receive Subscriptions for Deletes Made via AWS Lambda

### ISSUE THREAD

**Issue by rohit3d2003** [aws-amplify/amplify-swift#3759]
### Describe the bug

I'm using an AWS Amplify generated GraphQL API in my iOS application, which is configured to operate in offline mode using the DataStore approach. Additionally, I have several AWS Lambda functions that directly call AppSync queries and mutations to make changes to the data.

**Problem**:

When an object is deleted via an AWS Lambda function, the iOS app does not receive any subscription notifications, and the DataStore does not get updated with these changes. Specifically:

1. Deleting an object via Lambda does not trigger a subscription update in the iOS app.
2. Amplify verbose logging in Xcode does not show any errors related to this issue.
3. Restarting the app does not help; the app still shows the deleted records in the UI, which are supposed to be filtered out.

I am not sure if the auth rule on the model plays any part in it. So the record was created by owner but deleted by Admin from Lambda. Owner who is logged in to the iOS app not receiving these delete subscriptions/notifications.

![Screenshot 2024-06-20 at 8 05 11 AM](https://github.com/aws-amplify/amplify-swift/assets/16943885/e1558ef6-ec24-4e30-ad87-da0683ed8be7)

### Steps To Reproduce

```swift
1. Set up an AWS Amplify project with a GraphQL API and DataStore enabled in an iOS app.
2. Create a few AWS Lambda functions that perform AppSync queries and mutations.
3. Use one of the Lambda functions to delete an object in the database.
5. Observe that the iOS app does not receive any subscription updates about the deletion.
6. Verify that the DataStore does not reflect the deletion, even after restarting the app.
```

### Expected behavior

When an object is deleted via an AWS Lambda function, the iOS app should:

1. Receive a subscription notification about the deletion.
2. Update the local DataStore to reflect the deletion.
3. Update the UI to filter out and remove the deleted records.

### Amplify Framework Version

2.35.3

### Amplify Categories

DataStore

### Dependency manager

Swift PM

### Swift version

5.0

### CLI version

12.12.2

### Xcode version

15.4

### Is this a regression?

Yes

### Platforms

iOS

### OS Version

17.5

### Device

iPhone 15

**Comment by rohit3d2003** [comment]
I did more testing and seems like Subscriptions works for create operation but update and delete aren't working.

**Comment by 5d** [comment]
Hi @rohit3d2003 

Have you checked whether the records are updated or deleted in DynamoDB after the admin Lambda function was invoked?
Have you set up [conflict resolution](https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html#conflict-detection-and-resolution) in AWS AppSync?

**Comment by rohit3d2003** [comment]
> Hi @rohit3d2003
> 
> Have you checked whether the records are updated or deleted in DynamoDB after the admin Lambda function was invoked? Have you set up [conflict resolution](https://docs.aws.amazon.com/appsync/latest/devguide/conflict-detection-and-sync.html#conflict-detection-and-resolution) in AWS AppSync?

Yes, the records did get updated/deleted in dynamodb and they do show up if I restart the app.

**Comment by rohit3d2003** [comment]
> Thanks for providing that information too. To help us debug further, would you be able to provide any of the following?
> 
> 1. The logs you see in the console when the error happens. You can enable verbose logging to the console by doing this before calling `Amplify.configure`:
> 
> ```
> Amplify.Logging.logLevel = .verbose
> ```
> 
>  2. The contents of your amplify configuration file with sensitive information removed.

I am not seeing any activity in XCode console during updates/deleted with verbose logging. Only creates do show some activity in the console.

Amplify Config
![Screenshot 2024-06-21 at 10 53 49 AM](https://github.com/aws-amplify/amplify-swift/assets/16943885/6ea06955-234a-44c8-9a8e-a808ea48d081)

![Screenshot 2024-06-21 at 10 56 43 AM](https://github.com/aws-amplify/amplify-swift/assets/16943885/89aa7423-3d7f-408e-b334-715d307a15a9)

**Comment by rohit3d2003** [comment]
To provide more context, in lambda function, I am signing in using Admin credentials and using the JWT token while calling the app sync apis so that from App Sync perspective, an Admin is making the change

**Comment by 5d** [comment]
Hi @rohit3d2003 ,

How do you compose your GraphQL mutations to AppSync?

Please keep in mind that the selection set of the GraphQL mutation should align with the GraphQL selection set of the subscription used by Amplify DataStore. This is crucial because there might be filters applied to the subscription to help Amplify filter real-time events from the AppSync real-time data server. Additionally, the subscription could include metadata fields that are necessary for Amplify DataStore to accurately parse the subscription event.

Based on the GraphQL schema you provided, I suspect that the Amplify DataStore subscription includes a filter on the owner field. It might look something like this:

```
subscription OnCreateBlog($owner: String!) {
  onCreateBlog(owner: $owner) {
    id
    createdAt
    updatedAt
    __typename
    _version
    _deleted
    _lastChangedAt
    owner
  }
}


variables: {"owner":"test-user"}
```

To ensure that Amplify successfully filters data events from the AppSync real-time data server, it is crucial to align the selection set in your GraphQL request with that of the Amplify DataStore subscription. Therefore, it better to be:
```
mutation CreateBlog($input: CreateBlogInput!) {
  createBlog(input: $input) {
    id
    createdAt
    updatedAt
    __typename
    _version
    _deleted
    _lastChangedAt
    owner    
  }
}

variables: {
  "input" : {
    "id" : "12DDF815-22B1-4B2F-AE77-14D736C8F98E"
  }
}
```

**Comment by rohit3d2003** [comment]
Thanks @5d! That was it, I was missing owner field in update and delete mutation and hence probably subscriptions were not received nor any error was showing up in console. This is fixed now
