### ISSUE TITLE
DataStore in Amplify Gen 2

### ISSUE THREAD

**Issue by wilfredbtan** [aws-amplify/amplify-swift#3764]
### Is your feature request related to a problem? Please describe.

I used DataStore to create an offline-first app in gen 1 but it seems that gen 2 doesn't support Datastore yet as stated in the doc's FAQs:

```
Does Amplify Gen 2 support DataStore?

Amplify Gen 2 supports GraphQL APIs without DataStore. We will release migration support for moving DataStore Gen 1 apps to Gen 2.
````

### Describe the solution you'd like

Can Gen 2 support DataStore or provide another way to built an offline-first app?

### Describe alternatives you've considered

I've tried adding DataStore to the basic Todo app from the quickstart but it resulted in this error message:

```
Failed to emit ready event, error: DataStoreError: One or more errors occurred syncing models. See below for detailed error description.
Recovery suggestion: DataStoreError: An error occurred syncing Todo
Caused by:
DataStoreError: GraphQL service returned a successful response containing errors: [Amplify.GraphQLError(message: "Validation error of type FieldUndefined: Field \'syncTodos\' in type \'Query\' is undefined @ \'syncTodos\'", locations: Optional([Amplify.GraphQLError.Location(line: 2, column: 3)]), path: nil, extensions: nil)]
Recovery suggestion: The list of `GraphQLError` contains service-specific messages
```

### Is the feature request related to any of the existing Amplify categories?

DataStore

**Comment by ruisebas** [comment]
Hi @wilfredbtan, thanks for opening this.

We currently do not have plans to add DataStore support in Amplify Gen2, besides from the migration support from Gen1 to Gen2 that is mentioned in the FAQ.

**Comment by wilfredbtan** [comment]
@ruisebas Understood. Thanks for the clarification :D

**Comment by zaid-themedcompany** [comment]
Hi, just checking on this again. Are you saying that Amplify Gen 2 will never support offline-first approach? can you please confirm? as this is currently a major blocker for us for not upgrading to Gen2, many thanks

**Comment by fabriquetonvoyage** [comment]
> Hi @wilfredbtan, thanks for opening this.
> 
> We currently do not have plans to add DataStore support in Amplify Gen2, besides from the migration support from Gen1 to Gen2 that is mentioned in the FAQ.

Hi @ruisebas, where is the migration guide / support for Gen1 Datastore app ? I'm waiting for it since long time ...

**Comment by OperationalFallacy** [comment]
I think there won't be any migration guide. Gen1 is so convoluted and tangled that the best approach is to copy/paste code, then reproduce backend.

Then update front-end... which is where I'm right now seeing all the errors from DataStore lib. Planning to rip it off and then migrate (copy) data manually.

All this is not very complicated, just tedious. But the radio silence from Amplify team on the direction and any guidance is concerning. Amplify gen1 is a dead end and they should help customers get off of it.

**Comment by sgandon** [comment]
the Datastore features for working offline and simply caching locally the datamodel is such a great valuable feature that I am surprised it will not be supported by AWS.
But it may help reduce the number of calls to the backend and therefore reduce the income for AWS but I believe that would be a pity.

**Comment by zaid-themedcompany** [comment]
I totally agree with @sgandon about this, definitely having a datastore that caches both data from the API and the Cognito (user details) will be a wonderful thing to have. Actually this is the only reason stopping me from moving to Gen 2 (I do acknowledge that https://tanstack.com/query can be used with Amplify, but I am not sure if I like to have the mutations definitions and queries as part of the component (as per their documentation), I know I can have it separated but there was plenty of trial and error to resist the original intention design of tanstack

**Comment by OperationalFallacy** [comment]
@zaid-themedcompany looks like the direction Amplify quietly heading is local cashing with custom solutions

https://www.youtube.com/watch?v=-DcX0i9JYCM
https://github.com/aws-samples/offline-blog-title-creator
