### ISSUE TITLE
Need to pass API-Key dynamically through APIPlugins in iOS

### ISSUE THREAD

**Issue by Santosh2332** [aws-amplify/amplify-swift#3790]
### Is your feature request related to a problem? Please describe.

I have added awsconfiguration.json file in my project for configuration, now  i need to pass API Key dynamically to configure amplify  like below code(OIDC Auth)

```
class MyAPIAuthProviderFactory: APIAuthProviderFactory {
    let myAuthProvider = MyOIDCAuthProvider()

    override func oidcAuthProvider() -> AmplifyOIDCAuthProvider? {
        return myAuthProvider
    }
}

class MyOIDCAuthProvider : AmplifyOIDCAuthProvider {
    func getLatestAuthToken() async throws -> String {
       ....
    }
}

try Amplify.add(plugin: AWSAPIPlugin(apiAuthProviderFactory: MyAPIAuthProviderFactory()))
```

**Is there Any way to configure API-Key from my end like above example.**

### Describe the solution you'd like

Need to configure API-Key from project Swift class

### Describe alternatives you've considered

Provide any alternative from your end

### Is the feature request related to any of the existing Amplify categories?

API

**Comment by Santosh2332** [comment]
If it a feature request, can i aspect any solution from your end please. I need to implement it in my current project.

**Comment by ruisebas** [comment]
Hi @Santosh2332, thanks for opening this.

I'm a bit confused by what your describing. [**API Key**](https://docs.amplify.aws/gen1/swift/build-a-backend/graphqlapi/customize-authz-modes/#api-key) and [**OpenID Connect (OIDC)**](https://docs.amplify.aws/gen1/swift/build-a-backend/graphqlapi/customize-authz-modes/#openid-connect-oidc) are two separate and independent [Authorization Types supported by **AppSync**](https://docs.aws.amazon.com/appsync/latest/devguide/security-authz.html).

Could you please clarify your use case, or what are you trying to achieve?

---- 

Perhaps unrelated, but you've mentioned adding the `awsconfiguration.json` file to your project for configuration. 
Keep in mind that Amplify does not use that file, it uses [`amplifyconfiguration.json` for Gen1](https://docs.amplify.aws/gen1/swift/build-a-backend/graphqlapi/customize-authz-modes/#manual-configuration), and [`amplify_outputs.json` for Gen2](https://docs.amplify.aws/swift/build-a-backend/data/set-up-data/#connect-your-application-code-to-the-data-backend).

**Comment by Santosh2332** [comment]
Hi @ruisebas thanks for the reply.

I am using API_Key for amplify configuration that is configure in awsconfiguration.json file.
Now my requirement is to pass api key at run time, through plugin or any custome configuration, is it possible, if yes then please provide me the way.

Thanks,
Santosh Kumar

**Comment by ruisebas** [comment]
If you're relying on the `amplifyconfiguration.json` file to configure Amplify, then you cannot just overwrite **AWSAPIPlugin**'s `apiKey` value.

What you can do is create your own `AmplifyConfiguration` instance and set the key in there. However you will need to replicate the configuration for **all the plugins your use**.

Here's a simple example:

```swift
let apiKey: JSONValue = "YOUR API KEY"
let configuration = AmplifyConfiguration(
    api: .init(plugins: [
        "awsAPIPlugin" : [
            "[API NAME]": [
                "endpointType": "ENDPOINT TYPE]",
                "endpoint": "[ENDPOINT URL]",
                "region": "[REGION]",
                "authorizationType": "API_KEY",
                "apiKey": apiKey
            ]
        ]
    ]),
    // Add the remaining categories...
)

try Amplify.add(plugin: AWSAPIPlugin())
// Add the remaining plugins 

try Amplify.configure(configuration)
```

--- 

Alternatively, if you don't want to manually recreate the whole file because you have lots of plugins and/or properties, you can just parse the `amplifyconfiguration.json` into your own type, edit the corresponding `api` section and then create an updated `AmplifyConfiguration` instance:

```swift
struct MyConfiguration: Decodable {
    // You can omit categories that you don't use
    var analytics: AnalyticsCategoryConfiguration?
    var api: APICategoryConfiguration?
    var auth: AuthCategoryConfiguration?
    var dataStore: DataStoreCategoryConfiguration?
    var geo: GeoCategoryConfiguration?
    var hub: HubCategoryConfiguration?
    var logging: LoggingCategoryConfiguration?
    var notifications: NotificationsCategoryConfiguration?
    var predictions: PredictionsCategoryConfiguration?
    var storage: StorageCategoryConfiguration?

    init() throws {
        guard let url = Bundle.main.url(forResource: "amplifyconfiguration", withExtension: "json") else {
            throw ConfigurationError.invalidAmplifyConfigurationFile(
                "Unable to read amplifyconfiguration.json",
                "Make sure the file is present in the bundle"
            )
        }
        let data = try Data(contentsOf: url)
        self = try JSONDecoder().decode(MyConfiguration.self, from: data)
    }

    func createAmplifyConfiguration() -> AmplifyConfiguration {
        return .init(
            analytics: analytics,
            api: api,
            auth: auth,
            dataStore: dataStore,
            geo: geo,
            hub: hub,
            logging: logging,
            notifications: notifications,
            predictions: predictions,
            storage: storage
        )
    }
}
```
```swift
let apiKey: JSONValue = "YOUR API KEY"
var configuration = try MyConfiguration()
// Overwrite only the API category configuration, there's no need to do anything for the remaining ones
configuration.api = .init(plugins: [
    "awsAPIPlugin" : [
        "[API NAME]": [
            "endpointType": "ENDPOINT TYPE]",
            "endpoint": "[ENDPOINT URL]",
            "region": "[REGION]",
            "authorizationType": "API_KEY",
            "apiKey": apiKey
        ]
    ]
])

try Amplify.add(plugin: AWSAPIPlugin())
// Add the remaining plugins 
try Amplify.configure(configuration.createAmplifyConfiguration())
```

**Comment by Santosh2332** [comment]
@ruisebas Thank you.
