### ISSUE TITLE
[AnalyticsPlugin] `Configure` unit test requires network connectivity

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-swift#437]
refactor plugin configure code out into unit-testable chunks and/or move to integration test

**Comment by lawmicha** [comment]
this is fairly minor and is already covered by the integration test that it configures correctly. we can remove this test completely instead of skipping it when addressing code coverage

**Comment by lawmicha** [comment]
this is the test that should be updated: https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/Analytics/AWSPinpointAnalyticsPluginTests/AWSPinpointAnalyticsPluginConfigureTests.swift#L22

we could add a struct to hold the config values instead of relying on the JSONValue and running Amplify.configure, then we can isolate the test to just verifying that the struct can be created from the inputs

**Comment by royjit** [comment]
Closing this issue since it is addressed with the new release
