### ISSUE TITLE
Analytics rename `identityId` parameter to `userId`

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-swift#466]
https://github.com/aws-amplify/amplify-ios/blob/64c5ad75e4591278a1769690757b79074e9c38a8/Amplify/Categories/Analytics/AnalyticsCategoryBehavior.swift#L18

**Comment by raheel** [comment]
Should the change be only made to `AnalyticsCategoryBehavior.swift `and `AnalyticsCategory+ClientBehavior.swift` from the `Amplify/Categories/Analytics` category or should it also include files from the `AWSPinpointAnalyticsPlugin`  project as well?

**Comment by lawmicha** [comment]
Hi @raheel, yes this should be done at the category level and at the plugin's implementation. Since this requires some cordination across platforms for the category change and since it's also a breaking change, i'm going to remove this as a good first issue and mark it under milestone 2.0.0

**Comment by royjit** [comment]
Released in [v2.0.0](https://github.com/aws-amplify/amplify-swift/releases/tag/v2.0.0)
