### ISSUE TITLE
Generated models not compatible with UICollectionViewDiffableDataSource

### ISSUE THREAD

**Issue by mickeysox** [aws-amplify/amplify-swift#521]
**Is your feature request related to a problem? Please describe.**

The generated swift models that amplify produces are not compatible with UICollectionViewDiffableDataSource as they do not conform to Hashable

```
fileprivate var datasource: UICollectionViewDiffableDataSource<Section, User>! = nil

Error: Type 'User' does not conform to protocol 'Hashable'
```

**Describe the solution you'd like**

Could we please conform generated models to Hashable?

**Describe alternatives you've considered**
The current solution to this is to extend the class to be hashable:

```
//
//  User+Hashable.swift
//  FullStackSocial
//
//  Created by Develoment on 04/06/2020.
//  Copyright © 2020 Develoment. All rights reserved.
//

import Foundation

extension User: Hashable {
    
    var identifier: String {
        return UUID().uuidString
    }
    
    public func hash(into hasher: inout Hasher) {
        return hasher.combine(identifier)
    }
    
    public static func == (lhs: User, rhs: User) -> Bool {
        return lhs.identifier == rhs.identifier
    }
}
```

**Additional context**

**Comment by afern247** [comment]
I'm also facing the same problem, I want to store in a @Publish diccionary a Model and I can't because it's not Hashable, please fix this.

**Comment by lawmicha** [comment]
Since there isn't more discussion going on in this issue, I've referenced this issue in https://github.com/aws-amplify/amplify-swift/issues/593 to keep the history, while keeping https://github.com/aws-amplify/amplify-swift/issues/593 as the main feature request with all the details.
