### ISSUE TITLE
Integrate Storage with DataStore

### ISSUE THREAD

**Issue by amuresia** [aws-amplify/amplify-swift#537]
I have a use case where I create users via DataStore and I want to store their avatars in S3.

I would like a secure solution for retrieving a `.protected` avatar so that other users of the applications can see it.

At the moment I am using something like this:
```
type User
@model
{
  id: ID!
  picture: Picture!
}

type Picture @model {
  identityId: String!
  fileName: String!
}
```
As you can see, I store `identityId` in the object so that `Storage.download` can retrieve it from S3.

**Comment by palpatim** [comment]
We will provide a code sample that shows how we can accomplish this in the absence of baked-in support.

**Comment by ksp17788** [comment]
Any update on this or a work around that you suggest ?

**Comment by lawmicha** [comment]
We are currently working on some documentation here: https://github.com/aws-amplify/docs/pull/5649 Please see "working with files" section

**Comment by lawmicha** [comment]
Related issue, another customer also looking for this support: https://github.com/aws-amplify/amplify-swift/issues/799

**Comment by lawmicha** [comment]
Related https://github.com/aws-amplify/amplify-swift/issues/1517

**Comment by lawmicha** [comment]
please see https://docs.amplify.aws/swift/build-a-backend/graphqlapi/working-with-files/ for guidance on working with files
