### ISSUE TITLE
How can I fetch the sorted data using the DynamoDB Global Secondary Index?

### ISSUE THREAD

**Issue by hirokim** [aws-amplify/amplify-swift#565]
How can I fetch the sorted data using the DynamoDB Global Secondary Index?
Is it "Amplify.DataStore.query"? Or is it "Amplify.API.query"? Or is it another way?

schema.graphql is:
```
type GameScore
@model
@key(fields: ["userId", "gameId"])
@key(name: "rankingIndex", fields: ["gameId", "score"], queryField: "rankingQuery")
{
  userId: String!
  gameId: String!
  score: Int!
}
```

I hope you will be able to provide the information.
Thanks.

**Comment by wooj2** [comment]
Hi @hirokim 

If I understand you correctly, I believe you are using Amplify.Datastore and are looking to have the ability to sort items when doing a query.

For example, you are looking for something like a `sortedBy` parameter:
```
let p = GameScore.keys
Amplify.DataStore.query(GameScore.self,

//predicate to filter (this is currently supported)
         where: p.score > 4,

//some expression which gets executed to sort items
        sortedBy: { $0.score < $1.score}  
                                            )
{ result in
   switch (result) {
    ........
   }
}
```
If this is what you are looking for, then unfortunately, it is not currently supported.  But, the good news is that there are some plans to support something like this in the future.  (Note that the interface above is for demonstration purposes only and has not been determined yet)

**Comment by hirokim** [comment]
Hello @wooj2 
That feature helps me a lot.
I am looking forward to the addition of that function.
but I'm not particular about Amplify.Datastore.
I want to know how to use GSI with Amplify iOS.

**Comment by royjit** [comment]
Please find a similar github issue here and solution - https://github.com/aws-amplify/amplify-swift/issues/1435
