### ISSUE TITLE
Change MutationEvent.mutationType to type MutationType

### ISSUE THREAD

**Issue by Kilo-Loco** [aws-amplify/amplify-swift#572]
**Is your feature request related to a problem? Please describe.**
This is not a problem, but more of a preference. `MutationEvent.mutationType` is currently of type `String`. This means that the dev has to switch based on a `String` value, which is prone to errors due to incorrect spelling.
```swift
switch changes.mutationType {
  case "create":
      // create object

  case "update":
    // update object

  case "delete":
    // delete object

  default:
    break
}
```

**Describe the solution you'd like**
It would be nice if `MutationEvent.mutationType` was of type `MutationType`. This would allow the dev to switch based on all possible types and would prevent the possibility of misspelled cases.
```swift
switch changes.mutationType {
  case .create:
      // create object

  case .update:
    // update object

  case .delete:
    // delete object
}
```

**Describe alternatives you've considered**
Since this doesn't work right out the box, I could simply add this functionality as an extension to `MutationEvent`, but forcing devs to do this for each project seems less than ideal.

**Additional Context**
While the name suggests that it would be of type `MutationType`, the most important thing is to have some property, regardless of the name, that allows the dev to `switch` efficiently and make decisions based on the incoming `MutationEvent`.

**Comment by palpatim** [comment]
Changing the type will be a breaking change, so if/when we take this on, we'll want to introduce a new property of the appropriate type, and deprecate the old string-based one. It's possible that we'd need a `custom` type at some point in the future, to handle mutations outside of a strict model-based schema, that might have multiple side effects (e.g., create and update; delete and update, etc), but we'll want to wait until we have an actual customer use case before we add surface area.

**Comment by thisisabhash** [comment]
This has been implemented in the latest code. 

https://github.com/aws-amplify/amplify-swift/blob/main/Amplify/Categories/DataStore/Subscribe/MutationEvent%2BMutationType.swift
