### ISSUE TITLE
Predictions.identify detect labels requires casting when handling result

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-swift#573]
**Is your feature request related to a problem? Please describe.**
When using `Amplify.Predictions.identify(type: .detectLabels(.labels), image: image)`, in my result i have to cast it to `IdentifyLabelsResult`

```
switch event {
   case .success(let result);
      guard let data = result as? IdentifyLabelsResult else {
       ...
```

**Describe the solution you'd like**
An API where I do not have to cast.

**Additional context**
This impacts other Prediction API designs as well

**Comment by atierian** [comment]
All Predictions APIs now return concrete types; casting is no longer necessary.

Docs: https://docs.amplify.aws/lib/predictions/identify-text/q/platform/ios/#set-up-the-backend
Release: [2.9.0](https://github.com/aws-amplify/amplify-swift/releases/tag/2.9.0)
