### ISSUE TITLE
Per-field @auth terminates subscriptions instead of setting field to null

### ISSUE THREAD

**Issue by jimkqwantegy** [aws-amplify/amplify-swift#673]
**Describe the bug**
Given a multi @auth schema (abbreviated):
type Location
    @model
    @auth(
    rules: [
        { allow: owner,  operations: [create, update, delete, read] },
        { allow: private, provider: iam, operations: [create, update, delete, read] },
        { allow: groups, groups: ["Admins"] },
        { allow: groups, groups: ["Users"], operations: [read]  },
    ])
    @searchable {
  id: ID!
  owner: String
  name: String!
  clientUUID: String @auth(rules: [{ allow: owner}, { allow: private, provider: iam}, { allow: groups, groups: ["Admins"] }])
  clientId: String @auth(rules: [{ allow: owner}, { allow: private, provider: iam }, { allow: groups, groups: ["Admins"] }])
  clientSecret: String @auth(rules: [{ allow: owner}, { allow: private, provider: iam}, { allow: groups, groups: ["Admins"] }])
  ratings: Int
  rating: Float @auth(rules: [{ allow: private, provider: iam}, { allow: groups, groups: ["Admins"] }, { allow: groups, groups: ["Users"], operations: [read] }])
}

Subscriptions terminate due to unauthorized access for the specific fields. Why not set these fields to null and continue? This is what is implied in documentation: https://docs.amplify.aws/cli/graphql-transformer/directives#field-level-authorization in "Per-Field with subscriptions" section.

2020-07-25 20:24:11.001541-0400 ReGroup[25243:6464607] [InitialSyncOperation] Beginning sync for Account
2020-07-25 20:24:11.178240-0400 ReGroup[25243:6464625] [InitialSyncOperation] Beginning sync for Location
2020-07-25 20:24:11.415044-0400 ReGroup[25243:6464651] [InitialSyncOperation] Beginning sync for User
2020-07-25 20:24:11.579121-0400 ReGroup[25243:6464605] [InitialSyncOperation] Beginning sync for UserLocation
2020-07-25 20:24:11.719556-0400 ReGroup[25243:6464651] [RemoteSyncEngine] One or more errors occurred syncing models. See below for detailed error description.
2020-07-25 20:24:11.719758-0400 ReGroup[25243:6464651] [RemoteSyncEngine] DataStoreError: An error occurred syncing Location
Caused by:
DataStoreError: GraphQL service returned a partially-successful response containing errors: [Amplify.GraphQLError(message: "Not Authorized to access clientId on type String", locations: Optional([Amplify.GraphQLError.Location(line: 8, column: 7)]), path: Optional([Amplify.JSONValue.string("syncLocations"), Amplify.JSONValue.string("items"), Amplify.JSONValue.number(0.0), Amplify.JSONValue.string("clientId")]), extensions: Optional(["data": Amplify.JSONValue.null, "errorType": Amplify.JSONValue.string("Unauthorized"), "errorInfo": Amplify.JSONValue.null])), Amplify.GraphQLError(message: "Not Authorized to access clientSecret on type String", locations: Optional([Amplify.GraphQLError.Location(line: 9, column: 7)]), path: Optional([Amplify.JSONValue.string("syncLocations"), Amplify.JSONValue.string("items"), Amplify.JSONValue.number(0.0), Amplify.JSONValue.string("clientSecret")]), extensions: Optional(["errorType": Amplify.JSONValue.string("Unauthorized"), "errorInfo": Amplify.JSONValue.null, "data": Amplify.JSONValue.null])), Amplify.GraphQLError(message: "Not Authorized to access clientUUID on type String", locations: Optional([Amplify.GraphQLError.Location(line: 10, column: 7)]), path: Optional([Amplify.JSONValue.string("syncLocations"), Amplify.JSONValue.string("items"), Amplify.JSONValue.number(0.0), 
...

To further illustrate issue, there is no error generated about the "rating" field as Users have read access.

**To Reproduce**
Create graphql api with similar schema, authenticate as user in "Users" group. Launch application to start subscriptions.

**Expected behavior**
Expectation for a subscription if in "Users" group would be to receive subscriptions for Location objects with clientUUID field set to null as indicated in documentation. 

**Screenshots**
Not helpful in this case... error log shows subscriptions failing due to the issue.

**Environment(please complete the following information):**
Swift version 5
Relevant items from Podfile.lock:
  - Amplify (1.0.4):
    - Amplify/Default (= 1.0.4)
  - Amplify/Default (1.0.4)
  - Amplify/Tools (1.0.4)
  - AmplifyPlugins/AWSAPIPlugin (1.0.4):
    - AppSyncRealTimeClient (~> 1.1.0)
    - AWSAuthCore (~> 2.14.0)
    - AWSCore (~> 2.14.0)
    - AWSPluginsCore (= 1.0.4)
    - ReachabilitySwift (~> 5.0.0)
  - AmplifyPlugins/AWSCognitoAuthPlugin (1.0.4):
    - AWSAuthCore (~> 2.14.0)
    - AWSCore (~> 2.14.0)
    - AWSMobileClient (~> 2.14.0)
    - AWSPluginsCore (= 1.0.4)
  - AmplifyPlugins/AWSDataStorePlugin (1.0.4):

**Device Information (please complete the following information):**
iPhone 11 simulator and iPhone 11 device.

**Additional context**
The intent is for users to be able to read Locations while having sensitive data redacted.

**Comment by jimkqwantegy** [comment]
Interesting note... The error does not occur any longer on Simulator iPhone 11 (13.5) after upgrading to Amplify 1.0.5, but continues to occur on an iPhone 11 Pro Max device (13.5.1). I believe this was happening on both simulator and device earlier before upgrading to 1.0.5.

**Comment by lawmicha** [comment]
hi @jimkqwantegy, currently we have not tested support for `{ allow: private, provider: iam, operations: [create, update, delete, read] },` or the `@searchable` so it will be difficult to debug this issue. We do support auth rules with allow `owner` and static `groups`. I'll mark this as a follow up to provide more details regarding your use case.

**Comment by jimkqwantegy** [comment]
The use case is that asynchronous business logic needs access to these fields from other AWS services using IAM, while other Cognito groups should not have visibility whatsoever. This seems to work well at the entity level but breaks at the field level. Could probably abstract these fields to another entity but documentation implied this was possible.

**Comment by drochetti** [comment]
@jimkqwantegy we're currently reviewing the implementation of the `@auth` across all platforms and I'll keep you posted. Unfortunately I don't have an update right now.

Quick question, is your field protected with `@auth` required?

**Comment by jimkqwantegy** [comment]
Hi Daniel,

Yes… That model looks like the following, but the rules have been loosened a bit so things will work. In actuality, the Users group wouldn’t be able to read, etc…

Thanks
Jim


type Location

    @model

    @auth(

    rules: [

        { allow: owner, ownerField: "owner", operations: [create, update, delete, read] },

        { allow: groups, groupsField: "locationAccountId", operations: [create, update, delete, read] },

        { allow: private, provider: iam, operations: [create, update, delete, read] },

        { allow: groups, groups: ["Admins"] },

        { allow: groups, groups: ["Owners"] },

        { allow: groups, groups: ["Users"], operations: [read]  },

    ])

    @searchable {

  id: ID!

  owner: String

  locationAccountId: ID!

  name: String!

  address: String!

  region: String

  country: String

  coordinates: Coordinates

  status: Status

  api: String

  clientUUID: String @auth(rules: [{ allow: owner, ownerField: "owner"}, { allow: private, provider: iam}, { allow: groups, groupsField: "locationAccountId", operations: [read] }, { allow: groups, groups: ["Admins"] }, { allow: groups, groups: ["Users"], operations: [read] }])

  clientId: String @auth(rules: [{ allow: owner, ownerField: "owner"}, { allow: private, provider: iam }, { allow: groups, groupsField: "locationAccountId", operations: [read] }, { allow: groups, groups: ["Admins"] }, { allow: groups, groups: ["Users"], operations: [read] }])

  clientSecret: String @auth(rules: [{ allow: owner, ownerField: "owner"}, { allow: private, provider: iam}, { allow: groups, groupsField: "locationAccountId", operations: [read] }, { allow: groups, groups: ["Admins"] }, { allow: groups, groups: ["Users"], operations: [read] }])

  ratings: Int

  rating: Float @auth(rules: [{ allow: owner, ownerField: "owner"}, { allow: groups, groupsField: "locationAccountId", operations: [read] }, { allow: private, provider: iam}, { allow: groups, groups: ["Admins"] }, { allow: groups, groups: ["Users"], operations: [read] }])

  capacity: Int

  targetCapacity: Int

  currentCapacity: Int

  requiresAssessment: Boolean!

  requiresAuthentication: Boolean!

  requiresTemperature: Boolean

  requiresMask: Boolean

  requiredAccessControl: Boolean!

  entries: [EntryArray]

  type: LocationType

  dwellTime: Int

  account: Account @connection(fields: ["locationAccountId"])

}

**Comment by lawmicha** [comment]
Pasting schema to apply markdown
```
type Location
    @model
    @auth(
    rules: [

        { allow: owner, ownerField: "owner", operations: [create, update, delete, read] },
        { allow: groups, groupsField: "locationAccountId", operations: [create, update, delete, read] },
        { allow: private, provider: iam, operations: [create, update, delete, read] },
        { allow: groups, groups: ["Admins"] },
        { allow: groups, groups: ["Owners"] },
        { allow: groups, groups: ["Users"], operations: [read]  },
    ])
    @searchable {

  id: ID!
  owner: String
  locationAccountId: ID!
  name: String!
  address: String!
  region: String
  country: String
  coordinates: Coordinates
  status: Status
  api: String

  clientUUID: String @auth(rules: [{ allow: owner, ownerField: "owner"}, { allow: private, provider: iam}, { allow: groups, groupsField: "locationAccountId", operations: [read] }, { allow: groups, groups: ["Admins"] }, { allow: groups, groups: ["Users"], operations: [read] }])

  clientId: String @auth(rules: [{ allow: owner, ownerField: "owner"}, { allow: private, provider: iam }, { allow: groups, groupsField: "locationAccountId", operations: [read] }, { allow: groups, groups: ["Admins"] }, { allow: groups, groups: ["Users"], operations: [read] }])

  clientSecret: String @auth(rules: [{ allow: owner, ownerField: "owner"}, { allow: private, provider: iam}, { allow: groups, groupsField: "locationAccountId", operations: [read] }, { allow: groups, groups: ["Admins"] }, { allow: groups, groups: ["Users"], operations: [read] }])

  ratings: Int

  rating: Float @auth(rules: [{ allow: owner, ownerField: "owner"}, { allow: groups, groupsField: "locationAccountId", operations: [read] }, { allow: private, provider: iam}, { allow: groups, groups: ["Admins"] }, { allow: groups, groups: ["Users"], operations: [read] }])

  capacity: Int
  targetCapacity: Int
  currentCapacity: Int
  requiresAssessment: Boolean!
  requiresAuthentication: Boolean!
  requiresTemperature: Boolean
  requiresMask: Boolean
  requiredAccessControl: Boolean!
  entries: [EntryArray]
  type: LocationType
  dwellTime: Int
  account: Account @connection(fields: ["locationAccountId"])
}
```

**Comment by lawmicha** [comment]
The above schema contains a couple complex use cases which are in question of support:
1. containing multiple `@auth` rules, allow owner, private, groups
2. containing per field level `@auth` rule.

This is the set of use cases that have been tested for DataStore with `@auth` directive: https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/ios

If you'd like to use that schema right now, I'd say the the workaround is to disable conflict resolution, and make calls directly to AppSync using Amplify.API

**Comment by lawmicha** [comment]
We recently launched support for 1. containing multiple `@auth` rules on a single model. I'm not aware of the effort to support 2. per field level `@rule` rules on iOS at the moment.

**Comment by diegocstn** [comment]
@jimkqwantegy you can read more about Multiple Authorization types in DataStore [here](https://docs.amplify.aws/lib/datastore/setup-auth-rules/q/platform/ios#configure-multiple-authorization-types)

**Comment by thisisabhash** [comment]
Field level auth feature request is being tracked here:
https://github.com/aws-amplify/amplify-swift/issues/1749
