### ISSUE TITLE
[Predictions] Multiple `SelectionElement`s handling in `TextractResult`

### ISSUE THREAD

**Issue by ruiguoamz** [aws-amplify/amplify-swift#695]
**Is your feature request related to a problem? Please describe.**
See the image below, in cell (male and female selection), if multiple `selectionElement` occurs, the current model cannot handle it correctly

**Describe the solution you'd like**
Probably something like in each cell has multiple `keyValueSet`. In below example, `Key (text: Male): value (isSelected: false)` and `Key (text: Female): value (isSelected: true)` 

<img width="489" alt="Screen Shot 2020-08-06 at 11 36 52" src="https://user-images.githubusercontent.com/48600426/89569151-28c38a00-d7d9-11ea-8447-dec560dd8462.png">

**Comment by atierian** [comment]
If I understand the feature request correctly, I don't think this can be accomplished based on various combinations of `identify` queries and the corresponding responses from Amazon Textract. If anyone wants to see this feature request reopened, please comment here or open a new feature request with more details. Thanks.
