### ISSUE TITLE
Support or explicitly disallow cascade saves of GraphQL models

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-swift#729]
As noted in this code snippet https://github.com/aws-amplify/amplify-ios/blob/4cb4423a6eb3d46dc0caf4bf55392384b0e4acc8/AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model+GraphQL.swift#L48-L51

We do not currently support a "cascade save" of a graphql model--fields of type `.collection` must be saved separately from their parent.

We should either support it or explicitly disallow it. The mechanism by which we explicitly disallow it should be more robust than documentation.

**Comment by harsh62** [comment]
[Reference to the latest code](https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/Core/AWSPluginsCore/Model/Support/Model%2BGraphQL.swift#L76)
