### ISSUE TITLE
SyncEngine should inspect errors to determine retry advice

### ISSUE THREAD

**Issue by palpatim** [aws-amplify/amplify-swift#731]
As noted in the TODO in this code snippet https://github.com/aws-amplify/amplify-ios/blob/4cb4423a6eb3d46dc0caf4bf55392384b0e4acc8/AmplifyPlugins/DataStore/AWSDataStoreCategoryPlugin/Sync/RemoteSyncEngine+Retryable.swift#L31-L39

We do not currently respect error types when retrying sync errors; instead we always retry errors up to the limit, regardless of the incoming type. We should not retry error types that aren't considered retryable (e.g., 403, 404, etc)

**Comment by atierian** [comment]
It looks like this has been resolved through:
- #1773 
- #2571 

See [getRetryAdvice(error:) -> RequestRetryAdvice](https://github.com/aws-amplify/amplify-swift/blob/main/AmplifyPlugins/DataStore/Sources/AWSDataStorePlugin/Sync/RemoteSyncEngine%2BRetryable.swift#L31-L49) for current implementation.
