### ISSUE TITLE
How do I query on a @key (Global Secondary Index)?

### ISSUE THREAD

**Issue by bumbleparrot** [aws-amplify/amplify-swift#831]
**Describe the bug**
I have used the Amplify CLI to generate my GraphQL schema. The query and Schema work in the AWS AppSync Console. The DynamoDB tables are created and the query returns data via the online console.

My issue is that I have no idea how to query beyond the basic ".get(byId: [$id]" method via Amplify.API.query() inside of my iOS app using the Amplify Library.

**To Reproduce**
Below is my schema.
`
type Profile @model {
  id: ID!
  firstName: String
  lastName: String
  email: String
  socialProviderId: String
  socialProvider: String
  verified: Boolean
  address: [Address] @connection(name: "address", fields: ["id"])
  incident: [Incident] @connection(name: "incident", fields: ["id"])
  camera: [Camera] @connection(name: "camera", fields: ["id"])
}

type Address @model
@key(fields: ["id", "streetNumber"])
@key(name:"uniqueCode-index", fields:["uniqueCode"], queryField: "addressUniqueCode" )
@key(name:"geohashFirst6-index", fields:["geohashFirst6"], queryField: "addressGeohashFirst6" )
@key(name:"geohashLast5-index", fields:["geohashLast5"], queryField: "addressgGohashLast5" )
@key(name:"geohashLast4-index", fields:["geohashLast4"], queryField: "addressGeohashLast4" )
@key(name:"geohashLast3-index", fields:["geohashLast3"], queryField: "addressGeohashLast3" )
@key(name:"geohashLast2-index", fields:["geohashLast2"], queryField: "addressGeohashLast2" )
@key(name:"geohashLast1-index", fields:["geohashLast1"], queryField: "addressGeohashLast1" )
@key(name:"geohash-index", fields:["geohash"], queryField: "addressGeohash" )
@key(name:"latitude-index", fields:["latitude"], queryField: "addressLatitude" )
@key(name:"longitude-index", fields:["longitude"], queryField: "addressLongitude" )
{
  id: ID!
  createdAt: String
  geohash: String
  geohashFirst6: String
  geohashLast1: String
  geohashLast2: String
  geohashLast3: String
  geohashLast4: String
  geohashLast5: String
  geohashLast6: String
  latitude: Float
  longitude: Float
  state: String
  streetName: String
  streetNumber: Int!
  unit: String
  updatedAt: String
  zipCode: String
  cameras: [Camera] @connection(name: "cameras", fields: ["id"])
  claimed: Boolean
  userId: Profile @connection(name: "claimedBy", fields: ["id"])
  uniqueCode: String
}

type Camera @model
@key(fields: ["id"])
@key(name:"type-index", fields:["type"], queryField: "type" )
{
  id: ID!
  name: String
  type: String
  direction: String
  address: Address @connection(name: "atAddress", fields: ["id"])
}

type Incident @model
@key(fields: ["id"])
@key(name:"geohash-index", fields:["geohash"], queryField: "incidentGeohash" )
@key(name:"geohashFirst6-index", fields:["geohashFirst6"], queryField: "incidentGeohashFirst6" )
@key(name:"geohashLast5-index", fields:["geohashLast5"], queryField: "incidentGeohashLast5" )
@key(name:"geohashLast4-index", fields:["geohashLast4"], queryField: "incidentGeohashLast4" )
@key(name:"geohashLast3-index", fields:["geohashLast3"], queryField: "incidentGeohashLast3" )
@key(name:"geohashLast2-index", fields:["geohashLast2"], queryField: "incidentGeohashLast2" )
@key(name:"geohashLast1-index", fields:["geohashLast1"], queryField: "incidentGeohashLast1" )
@key(name:"latitude-index", fields:["latitude"], queryField: "incidentLatitude" )
@key(name:"longitude-index", fields:["longitude"], queryField: "incidentLongitude" )
{
  id: ID!
  dateTime: AWSDateTime
  geohash: String
  geohashFirst6: String
  geohashLast1: String
  geohashLast2: String
  geohashLast3: String
  geohashLast4: String
  geohashLast5: String
  geohashLast6: String
  latitude: Float
  longitude: Float
  title: String
  description: String
  userId: Profile @connection(name: "reportedBy", fields: ["id"])
}
`

**Expected behavior**
I should be able to query this without any issue right?

**Code**
I based my code on t[his example in the documents](https://docs.amplify.aws/lib/graphqlapi/advanced-workflows/q/platform/ios#subset-of-data) because I can't figure out any other obvious way to query the indexes i created in the schema.

Here is my code. that starts the Amplify.API.request
`
            Amplify.API.query(request: .getAddressByUniqueCode(uniqueCode: pinCode)) { response in
                switch(response) {
                case .success(let result):
                    switch(result) {
                    case .success(let address):
                        print("Address: \(address)")
                        break
                    case .failure(_):
                        print("getById - error: Error in result")
                        break
                    }
                    break
                case .failure(_):
                    print("getById - error: Error in response")
                    break
                }
`

Here is how i define .getAddressByUniqueCode
`
extension GraphQLRequest {
    static func getAddressByUniqueCode(uniqueCode uniqueCode: String) -> GraphQLRequest<Address> {
        let operationName = "addressUniqueCode"
        let document = """
        query addressUniqueCode($uniqueCode: String) {
          \(operationName)(uniqueCode: $uniqueCode) {
            nextToken
            items {
              geohashFirst6
              streetName
              streetNumber
              longitude
              state
              latitude
              id
              zipCode
              updatedAt
              unit
              uniqueCode
              geohashLast6
              geohashLast5
              geohashLast4
              geohashLast3
              geohashLast2
              geohashLast1
              geohash
              createdAt
              claimed
            }
          }
        }
        """
        
        return GraphQLRequest<Address>(document: document,
                                    variables: ["uniqueCode": uniqueCode],
                                    responseType: Address.self,
                                    decodePath: operationName)
    }
}
`

**The error I am getting is: No value associated with key CodingKeys(stringValue: \"id\", intValue: nil) (\"id\").** 

Is there an issue with my schema or how I queried it? The same query works fine in the online AWS AppSync Console.

**Environment(please complete the following information):**
 - Amplify Framework Version: 4.29.7
 - Dependency Manager: Cocoapods
 - Swift Version : 5.0

**Device Information (please complete the following information):**
 - Device: iPhone 11 Simulator
 - iOS Version: iOS 14

**Additional context**

**Comment by bumbleparrot** [comment]
After some really really careful debugging. I got it to work by doing the following:

Update the code to my GraphQLRequest extension to the following:
`
    static func getAddressByUniqueCode(uniqueCode uniqueCode: String) -> GraphQLRequest<**[Address]**> {
        let operationName = "**addressUniqueCode.items"**
        let document = """
        query addressUniqueCode($uniqueCode: String) {
            addressUniqueCode(uniqueCode: $uniqueCode) {
                nextToken
                items {
                  geohash
                  geohashFirst6
                  geohashLast1
                  id
                  zipCode
                  updatedAt
                  unit
                  uniqueCode
                  streetNumber
                  streetName
                  state
                  longitude
                  latitude
                  geohashLast6
                  geohashLast5
                  geohashLast4
                  geohashLast3
                  geohashLast2
                  createdAt
                  claimed
                }
              }
        }
        """
        
        return GraphQLRequest<**[Address]**>(document: document,
                                    variables: ["uniqueCode": uniqueCode],
                                    responseType: **[Address].self**,
                                    decodePath: operationName)
    }
`

The main difference is is:
1. Since this is a query on a secondary index, it will return a list. So i changes the "Address" to [Address].
2. The decodePath is dot notated. So i updated the path to the list to be **"addressUniqueCode.items"** which results in the array to be stored in the responseType.

My question now that this works, is it the correct pattern?
I have many other indexes I need to query on and I want to ensure I'm doing it right.

**Comment by bumbleparrot** [comment]
@drochetti , Hello! Do you happen to know if this is the right way to query on GSI's created through the schema.graphql and AWS Amplify CLI?

**Comment by drochetti** [comment]
Hi @bumbleparrot, as of now the way you did is the right way. We are evaluating a more automated way of providing those queries with the correct iOS types. But in the meantime, if you create your own extension like you did it should do it.

I'm happy to chat more about your use case, you said you have many more GSI queries and I understand creating your own extension for every single one is not ideal. Feel free to reach out to me on [Discord](https://discord.gg/amplify) or on [Twitter](https://twitter.com/drochetti), happy to chat more and gather your feedback while we address this pain point.

**Comment by bumbleparrot** [comment]
Thank you @drochetti, that is helpful.

I think the GraphQL schema should generate code for all queries annotated by @connection and @key. We can use the attributes of @key and @connection to determine the method name as well as the input parameters and its type.

One of the challenges this introduces is how deep is the default nesting for the models that get returned? Theres no data in the schema that would indicate that.

**Comment by raviscn** [comment]
This feature is available by default now i believe.
