### ISSUE TITLE
User auth MFA and TOTP support

### ISSUE THREAD

**Issue by springlo** [aws-amplify/amplify-swift#938]
Is it possible with the iOS Amplify framework to enable MFA for the user client side, in pools that have MFA as an option?
I haven't been able to find any documentation for this, and im wondering if the only workaround is to call a lambda function instead

**Comment by wooj2** [comment]
Hi @springlo -
I'm not sure if I understand your question -- you want to enable MFA for the user client side in pools that have MFA as an option?  Can you provide an example of what you're trying to do?

Here is our official documentation with regards to MFA:
https://docs.amplify.aws/lib/auth/signin/q/platform/ios#multi-factor-authentication

**Comment by Zenovis** [comment]
@wooj2 
I originally raised this question in the discord. When a Cognito user pool is created, it gives you the option to have MFA enabled case by case for users as an option.
Right now in my use case, Users sign up by putting their phone number and password in, and then they are prompted whether or not they want to enable MFA for extra security. If I want to enable MFA for them, I have to call a lambda function that uses AWS' boto3 API to enable MFA for the user. 
Is it possible to enable it for each user client side, or do I have to continue using the lambda function workaround until this is implemented?

**Comment by springlo** [comment]
After successful signup with MFA, how do I automatically sign in the user? It would be annoying for the user and costly for the developer to send another SMS for sign-in.

I don't see in the docs how to do this. Is this possible with current amplify?

**Comment by wooj2** [comment]
Hi @springlo , 
After a user successfully signs up with MFA, the user must go through the sign in process again.  There is currently no way to automatically sign them in.

Hi @Zenovis ,
Can you provide more info on which boto3 API you are using in your lambda to enable this?

Thanks!

**Comment by Zenovis** [comment]
Hey @wooj2,

Im using the cognito-idp boto3 client to enable MFA for the user. The code below is in Python 3.8

    class Cognito:
        Client = boto3.client("cognito-idp")
        def UpdateSMSMFAStatusForUser(userAccessToken, newStatus): 
            try:
                Response = Cognito.Client.set_user_mfa_preference(SMSMfaSettings = { 
                    "Enabled": newStatus,
                    "PreferredMfa": newStatus
                }, AccessToken = userAccessToken)
                if Response["ResponseMetadata"]["HTTPStatusCode"] == 200:
                    return True
                else:
                    #Failure
                    return False
            except Exception as Error:
                #Failure
                return False

User Access Token is acquired by creating an escape hatch to the AWSMobileClient instance in Amplify, even though it is not recommended.

**Comment by royjit** [comment]
@Zenovis Thank you for the information. Set user mfa preference is not currently available in the iOS Amplify.Auth. We will take this as a feature request and will update this ticket when we have more information.

**Comment by euphio** [comment]
+1 to be able to enable / check MFA status via SDK. Useful to allow users to enable / disable directly in the application.

**Comment by eduardo-rta** [comment]
It's July 2022 and this feature is still not available. As mater of fact, MFA doesn't event work properly with the current version, Software token will be returned as SMS by the SDK... I just don't understand how a big company such Amazon would have a project incomplete like this one for so long

**Comment by tylerjames** [comment]
Wait so is this saying that there is no way to set the preferred MFA method from the mobile client?

So if our app wants to provide MFA support and the user gets to decide whether they want to use SMS or TOTP how do they set that preference from the app?

**Comment by harsh62** [comment]
@tylerjames That is correct. At the moment there is no direct way of setting the user MFA preference. This is being actively worked upon as part of a broader TOTP effort. Having said that, you can still try to implement it yourself using the [Escape Hatch](https://docs.amplify.aws/lib/auth/escapehatch/q/platform/ios/) and then call the [Cognito API](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_SetUserMFAPreference.html) directly using the escape hatch client.

**Comment by tylerjames** [comment]
I'm not sure about the escape hatch business but I was able to do it like this:  
First get an `accessToken` using `AWSMobileClient.getTokens()`
Then use `AWSCognitoIdentityProvider` like this:

```swift 
var setting = AWSCognitoIdentityProviderSMSMfaSettingsType() 
setting.enabled = true
setting.preferredMfa = true

var request = AWSCognitoIdentityProviderSetUserMFAPreferenceRequest()
request.accessToken = token
request.smsMfaSettings = setting

AWSCognitoIdentityProvider
    .default()
    .setUserMFAPreference(request)
    // etc
```

That seemed to do it

**Comment by harsh62** [comment]
The AWS iOS SDK supports it as you suggested. I was talking about Amplify. In Amplify V2, it is only possible using the escape hatch.

**Comment by tylerjames** [comment]
Good to know. I'm hoping to upgrade to Amplify sometime in the near future so I'll probably have to come back to this solution anyway

**Comment by harsh62** [comment]
Amplify added support for TOTP MFA in [2.16.0](https://github.com/aws-amplify/amplify-swift/releases/tag/2.16.0).
